### ISSUE TITLE
Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin`

### ISSUE THREAD

**Issue by DanielProj** [react-community/react-navigation#923] opened 2017-04-05 10:04 UTC
UnableToResolveError: Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `/node_modules/react-navigation/src/views/Header.js`

**Comment by VictorVolovik** [comment] 2017-04-05 10:10
Same issues with node 6.10.1, npm 4+, mac os.

**Comment by hilkeheremans** [comment] 2017-04-05 10:17
See #901 and after that see #908

tl;dr:
For now, use `react-navigation`'s master branch here on github, and make sure you manually upgrade React to the dependency version specified by RN 0.43.

**Comment by hilkeheremans** [comment] 2017-04-05 10:18
Also linked to #906

**Comment by ryanbennettvoid** [comment] 2017-04-05 20:28
@hilkeheremans's tip fixed the issue.

In your `package.json`, replace the react-navigation dependency with this:
```
"react-navigation": "git+https://github.com/react-community/react-navigation.git"
```
then do `npm install`

**Comment by thurt** [comment] 2017-04-06 15:29
@ryanbennettvoid @hilkeheremans don't use master.

use the fix #809, commit hash 7edd9a7

```
"react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"
```

**Comment by joemckie** [comment] 2017-04-06 22:39
Unfortunately, even with these fixes there are plenty of Flow errors, e.g:

```
node_modules/react-navigation/src/views/CardStack.js:534
534:       <SceneView
           ^ property `navigation`. Property not found in
521:         <View style={styles.container}>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `View`

node_modules/react-navigation/src/views/CardStack.js:534
534:       <SceneView
           ^ property `screenProps`. Property not found in
521:         <View style={styles.container}>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `View`
```

Most of these are from the return type of [`_renderInnerCard`](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L509).

Current specs:
```
- react-native: 0.43.2
- react-navigation: 1.0.0-beta.7
- flow-bin: 0.40.0
```

**Comment by thurt** [comment] 2017-04-07 00:33
@joemckie Saw these errors as well. when i upgraded react-native to 0.43.1 using `react-native-git-upgrade` it appeared to bump my flow-bin version from 0.38.0 -> 0.40.0. before this upgrade i did not have flow errors.

**Comment by Dhrin** [comment] 2017-04-07 05:18
This work on me

"react": "16.0.0-alpha.3",
"react-native": "0.43.2",
"react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"

then

rm -rf node_modules && npm install

Clean ios/android build folder:

rm -rf android/build && rm -rf ios/build

After that, just run as usual:

react-native run-ios or react-native run-android

**Comment by joemckie** [comment] 2017-04-07 06:38
@thurt yeah it looks like there may have been some changes in how the `React$Element<*>` type is handled in between those versions? If it's not on the radar of the maintainers I'll take a look into it if I get a chance

**Comment by JeyWong** [comment] 2017-04-08 16:09
这应该是v1.0.0-beta.7版本的小错误，忘记清楚不必要的代码。Header.js中引入了ReactComponentWithPureRenderMixin，但后面未发现对这个引入的使用，只需要删除第12行的代码即可，亲测有效！
Delete node_modules\react-navigation\src\views\Header.js line 12 codes: 
import ReactComponentWithPureRenderMixin from 'react/lib/ReactComponentWithPureRenderMixin';

**Comment by RWOverdijk** [comment] 2017-04-13 19:37
I can verify that this works for me:

```json
{
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"
}
```

**Comment by keeleycarrigan** [comment] 2017-04-13 23:28
@RWOverdijk's solution works.

It kind of sucks that this has to be so complicated considering I just upgraded my app to RN 0.43.3 and I'm getting warnings in the console about NavigationExperimental yet react-navigation doesn't seem to be ready for prime time.

**Comment by nealz** [comment] 2017-04-17 09:55
The worked for me

  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git"
}

**Comment by nonameolsson** [comment] 2017-04-18 09:44
This works for me when I perform a local build on my machine. But I'm having trouble to get it to work with [Mobile Center](https://mobile.azuere.com).
```
Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `/Users/ci/agent/vstsagent/_work/1/s/node_modules/react-navigation/src/views/Header.js`: Module does not exist in the module map or in these directories:
  /Users/ci/agent/vstsagent/_work/1/s/node_modules/react-navigation/node_modules/react/lib
,   /Users/ci/agent/vstsagent/_work/1/s/node_modules/react/lib
,   /Users/ci/agent/vstsagent/_work/node_modules/react/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.

:app:bundleReleaseJsAndAssets FAILED
```

**Comment by Barvin** [comment] 2017-04-18 13:08
Editing the `package.json` does remove the error.
However, I don't see any results when using TabNavigator or StackNavigator. 
I'm running on Android.

**Comment by nonameolsson** [comment] 2017-04-18 13:09
@Barvin How do you edit the `package.json`?

**Comment by Barvin** [comment] 2017-04-18 13:10
@nonameolsson 
```
{
  "name": "TestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "^16.0.0-alpha.6",
    "react-native": "^0.43.3",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by grabbou** [comment] 2017-04-18 13:15
I am going to close this issue since `master` is working for latest React (see its dependencies). Until it ships as a `npm` version, pin your dependency to a commit of your choice.

**Closed by grabbou** 2017-04-18 13:15 UTC

**Comment by nonameolsson** [comment] 2017-04-18 13:20
So, is the solution to do the following:
```json
"dependencies": {
    "react": "^16.0.0-alpha.6",
    "react-native": "^0.43.3",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git"
} 
```

Because when I do that my build fails :-/

**Comment by nazmulidris** [comment] 2017-04-18 13:29
@nonameolsson The following works for me:
`  "dependencies": {
    "lodash": "^4.17.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-elements": "^0.10.3",
    "react-native-vector-icons": "^4.0.1",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git#7165efce02a60eecc41813fe5e030883996671ec"
  },
`

You can also check out [this tutorial](https://developerlife.com/2017/04/15/navigation-and-styling-with-react-native/) which goes over using the different navigators (this is where the package.json excerpt is from).

**Comment by nonameolsson** [comment] 2017-04-18 13:31
@nazmulidris Thanks! Will try that!

**Comment by nazmulidris** [comment] 2017-04-18 13:32
@nonameolsson You're most welcome. Here's a [link to the package.json](https://github.com/r3bl-alliance/react-native-weather/blob/master/package.json) file.

**Comment by farrukhbashir** [comment] 2017-04-19 12:07
@nazmulidris i also chang the dependencies but still  get error

**Comment by MohamedHussienMostafa** [comment] 2017-04-19 13:28
Still the same error after change the dependencies in package.json

{
  "name": "SimpleApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by jaygarcia** [comment] 2017-04-20 03:13
Confirmed working with using 
```
"react-navigation": "git+https://github.com/react-community/react-navigation.git"

```

I can now see icons after doing this too! :)

**Comment by newosetroc** [comment] 2017-04-21 03:26
> "react-navigation": "git+https://github.com/react-community/react-navigation.git"
This worked for me :) thanks

**Comment by nonameolsson** [comment] 2017-04-21 06:26
Just using the repo url didn't solve it for me. I had to use a specific commit hash.

**Comment by joemckie** [comment] 2017-04-21 07:13
This has been fixed in the latest version. Try using 1.0.0-beta.8

**Comment by Chandhru08** [comment] 2017-04-22 18:03
Guys, Im also facing the below error while trying to build an android app :
UnableToResolveError: Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `c:\Users\chand\manager\node_modules\react-addons-pure-render-mixin\index.js`: Module does not exist in the module map or in these directories:
  c:\Users\chand\manager\node_modules\react\lib
,   c:\Users\chand\node_modules\react\lib

I confused by reading all over the top to bottom in this page. 

Can anybody explain what  steps needs to be followed in short?

**Comment by Chandhru08** [comment] 2017-04-23 17:42
What is going on. Why Grabbou is creating a loop between #1181 and #923 ?

**Comment by jamieparkinson** [comment] 2017-04-23 18:20
@Chandhru08 github is just automatically noting that he referenced this in another issue :slightly_smiling_face:

In short, you just need to update your dependency (in react-navigation) to something a bit more recent than the current release that's on NPM - for example, see https://github.com/react-community/react-navigation/issues/923#issuecomment-292442911

**Comment by Chandhru08** [comment] 2017-04-23 18:40
@jamieparkinson 
Thank you for explaining. 

I just have this confusion now, do I have to remove other dependency items which are present in Package.json file or should I add it with existing items?

**Comment by jamieparkinson** [comment] 2017-04-23 19:28
Just replace the `react-navigation` item, that should be sufficient. So somewhere under `dependencies` you'll have something like:
```
"react-navigation": "1.0.0-beta.7",
```
And that needs to be replaced with, for example:
```
"react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"
```

Then you can follow the other steps in https://github.com/react-community/react-navigation/issues/923#issuecomment-292442911. I hope that works OK for you!

**Comment by shooterRao** [comment] 2017-04-24 08:21
Today I have encountered the same problem，Later, I found React-navigation": "1.0.0-beta.7  is not supported react-native version 0.43.4，so you can modify "react-native": "0.43.3" in package.json，
then 
1. rm -rf node_modules && npm install ,
2. rm -rf android/build && rm -rf ios/build , 
3.react-native run-ios or react-native run-android
thank you very much @Dhrin

**Comment by wswoodruff** [comment] 2017-04-26 03:12
Setting
```
"react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7",
```
in my package.json just fixed a slew of errors that just attacked me, and none of them looked related. Involved LinkedStateMixin, ReactComponentTreeHook, it was just weird.

And I got down this entire rabbit hole over trying to use <FlatList>

**Comment by epinapala** [comment] 2017-04-26 03:25
Finally the below worked for me : 
` "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"`

**Comment by lifez** [comment] 2017-04-26 05:42
Same here with 
```
 "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "^0.43.3",
    "react-navigation": "1.0.0-beta.8"
  }
```
and 
```
"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "^0.43.3",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"
  }
```

Already try with `react-native` `0.43.4` got the same error

**Comment by mehtamanan** [comment] 2017-04-26 06:51
@lifez I am using the latter with 0.43.4 and it works fine! 

Did you try:
rm -rf node_modules && npm install

And then reloading the screen multiple times?

**Comment by benjick** [comment] 2017-04-26 09:38
Why not just publish a new release to NPM with this cherrypicked?

How do I do this with yarn? Changed package.json, deleted my lockfile, re-installed but still the same problem

**Comment by grabbou** [comment] 2017-04-26 11:33
New release will be published today containing a fix. 

I am going to `lock` this issue to prevent unnecessary notifications.
