### ISSUE TITLE
Feautre request: allow only filtering of routes that get drawn in DrawerNavigatorItems component

### ISSUE THREAD

**Issue by evansiroky** [react-community/react-navigation#1496] opened 2017-05-13 00:43 UTC
It would be nice to only show certain navigator items in the drawer menu instead of all of them.

**Comment by kelset** [comment] 2017-10-28 13:14
Duplicate of https://github.com/react-community/react-navigation/issues/1461

**Closed by kelset** 2017-10-28 13:14 UTC
Labels: Type: Feature Request
