### ISSUE TITLE
iOS: Setting header to not visible in screen doesn't hide it

### ISSUE THREAD

**Issue by ccdwyer** [react-community/react-navigation#465] opened 2017-02-23 20:02 UTC
Added:
`
static navigationOptions = {
    header: {
      visible: false,
    },
  };
`

to a component which is called by my main StackNavigator.  In Android, the navbar is not visible; In iOS (iPhone and iPad), the navbar is still visible.  Is this the intended functionality?

Using react-navigation version 1.0.0-beta.5.

**Comment by grabbou** [comment] 2017-02-23 20:03
Duplicate of #53. Change headerMode to `screen` otherwise to get it work as of now :) PRs welcome, I still have that on my list.

**Closed by grabbou** 2017-02-23 20:03 UTC
