### ISSUE TITLE
iOS swipe back gesture is still enabled when using Modal in a StackNavigator

### ISSUE THREAD

**Issue by jonasb** [react-community/react-navigation#513] opened 2017-02-28 12:20 UTC
If I open a `<Modal>` in a screen in a StackNavigator, the swipe back gesture still works. So if the modal is transparent I can see that the screen underneath is swept away.

I expect the swipe back gesture to be disabled when modals are up.

**Comment by grabbou** [comment] 2017-03-01 11:27
Duplicate of #67

**Closed by grabbou** 2017-03-01 11:27 UTC
