### ISSUE TITLE
TabNavigator's tabs are not displayed when nested in a DrawerNavigator

### ISSUE THREAD

**Issue by Colmea** [react-community/react-navigation#38] opened 2017-01-27 15:47 UTC
Hi,

First, thank you for this module !

I have an issue when using a TabNavigator nested in a DrawerNavigator: tabs are not displayed.
This issue appears only when I go to the nested TabNavigator from the Drawer menu link *and* when using `navigate('MyNestedTabStack')` like in the get started guide.

Here is an example:

```js
class HomeScreen extends React.Component {
    render() {
        return <Button
            onPress={() => this.props.navigation.navigate('Projects')}
            title="Go to Projects"
        />;
    }
}

class RecentProjectsScreen extends React.Component {
    render() {
        return <Text>List of recent projects</Text>
    }
}

class AllProjectsScreen extends React.Component {
    render() {
        return <Text>List of all projects</Text>
    }
}

const ProjectScreenNavigator = TabNavigator({
    Recent: { screen: RecentProjectsScreen },
    All: { screen: AllProjectsScreen },
});


const App = DrawerNavigator({
    Home: { screen: HomeScreen },
    Projects: { screen: ProjectScreenNavigator }
});

AppRegistry.registerComponent('App', () => App);
```

**Comment by hilkeheremans** [comment] 2017-01-27 16:18
I can confirm this issue, and it is also related to issue #31.

I have tracked down this issue to the way `DrawerNavigator` attempts to retrieve the components it renders. `DrawerNavigator` internally uses a `TabRouter` to find out what content it needs to render. However, whenever you nest a `StackNavigator`, or in this case a `TabNavigator`, this router will retrieve the _deepest_ component in the navigation tree, bypassing all intermediary navigators from rendering.

The root cause of this seems to lie in `TabRouter's` `getComponentForState` function, which will automatically recurse through all child routers:

```
    getComponentForState(state: NavigationState) {
      const routeName = order[state.index];
      invariant(
        routeName,
        `There is no route defined for index ${state.index}. Check that
        that you passed in a navigation state with a valid tab/screen index.`
      );
      const childRouter = tabRouters[routeName];
      if (childRouter) {
        return childRouter.getComponentForState(state.routes[state.index]);
      }
      return getScreenForRouteName(routeConfigs, routeName);
    },
```

Bypassing this recursion allows tabs and stacks inside drawers to function normally. However, I want to hold off on a PR as I assume this recursion is there for a reason, and I do not yet grok `react-navigation` sufficiently to fully understand the consequences.

I believe that, ideally, DrawerNavigation should get its own router to cleanly separate concerns with TabRouter.

@ericvicenti @skevy Any insight for us laypeople?

**Comment by frankrowe** [comment] 2017-01-27 16:44
Can confirm the same issue with embedding `StackNavigators` in a `DrawerNavigator`

**Comment by ericvicenti** [comment] 2017-01-27 17:58
Maybe the drawer navigator should use the `router.getComponentForRouteName` instead? If you can find a fix inside the drawer navigator without changing any routers, then the PR would be quickly accepted!

cc @satya164

**Comment by hilkeheremans** [comment] 2017-01-27 18:42
I will attempt to push out a fix ASAP, in a few hours.

On 27 Jan 2017, at 18:58, Eric Vicenti <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe the drawer navigator should use the router.getComponentForRouteName instead? If you can find a fix inside the drawer navigator without changing any routers, then the PR would be quickly accepted!

cc @satya164<https://github.com/satya164>

-

**Comment by satya164** [comment] 2017-01-27 19:15
Fixed in https://github.com/react-community/react-navigation/pull/46

**Closed by satya164** 2017-01-27 19:15 UTC
Labels: bug

**Comment by hilkeheremans** [comment] 2017-01-27 19:18
Thanks @satya164! FYI, I was doing the same fix at the same time. I have tested it in the following scenarios:
```
Tab in Drawer --> ok
Tab in Tab in Drawer --> ok
Stack in Tab in Drawer --> ok
Tab in Drawer in Tab --> ok
Tab in Drawer in Stack --> ok
```

... so we should be golden!

**Comment by satya164** [comment] 2017-01-27 19:33
Awesome!

**Comment by Colmea** [comment] 2017-01-27 22:27
Wow 4 hours after my issue, thank you ! Best.Customer.Service.Ever

**Comment by jpca999** [comment] 2017-06-27 22:47
How can we handle the scenarios of   Drawer inside the Tab , Can you please point me to some working code ?

**Comment by markusguenther** [comment] 2017-07-14 19:00
That would be interesting. Or a way to have both - a TabNavigator and a DrawerNavigator.

I have a project where I should have 3 Tabs on all screens and a drawer with other NavigationItems.

**Comment by jpca999** [comment] 2017-07-14 20:41
Can you pls share the link ?

**Comment by markusguenther** [comment] 2017-07-14 21:15
Which link should I share? It is more or less a question ... will try to join this with a stacknavigator or so.
