### ISSUE TITLE
header: null not working when dynamically creating tabNavigator

### ISSUE THREAD

**Issue by raarts** [react-community/react-navigation#2192] opened 2017-07-19 21:24 UTC
Here's code that works, followed by code that doesn't:

```
const HomeScreen = (props) => {
  return ( <View><Text>This is HomeScreen</Text></View> );
};

const SettingScreen = (props) => {
  return ( <View><Text>This is SettingScreen</Text></View> );
};

const MainScreen = TabNavigator({
  Home: { screen: HomeScreen,  },
   Settings: {  screen: SettingScreen, },
});

MainScreen.navigationOptions = { header: null, }

const RootStackNavigator = StackNavigator({
    Main: { screen: MainScreen, }
});

export default class RootNavigator extends React.Component {
  render() {
    return <RootStackNavigator />;
  }
}
```

When I change it to this, there's suddenly a header showing in all tab screens:

```
const HomeScreen = (props) => {
  return ( <View><Text>This is HomeScreen</Text></View> );
};

const SettingScreen = (props) => {
  return ( <View><Text>This is SettingScreen</Text></View> );
};

class MainScreen extends React.PureComponent {
  render() {
    const Main = TabNavigator({
      Home: {  screen: HomeScreen },
      Settings: { screen: SettingScreen },
    });
    Main.navigationOptions = { header: null }
    return <Main/>
  }
}

const RootStackNavigator = StackNavigator( {
  Main: { screen: MainScreen },
});

export default class RootNavigator extends React.Component {
  render() {
    return <RootStackNavigator />;
  }
}
```

### Current Behavior
When creating a tabNavigator dynamically (to be able to theme it dynamically) the header: null option is ignored in the navigationOptions, so I get a header in all tab screens I don't want. 

### Expected Behavior

No header in the tab screens

### Your Environment

```
    "expo": "^18.0.4",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-navigation": "^1.0.0-beta.11",
```

**Comment by spencercarli** [comment] 2017-08-28 01:40
Can you provide a running reproduction of this? Thanks!

**Comment by kelset** [comment] 2017-11-25 09:15
Hi there @raarts,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since Spencer's last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-11-25 09:15 UTC
Labels: bug, needs more info
