### ISSUE TITLE
Back Button invisible on real Android device (but visible on VM)

### ISSUE THREAD

**Issue by ayalpani** [react-community/react-navigation#442] opened 2017-02-22 20:27 UTC
This is how my page looks like on a **real device**:

![2017-02-22-211647](https://cloud.githubusercontent.com/assets/603179/23230640/0ba9d4c2-f945-11e6-8ab7-8617ff434190.jpg)

This is the same page on a **AVM**:

![screenshot](https://cloud.githubusercontent.com/assets/603179/23230766/73eb0b28-f945-11e6-8986-44e9796654b8.png)

Now, why is the back button's image possibly not shown on the real device?

**Comment by satya164** [comment] 2017-02-22 22:53
Can you verify you're using the version from master?

**Comment by ayalpani** [comment] 2017-02-23 07:22
Hi @satya164 

Yes I do! 
package.json: `"react-navigation": "git+https://github.com/react-community/react-navigation/"`

**Comment by charafau** [comment] 2017-02-23 18:32
I have the same bug with the very first example from the site (StackNavigator with one view) there's some strange margin from the left (rendering invisible icon?) - used to work on beta1, doesnt on beta5

<img width="282" alt="screen shot 2017-02-24 at 3 30 34" src="https://cloud.githubusercontent.com/assets/1143994/23273277/ce4d3fa8-fa41-11e6-9e7e-ee6b1cc6c879.png">

**Comment by grabbou** [comment] 2017-02-23 18:58
@charafau please try master. That header left padding was fixed a while ago. Needs a new release. The OP is talking about a different case.

**Comment by filipsuk** [comment] 2017-06-06 21:00
@ayalpani Have you figured out the solution please? I would like to release my Android app and this the only blocker :/

**Comment by TheRohitSharma** [comment] 2017-06-11 18:18
I've been having this same issue. Back button only shows when I'm debugging, but when the app is on its own on my device, the back button becomes invisible. Still functional but invisible. Has anyone found a workaround?

**Comment by filipsuk** [comment] 2017-06-14 15:45
I found a solution here: https://stackoverflow.com/questions/41937443/local-images-are-not-visible-in-react-native-app-release-build

Running this solved the problem for me 🎉
```bash
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
```

**Comment by matthamil** [comment] 2017-07-11 01:54
I'm going to close this issue for now. If you continue to experience this, please reopen another issue. It looks like @filipsuk 's solution should help. I can't seem to reproduce this on the current version of `master`.

**Closed by matthamil** 2017-07-11 01:54 UTC

**Comment by Garib-ka-code** [comment] 2017-12-08 19:29
@filipsuk and @matthamil its not working for me.. I am getting same issue ...

**Comment by ahmad2smile** [comment] 2018-02-28 14:03
Getting the same issue on `Android ZUK by Lenovo`. Back arrow and title both are invisible but Tap on the same position still works with Opacity Feedback. Note color of the Header is greenish so not font color like problem.

But it works just fine on 

1. Google Pixel Simulator
2. iPhone 6 Simulator
3. iPhone 6
4. LG Nexus 5

**Comment by brentvatne** [comment] 2018-03-06 23:26
thanks for the info @ahmad2smile!

can someone please create a new issue for this which provides a project that we can repro this on, along with a list of devices that this happens on? thanks!

also -- the back icon is only an image. this may happen if you build your app and run it on your phone in debug mode, and then turn off the react native packager or it is no longer reachable from your phone.
