### ISSUE TITLE
screenB reset TabNavigator, I cann‘t get  the value of the past

### ISSUE THREAD

**Issue by Mscynol** [react-community/react-navigation#2987] opened 2017-11-16 09:23 UTC
const resetAction = NavigationActions.reset({

      index: 0,

      actions: [

            NavigationActions.navigate({routeName: 'ScreenA', params: { foo: 'bar' }})

    ]

})
this.props.navigation.dispatch(resetAction);
It can  get the value by the way of 'this.props.navigation.state.params.foo'
But ?
 if screenA in tab, that is, screenB reset TabNavigator, I cann‘t get  the value of the past

**Comment by kelset** [comment] 2017-11-16 10:06
1. you haven't followed the issue template
1. duplicate of https://github.com/react-community/react-navigation/issues/2073

**Closed by kelset** 2017-11-16 10:06 UTC

**Comment by Mscynol** [comment] 2017-11-16 11:50
MainStackNavigator
       ScreenB
       TabNavigator
it does not work for me  ScrenB reset TabNavigator by the "The way?"
reset: (props, routeName, paramsValue) => {
        console.log(`The params--------->${JSON.stringify(paramsValue)}`);
        const resetAction = NavigationActions.reset({
            index: 0,
            actions: [NavigationActions.init({
                routeName: routeName,
                params: paramsValue
            })]
        })
        props.navigation.dispatch(resetAction);
    }
it‘s wrong 
屏幕快照 2017-11-16 下午7.50.11.png

**Comment by Mscynol** [comment] 2017-11-16 11:57
![Uploading 屏幕快照 2017-11-16 下午7.50.11.png…]()

**Comment by Mscynol** [comment] 2017-11-16 12:04
![Uploading 屏幕快照 2017-11-16 下午7.50.11.png…]()

**Comment by Mscynol** [comment] 2017-11-16 12:18
![1510834592489](https://user-images.githubusercontent.com/13941582/32890793-37ee9624-cb0b-11e7-82b2-8f49cdb4346e.jpg)

**Comment by flynnch** [comment] 2017-11-24 08:16
@Mscynol do you solve it？
