### ISSUE TITLE
Error: Cannot get config because the route does not have a routeName

### ISSUE THREAD

**Issue by quadsurf** [react-community/react-navigation#2282] opened 2017-08-01 00:50 UTC
In my logout() function, I am trying to send my users back to the top level screen, using the following:

let resetAction = NavigationActions.reset({
            index: 0,
            actions: [
              NavigationActions.navigate({ routName: 'Root' })
            ]
          })
          this.props.navigation.dispatch(resetAction)

The problem is that I am trying to do this from a child component that should not be registered as a screen in the stack, which causes the dispatch method above to lose context, which causes the following error:

Cannot get config because the route does not have a routeName

So I figured a workaround would be to pass that context down as a prop, so that the child can 'borrow' the parent component's routeName during the Navigation Action.

IMPORTANT: bringing this reset option up to its parent component where the proper "this.props.navigation" context lives, is NOT an option. Can anyone help?

**Comment by spencercarli** [comment] 2017-08-18 22:17
A running demo of this issue would help addressing this issue (and/or providing any temporary work arounds). Thanks!

**Comment by quadsurf** [comment] 2017-08-24 12:15
My issue is that I am trying to dispatch a reset action from a child component that is not registered to any Stack (nor should it be registered to/in Stack) because this child component is not a screen/route. So when I dispatch the reset action, I get the following error:

> Cannot get config because the route does not have a routeName

Well of course it can't get "config" because it's not registered on Stack... it's not a route, it's a nested child component, and converting this child component to a route is not an option.

This is a bug in my opinion, because 'reset' should have a default outcome if no config exists, and the default outcome should index 0 of the most top-level stack. Can we pls make this the resolution for this bug?

**Comment by bakarshams** [comment] 2017-09-21 08:42
@quadsurf  any update regarding this issue?

**Comment by ybentlili** [comment] 2017-10-12 08:01
Any update for this issue ?

**Comment by flynnch** [comment] 2017-11-07 01:34
Any update?

**Comment by spencercarli** [comment] 2017-11-09 17:33
Would using [`withNavigation`](https://reactnavigation.org/docs/views/with-navigation) help in this situation? Without a reproduction, it's hard to fully understand what's happening & how to recreate. 

From what I can tell though, using `withNavigation` to make the nav context available to any component (even if they aren't registered with a navigator) should help. I'll leave it open for now though.

**Comment by kelset** [comment] 2017-11-25 09:35
Hi there @quadsurf,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since Spencer's last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-11-25 09:35 UTC
Labels: needs more info

**Comment by quadsurf** [comment] 2017-12-14 14:00
yes @spencercarli ... `withNavigation` resolves this issue very effectively, thank you!
