### ISSUE TITLE
Transparent Cards in CardStack navigator

### ISSUE THREAD

**Issue by ptc-jhughes** [react-community/react-navigation#1236] opened 2017-04-25 23:37 UTC
I have a CardStack navigator with several screens nested in a background image like so: 

```javascript
<Image source={getAsset('BackgroundImage')} style={styles.backgroundImage}>
  <MyStackNavigator screenProps={this._getFilteredProps()} ref={nav => { this.navigator = nav; }} onNavigationStateChange={this._navigationStateChanged}/>
</Image>
```
Each of the cards in this stack has a `backgroundColor` of `transparent` so that the background image is shown. When transitioning from A->B, it works correctly about 98% of the time.  On rare occasions, after the default transition animation, the bottom card's opacity does not change and, because the cards are on top of each other, I see a combined render of both cards. Card B still functions correctly, but all the elements from card A also show.

**Comment by grabbou** [comment] 2017-04-26 04:22
> I see a combined render of both cards

I believe it's a duplicate of #229 (header is also transparent to allow animations).

**Closed by grabbou** 2017-04-26 04:22 UTC
