### ISSUE TITLE
Mounts previous component, causes loop

### ISSUE THREAD

**Issue by spearmootz** [react-community/react-navigation#2633] opened 2017-09-22 16:07 UTC
### Current Behavior
- If i have a splash screen that basically changes to screen2 during componentWillMount, doing a NavigationActions.reset back to the splash creates a loop. in my case i have an app in which when it goes to the background i want to reset back to the splash to protect sensitive information.

it goes a little bit like this
-Splash
-screen2
-login
-user does whatever, presses home button and gets out of the app
- reset to splash
- screen2 for some reason after the reset, when navigating to screen2 the splash componentWillMount gets called over and over
- loops splash and screen2

### Expected Behavior
no loop, stays at screen2

### Your Environment
using react-navigation@1.0.0-beta.12
tested on ios

here is the resetaction that is dispatched when user exits app

const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'Splash'})
  ]
});

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by spearmootz** [comment] 2017-09-22 17:23
it seems to happen on navigate too. so i have screen2 (it does fingerprint auth on mount) and when it passes and i go to authorizedScreen screen2's componentDidMount gets called.

**Comment by luco** [comment] 2017-10-30 20:39
+1 on this.

**Comment by spearmootz** [comment] 2017-11-14 17:13
@spencercarli what questions do you have?

**Comment by spencercarli** [comment] 2017-11-14 19:07
need a reproduction of this issue. I don't know what `componentWillMount` would ever be called more than once because past screens in a stack aren't unmounted

**Comment by kelset** [comment] 2017-12-03 11:05
Closing in favor of https://github.com/react-community/react-navigation/issues/2473

**Closed by kelset** 2017-12-03 11:05 UTC
Labels: needs more info, question
