### ISSUE TITLE
accessibilityLabel for android

### ISSUE THREAD

**Issue by bouzoumita** [react-community/react-navigation#3131] opened 2017-12-15 14:07 UTC
Hi I'm testing my app written with the help of react-navigation, I'm using testID='header-back' to access the back button navigation in ios UITesting and click it, but this is not working with android, and it seems that accessibilityLabel is not available for android is there a work around this, I'm using "react-navigation": "^1.0.0-beta.19" and testing with espresso in android.

**Comment by kelset** [comment] 2017-12-15 14:36
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-15 14:36 UTC
