### ISSUE TITLE
Conflict with collectionsjs and StackNavigator

### ISSUE THREAD

**Issue by ruqqq** [react-community/react-navigation#1408] opened 2017-05-08 01:20 UTC
### Current Behavior
If `collectionsjs` is imported, and `StackNavigator` is used, there will be an error stating that `undefined is not an object (evaluation '_ref.routes')`.

Code:
`import SortedArray from 'collections/sorted-array'`

### Expected Behavior
There should be no error and `StackNavigator` should work as per normal.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             |  4.1.2
| yarn      | 0.18.1
| collections | 5.0.6

**Comment by spencercarli** [comment] 2017-08-15 02:19
Can you provide a reproduction of this?

**Comment by kelset** [comment] 2017-10-28 12:40
Hi there @ruqqq , 

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-10-28 12:40 UTC
Labels: Status: Needs More Info
