### ISSUE TITLE
TabNavigator can't show label and icon together on iOS 11.0.1

### ISSUE THREAD

**Issue by yiky84119** [react-community/react-navigation#2831] opened 2017-10-26 16:52 UTC
TabNavigator can't show label and icon together on iOS 11.0.1.

I found some codes in `TabBarBottom.js` Line 59

`const majorVersion = parseInt(Platform.Version, 10);`
`const isIos = Platform.OS === 'ios';`
`const useHorizontalTabs = majorVersion >= 11 && isIos;`

When iOS version is 11.0.1, useHorizontalTabs is true. Line 148

`<TabBarIcon`
       ` position={position}`
`        navigation={navigation}`
`        activeTintColor={activeTintColor}`
`        inactiveTintColor={inactiveTintColor}`
`        renderIcon={renderIcon}`
`        scene={scene}`
`        style={showLabel && useHorizontalTabs ? {} : styles.icon}`
`      />`

TabBarIcon style will be set to {}, icon can't display

Environment:
  OS:  macOS High Sierra 10.13
  iOS: 11.0.1
  Node:  8.7.0
  Yarn:  1.2.1
  npm:  5.4.2
  Watchman:  4.7.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.49.3 => 0.49.3
  react-navigation: 1.0.0-beta15

**Comment by kelset** [comment] 2017-10-26 18:13
Hey thanks for reporting.

@spencercarli maybe it's simply a typo and you actually wanted to write `style={showIcon && useHorizontalTabs ? {} : styles.icon}` ?

**Comment by chochihim** [comment] 2017-10-27 03:50
Similar problem here. Please refer to below screenshots:

Physical device - iPhone 7 with iOS 10.3.3:
![img_3960](https://user-images.githubusercontent.com/19410131/32087008-65ea30ca-bb0b-11e7-90f9-d845af76c881.PNG)

Simulator - iPhone 7 with iOS 11.0.1:
![simulator screen shot - iphone 7 - 2017-10-27 at 11 34 38](https://user-images.githubusercontent.com/19410131/32086973-484d3bd4-bb0b-11e7-978c-4a74f99df919.png)

The tabbar icon and label are overlapping in iOS 11.0.1.

I am using a custom react component for tabBarLabel. There is no problem if I use string for it.

I notice a [margin handling](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L107-L114) is added for iOS >= 11

Why such margin is added? Does it means that I need to add it myself if I use my own tabBarLabel?

**Comment by spencercarli** [comment] 2017-10-28 15:17
Duplicate of #2805. Check out the discussion in there and please provide your tabbar configuration. Thanks!

**Closed by spencercarli** 2017-10-28 15:17 UTC
Labels: Type: Bug
