### ISSUE TITLE
GoBack init screen

### ISSUE THREAD

**Issue by Jakevin** [react-community/react-navigation#1896] opened 2017-06-16 03:44 UTC
### Current Behavior
goback("Init-key"), not work for me. 

The init Screen's backRouteIndex = 0. 

```
if (action.type === NavigationActions.BACK) {
        let backRouteIndex = null;
        if (action.key) {
          const backRoute = state.routes.find(
            /* $FlowFixMe */
            (route: *) => route.key === action.key
          );
          /* $FlowFixMe */
          backRouteIndex = state.routes.indexOf(backRoute);
        }
        if (backRouteIndex == null) {
          return StateUtils.pop(state);
        }
        if (backRouteIndex > 0) {
          return {
            ...state,
            routes: state.routes.slice(0, backRouteIndex),
            index: backRouteIndex - 1,
          };
        }
      }
```

### Expected Behavior
Edit src/routers/StatckRouter.js to

```
if (action.type === NavigationActions.BACK) {
        let backRouteIndex = null;
        if (action.key) {
          const backRoute = state.routes.find(
            /* $FlowFixMe */
            (route: *) => route.key === action.key
          );
          /* $FlowFixMe */
          backRouteIndex = state.routes.indexOf(backRoute);
        }
        if (backRouteIndex == null) {
          return StateUtils.pop(state);
        }
        if (backRouteIndex > 0) {
          return {
            ...state,
            routes: state.routes.slice(0, backRouteIndex),
            index: backRouteIndex - 1,
          };
        }else{
          return {
            routes: state.routes.slice(0, 1),
            index: 0,
          };
        }
      }
```
goBack('home-key'), will go back to init screen

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |   1.0.0.beta 11
| react-native     |   0.45.1
| node             |  
| npm or yarn      |

**Comment by AnatoliyGatt** [comment] 2017-06-16 19:17
@Jakevin It's a not a bug. Actually, if you take a look at the docs you'll see that the key you pass to the goBack() is the key of the screen you want to navigate FROM, not TO.

**Comment by matthamil** [comment] 2017-06-21 04:00
Closing this issue as it appears resolved. Please open a new issue or comment if the problem persists.

**Closed by matthamil** 2017-06-21 04:00 UTC
