### ISSUE TITLE
Header too high on Android 

### ISSUE THREAD

**Issue by babsonmatt** [react-community/react-navigation#826] opened 2017-03-26 03:28 UTC
Anyone else experiencing this? I have a header with a title and a right button and its something like 10 px too high.  No issues with iOS though.

**Comment by nihgwu** [comment] 2017-03-26 15:37
That's designed to according to the Android Spec, not a bug, you can override the default style

**Comment by babsonmatt** [comment] 2017-03-27 00:37
@nihgwu I'll have to attach a pic just to make sure, right now the right button is cut off mid way - thats intended? Apologies if so.

**Comment by stanonyime** [comment] 2017-03-28 07:34
@nihgwu how does one override the style for the header container? I tried styling the screen header but it had no effect on the positioning

**Comment by AlanFoster** [comment] 2017-04-03 23:35
@babsonmatt A picture would definitely help clarify this issue :+1:

**Comment by babsonmatt** [comment] 2017-05-15 04:34
@AlanFoster apologies for the delay! - this is with the android emulator (pixel xl)

![image](https://cloud.githubusercontent.com/assets/853220/26042820/43e56788-3906-11e7-8e81-4cde4b44cebe.png)

**Comment by dantman** [comment] 2017-05-15 07:18
@babsonmatt That's not "too high". You're using Expo, which implicitly sets the StatusBar to translucent. React Native's default is a translucent StatusBar on iOS you can go under, but an opaque StatusBar on Android that content does not go under.

You need to add padding+height to compensate for the translucent status bar Expo adds.

This is a duplicate of #12 and #1478.

**Comment by skevy** [comment] 2017-05-15 18:01
Closing in favor of #1478

**Comment by babsonmatt** [comment] 2017-05-15 18:01
@dantman thank you for clarifying that for me - apologies for the duplicate issue

**Closed by skevy** 2017-05-15 18:01 UTC

**Comment by rawteech** [comment] 2019-05-17 10:23
This [work-around](https://github.com/react-navigation/react-navigation/issues/1478#issuecomment-301220017) did the trick for me
