### ISSUE TITLE
Add badge for TabNavigator

### ISSUE THREAD

**Issue by yolosaucisson** [react-community/react-navigation#2644] opened 2017-09-25 14:31 UTC
I would like to add badge for the TabNavigator but I have no idea how to do that, I tried with the custom render of the tabBarComponent.

I can display one badge but it's only rerender when I click on one button of the tabBar, how can I force to re-render this component?

Thanks,

**Comment by matthamil** [comment] 2017-09-25 17:26
Duplicate of https://github.com/react-community/react-navigation/issues/766

**Closed by matthamil** 2017-09-25 17:26 UTC
