### ISSUE TITLE
How to navigate from one screen to another with nested navigators ??

### ISSUE THREAD

**Issue by mikhail709** [react-community/react-navigation#1979] opened 2017-06-24 14:03 UTC
Now I have this navigation structure:
```
AppStackNavigator: {
	LoginStackNavigator: {
		SplashScreen,
		LoginScreen,
		ForgotPasswordScreen,
		ect.
	}
	MainSctackNavigator: {
		MainScreen,
		SettingsScreen,
		SomeTabNavigator: {
			FirstTabScreen,
			SecondTabScreen,
			ThirdTabScreen
		},
		ect.
	}
}
```
So, I need an example of how to navigate from LoginScreen to MainScreen  and how to navigate from MainScreen to SecondTabScreen. 
Sorry for my English
Thanks for your answers

**Comment by mcampsall** [comment] 2017-06-24 18:54
Have you tried this?

`this.props.navigation.navigate('MainScreen');`

and 

`this.props.navigation.navigate('SecondTabScreen');`

**Comment by mikhail709** [comment] 2017-06-25 10:29
@mcampsall, yes. "There is no route defined for key MainScreen. Must be one of: 'SplashScreen','LoginScreen','ForgotPasswordScreen',..." error appears in the first case. 
The second works

**Comment by jeserodz** [comment] 2017-06-27 10:36
@mikhail709 would this way of structuring your app navigation works better in your case?

```javascript
const AppStackNavigator = StackNavigator({
  loginFlow: { 
    screen: StackNavigator({
      splash: { screen: SplashScreen },
      login: { screen: LoginScreen },
      forgotPassword: { screen: ForgotPasswordScreen }
    })
  },
  mainFlow: {
    screen: StackNavigator({
      main: { screen: MainScreen },
      settings: { screen: SettingsScreen },
      someTab: { 
        screen: SomeTabNavigator({
          firstTab: { screen: FirstTabScreen },
          secondTab: { screen: SecondTabScreen },
          thirdTab: { screen: ThirdTabScreen }
        })
      }
    })
  }
})

[...]

render() {
  return <AppStackNavigator/>
}
```

To navigate:

`this.props.navigation.navigate('login');`
`this.props.navigation.navigate('secondTab');`
`this.props.navigation.navigate('splash');`

**Comment by alxvallejo** [comment] 2017-07-10 16:21
Side question here - do you have to define all routes on initial load of the app? I have nested navigators but they are defined amongst their nested routes. It doesn't look like I can navigate to a route unless it is part of the current stack (e.g., can't navigate from one nested stacknav to another). It was never clear from the documentation on whether defining routes upfront was the best practice.

**Comment by NazeerBZ** [comment] 2017-08-25 08:19
How can i navigate from 'Patient' to 'Add Patient'(which is present in DrawerNav)

const Navigation = StackNavigator({

    'Login': {
        screen: Login
    },

    'Signup': {
        screen: Signup
    },

    'DrawerNav': {
        screen: DrawerNav
    },

    'Patient': {
        screen: Patient
    }
},

    {
        navigationOptions: {
            header: null
        }
    }
)

const DrawerNav = DrawerNavigator({

    "Add Patient": {
        screen: AddPatient
    },

    "All Patient": {
        screen: AllPatient
    },

    "Logout": {
        screen: Logout
    }
})

**Comment by spencercarli** [comment] 2017-08-28 01:27
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:27 UTC
Labels: Type: Question

**Comment by Laurensdc** [comment] 2018-02-05 08:08
@jeserodz WOW, I never knew you could do this!! Amazing 😮 

The docs should really state this. They seem to suggest separating Navigators to different files, where this way of nesting navigators really starts to suck. In my last project I was passing params as screenProps to allow for callbacks to navigate back...

**Comment by WataruKay** [comment] 2018-02-06 13:37
@Laurensdc I wish I saw this earlier as well...

**Comment by swingywc** [comment] 2018-02-22 12:40
@Laurensdc May I know how you can pass the params as screenProps. Would like to get some reference for different methods...

**Comment by Laurensdc** [comment] 2018-02-22 14:17
@swingywc 

I'll try to give a complete example, since when I read these types of answers, I'm often very confused.

So I have a nested navigation structure

This is my root navigation (parent component of my app, I render this one in `App.js`)

``` js
import React from 'react';
import { StackNavigator } from 'react-navigation';

import AccountNavigation from './AccountNavigation';
import ProjectNavigation from './ProjectNavigation';

const RootStackNavigation = StackNavigator(
    {
        Account: {
            screen: AccountNavigation,
        },
        Projects: {
            screen: ProjectNavigation,
        },
    },
    {
        navigationOptions: () => ({
            header: null,
        }),
    }
);

export default class RootNavigation extends React.Component {
    render() {
        return (
            <RootStackNavigation />
        );
    }
}
```

I have two screens, that are Navigators themselves, so they are nested under Navigator.
These screens are `AccountNavigation` and `ProjectNavigation`.

Accountnavigation looks like this:

```js
import React from 'react';
import {
    StackNavigator,
} from 'react-navigation';

import LoginScreen from '../screens/account/LoginScreen';
import RegisterScreen from '../screens/account/RegisterScreen';

const AccountStackNavigation = StackNavigator(
    {
        Login: {
            screen: LoginScreen
        },

        Register: {
            screen: RegisterScreen
        },

    },
    {
        navigationOptions: () => ({
            header: null,
        }),
    }
);

export default class AccountNavigation extends React.Component {
    render() {
        return (
            <AccountStackNavigation
                // Pass these navigation props to child navigation
                // So that it's possible to navigate back to home
                screenProps={{ rootNavigation: this.props.navigation }}
            />
        );
    }
}
```

Notice because AccountNavigation is a child of RootNavigation, I can access the navigation props `this.props.navigation` of rootnavigation.
Now I'm passing these as screenProps.

With this, I can access the rootNavigation in screens that belong to accountNavigation (`LoginScreen` and `RegisterScreen`).

For example, some code within `LoginScreen`:

```js
const rootNav = this.props.screenProps.rootNavigation;
rootNav.navigate('Projects');
```

Note that I didn't know @jeresodz' tactic here, and recommend that way of doing this.
The way I described above is very tedious, and with the solution from jeresodz you can simply do `this.props.navigate('Projects')` because the navigators know the nested routes.

I hope this is a bit clear. You can also pass normal data instead of the navigation prop with `screenProps`.

Also check out the [docs](https://reactnavigation.org/docs/stack-navigator.html#navigator-props) on this (even though they apparently completely changed just now).

**Comment by shekharskamble** [comment] 2018-03-01 00:40
@Laurensdc thanks for the example how about going to inner screen of ProjectNavigation? this.props.navigate('Projects') will route to default screen but what if we need to go to some other screen.

**Comment by Laurensdc** [comment] 2018-03-01 08:37
@shekharskamble You will probably have to add the screen itself to the Navigator. You can put the screen both in ProjectNavigation and in RootNavigation.

For example:

`RootNavigation`
``` js
const RootStackNavigation = StackNavigator(
    {
        Account: {
            screen: AccountNavigation,
        },
        Projects: {
            screen: ProjectNavigation,
        },
        ChildOfProjects: {
            screen: ChildOfProjectsScreen,
        },        
    },
    {
        navigationOptions: () => ({
            header: null,
        }),
    }
);
```

`ProjectNavigation`
``` js
const ProjectStackNavigation = StackNavigator(
    {
        ProjectOverview: {
            screen: ProjectOverviewScreen,
        },
        ScanView: {
            screen: ScanNavigation,
        },
        AddProject: {
            screen: AddProjectScreen,
        },
        EditProject: {
            screen: EditProjectScreen,
        },
        ChildOfProjects: {                                 // <------- Screen is available from two Navigators
            screen: ChildOfProjectsScreen,     
        },        
    },
    {
        navigationOptions: () => ({
            header: null,
        }),
    }
);

```
By putting your screens in the right navigators, potentially putting them in two places, and passing navigation props as screenProps to other navigators, you can get around where you need to.

In my opinion, it's very inelegant.

**Comment by dihan** [comment] 2018-03-06 08:04
@jeserodz TabNavigator is missing when I tried your example.

**Comment by brentvatne** [comment] 2018-03-06 22:42
@Laurensdc - can you describe this problem in depth on the issues on https://github.com/react-navigation/rfcs so we can discuss a more elegant solution?

**Comment by mauron85** [comment] 2018-03-09 10:40
@Laurensdc nice solution. But have question related to
>The way I described above is very tedious, and with the solution from jeresodz you can simply do this.props.navigate('Projects') because the navigators know the nested routes.

I think this is only possible if navigating to navigator that is children of navigator which are u navigating from, but it doesn't work way round (from child to parent). Only solution that works is yours. Would like to know if my conclusion is correct.

**Comment by Laurensdc** [comment] 2018-03-09 13:30
@shekharskamble @mauron85 I'm able to navigate to any screen from any screen, nested or not.

I'm currently using this structure:

```js
export const AppNavigator = StackNavigator(
    {
        Login: {
            screen: LoginScreen,
        },
        SetPassword: {
            screen: SetPasswordScreen,
        },

        mainFlow: {
            screen: TabNavigator(
                {
                    overviewFlow: {
                        screen: StackNavigator(
                            {
                                Overview: {
                                    screen: OverviewScreen,
                                },
                                DietitianInfo: {
                                    screen: DietitianInfoScreen,
                                },
                            },
                            {
                                headerMode: 'none',
                            }
                        )
                    },
                    Goals: {
                        screen: GoalsScreen,
                    },
                    diaryFlow: {
                        screen: StackNavigator(
                            {
                                DiaryOverview: {
                                    screen: DiaryOverviewScreen,
                                },
                                DiaryEntry: {
                                    screen: DiaryEntryScreen,
                                },
                            },
                            {
                                headerMode: 'none',
                            }
                        )
                    },

                    Notes: {
                        screen: NotesScreen,
                    },
                },
                {
                    tabBarPosition: 'bottom',
                    navigationOptions: ({ navigation }) => ({
                        // ...                         
                    }),
                    tabBarOptions: {
                       // ...
                    },
                }
            )
        }
    },
    {
        headerMode: 'none',
        // onTransitionStart: (e) => {
        //     console.log('Navigating somewhere');
        //     console.log(e);
        // },
    }
);
```

I can navigate from `DiaryEntry` to `LoginScreen`, and from `LoginScreen` to `DiaryEntry`. Simply with `this.props.navigation.navigate('DiaryEntry')`.

**Comment by mauron85** [comment] 2018-03-09 15:12
@Laurensdc wondering what I'm doing wrong, because navigating from nested child to parent in my case don't do anything (no error but also no action). Anyway thank you, at least now I know it's possible and my issue.

BTW what version are you using?

**Comment by mauron85** [comment] 2018-03-12 07:56
Ok I figured it out. My problem was having plain React component which contained TabNavigator in the flow.

These are just the examples:

```
const MyTabNavigator = TabNavigator({
  Tab1: Tab1,
  Tab2: Tab2,
});

const ScreenWrappingMyTabNavigator = ({ navigation }) => {
  const { params } = navigation.state;
  return (
    <MyTabNavigator screenProps={params} />
  );
};

const AppNavigator = StackNavigator({
  Login: { screen: LoginScreen },
  mainFlow: {
    screen: StackNavigator({
       Screen1: Screen1,
       Screen2: ScreenWrappingMyTabNavigator
    })
  }
});

```

Navigating from `ScreenWrappingMyTabNavigator` to `Login` was not working until I passed `navigation` prop from TabNavigator to ScreenWrappingMyTabNavigator.

```
const ScreenWrappingMyTabNavigator = ({ navigation }) => {
  const { params } = navigation.state;
  return (
    <MyTabNavigator navigation={navigation} screenProps={params} />
  );
};
// maybe also this (used to be required in v1.0.0)
ScreenWrappingMyTabNavigator.router = MyTabNavigator.router;
``` 

I used to have same syntax and was working fine with `react-navigation 1.0`, but somehow it stopped working with `1.5`. In my project i'm wrapping lot components with redux connect which I guess might also intervene with Components like `ScreenWrappingMyTabNavigator` from my example.

**Comment by jamesone** [comment] 2018-06-08 07:56
Is there a better way of handling this with react-navigation 2.0?

**Comment by brentvatne** [comment] 2018-06-08 16:03
i'm not sure i really understand this thread. the original question can be answered by just `this.props.navigation.navigate('SecondTabScreen');`. if you are still having an issue here then please create a new issue and provide a minimal reproducible example and explain it as clearly as possible
