### ISSUE TITLE
Multiply screens open when calling navigation.navigate() with the same navigate action multiply times

### ISSUE THREAD

**Issue by timhonders** [react-community/react-navigation#471] opened 2017-02-24 09:49 UTC
**Problem:**

We have the following issue, when a user pushes a button a couple of times and navigation.navigate() gets called a couple of times.

Multiply screens will open.

**Reproduce:**

Run NavigationPlayground and push a random menu item a couple of times.

**Solution:**

Expand the check in the dispatch function in createNavigationContainer.js, if the NavigationActions.NAVIGATE has the same routeName don't dispatch.

Somthing like:

```
let lastRouteName = (state.action ? state.action.routeName : '');

if (nav && nav !== state.nav && (action.type == NavigationActions.NAVIGATE && action.routeName !== lastRouteName || action.type != NavigationActions.NAVIGATE)) {

if (console.group) {
	console.group('Navigation Dispatch: ');
	console.log('Action: ', action);
	console.log('New State: ', nav);
	console.log('Last State: ', state.nav);
	console.groupEnd();
} else {
	console.log('Navigation Dispatch: ', { action, newState: nav, lastState: state.nav });
}

this.setState({ nav:nav, action:action});
```

If this is a good solution i can make a PR

**Comment by grabbou** [comment] 2017-02-24 10:15
> We have the following issue, when a user pushes a button a couple of times and navigation.navigate() gets called a couple of times.

I believe this is very application specific behaviour and any should be taken care of by library consumers. You could easily do that by debouncing the method that gets called on button press for instance or making it disabled after firing initial action.

**Comment by satya164** [comment] 2017-02-24 10:27
Duplicate of #271

**Closed** 2017-02-24 10:27 UTC

**Comment by satya164** [comment] 2017-02-24 10:29
> if the NavigationActions.NAVIGATE has the same routeName don't dispatch.

I don't think this is good solution. Same route name could have different params and it should work when you have multiple profile screens of different users, for example.
