### ISSUE TITLE
How to realize function like navigator.replace() ?

### ISSUE THREAD

**Issue by justbettereveryday** [react-community/react-navigation#774] opened 2017-03-22 06:46 UTC

**Comment by rmevans9** [comment] 2017-03-22 13:02
You would import `NavigationActions` and call/dispatch `NavigationActions.reset`.

Docs: https://reactnavigation.org/docs/navigators/navigation-prop#Reset

**Comment by justbettereveryday** [comment] 2017-03-23 13:20
Yeah，I had tried this last night,and it does well
Thanks!

**Comment by joonhocho** [comment] 2017-03-24 08:42
@rmevans9 @justbettereveryday 
https://github.com/react-community/react-navigation/issues/802

I think `reset` is not what we want.
It sounds like `reset` will empty your stack instead of replacing one item in your stack.

**Comment by mgtitimoli** [comment] 2017-03-26 19:50
Meanwhile one could be able to do this by getting the whole state and overwriting the current route with the new one, the problem is that it's also not so easy to get the whole state, since in navation prop it's only the portion of the current route...

**Comment by MrHubble** [comment] 2017-05-30 06:55
@joonhocho `reset` now accepts a `key` parameter which allows you to specify what level of state you want to reset to: https://github.com/react-community/react-navigation/pull/789

There's also the option of overriding `getStateForAction` as shown in this video: [Replace a Screen Using React Navigation](https://youtu.be/-XULdsZWowU)

However, if `reset` (with a `key`) doesn't work as required then I agree that adding `replace` to the stack api would be much more user friendly than overriding `getStateForAction`.

**Comment by spencercarli** [comment] 2017-08-28 01:33
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:33 UTC
Labels: Type: Question

**Comment by joshuapinter** [comment] 2017-08-28 15:56
@spencercarli Hey Spencer, we ended up using your solution to create a replace method for react-navigation. Works pretty well besides not having an animation, but I still think this is less of a question and more of a feature request.

I think this should be added to the core library because it's such a common situation. And because this is the "standard" navigation library for React Native now, it should cover the most common situations, including replacing the current screen with a new screen and support an animation between those two.

**Comment by sibelius** [comment] 2017-08-30 21:47
```jsx
const reset = (navigation, routeName, params = {}) => {
  const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
          NavigationActions.navigate({ routeName, params })
      ],
  });

  navigation.dispatch(resetAction);
};
```

**Comment by joshuapinter** [comment] 2017-08-31 00:32
@sibelius Does that provide an animation?

**Comment by uinz** [comment] 2017-09-01 07:25
@joshuapinter no animation and feedback slowly

**Comment by icaromagalhaes** [comment] 2018-01-02 14:23
Any updates about the animation?

**Comment by mehulmpt** [comment] 2018-02-18 19:09
Any update on this?

**Comment by brentvatne** [comment] 2018-02-19 02:54
this was added recently: https://reactnavigation.org/docs/navigation-prop.html#replace

it doesn't have any animation. it'll take some work on the card stack transitioner to make an animation possible here.

**Comment by vkedwardli** [comment] 2018-02-26 15:17
Still a newbie in JS, but this is my hack for replace with animation (not submitting a pull request due to poor code quality)

https://github.com/react-navigation/react-navigation/compare/master...vkedwardli:feature/navigation-action-stack-replace-with-animation

basically you can just call `navigation.replaceWithAnimation(routeName, params, action)`

What I did: I remove the previous screen from the routes during `COMPLETE_TRANSITION` (so we can have animation) and then reset the Transitioner's navigation index to the correct values

My environment is a Stack (for those login / splash stuff) -> Tab -> Stack -> Tab, seems to be working on my side, YMMV

**Comment by brentvatne** [comment] 2018-03-06 23:58
cc @ericvicenti ^

**Comment by ericvicenti** [comment] 2018-03-07 00:33
Interesting hack, @vkedwardli! I've been thinking about how to get this right for a little while now, and I just had an idea.

Something has been missing in our navigation state that we pass from the stack router to the transitioner, and I think I just realized what it might be. Currently we hold 'isTransitioning' in state, but we don't know what key we were transitioning from. So instead of `isTransitioning`, what if we had `transitioningFromKey`, which specified the key we are currently moving away from.

With the following "before" state:
```
{
  index: 1,
  routes: [ {key: 'a'}, {key: 'b'} ],
  transitioningFromKey: null
}
```
When the state changes to this, there is no transition.
```
{
  index: 1,
  routes: [ {key: 'a'}, {key: 'c'} ],
  transitioningFromKey: null
}
```
When the state changes to this, we do an animated replace to 'c':
```
{
  index: 1,
  routes: [ {key: 'a'}, {key: 'c'} ],
  transitioningFromKey: 'b'
}
```

I think this might be the sanest way to model our transitioning state. It would also enable animations for reset.

Thoughts?

**Comment by liyanxi** [comment] 2018-05-09 17:53
@ericvicenti  
navigation.replace transitioning animation
Is this problem solved?

**Comment by hafizmuhammadshoaib** [comment] 2018-07-15 06:43
use this function to replace the history in react navigation:

this function in your root navigation file App.js

const prevGetStateForActionHomeStack = RootStack.router.getStateForAction;
RootStack.router.getStateForAction = (action, state) => {
  if (state && action.type === 'ReplaceCurrentScreen') {
    const routes = state.routes.slice(0, state.routes.length - 1);
    routes.push(action);
    return {
      ...state,
      routes,
      index: routes.length - 1,
    };
  }
  return prevGetStateForActionHomeStack(action, state);
};


call this function whenever you want to replace a screen
this.replaceScreen('routename')
replaceScreen = (route) => {
        // const { locations, position } = this.props.navigation.state.params;
        this.props.navigation.dispatch({
            type: 'ReplaceCurrentScreen',
            key: `${route}`,
            routeName: `${route}`,
            // params: { locations, position },
        });
    };

**Comment by hafizmuhammadshoaib** [comment] 2018-08-21 17:15
No it will not give you an animation.

**Comment by sjq9026** [comment] 2018-11-30 02:41
> @ hafizmuhammadshoaib thank you, it works like a charm!!
> 
> this is the formatted code:
> 
> Add this to your Root Navigator:
> 
> ```js
> const prevGetStateForActionHomeStack = HomeStack.router.getStateForAction;
> HomeStack.router.getStateForAction = (action, state) => {
>     if (state && action.type === 'ReplaceCurrentScreen') {
>       const routes = state.routes.slice(0, state.routes.length - 1);
>       routes.push(action);
>       return {
>         ...state,
>         routes,
>         index: routes.length - 1,
>       };
>     }
>     return prevGetStateForActionHomeStack(action, state);
>   },
> };
> ```
> 
> Use this to replace screen:
> 
> ```js
>   replaceScreen = (screen, params) => {
>     this.props.navigation.dispatch({
>       key: screen,
>       type: "ReplaceCurrentScreen",
>       routeName: screen,
>       params: params,
>     });
>   };
> ```
你好，使用这个方法之后报了一个异常如下，请教哈怎么处理 多谢

**Comment by hafizmuhammadshoaib** [comment] 2018-11-30 06:20
please give me some code from where you are calling this code?? are you using a drawer???

**Comment by bashirpour** [comment] 2018-12-19 12:44
import {StackActions} from 'react-navigation';
	import {NavigationActions} from 'react-navigation';

	const resetAction = StackActions.reset({
	    index: 1,
	    actions: [
	    	// add other screen if you want
	        NavigationActions.navigate({routeName: 'screen2'}),
	        NavigationActions.navigate({routeName: 'newScreen'}),
	    ],
	});
