### ISSUE TITLE
Having back button re-render the page when going back

### ISSUE THREAD

**Issue by ptz3233** [react-community/react-navigation#1857] opened 2017-06-13 15:10 UTC
I can't seem to figure out if there is any event or easy way to this. I have a page that represents an object, and a button to a page that allows you to modify something on that page. If I make the submit button just goBack, it doesn't register the changes. If I make it open a new copy of the previous page, then there are two copies of the page on the stack. Is there a way to manually pop something from the stack? (maybe not even popping because it would be removing something thats not on the top)

**Comment by njt1982** [comment] 2017-07-19 07:54
@manoharank posted one possible solution to this here: https://github.com/react-community/react-navigation/issues/922#issuecomment-304827787

(I have the same issue)

**Comment by spencercarli** [comment] 2017-08-31 14:29
Could you add some code examples to this? A running example demonstrating the current behavior with a description of how you would like it to work would be even better. Thanks!

**Comment by kelset** [comment] 2017-11-12 10:58
Closing since OP hasn't replied to Spencer.

(duplicate of https://github.com/react-community/react-navigation/issues/922 & https://github.com/react-community/react-navigation/issues/1617)

**Closed by kelset** 2017-11-12 10:58 UTC
Labels: feature request, needs more info
