### ISSUE TITLE
react-navigation in "react-native": "0.43.2"show error  code 500

### ISSUE THREAD

**Issue by shaoyi52** [react-community/react-navigation#979] opened 2017-04-10 07:50 UTC
react-navigation in "react-native": "0.43.2"show error code；
code message："Unable to resolve modele 'react/lib/ReactComponentWithPureRenderMixin';"
is react-native error or react-navigation error?

**Comment by danielbrodin** [comment] 2017-04-10 08:07
This is solved if you use the master branch, so I guess it will be in the next release.

**Comment by ragnorc** [comment] 2017-04-10 08:30
#923

**Comment by ragnorc** [comment] 2017-04-10 08:30
#923

**Comment by AlMel3000** [comment] 2017-04-10 12:23
Same mistake on not master branch

**Comment by tangentlin** [comment] 2017-04-10 15:40
Since this question has been asked numerous times, what is preventing master branch from being released to NPM?

**Comment by sibelius** [comment] 2017-04-10 17:05
please check rn-diff https://github.com/ncuillery/rn-diff

```
"react": "16.0.0-alpha.6",
    "react-native": "0.43.1",
```

**Comment by henrikra** [comment] 2017-04-18 13:56
This is serious problem <.<

**Comment by smhatre59** [comment] 2017-04-21 08:25
Same issue occurred even when I pulled from master branch in node_modules folder
versions:
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-navigation": "^1.0.0-beta.7" 
Detailed error:
error: bundling: UnableToResolveError: Unable to resolve module `prop-types` from `App/node_modules/react-navigation/src/views/withNavigation.js`: Module does not exist in the module map or in these directories

**Comment by matthamil** [comment] 2017-08-03 02:47
Hi there! This issue is being closed because it has been inactive for a while. We're closing issues after a period of inactivity. Please do not take this personally :)
If you think this issue should remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:
* Does the issue still reproduce on the latest release? Post a comment with the version you tested.
* If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/react-community/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md).
* Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.
If you would like to work on a patch to fix the issue, contributions are very welcome! Read through the [contributors guide](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md), and feel free to hop into [#react-navigation](https://reactiflux.com) if you need help planning your contribution.

**Closed by matthamil** 2017-08-03 02:47 UTC
