### ISSUE TITLE
DrawerNavigator bug in 1.0.0-beta.22

### ISSUE THREAD

**Issue by ahmetabdi** [react-community/react-navigation#3175] opened 2017-12-22 15:04 UTC
When you provide the DrawerNavigatorConfig option the application crashes in `DrawerNavigator(RouteConfigs, DrawerNavigatorConfig)`

It looks like this is not even being tested in the code https://github.com/react-community/react-navigation/blob/1ca407b5ec9bb40d7870b2a5c3db99973b20425b/src/navigators/__tests__/DrawerNavigator-test.js

`"react-navigation": "^1.0.0-beta.22"`

Example:

```
const DrawerStack = DrawerNavigator({mapScreen: {screen: MapScreen}}, {});

const PrimaryNav = StackNavigator({
  drawerStack: { screen: DrawerStack }
}, {
  headerMode: 'none',
  initialRouteName: 'drawerStack'
})

export default PrimaryNav
```

<img width="371" alt="screen shot 2017-12-22 at 15 00 43" src="https://user-images.githubusercontent.com/778015/34302564-63e490e6-e729-11e7-869e-95258329b91d.png">

**Comment by kelset** [comment] 2017-12-22 17:01
Duplicate of https://github.com/react-community/react-navigation/issues/3148

**Closed by kelset** 2017-12-22 17:01 UTC
