### ISSUE TITLE
Proposal: make Stack Navigator animations the same for android and ios

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#461] opened 2017-02-23 17:32 UTC
Topic is in the title.

The Stack Navigator appears to produce different screen transition animations b/w android and ios. On android, the next screen does a slide up animation. While on ios, the next screen does a slide left animation. I would propose that this animation be the same for both platforms.

I think one of my expectations with react native, and its ecosystem of tools, is that it produces more consistency between the android user experience and the ios user experience.

**Comment by xtreme-andleung** [comment] 2017-02-23 18:37
Hmm, I might disagree with that.  Android and iOS should feel 'native' and use their default designs.  It makes more sense to make an Android app feel Android-y following Google's material designs, while iOS should follow Apple's guidelines.  

Android are Android users and would be familiar with Android's user experience.  What I find when building cross-platform native apps is that people fight the native platform UI design to make the apps look and 'feel' like their counter-part.

Perhaps however what feature would be nice is to control the transition types for each platform to match what what your app is trying to achieve rather than make iOS and Android app look exactly the same.

**Comment by thurt** [comment] 2017-02-23 19:04
> Perhaps however what feature would be nice is to control the transition types for each platform to match what what your app is trying to achieve rather than make iOS and Android app look exactly the same.

this. if it is not consistent by default, I would like to see easy configuration options to make the animation transitions consistent.

**Comment by grabbou** [comment] 2017-02-23 19:08
I believe it's a duplicate of #308 then?

**Comment by grabbou** [comment] 2017-02-23 19:24
Okay, definitely a duplicate of #124 :)

**Closed by grabbou** 2017-02-23 19:24 UTC

**Comment by thurt** [comment] 2017-02-23 19:26
@grabbou killin it. thnx for links

**Comment by grabbou** [comment] 2017-02-23 19:27
No worries! Thanks for being an early adopter! Finding bugs and new features is what we need now!
