### ISSUE TITLE
Drawer navigation causes re-mounting of components

### ISSUE THREAD

**Issue by amirmatin** [react-community/react-navigation#3114] opened 2017-12-11 23:44 UTC
Having implemented the Drawer navigation, going from Component "Home" to "Settings" from Drawer and going back to "Home" causes the Home component to reload ... how can I prevent this ?

 thanks.!

**Comment by kelset** [comment] 2017-12-11 23:48
Closing because you haven't followed the issue template; please open a new one that **follows the template**.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-11 23:48 UTC

**Comment by amirmatin** [comment] 2017-12-11 23:50
@kelset  sorry, where is this template you are referring to ?

**Comment by kelset** [comment] 2017-12-11 23:51
The one that appears when you click on New Issue.
