### ISSUE TITLE
Closing Drawer Causes the app to re render itself and return to initial route.

### ISSUE THREAD

**Issue by NirBenya** [react-community/react-navigation#2503] opened 2017-08-31 07:57 UTC
### Current Behavior
When closing the drawer from any place, the App refreshes itself, and the initialRoute in the drawer config appears.
Changing "initialRoute" to "none", doesn't affect this behavior.

### Expected Behavior
When the drawer is closes , nothing will happen, nothing wil be re-rendered and we should stay on our current route.

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.46
| node             | 6.11.0
| npm or yarn      | 4.6.1

**Comment by NirBenya** [comment] 2017-08-31 08:45
solved by doing : 

```
const drawerAction = Drawers.router.getStateForAction;

Drawers.router= {
    ...Drawers.router,
    getStateForAction(action, state){

        const isCloseDrawerEvent = (state && action.type === 'Navigation/NAVIGATE' && action.routeName === 'DrawerClose');
        return isCloseDrawerEvent ? state : drawerAction(action, state);
    }
};```

**Comment by spencercarli** [comment] 2017-08-31 14:46
Please put together a reproduction of this issue. Thanks!

**Comment by benyanir** [comment] 2017-09-01 14:09
This is my navigation stack:

It seems like each time the drawer closes it open's the most top stack , in my case "Navigator" (which opens in modal mode. and go directly to it's initial route.

```
const navigationOptionsStyle = {
    headerTintColor: colors.WHITE,
    headerStyle: {
        backgroundColor: colors.CHERRY
    }
};

const navigationCommonOptions = {
        drawerLockMode: 'locked-closed'
};

const Tabs = TabNavigator({
    Path: {
        screen: PathContainer,
        navigationOptions: {
            title: 'Path',
            ...navigationCommonOptions
        }
    },
    Inbox: {
        screen: InboxContainer,
        navigationOptions: {
            title: 'Inbox',
            ...navigationCommonOptions
        }
    },
    Wishlist: {
        screen: WishlistContainer,
        navigationOptions: {
            title: 'Wishlist',
            ...navigationCommonOptions
        }
    },
    Settings: {
        screen: SettingsContainer,
        navigationOptions: {
            title: 'Settings',
            ...navigationCommonOptions
        }
    }
}, {
    tabBarComponent: NavbarContainer
});

const Stacks = StackNavigator({
    Tabs: {
        screen: Tabs,
        navigationOptions: {
            ...navigationCommonOptions
        }
    },
    Job: {
        screen: JobContainer,
        navigationOptions: ({ navigation }) => {
            return {
                title: (navigation.state.params.context === 'inbox') ? `It's a match` : 'Job',
                ...navigationCommonOptions
            }
        }
    }
}, {
    navigationOptions: {
        ...navigationOptionsStyle,
    },
});

const prevGetStateForActionHomeStack = Stacks.router.getStateForAction;

Stacks.router = {
    ...Stacks.router,
    getStateForAction(action, state) {

        if (state && action.type === 'ReplaceCurrentScreen') {
            const routes = state.routes.slice(0, state.routes.length - 1);
            routes.push(action);
            return {
                ...state,
                routes,
                index: routes.length - 1,
            };
        }

        return prevGetStateForActionHomeStack(action, state);

    }
};

const Drawers = DrawerNavigator({
    Stacks: {
        screen: Stacks
    },
    Menu: {
        screen: MenuContainer,
        navigationOptions: {
            ...navigationCommonOptions
        }
    }
}, {
    contentComponent: MenuContainer,
    drawerPosition: 'right'
});

const Screens = StackNavigator({
    Login: {
        screen: LoginContainer,
        navigationOptions: {
            ...navigationCommonOptions
        }
    },
    Drawers: {
        screen: Drawers,
        navigationOptions: {
            ...navigationCommonOptions
        }
    }

}, {
    headerMode: 'none',
    navigationOptions: {
        gesturesEnabled: false,
        ...navigationCommonOptions
    }
});

const Navigator = StackNavigator({
    Screens: {
        screen: Screens,
        navigationOptions: {
            ...navigationCommonOptions
        }
    },
    Viewport: {
        screen: Viewport,
        navigationOptions: {
            ...navigationOptionsStyle,
            header: undefined,
            ...navigationCommonOptions
        }
    },

    RejectReasons: {
        screen: RejectReasons,
        navigationOptions: {
            ...navigationOptionsStyle,
            title: 'Reject Reasons',
            header: undefined,
            ...navigationCommonOptions
        }
    },

    Locations: {
        screen: LocationsContainer,
        navigationOptions: {
            ...navigationOptionsStyle,
            title: 'Locations',
            header: undefined,
            ...navigationCommonOptions
        }
    }
}, {
    mode: 'modal',
    navigationOptions: {
        header: null,
        headerBackTitle: 'Back',
        ...navigationCommonOptions
    }
});

export default Navigator;
```

**Comment by NirBenya** [comment] 2017-09-01 14:11
This is my navigation stack:

It seems like each time the drawer closes it open's the most top stack , in my case "Navigator" (which opens in modal mode. and go directly to it's initial route.

```
const navigationOptionsStyle = {
    headerTintColor: colors.WHITE,
    headerStyle: {
        backgroundColor: colors.CHERRY
    }
};

const navigationCommonOptions = {
        drawerLockMode: 'locked-closed'
};

const Tabs = TabNavigator({
    Path: {
        screen: PathContainer,
        navigationOptions: {
            title: 'Path',
            ...navigationCommonOptions
        }
    },
    Inbox: {
        screen: InboxContainer,
        navigationOptions: {
            title: 'Inbox',
            ...navigationCommonOptions
        }
    },
    Wishlist: {
        screen: WishlistContainer,
        navigationOptions: {
            title: 'Wishlist',
            ...navigationCommonOptions
        }
    },
    Settings: {
        screen: SettingsContainer,
        navigationOptions: {
            title: 'Settings',
            ...navigationCommonOptions
        }
    }
}, {
    tabBarComponent: NavbarContainer
});

const Stacks = StackNavigator({
    Tabs: {
        screen: Tabs,
        navigationOptions: {
            ...navigationCommonOptions
        }
    },
    Job: {
        screen: JobContainer,
        navigationOptions: ({ navigation }) => {
            return {
                title: (navigation.state.params.context === 'inbox') ? `It's a match` : 'Job',
                ...navigationCommonOptions
            }
        }
    }
}, {
    navigationOptions: {
        ...navigationOptionsStyle,
    },
});

const prevGetStateForActionHomeStack = Stacks.router.getStateForAction;

Stacks.router = {
    ...Stacks.router,
    getStateForAction(action, state) {

        if (state && action.type === 'ReplaceCurrentScreen') {
            const routes = state.routes.slice(0, state.routes.length - 1);
            routes.push(action);
            return {
                ...state,
                routes,
                index: routes.length - 1,
            };
        }

        return prevGetStateForActionHomeStack(action, state);

    }
};

const Drawers = DrawerNavigator({
    Stacks: {
        screen: Stacks
    },
    Menu: {
        screen: MenuContainer,
        navigationOptions: {
            ...navigationCommonOptions
        }
    }
}, {
    contentComponent: MenuContainer,
    drawerPosition: 'right'
});

const Screens = StackNavigator({
    Login: {
        screen: LoginContainer,
        navigationOptions: {
            ...navigationCommonOptions
        }
    },
    Drawers: {
        screen: Drawers,
        navigationOptions: {
            ...navigationCommonOptions
        }
    }

}, {
    headerMode: 'none',
    navigationOptions: {
        gesturesEnabled: false,
        ...navigationCommonOptions
    }
});

const Navigator = StackNavigator({
    Screens: {
        screen: Screens,
        navigationOptions: {
            ...navigationCommonOptions
        }
    },
    Viewport: {
        screen: Viewport,
        navigationOptions: {
            ...navigationOptionsStyle,
            header: undefined,
            ...navigationCommonOptions
        }
    },

    RejectReasons: {
        screen: RejectReasons,
        navigationOptions: {
            ...navigationOptionsStyle,
            title: 'Reject Reasons',
            header: undefined,
            ...navigationCommonOptions
        }
    },

    Locations: {
        screen: LocationsContainer,
        navigationOptions: {
            ...navigationOptionsStyle,
            title: 'Locations',
            header: undefined,
            ...navigationCommonOptions
        }
    }
}, {
    mode: 'modal',
    navigationOptions: {
        header: null,
        headerBackTitle: 'Back',
        ...navigationCommonOptions
    }
});

export default Navigator;
```

**Comment by kelset** [comment] 2017-12-03 11:17
Pinging OP @NirBenya since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment] 2017-12-10 12:32
Hi there @NirBenya ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-12-10 12:32 UTC
Labels: 7 days countdown, bug, component: Drawer
