### ISSUE TITLE
how to close drawer screen

### ISSUE THREAD

**Issue by ngankt2** [react-community/react-navigation#3176] opened 2017-12-23 02:02 UTC
Step1: i'm on the home Screen and I open the menu. and them i click to one category in menu 
I just want to close the menu and switch to the new screen "ProductList".
and I've used:
```
this.props.navigation.navigate('ProductList', {category});
this.props.navigation.navigate('DrawerToggle');
```
But it close menu and go home Screen ;(

**Comment by kelset** [comment] 2017-12-23 09:23
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

Moreover I highly suggest you check the README; there's a link to a series of articles about how to use Drawers that will surely help you.

**Closed by kelset** 2017-12-23 09:23 UTC
