### ISSUE TITLE
Changing screenProps does not trigger a re-render

### ISSUE THREAD

**Issue by Ehesp** [react-community/react-navigation#602] opened 2017-03-07 14:39 UTC
I've got a single instance of a TabNavigator, which I'm using to pass through various props via `screenProps`. When the page updates state, I use the same instance of the navigator and send the new props through. The screens though do not update.

Pseudo code:

```javascript

constructor(props) {
  super(props);
  this.navigator = TabNavigator(props.pages);
}

render() {
  return (
    <this.navigator 
       screenProps={{
         data: this.state.data,
       }}
    />
  );
}
```

When `data` updates in state, my pages/screens do not get the new data. Is this expected?

The reason for doing it this way, is that currently when state updates and I return a new TabNavigator, the page resets back to the first page. I was hoping this was a way around it.

EDIT: Using beta6

**Comment by Ehesp** [comment] 2017-03-07 14:47
Related https://github.com/react-community/react-navigation/issues/577

**Comment by Ehesp** [comment] 2017-03-07 15:17
Doing some digging around, it seems as though `TabView` wraps `withCachedChildNavigation`, which is a `PureComponent`. If `screenProps` contains a nested object it won't update.

**Comment by grabbou** [comment] 2017-03-07 15:37
Closing as it's a duplicate of #577

**Closed by grabbou** 2017-03-07 15:37 UTC
