### ISSUE TITLE
How to reach this.method() from StackNavigator titlebar components?

### ISSUE THREAD

**Issue by dht** [react-community/react-navigation#2690] opened 2017-10-04 16:36 UTC
``` JS
export default class ContactDetails extends Component {
    static navigationOptions = {
        headerRight: <Save onPress={this.save} />
    };
   ....
```

How to reach this.state from a headerRight component in a StackNavigator screen?

**Comment by andrew-wagner89** [comment] 2017-10-04 20:32
The only solution I have found for this is to call setParams() in componentDidMount and then access the params in the state like so: `static navigationOptions = ({ navigation }) => {
    const { params } = navigation.state;
    if (params) {
      return {
        headerRight: (
          <TouchableOpacity onPress={params.switchEditing}>
            <Text style={{ color: "white", fontSize: 17, marginRight: 10 }}>
              {params.editing ? "Cancel" : "Edit"}
            </Text>
          </TouchableOpacity>
        )
      };
    } else {
      return {
        headerRight: (
          <TouchableOpacity>
            <Text style={{ color: "white", fontSize: 17, marginRight: 10 }}>
              Loading
            </Text>
          </TouchableOpacity>
        )
      };
    }
  };

  componentDidMount() {
    this.props.navigation.setParams({
      switchEditing: this.switchEditing,
      editing: this.state.editing
    });
  }`

**Comment by vonovak** [comment] 2017-10-08 10:17
this is a duplicate of #145

**Comment by vonovak** [comment] 2017-10-11 11:48
@spencercarli this can be closed

**Closed** 2017-10-11 21:47 UTC
