### ISSUE TITLE
Change color of HeaderBackButton

### ISSUE THREAD

**Issue by Ehesp** [react-community/react-navigation#98] opened 2017-01-30 20:02 UTC
HeaderBackButton requires the `assets/back-icon.png` file, which on Android is a black back arrow.
Is it possible to change the color of this?

I noticed there is a tintColor prop, but on the `Header.js` file it only has the following:

```
      return (
        <HeaderBackButton
          onPress={props.onNavigateBack}
        />
      );
```

**Comment by satya164** [comment] 2017-01-30 20:03
Duplicate of #36

**Closed by satya164** 2017-01-30 20:03 UTC

**Comment by Ehesp** [comment] 2017-01-30 20:12
Ah sorry :)
