### ISSUE TITLE
 [bug] SafeAreaView

### ISSUE THREAD

**Issue by vance-liu** [react-community/react-navigation#2861] opened 2017-11-01 09:10 UTC
tabBarOptions style is no help when pass style props to SafeAreaView, like [https://github.com/react-community/react-navigation/blob/185289ad6658e07783c807ee7ac29b9e1244fa21/src/views/TabView/TabBarBottom.js#L183](link), or same code.

**Comment by kelset** [comment] 2017-11-01 09:13
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-01 09:13 UTC
