### ISSUE TITLE
Navigate and delete previous route... possible?

### ISSUE THREAD

**Issue by aroth** [react-community/react-navigation#295] opened 2017-02-11 02:41 UTC
Screen structure:
```
Home
  --> Login         (back button goes to Home)
  --> Sign Up       (back button goes to Home)
     --> Login      (back button goes to Sign Up, but I'd like it to go Home)
```

- From the 'Home' screen a user can navigate to 'Sign Up' or 'Login'
- From 'Sign Up' a user can also navigate to 'Login'
  - The back button will return the user to the 'Sign Up' screen, but I'd like to return to 'Home' instead (essentially removing the 'Sign Up' route from the stack).

This code works, but without animation as it's a reset: 
```
//
// SignUpScreen
//
  navigateToLogin() {
    const resetAction = NavigationActions.reset({
      index: 1,
      actions: [
        NavigationActions.navigate({ routeName: 'Home' }),
        NavigationActions.navigate({ routeName: 'Login' })
      ]
    });

    this.props.navigation.dispatch(resetAction);
}
```

What may be the ideal way to achieve this?

**Comment by ericvicenti** [comment] 2017-02-13 06:31
To hack it with the current API, you could override the router getStateForAction and do some extra logic to remove it from the stack.

But ideally you would be able to configure login and sign up as routes that can replace each-other. Then, when navigating between them, you would actually replace but the card stack would make it look like a push. There is no existing mechanism for this, but if you want to post a more detailed proposal of how routes could be configured to replace eachother, I'd be in support of it.

**Comment by satya164** [comment] 2017-02-13 11:21
I think we could maybe document this particular example. It's a very common case.

**Comment by ericvicenti** [comment] 2017-02-13 16:25
Agreed, maybe somebody could add it to [this area of the routers doc](https://reactnavigation.org/docs/routers/#Custom-Navigation-Actions).

**Comment by MichalZalecki** [comment] 2017-02-26 14:57
Is this acceptable solution? It works perfectly fine for me although `newIndex = newRoutes.length - 1;` somehow feels wrong.

```js
const prevGetStateForAction = MyApp.router.getStateForAction;

MyApp.router.getStateForAction = (action, state) => {
  // Do not allow to go back from Login
  if (action.type === "Navigation/BACK" && state && state.routes[state.index].routeName === "Login") {
    return null;
  }
  // Do not allow to go back to Login
  if (action.type === "Navigation/BACK" && state) {
    const newRoutes = state.routes.filter(r => r.routeName !== "Login");
    const newIndex = newRoutes.length - 1;
    return prevGetStateForAction(action, { index: newIndex, routes: newRoutes });
  }
  return prevGetStateForAction(action, state);
};
```

**Comment by MichalZalecki** [comment] 2017-02-26 14:59
Is this acceptable solution? It works fine for m although `const newIndex = newRoutes.length - 1;` somehow feels wrong.

```js
Navigator.router.getStateForAction = (action, state) => {
  // Do not allow to go back from Login
  if (action.type === "Navigation/BACK" && state && state.routes[state.index].routeName === "Login") {
    return null;
  }
  // Do not allow to go back to Login
  if (action.type === "Navigation/BACK" && state) {
    const newRoutes = state.routes.filter(r => r.routeName !== "Login");
    const newIndex = newRoutes.length - 1;
    return prevGetStateForAction(action, { index: newIndex, routes: newRoutes });
  }
  return prevGetStateForAction(action, state);
};
```

**Comment by 13860120868** [comment] 2017-05-05 08:40
hack getStateForAction works on android, but it would have problem in IOS when user go back trigger by gesture, the problem is UI has switch back and the the router state is block and become inconsistency.

I am seeking a way of blocking gesture in IOS in some case we don't allow to back e.g, but cannot find a good solution.

**Comment by keshavkaul** [comment] 2017-05-10 09:35
@13860120868 @ericvicenti @satya164 We should have a way to pop the current screen and push the next screen. In iOS, we can do this easily. Any thoughts on the effort required? I need this feature in my app so, I wouldn't mind making a PR but need some guidance on where to start.

**Comment by 13860120868** [comment] 2017-05-22 22:40
@keshavkaul Yes, it's possible to do by hack "getStateForAction", I do in in this way:
1) hack getStateForAction to support carrying options parameters on back
2) Based on parameter to jump to new target page.

`Navigator.router.getStateForAction = (action, state) => {
            if(state && action.type === 'BACK') {
                let backRouteIndex = null;
                let routes, backRoute;

                if (action.key) {
                  backRoute = state.routes.find((route: *) => route.key === action.key);//TODO: Can be route.routeName
                  backRouteIndex = state.routes.indexOf(backRoute);
                }

                if (backRouteIndex == null) {
                    backRouteIndex = -1;
                }

                routes = state.routes.slice(0, backRouteIndex);

                if(action.params) {
                  backRoute = routes[routes.length - 1];
                  const params = {
                    ...backRoute.params,
                    ...action.params,
                  };

                  routes[routes.length - 1] = {
                    ...backRoute,
                    params,
                  };
                }

                return {
                    ...state,
                    routes: routes,
                    index: routes.length - 1,
                };
            }

            return defaultGetStateForAction(action, state);
        };`

----------
`goBack: () => {
                this.props.navigation.dispatch({
                    type: 'BACK',
                    key: 'Home',
                    params: {forwardTo: "Some page"}
                });
            }`

----------
`componentWillReceiveProps(nextProps) {
        let {forwardTo} = nextProps.navigation.state.params;
        if(forwardTo) {
            this.props.navigation.navigate(forwardTo);
        }
    }`

It's not too difficult to combine these two steps in one single new navigation dispatch action to pop the current screen and push the next screen, I just doesn't have a good name for this popAndPush action:), and in some case we need to pop several screens and then push to the next screen like backAndPush.

**Comment by stokesbga** [comment] 2017-05-31 04:28
I'm confused why this is not built in. Is this anti-pattern? Definitely should have a ```replace``` method

**Comment by peacechen** [comment] 2017-06-12 14:46
@13860120868  --  Thanks for the example.

> t's not too difficult to combine these two steps in one single new navigation dispatch action to pop the current screen and push the next screen, I just don't have a good name for this popAndPush action

I would call it `replace`, and I wholeheartedly agree that there are cases where we need to replace several screens at once.  We could call it `replaceAt`, specifying the screen at which to go back to (could be multiples).

**Comment by nloomans** [comment] 2017-06-15 14:29
For everyone coming here from Google, it should be noted that you can use the reset action in order to navigate to a screen and clear the *entire* history.

https://reactnavigation.org/docs/navigators/navigation-actions#Reset

**Comment by douglasjunior** [comment] 2017-06-17 20:34
Like @nloomans  says, I used `Reset` to this, but Reset have no animation. 

Is it possible to add animation in the Reset?

**Comment by neetocode** [comment] 2017-07-13 03:19
Is there any solution to the problem of 'replacing' the stack of routes?

**Comment by xhou** [comment] 2017-07-22 00:20
@nloomans The issue with reset is I don't want to ruin the entire history.

**Comment by voidstarfire** [comment] 2017-08-02 07:39
Any progress on this? How is this not a feature from day 1 amazes me.

**Comment by justinlok** [comment] 2017-08-11 09:20
Looking for this feature as well.

**Comment by baba43** [comment] 2017-08-18 09:05
Looking for this too.

**Comment by icesyc** [comment] 2017-08-21 07:29
Looking for this feature..
I used the reset api, it did the work with animation
But I think, there should be a replace api

**Comment by joshuapinter** [comment] 2017-08-22 22:45
@icesyc Can you provide a snippet of code how you used the `reset` and achieved an animation as well? That would be great. Thanks!

**Comment by limichange** [comment] 2017-08-22 22:58
```js
    import { NavigationActions } from 'react-navigation'

    // ...

    this.props.navigation.dispatch(NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'homel' })
      ]
    }))
```

**Comment by joshuapinter** [comment] 2017-08-24 14:58
@limichange If you're 4 levels deep in navigation, is it possible to keep that existing stack and just use reset to replace the current screen?

**Comment by justinlok** [comment] 2017-08-24 15:42
@joshuapinter check this out: https://medium.com/handlebar-labs/replace-a-screen-using-react-navigation-a503eab207eb

Some of the solutions others have mentioned earlier in this thread might be similar. I just used exactly what's in the link and it works perfectly.

**Comment by joshuapinter** [comment] 2017-08-24 16:06
@justinlok Thanks. Yeah, that's what we're using now but there's no animations. @icesyc mentioned that they were using reset and also achieving animations so that's why I was interested in hearing the solution.

**Comment by guerjon** [comment] 2017-08-28 21:06
Hello, everybody, this solution works for me but I have another problem, the previous render screens are re-render on, I mean the methods componentWillMount,componendDidMount are called again on my previously screens, the same with reseStack, it's any way to just delete the current screen and don't re-render the previous screens?

**Comment by leesolway** [comment] 2017-08-31 15:32
A replace method would be amazing to have, and should be built into the lib.

**Comment by voidstarfire** [comment] 2017-09-04 13:06
I created some methods, only thing I can't figure out is how to get the transition animation (Friggin mess in this library) working for 'Pop' feature.

When navigating simple add the type, example:

```
// PopPreviousScreen will remove the previous screen, even if it's the same screen.
this.props.navigation.dispatch(NavigationActions.navigate({
                    routeName: 'SomeScreenToGoToo',
                    type: 'PopPreviousScreen',
```
```
// GoBackToRoute will go back to any previous route via name.
this.props.navigation.dispatch(NavigationActions.navigate({
                    routeName: 'SomeScreenToGoToo',
                    type: 'GoBackToRoute',
```
Now the code, if someone could help me to get transitions working for 'PopPreviousScreen' that would be great:

My transitioner
```
const DefaultTransitionSpec = ({
  duration: 500,
  easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
  timing: Animated.timing,
});

let TransitionConfiguration = () => {
  return {
    transitionSpec: DefaultTransitionSpec,
    // Define scene interpolation, eq. custom transition
    screenInterpolator: (sceneProps) => {

      const { scene } = sceneProps;
      const { index, route } = scene;
      const params = route.params || {};

      if (params.transition) {
        return params.transition(sceneProps);

      } else {
        return DefaultAndroid(sceneProps);
      }
    }
  }
};
```

The code that adds two new types, 'GoBackToRoute' & 'PopPreviousScreen'

```
const AppNavigator = StackNavigator(routes, { transitionConfig: TransitionConfiguration });

const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('ScreenStart'));

// Save the function for default navigation actions.
const defaultGetStateForAction = AppNavigator.router.getStateForAction;

AppNavigator.router.getStateForAction = (action, state) => {

  // Go to a screen via name.
  if (state && action.type === 'GoBackToRoute') {

    // Get the index of the root we want to go too.
    let index = state.routes.findIndex((item) => {
      return item.routeName === action.routeName;
    });

    // Find the scene active.
    const routeToGoBackToo = state.routes.slice(0, index + 1);

    return {
      routes: routeToGoBackToo,
      index
    };
  }

  // Remove previous screen.
  if (state && action.type === 'PopPreviousScreen') {

    const routeToGoBackToo = state.routes.slice(0, state.routes.length - 1);

    // New routes for application, removing previous ones.
    const routes = [
      ...routeToGoBackToo,
      { key: (Math.random() * 1e32).toString(36), routeName: action.routeName, params: action.params }
    ];

    return {
      routes,
      index: routes.length - 1,
    };

  }

  return defaultGetStateForAction(action, state);
};
```

**Comment by voidstarfire** [comment] 2017-09-04 14:23
I've figured it out (working with any transitions)

You only need to override the function **getStateForAction**

Here are two new types that will allow you to do basic routing (Which should be supported by default).
**PopPreviousScreen** (Removes the previous screen from the stack)
**GoBackToRoute** (Goes back to any route via the name)
**PopStack** (Marks all previous routes apart from the root dead)

Whenever you navigate simply add the type for example: 
```
            const navAction = NavigationActions.navigate({
                routeName: 'SomeScreenToGoToo',
                type: 'PopStack',
                params: {
                    transition: SlideInFromRight
                }
            });
            navigation.dispatch(navAction);
```

```
// Called when the navigator needs the next state.
AppNavigator.router.getStateForAction = (action, state) => {

  // Go to a screen via name.
  if (state && action.type === 'GoBackToRoute') {

    // If a route is dead, remove it from the state so we don't animate it when we go back.
    if (state && state.routes) {
      state.routes = state.routes.filter((eachRoute) => {
        if (eachRoute.params && eachRoute.params.isDead) {
          return !eachRoute.params.isDead;
        }
        return true;
      });
    }

    // Get the index of the root we want to go too.
    let index = state.routes.findIndex((item) => {
      return item.routeName === action.routeName;
    });

    // Find the scene active.
    let routeToGoBackToo = state.routes.slice(0, index + 1);

    return {
      routes: routeToGoBackToo,
      index
    };
  }

  // Remove all the previous routes apart from the start route.
  if (state && action.type === 'PopStack') {

    let routesFinal = state.routes.slice(0, state.routes.length);

    // Remove previous popped screens for performance reasons.
    routesFinal = routesFinal.filter((eachRoute, index) => {
      // We don't remove the current route so we get an animation.
      if (index == routesFinal.length - 1) {
        return true;
      }
      // Remove previous routes.
      if (eachRoute.params && eachRoute.params.isDead) {
        return !eachRoute.params.isDead;
      }
      return true;
    });

    routesFinal = routesFinal.map((eachRoute, index) => {
      // Don't pop final on the first route.
      if (index != 0) {
        if (eachRoute.params) {
          eachRoute.params.isDead = true;
        } else {
          eachRoute.params = { isDead: true };
        }
      }
      return eachRoute;
    });

    const routes = [
      ...routesFinal,
      { key: (Math.random() * 1e32).toString(36), routeName: action.routeName, params: action.params }
    ];

    return {
      routes,
      index: routes.length - 1,
    }
  }

  // Remove previous screen.
  // We can't remove it from the state right away otherwise the animation won't work correctly, so we mark 'isDead'
  if (state && action.type === 'PopPreviousScreen') {

    let routesFinal = state.routes.slice(0, state.routes.length);

    // Mark screen as dead, dead screens are filtered on 'GoBackToRoute' navigation.
    if (routesFinal[routesFinal.length - 1]) {
      if (!routesFinal[routesFinal.length - 1].params) {
        routesFinal[routesFinal.length - 1].params.isDead = true;
      } else {
        routesFinal[routesFinal.length - 1].params = { isDead: true };
      }
    }

    // Remove previous popped screens for performance reasons.
    routesFinal = routesFinal.filter((eachRoute, index) => {

      // We don't remove the current route so we get an animation.
      if (index == routesFinal.length - 1) {
        return true;
      }

      // Remove previous routes.
      if (eachRoute.params && eachRoute.params.isDead) {
        return !eachRoute.params.isDead;
      }

      return true;
    });

    // New routes for application, removing previous ones.
    const routes = [
      ...routesFinal,
      { key: (Math.random() * 1e32).toString(36), routeName: action.routeName, params: action.params }
    ];

    return {
      routes,
      index: routes.length - 1,
    };
  }

  return defaultGetStateForAction(action, state);
};
```

**Comment by peacechen** [comment] 2017-09-05 15:53
Thanks for the example @voidstarfire .  This is a good example of the excessive boilerplate needed to work around the missing replace method.

**Comment by voidstarfire** [comment] 2017-09-08 21:38
Don't bother with this library it's useless and not being maintained, use the Wix one instead; much much better.

**Comment by douglasjunior** [comment] 2017-09-09 00:51
>Don't bother with this library it's useless and not being maintained, use the Wix one instead; much much better.

@voidstarfire  It's not true.

![image](https://user-images.githubusercontent.com/1512341/30235533-b35fc394-94df-11e7-9eb9-0c564aca6d31.png)

This library has problems, but is still in development and in activity. And Wix also has problems, starting with the installation overhead.

**Comment by voidstarfire** [comment] 2017-09-09 06:58
The installation overhead is 5 minutes, I've wasted countless days on this library trying to hack it only to get a shoddy result, some of the features not included are outstanding and the Android animations look and feel non-Android at all. 

- This library will not pass standard QA.
- Previous screens are rendered resulting in low performance, how is this even a thing?
- goBack will not work with ID's half of the time
- Complex animation system, no defaults for platforms provided.
- No events and endless discussion with no result, Wix has 'willAppear', etc very simple.
- Component never un-mounts
- No popToRoot or popStack by default (Extremely standard thing for a navigator to have)
- No popAndReplace by default
- Serve lack of documentation, end up hunting for broken solutions around the web
- Have to implement a mapToProps hack just to passProps.. (Again should be standard)
- Redux is misused in this lib completely
- Animations are fixed to indexes, so editing routes / switching routes breaks animations. No way to fix. Ridicules. (Reset for example....)

I could go on but:

All in all by far the worst experience (I'm not the only one) I've had with React Native is this lib and I implore other people NOT to use it, don't waste you time.

**Comment by kelset** [comment] 2017-09-09 10:02
As we mentioned many times in many issues, this library is in a transition phase - so saying this like "the worst experience (I'm not the only one) I've had with React Native" is just being toxic.

It seems people forget that this is a **community maintained** library, so if you want a feature that is not there yet, instead of just complaining you could send a PR. We, collaborators, are dedicating our spare time to trying to get this lib back on track; using GitHub issues to complain is **not** helpful.

I'm going to close this issue since a couple of solutions provided help solving the initial problem, and we'll work on having a better implementation in future versions.

**Closed by kelset** 2017-09-09 10:02 UTC
Labels: Component: Docs, Type: Good First Task

**Comment by voidstarfire** [comment] 2017-09-09 10:04
I'm not being toxic I'm warning people off this library and I think they deserve to know and to avoid the pains that developers are having with it.

**Comment by voidstarfire** [comment] 2017-09-09 10:06
This issue isn't resolved at all, how to make a library better: Close hot issues that are obviously not resolved, great job.

**Comment by douglasjunior** [comment] 2017-09-09 13:37
@voidstarfire you who contaminated the issue with unnecessary discussions. Please, if a comment is unrelated to the problem itself, it does not need to be posted.

**Comment by hmenzagh** [comment] 2017-09-09 19:46
This is indeed a problem i've been facing for months and no solution has proven to be stable or scalable enough for me to use ..  @kelset closing this has no sense .. it should be a priority .. (I personally dont have the skills to do a PR myself .. )

**Comment by icesyc** [comment] 2017-09-11 13:52
@joshuapinter the animation is the default feature.

here is the code

```
        const resetAction = NavigationActions.reset({
            index: 0,
            actions: [NavigationActions.navigate({routeName: 'Home'})]
        });
        this.props.navigation.dispatch(resetAction);
```

what I actually need is to delete the previous screen, but there is no way to achieve this.

**Comment by adkl** [comment] 2017-09-11 14:07
It removes the previous screen for me, but then my DrawerNavigator on the next screen is not working.

**Comment by peacechen** [comment] 2017-09-11 14:27
@kelset  Expectations for this library are high because it's the [officially recommended cross-platform navigator for React Native](https://facebook.github.io/react-native/docs/navigation.html).  It's supposed to supersede NavigationExperimental and the original Navigator.  We invested time to integrate those navigators, only to have them pulled out in favor of react-navigation. 

I'm not sure what the coordination is between Facebook and this library.  If Facebook thrust this upon you, then I can understand how you feel it's unfair to expect a mature feature set right off the bat.  OTOH if there was an agreement between Facebook and the react-navigation project, then expectations for a production quality navigator are fair.

**Comment by justinlok** [comment] 2017-09-12 04:37
@icesyc you can use the reset action to delete the previous screen.
https://medium.com/handlebar-labs/replace-a-screen-using-react-navigation-a503eab207eb

**Comment by icesyc** [comment] 2017-09-12 04:49
@justinlok, thanks.
I have read the post,  but the way does not have animation when push a new screen.

**Comment by justinlok** [comment] 2017-09-12 05:21
@icesyc It has the usual animation for me on android. Make sure you use a unique key. It seems there is no animation if the key was already used. I haven't tested it on ios.

**Comment by mleduque** [comment] 2017-09-21 15:36
@jslok I tried that, but I think it doesn't work across navigator changes. Does it ?

**Comment by mleduque** [comment] 2017-09-21 16:48
OK that's a little more complicated to replace with a "sub-router screen".

I'm yet to become familiar with the API but I made it work with somethig like that
```javascript
      const routes = state.routes.slice(0, state.routes.length - 1);

      const target = this.getComponentForRouteName(action.routeName);
      if (target.router) {
        const childRoute = target.router.getStateForAction(NavigationActions.init());
        const routeItem = {
          ...action,
          ...childRoute,
        };
        routes.push(routeItem);
      } else {
        routes.push(action);
      }
```

**Comment by eemebarbe** [comment] 2017-10-20 21:57
I, for one, appreciate @voidstarfire 's blunt statement. I recognize that there is an expected etiquette for comments within an issue, but this seems like an exceptional case. Putting aside blame, the fact of the matter is, this is the officially supported navigation library and when you talk to other developers, this is what's being recommended. If a library is flawed in some sort of fundamental way, It isn't enough to just say, "if you don't like it, submit a PR". People need to be warned if everything online suggests that you aught to be using this package, and as a result you're going to waste significant hours of your time, only to hack your way around problems, and to eventually conclude that patchwork isn't enough and end up moving to another solution. I think the documentation should do a better job of acknowledging the spectrum of issues within the project and communicate it effectively to the reader.

**Comment by aayush123** [comment] 2017-11-09 03:31
any suggestions for the best navigation library out there right now?

**Comment by voidstarfire** [comment] 2017-11-09 08:11
@aayush123 https://github.com/wix/react-native-navigation
Easily the best one, they redesigned the way React works around screens, each screen is basically it's own React module harnessed in a native screen with native a toolbar etc.
Also it's super easy to work and comes with everything you need right out the box (no hacks required)

**Comment by haotangio** [comment] 2017-11-11 12:55
My complete SOLUTION for this

`SignupScreen.js`
```
goToLoginScreen = () => {
  this.props.navigation.navigate('LoginScreen', {
    dontBackToMe: this.props.navigation.state.key // this will contains screen key of SignupScreen
  })
}
```
`LoginScreen.js`
```
goBack = () => {
  const backFrom = this.props.navigation.state.params.dontBackToMe
  this.props.navigation.goBack(backFrom) // Will back to screen before SignupScreen
}
```

For Android's `hardwareBackButton` event
`Navigation.js`
```
class Navigation extends React.Component {
  componentDidMount () {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress)
  }

  componentWillUnmount () {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress)
  }

  getSkippedScreen = () => {
    const params = _.last(this.props.nav.routes).params
    return params && params.dontBackToMe
  }

  onBackPress = () => {
    const {dispatch, nav} = this.props
    if (nav.index === 0) {
      return false
    }
    const skipFrom = this.getSkippedScreen()
    dispatch(NavigationActions.back({key: skipFrom}))
    return true
  }
  
  ...

}
```

**Comment by AndreiCalazans** [comment] 2017-11-22 17:27
@haotangio Nice job! it works.

this here also works equally incase you don't want to control the nav key.
```
onBack={() =>
            navigation.dispatch(
              NavigationActions.reset({
                index: 0,
                actions: [
                  NavigationActions.navigate({ routeName: ROUTES.FLY_TOGETHER }),
                  NavigationActions.navigate({ routeName: ROUTES.FLY_TOGETHER_TIMELINE }),
                ],
              }),
            )
          }
``` 


But my problem with both of them is that I have a transition which is a slide to the left when you go back, and when i go back before the Popped screen shows up in the transition even though it is going back correctly to where I want.


I'm still looking for a solution which completely removes the screen from the stack like if it never existed. if anyone

**Comment by abhishek-raj** [comment] 2018-01-29 20:37
```
const mainFlow = {
      screen: StackNavigator({
        home: { screen: HomeScreen },
        settings: { screen: SettingsScreen },
        record: { screen: RecordScreen },
        send: { screen: SendScreen },
        videos: { screen: VideosScreen },
        videopreview: { screen: VideoPreviewScreen }
      })
    }

 const MainNavigator = TabNavigator({
      welcome: { screen: WelcomeScreen },
      signin: { screen: SigninScreen },
      signup: { screen: SignupScreen },
      mainFlow: mainFlow
    }, {
      navigationOptions: {
        tabBarVisible: false
      },
      lazy: true,
      swipeEnabled: false,
      backBehavior: 'none'
    });
```

I use this to achieve the result needed. The `TabNavigator` works well with the `tabBarVisible` set to `false` and `backBehavior` set to `none`.

**Comment by wachunei** [comment] 2018-02-08 18:27
`replace` has been implemented and [appears on the API docs](https://reactnavigation.org/docs/navigation-prop.html) now, haven't tested if it behaves as the patterns described along this thread.

It seems like for now it behaves like a `RESET` action starting from the previous screen, therefore it has no animation, thus the `inmediate` parameter as a placeholder.

If anyone tests it please share.

**Comment by Noitidart** [comment] 2018-02-08 18:35
> therefore it has no animation

Darn that totally stinks. The animation is crucial to give user sense of screen change.

**Comment by brentvatne** [comment] 2018-02-08 18:37
@Noitidart - it would be nice to have an animation indeed! a decent amount of work needs to be done for that. until then you could animate in the screen that you replace to using standard react-native animation techniques
