### ISSUE TITLE
Custom header component for each screen with `headerMode: 'float'` transition

### ISSUE THREAD

**Issue by shivrajkumar** [react-community/react-navigation#1157] opened 2017-04-21 07:39 UTC
I want to use NativeBase Header component in my each screen and also have the float header transition provided by react-navigation with it.
Is there a way to do it?

**Comment by shivrajkumar** [comment] 2017-04-21 08:34
If i make the change here https://github.com/react-community/react-navigation/blob/master/src/views/Header.js#L273
and replace the <View> with `NativeBase` <Header>.
I can make it work.
But i don't want to fork the repo and merge every change with future releases.
Would be great if i could provide custom Header of NativeBase with the screen component itself.

**Comment by grabbou** [comment] 2017-04-22 06:22
Duplicate of #100

**Closed by grabbou** 2017-04-22 06:22 UTC
