### ISSUE TITLE
Linking to tab in TabNavigator doesn't work if tab is StackNavigator

### ISSUE THREAD

**Issue by EdmundMai** [react-community/react-navigation#2225] opened 2017-07-24 11:14 UTC
I'm following these steps to link to my tab in my TabNavigator: https://github.com/react-community/react-navigation/blob/master/docs/guides/Deep-Linking.md

However, it doesn't work when I link to my tab, which is a StackNavigator. It works 100% of the time if I link to an ordinary component. When I say it breaks, I mean it opens the correct tab, and then it pushes the tab (a StackNavigator) onto itself again for some reason.

I have a button that calls `Linking.openURL("myscheme://mytab);`

I have a RootTabContainer:

```
const routeConfig = {
  Chats: {
    screen: ChatContainer,
    path: "mytab",
    ...
  },
  ...
};

const TabNav = TabNavigator(routeConfig, ...);


const RootTabsContainer = props => {
  return h(TabNav, {
    uriPrefix: "myscheme://",
  });
};
```

ChatContainer is a StackNavigator:

```

const routeConfig = {
  ChatList: {
    screen: ChatListContainer,
    navigationOptions: ({ navigation }) => ({
      title: "chats",
      headerBackTitle: " "
    })
  },
  ChatDetail: {
    screen: ChatDetailContainer,
    navigationOptions: ({ navigation: { state: { params: chat } } }) => {
      const { users: [peer] } = chat;
      return {
        title: peer.name,
        tabBarVisible: false // <--------- this is why I need to have StackNavigator as the direct tab of the TabNavigator. If I wrap the StackNavigator inside another component, it breaks this
      };
    }
  }
};

const stackNavConfig = {
  initialRouteName: "ChatList",
  navigationOptions: {
    headerStyle: styles.header,
    headerTitleStyle: styles.headerTitle,
    headerTintColor: COLORS.HEADER_TXT
  }
};

export default StackNavigator(routeConfig, stackNavConfig);
```

Here's a visual of what I mean. As you can see there is a back button to my chats header. That shouldn't be the case, because it is the first screen in my stack navigator

![chats](https://user-images.githubusercontent.com/1857068/28521174-662866ea-70ad-11e7-904e-a3cf49bba1bb.gif)

**Comment by p0d3r** [comment] 2017-08-17 23:00
+1

**Comment by spencercarli** [comment] 2017-08-24 02:42
A running example of this issue would be very helpful - thanks!

**Comment by PatNeedham** [comment] 2017-09-14 17:20
@spencercarli I encountered the same bug, here's a reproducible example with that behavior:

` $ react-native init SampleApp`
Replace `index.android.js` and `index.ios.js` with `import './src/app'`

`src/app.js`:
```
import React from 'react';
import { AppRegistry, Platform, Text, View } from 'react-native';
import { StackNavigator, TabNavigator } from 'react-navigation';

class StoresScreen extends React.Component {
  static navigationOptions = ({ navigation }) => ({ title: `Stores` });
  render() {
    return (<Text>List of Stores</Text>)
  }
}

class StoreItemsScreen extends React.Component {
  static navigationOptions = ({ navigation }) => ({ title: `Store Items` });
  render() {
    const { params } = this.props.navigation.state;
    return (<Text>Store Items Screen for store with id {params.store_id}</Text>)
  }
}

const StoresTab = StackNavigator({
  Stores: { screen: StoresScreen, path: '' },
  StoreItems: { screen: StoreItemsScreen, path: ':store_id'}
});

class OtherTabScreen extends React.Component {
  static navigationOptions = ({ navigation }) => ({
    title: `Unimportant other screen`,
  });
  render() {
    return (
      <View>
        <Text>Other Screen</Text>
      </View>
    );
  }
}

const MyTabs = TabNavigator({
  StoresTab: { screen: StoresTab, path: 'stores' },
  OtherTab: { screen: OtherTabScreen, path: 'other'}
},{
  animationEnabled: false,
  tabBarOptions: { activeTintColor: '#000' }
})

const prefix = Platform.OS == 'android' ? 'mychat://mychat/' : 'mychat://'
const MainApp = () => <MyTabs uriPrefix={prefix} />
AppRegistry.registerComponent('SampleApp', () => MainApp);
```

I followed the [Deep Linking](https://reactnavigation.org/docs/guides/linking) guides for Android. When opening the app either from running `react-native run-android` or (after it's installed) clicking its icon in the app drawer, everything looks normal:

![image](https://user-images.githubusercontent.com/967811/30443690-613e50b2-994e-11e7-9623-ad39c35ff6eb.png)

But when I run the command `adb shell am start -W -a android.intent.action.VIEW -d "mychat://mychat/stores" com.sampleapp`, it appears like this after opening:

![image](https://user-images.githubusercontent.com/967811/30443741-977a135a-994e-11e7-806e-da42b2f526a3.png)

That back arrow shouldn't be part of the navigation header because the Stores screen in my case is the root of that `StackNavigator`. And when I press it, the same screen appears, just without a back arrow this time.

My dependencies look like this in `package.json`:
```
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.1",
    "react-navigation": "^1.0.0-beta.11"
  },
```

**Comment by kelset** [comment] 2017-11-25 09:21
Pinging OP @EdmundMai since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I think it's a duplicate of https://github.com/react-community/react-navigation/issues/2913 // https://github.com/react-community/react-navigation/issues/2904

**Comment by kelset** [comment] 2017-12-03 09:59
Hi there @EdmundMai ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-12-03 09:59 UTC
Labels: 7 days countdown, bug
