### ISSUE TITLE
How to dismiss modal containing a StackNavigator

### ISSUE THREAD

**Issue by davideweaver** [react-community/react-navigation#686] opened 2017-03-14 18:47 UTC
I have a few **StackNavigators** with the root having `mode: "modal"`...

```
const AddStack = StackNavigator({
  Add1: { screen: Add1Screen },
  Add2: { screen: Add2Screen },
  Add3: { screen: Add3Screen }
}, {
  mode: "screen"
});

const Root StackNavigator({
  MainStack: { screen: MainStack },
  AddStack: { screen: AddStack }
}, {
  mode: "modal"
})
```

The `AddStack` modal is a 3-step series of screens. When the user is on the third screen (`AddScreen3`) I would like them to click Save and have the modal go away (and be back on `MainStack`).

It looks like the right way to do it would be using **NavigationActions.reset**, but I can't figure it out.

Can anyone shed some light on the right way to do it?

**Comment by davideweaver** [comment] 2017-03-14 19:20
After looking into this more, I can achieve the results I want by swiping down on `Add3Screen`. However I need to be able to do it with a button click. Swiping down dispatches the following...

```
action Object {type: "Navigation/BACK", key: "id-1489519010411-0"}
```

It looks like that key is being generated automatically. Is there a way to assign or lookup the key so I can use it programmatically?

**Comment by davideweaver** [comment] 2017-03-14 22:18
I've figured out a solution until I find a better one. The solution is based on the previous comment about dispatching a "Navigation/BACK" action with the key of the modal StackNavigator screen. I use the routeName to find the key, then dispatch the action. In my case the routeName is `AddStack`.

**navActions.js** (partial)
```
export function dismissModal(modalRouteName) {
  return async (dispatch, getState) => {
    var modalKey = findRouteKey(getState(), modalRouteName);
    if (modalKey) {
      dispatch(NavigationActions.back({key: modalKey}));
    }
  }
}
```

This goes in my screen component...
```
dispatch(navActions.dismissModal("AddStack")
```
see the full **navActions.js** at [https://gist.github.com/davideweaver/34d701c402c199676916d471916f9dca](https://gist.github.com/davideweaver/34d701c402c199676916d471916f9dca)

Maybe we can add a helper like this to **NavigationActions** in the future.

**Comment by blaues0cke** [comment] 2017-03-20 17:41
Thank you, @davideweaver. Your code helped me a lot to understand my very similiar problem. Actually my problem was that the modal was closed whenever I hit the "back" button inside the child `StackNavigator`.

I digged around a lot and found a solution by modifying the reducer. Since I am very new to redux and react-native, it would be great to get some feedback if this approach may be the "best-practice". Let me explain:

My top navigator is a `StackNavigator`. It contains at index `0` a instance of `TabNavigator` that represents my app. The following indexes are another `StackNavigator`s that just offer some modal stuff like controllers for login or a camera view:

```
const MainTabNavigator = TabNavigator(
    {
        Tab1Home: { screen: Tab1WithNavigationState },
        // And so on
    }
);

const LoginRegisterStackNavigator = StackNavigator({
    Modal_Login: { screen: LoginScreen }
});

const ModalStackNavigator = StackNavigator({
    MainTabNavigator:                   { screen: MainTabNavigator                 },
    ModalSub_LoginScreenStackNavigator: { screen: LoginRegisterWithNavigationState }
}, {
    headerMode: 'none',
    mode:       'modal'
});
```

Since the `Navigation/NAVIGATE` event is fired to all reducers, I decided to start the name of all modal routes with `ModalSub_` to detect them later.

With this approach, I can count all opened and closed sub views of `LoginRegisterStackNavigator` in `ModalNavigationReducer`, too. So I added a counter that just returns the old state (with an updated counter) until the counter reached zero. Then I return the new state that closes the modal, too:

```
const ModalNavigationReducer = (state, action) => {
    if (action && state) {
        if (action.type == 'Navigation/NAVIGATE') {
            if (action.routeName.indexOf('ModalSub_') > -1) {
                state.modalSubViewCount = 0;
            } else {
                state.modalSubViewCount++;
            }
        } else if (action.type == 'Navigation/BACK') {
            if (state.modalSubViewCount > 0) {
                state.modalSubViewCount--;
                return state;
            }
        }
    }

    // Default state handling here, results in newState

    return newState || state;
};

module.exports = ModalNavigationReducer;
```

To close the modal and reset its child stack navigator, I just fire a custom action:

    this.props.navigation.dispatch({ type: 'Navigation/CLOSE_MODAL' });

And then I can update my reducers to reset and/or close the modal even when the stack is not empty:

```
const ModalNavigationReducer = (state, action) => {
    if (action && state) {
        if (action.type == 'Navigation/NAVIGATE') {
            if (action.routeName.indexOf('ModalSub_') > -1) {
                state.modalSubViewCount = 0;
            } else {
                state.modalSubViewCount++;
            }
        } else if (action.type == 'Navigation/BACK') {
            if (state.modalSubViewCount > 0) {
                state.modalSubViewCount--;
                return state;
            }
        } else if (action.type == 'Navigation/CLOSE_MODAL') {
            action.type = 'Navigation/BACK';
        }
    }

    // Default state handling here, results in newState

    return newState || state;
};

module.exports = ModalNavigationReducer;
```

```
const LoginRegisterNavigationReducer = (state, action) => {
    if (action && action.type == 'Navigation/CLOSE_MODAL') {
        return {
            index: 0,
            routes: [
                {
                    key: 'Init',
                    routeName: 'Modal_Login'
                }
            ]
        };
    }

    // Default state handling here, results in newState

    return newState || state;
};

module.exports = LoginRegisterNavigationReducer;
```

So I now just have to send the action `Navigation/CLOSE_MODAL` without caring about what modal view is opened right now.

**Comment by richardfickling** [comment] 2017-04-06 16:13
My solution to this problem was to create a `DismissableStackNavigator`:
```
import React, { Component } from 'react';
import { StackNavigator } from 'react-navigation';
export default function DismissableStackNavigator(routes, options) {
  const StackNav = StackNavigator(routes, options);

  return class DismissableStackNav extends Component {
    static router = StackNav.router;

    render() {
      const { state, goBack } = this.props.navigation;
      const nav = {
        ...this.props.navigation,
        dismiss: () => goBack(state.key),
      };
      return (
        <StackNav
          navigation={nav}
        />
      );
    }
  }
};
```

For example:
```
const AddStack = DismissableStackNavigator({
  Add1: { screen: Add1Screen },
  Add2: { screen: Add2Screen },
  Add3: { screen: Add3Screen },
});

const Root StackNavigator({
  MainStack: { screen: MainStack },
  AddStack: { screen: AddStack }
}, {
  mode: "modal"
})
```

Now, in `Add3Screen`, you can call `this.props.navigation.dismiss()`

**Comment by superquest** [comment] 2017-04-09 01:48
@richardfickling: Bravo. Works like a charm!

**Comment by boudellaredouane** [comment] 2017-04-26 09:15
@richardfickling Man that's brilliant!

Do you have any in depth courses for us RN newbies to get up to speed with things ?
Cause i don't understand what you did other then that it does actually work.

Cheers

**Comment by stevenleeg** [comment] 2017-04-26 16:28
@richardfickling you are my hero! 😍  you have no idea how much time I've spent on trying to figure this out and your solution appears to have finally solved my issues.

**Comment by benoitvallon** [comment] 2017-06-09 01:33
Thank you, it works great. I think this should be in the official documentation in the advanced section as nested stackNav is quite common.

**Comment by almirfilho** [comment] 2017-06-20 02:51
For those who still are in pain with this, the following solution works just fine:

```javascript
this.props.navigation.dispatch(NavigationActions.back());
```

Found this solution [here](https://github.com/react-community/react-navigation/issues/697#issuecomment-309359044).

**Comment by yukkeechang** [comment] 2017-06-25 19:10
I tried richardfickling's method but i get an error in my Add3Screen or basically my last screen to dismiss the whole stack. It says that this.props.navigation.dismiss in this.props.navigation.dismiss() is undefined. I imported his function DismissableStackNavigator into that file. Am i missing a step?

**Comment by yukkeechang** [comment] 2017-07-21 19:35
hey @richardfickling, I used your dismissNav which works like a charm btw but now I have a different issue. If a nest a bunch a screens using your dismiss nav inside another Stack nav, the first screen of my dismiss nav is also rendered in the stack nav meaning that if I want to go back or exit the stack, the first screen is actually rendered twice. How can I prevent that from happening?

**Comment by wkoutre** [comment] 2017-07-30 19:47
Seems to me that:

 `this.props.navigation.dispatch(NavigationActions.back()))`

is essentially the same as:

`export const getNextBackKey = keyStr => {
  let newKey = keyStr.split("");
  const lastNum = +newKey[newKey.length - 1];
  newKey[newKey.length - 1] = (lastNum + 1).toString();

  const finished = newKey.join("").replace("Init-", "");
  return finished;
};`

And then dispatching type: Navigation/BACK with the new key.

**Comment by spencercarli** [comment] 2017-08-28 01:33
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:33 UTC
Labels: Type: Question

**Comment by lukecwilliams** [comment] 2017-10-02 19:44
@richardfickling Thanks for the great solution.  `.dismiss()` is available in `this.props.navigation`, but not in `static navigationOptions = { navigation } => ...`

Do you know why?

**Comment by lukecwilliams** [comment] 2017-10-09 21:01
Follow-up: we needed to wrap the dismissible Stack Nav in order to use it with Apollo Client.  This requires setting the router on the wrapping component to that of the wrapped component (or else an error is thrown: `navigation.states.routes is not an object`).

Solved like this, returning both the class and the router:

```
function DismissibleStackNavigator(
  routeConfigMap: NavigationRouteConfigMap,
  stackConfig?: StackNavigatorConfig,
) {
  const StackNav = StackNavigator(routeConfigMap, stackConfig);

  return {
    router: StackNav.router,
    DismissableStackNav: class extends React.Component<any, any> {
      public static router: any = StackNav.router;

      public render() {
        const { state, goBack } = this.props.navigation;
        const nav = {
          ...this.props.navigation,
          dismiss: () => goBack(state.key),
        };
        return <StackNav navigation={nav} />;
      }
    },
  };
}

const {
  DismissableStackNav: WorkoutStackNavigator,
  router: stackRouter,
} = DismissableStackNavigator( // ...

export default class extends React.Component<any, any> {
  // Must set router from wrapped component
  // https://github.com/react-community/react-navigation/issues/90
  public static router: any = stackRouter;

  public render() {
    // Must pass navigation object to wrapped component
    return (
      <ApolloProvider client={createClient()}>
        <WorkoutStackNavigatorWithData
          navigation={this.props.navigation}
        />
      </ApolloProvider>
    );
  }
}

// Specify any, any so props can be passed
const WorkoutStackNavigatorWithData = graphql<any, any>(
// ...
  {
    options: {},
    props: ({ ownProps, data }) => {
      return {
        ...ownProps,
        screenProps: { data },
      };
    },
  },
)(WorkoutStackNavigator);

```

**Comment by lukecwilliams** [comment] 2017-10-13 20:41
We were using DismissableStackNavigator but switched to simply passing the parent navigation options through to screenProps, and accessing it there.

**Comment by sbkl** [comment] 2017-11-07 14:01
Hi @richardfickling and all, Used your solution on react-native v0.48. Just upgraded to 0.50 and it doesn't work anymore.The dismiss function is not in navigation props anymore. Anyone encountered the same issue?

**Comment by martnu** [comment] 2017-11-08 09:50
@sbkl @raggiadolf We solved it by using screenProps instead in DismissableStackNavigator and calling it using `this.props.screenProps.dismiss();` in our screens.

```js
render() {
  const { state, goBack } = this.props.navigation;
  const props = {
    ...this.props.screenProps,
    dismiss: () => goBack(state.key),
  };
  return (
    <StackNav
      screenProps={props}
    />
  );
}
```

**Comment by sbkl** [comment] 2017-11-08 12:49
@martnu in which component do you put this code?

**Comment by lprhodes** [comment] 2017-11-22 07:19
Thanks @martnu !

Shame we're still having top use work-arounds like this

**Comment by tylerstephens814** [comment] 2017-11-27 20:01
thank goodness for @richardfickling who has saved my life on multiple occasions

**Comment by vlgusakov-ap** [comment] 2017-12-12 17:10
Since `React Native` allows to pass props only through `screenProps` here is an updated way to dismiss a `StackNavigator` (based on @richardfickling's response)

```
import React, { Component } from 'react';
import { StackNavigator } from 'react-navigation';

export default function DismissableStackNavigator(routes, options) {
  const StackNav = StackNavigator(routes, options);

  return class DismissableStackNav extends Component {
    static router = StackNav.router;

    render() {
      const { state, goBack } = this.props.navigation;

      const screenProps = {
        dismiss: () => goBack(state.key),
      }
      return (
        <StackNav
          navigation={this.props.navigation} screenProps={screenProps}
        />
      );
    }
  }
};

```

And then you call `this.props.screenProps.dismiss()` from your component(s)

**Comment by tslater** [comment] 2017-12-30 04:18
@vlgusakov-ap I'm having some trouble trying to figure out how to get screen props to work. I'm using a stack navigator nested inside a drawer navigator. Any idea on how I could work this? I confirmed that calling:
```
 const { state, goBack } = this.props.navigation;
goBack(state.key
```
works. The issue is that I can't seem to get the "dismiss" screen prop to show up on my screen. It's undefined. Could the parent drawer navigator be messing me up?

**Comment by LordParsley** [comment] 2018-02-20 09:48
Following [this approach](https://github.com/maxs15/react-native-modalbox/issues/75#issuecomment-243876689), you might want to intercept the Android hardware back button in your view too:

```
  componentWillMount() {
    if (Platform.OS === 'android') {
      BackHandler.addEventListener('hardwareBackPress', this.dismiss);
    }
  }

  componentWillUnmount() {
    if (Platform.OS === 'android') {
      BackHandler.removeEventListener('hardwareBackPress');
    }
  }

  dismiss = () => {
    this.props.screenProps.dismiss();
    return true;
  }
```

**Comment by hammadzz** [comment] 2018-03-04 00:32
Using a back action with null key used to work for me but seems it broke with v1.2.

Do I have to go with dismissible stack navigator? This feels really hacky.

```
NavigationActions.back({
	key: null
})
```

**Comment by brentvatne** [comment] 2018-03-06 01:15
@hammadzz - `goBack(null)` should still work, *but* only if you're on the first screen in the nested stack. see https://github.com/react-navigation/react-navigation/pull/3669 on a potential solution baked into react-navigation

**Comment by hammadzz** [comment] 2018-03-06 12:10
@brentvatne that would be great if it gets merged. I want to dismiss the nested stack from the last screen. This used to work. I implemented the dismissible stack navigator and will remove it and use `.dismiss()` once it gets merged.

**Comment by ScreamZ** [comment] 2018-03-07 09:21
@hammadzz  @brentvatne 

I also encountered the same issue one day. I solved using:

```js
this.props.navigation.popToTop() // Reset all modal of modal stacks.
this.props.navigation.goBack(null) // Then close modal itself to display the main app screen nav.
```

That did the job.

Maybe you can consider it for #3669 ? Instead of querying parent key from state ?

Regards

**Comment by hammadzz** [comment] 2018-03-08 14:05
@ScreamZ wouldn't that first pop to top then dismiss? I don't want it to pop to top as that would look buggy to the end user.

**Comment by ScreamZ** [comment] 2018-03-08 14:59
@hammadzz I'm not sure if popToTop is generating an animation, but even if it do it, it's quick enough to not being noticed, I use it already some a similar case.

**Comment by anhhai680** [comment] 2018-05-31 04:11
Hi everybody, I'm using react-native versions 0.50.3 but when I'm navigating to modal screen, I always get an error as capture belows.
![capture](https://user-images.githubusercontent.com/644008/40760817-bda45230-64c2-11e8-8177-1f53645d9a5c.PNG)
I integrated Redux with React Navigation and here's my AppNavigator code.
`
export const OrderStack = DismissableStackNavigator(
    {
        Cart: {
            screen: Cart
        },
        Checkout: {
            screen: Checkout
        },
        FinishOrder: {
            screen: FinishOrder
        }
    },
    {
        //mode: 'modal',
        headerMode: 'none'
    }
);

export const MainStack = StackNavigator(
    {
        Home: {
            screen: Home,
            navigationOptions: {
                header: null
            }
        },
        About: { screen: About },
        Product: {
            screen: Product,
            navigationOptions: {
                tabBarVisible: false
            }
        },
        ViewCart: {
            screen: OrderStack,
            navigationOptions: {
                header: null,
                tabBarVisible: false
            }
        },
        List: { screen: List }
    },
    {
        mode: 'modal'
    }
);

export const AppNavigator = TabNavigator(
    {
        Main: {
            screen: MainStack,
            navigationOptions: {
                tabBarLabel: 'Trang chủ'
            }
        },
        Products: {
            screen: List,
            navigationOptions: {
                tabBarLabel: 'Sản phẩm'
            }
        },
        Cart: {
            screen: Cart,
            navigationOptions: {
                tabBarLabel: 'Giỏ hàng'
            }
        },
        NotifyList: {
            screen: Notifications,
            navigationOptions: {
                tabBarLabel: 'Thông báo'
            }
        },
        Contact: {
            screen: About,
            navigationOptions: {
                tabBarLabel: 'Liên hệ'
            }
        }
    },
    {
        navigationOptions: ({ navigation }) => ({
            tabBarIcon: ({ focused, tintColor }) => {
                const { routeName } = navigation.state;
                let iconName;
                if (routeName == 'Main') {
                    iconName = `ios-home${focused ? '' : '-outline'}`;
                }
                else if (routeName == 'Products') {
                    iconName = `ios-list-box${focused ? '' : '-outline'}`;
                }
                else if (routeName == 'Cart') {
                    iconName = `ios-cart${focused ? '' : '-outline'}`;
                }
                else if (routeName == 'NotifyList') {
                    iconName = `ios-notifications${focused ? '' : '-outline'}`;
                }
                else if (routeName == 'Contact') {
                    iconName = `ios-contacts${focused ? '' : '-outline'}`;
                }
                return <Ionicons name={iconName} color={tintColor} size={25} />;
            }
        }),
        tabBarOptions: {
            activeTintColor: 'tomato',
            inactiveTintColor: 'gray',
            showIcon: true
        },
        tabBarComponent: TabBarBottom,
        tabBarPosition: 'bottom',
        animationEnabled: false,
        swipeEnabled: false,
        lazy: true,
        initialRouteName: 'Main'
    }
);


class AppWithNavigationState extends React.Component {

    static propTypes = {
        dispatch: PropTypes.func.isRequired,
        nav: PropTypes.object.isRequired
    };

    componentDidMount() {
        //initializeListeners("root", this.props.nav);
    }

    render() {
        const { dispatch, nav } = this.props;
        return (
            <AppNavigator
                navigation={addNavigationHelpers({
                    dispatch,
                    state: nav,
                    addListener
                })} />
        );
    }
}

const mapStateToProps = (state) => ({
    nav: state.nav
});

export default connect(mapStateToProps)(AppWithNavigationState);
`
Anybody can help me to resolve this issue. Thank you so much!

**Comment by ScreamZ** [comment] 2018-05-31 12:36
@anhhai680 Are you using React navigation >= 2 ?

**Comment by brentvatne** [comment] 2018-05-31 20:19
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
