### ISSUE TITLE
How can I set the Stack Navigator title as an image

### ISSUE THREAD

**Issue by Anu-Ujin** [react-community/react-navigation#1118] opened 2017-04-19 15:29 UTC

**Comment by dantman** [comment] 2017-04-21 00:24
Have you tried using `headerTitle` (formerly `header.title`)?

**Comment by dantman** [comment] 2017-04-21 00:33
Duplicate of #1118.

**Comment by Anu-Ujin** [comment] 2017-04-21 06:01
it works,, thank you @dantman

**Closed** 2017-04-24 14:09 UTC
