### ISSUE TITLE
Cannot overrider certain props with `contentOptions` for `DrawerNavigator`

### ISSUE THREAD

**Issue by krazi3** [react-community/react-navigation#2506] opened 2017-08-31 11:43 UTC
It states in the docs that the routes array can be modified by  adding an `items` array to `contentOptions`.
[https://reactnavigation.org/docs/navigators/drawer#contentOptions-for-DrawerItems](url)

Even after adding an `items` array the drawer routes are not changed. After looking into it for sometime i found that this line 
[https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerSidebar.js#L106](url)
overrides the `items` array sent from outside. 

If this is the desired functionality then why does the docs suggest overriding the `items` array? Or maybe i am missing something. 

Plus is there anyway to make certain routes not show up in the drawer layout even if they are a screen.

Thanks

**Comment by spencercarli** [comment] 2017-08-31 14:49
Could you provide a reproduction of this issue? Could you also format and complete your issue to follow the [issue template](https://github.com/react-community/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md)? It's there to make sure everyone has the information needed. Thanks!

**Comment by rpopovici** [comment] 2017-09-01 13:06
@krazi3 there are some PRs already opened about this https://github.com/react-community/react-navigation/pull/2294

**Comment by kelset** [comment] 2017-12-10 12:36
Pinging OP @krazi3 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

---

A lot of work has been done around Drawers so I'm not sure this has been fixed - and it looks like the PR mentioned #2294 should be actually closed in favor of https://github.com/react-community/react-navigation/pull/2180 and https://github.com/react-community/react-navigation/pull/2183.

**Comment by kelset** [comment] 2017-12-17 15:31
Hi there @krazi3 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-12-17 15:31 UTC
Labels: 7 days countdown, component: Drawer, needs more info
