### ISSUE TITLE
Right button of header of 1st screen shown in second screen

### ISSUE THREAD

**Issue by ooochris** [react-community/react-navigation#183] opened 2017-02-05 11:36 UTC
In a StackNavigator,

I stack the same screen twice and the 1st one has a right button in the header but not the second one.
 The right button of the 1st screen will be shown in the second scren.

Here is the code
`
  static navigationOptions = {

                  header: (navigation) => {
                        if(addButton) {
                                 let right = <Button/>
              			return {right}
                         }
                         return null
		   },
            };  
`

Am I doing something wrong or is this a bug?
Thanks

**Comment by javierM84** [comment] 2017-02-10 07:48
Having exactly the same issue, in the first screen I have a list and an add button on the top right corner, then in the second screen I don't want any button in the navigation bar but it is still there. After going back and come to this screen the second time the button doesn't appear anymore.

Could it be something related to what is mentioned in this post https://github.com/react-community/react-navigation/issues/229?

**Comment by satya164** [comment] 2017-02-10 14:52
Closing as duplicate of #229

**Closed by satya164** 2017-02-10 14:52 UTC
Labels: bug
