### ISSUE TITLE
Problem with RESET with parallel nested routers.

### ISSUE THREAD

**Issue by TomiHiltunen** [react-community/react-navigation#395] opened 2017-02-19 22:15 UTC
I'm having problems understanding how to use `RESET` action when I want to take user to **ListMyMaskedItems** screen under a separate navigator after completing login. `RESET` prints to console the names of the available screens which only include the ones under **OnboardingNavigator**

My navigator/screen structure is as follows:
```
- RootNavigator
    - OnboardingNavigator
        - Intro
        - Login (user is here)
        - Register
    - MainNavigator
        - ListMyMaskedItems (user should go here)
```

Piece from log (I know I'm requesting a view with routeName Onboarding in this excerpt):
```
<Error>: There is no route defined for key Onboarding.
	Must be one of: 'Intro','Login','Register'
```

Any ideas on this?

**Comment by chandu0101** [comment] 2017-02-20 00:09
I am also facing similar issue #389

**Comment by ericvicenti** [comment] 2017-02-20 02:02
Have you tried simply using navigate for this? It should work to call `props.navigation.navigate('ListMyMaskedItems', {...myParams});`

**Comment by TomiHiltunen** [comment] 2017-02-20 19:24
@ericvicenti simply navigating to the parallel router works but the effect isn't really as I hoped. It pushes the next view in but if I drag the screen from left, I am brought back to login screen. My hope is to replace the previous state so that there wouldn't be anything to go back to but rather the first view should be the ListMyMaskedItems.

Preferred history/stack:
```
- RootNavigator
    - ListMyMaskedItems
```

actual history/stack:
```
- RootNavigator
    - Intro
        - Login
            - ListMyMaskedItems
```

**Comment by dggriffin** [comment] 2017-02-22 17:43
Running in to the same exact problem. Any insight would be wonderful.

**Comment by ericvicenti** [comment] 2017-02-22 17:51
@dggriffin, can you check out the repo and add a unit test for the routers that demonstrates the issue? The contributors guide should help you set up the tests.

This way it will be super clear to see what the issue is.

**Comment by dggriffin** [comment] 2017-02-22 21:30
@ericvicenti I could write a failing unit test, but in this case it seems less like a bug and more like a library assumption (which you acknowledge here: https://github.com/react-community/react-navigation/issues/199).

#199, #395, #335 all seem to be a similar use case were developers are attempting to navigate between parallel navigators managed by one parent app navigator whilst also dumping the existing navigation stack when transitioning between those parallel navigators.

In your eyes, does this demonstrate an uncovered use case for react-navigation, or are we approaching the the solution wrong conceptually?

Perhaps if we don't intend to maintain navigation history between parallel navigators, there shouldn't be an parent app navigator at all? (And instead we use a glorified switch statement for rendering?)


As for what I'm currently doing, my app looks like this:

![example](http://i.imgur.com/zFXqC7s.png)

AppNavigator establishes a listener on a user authentication object, if this authentication ever changes, it tries to dump the navigation history, and then route the user to the appropriate sub-navigator (MainNavigator if there is now user auth, LoginNavigator if there is now no user auth).

**Comment by stief510** [comment] 2017-02-22 22:30
If you are in route `Login` how do you jump over to `ListMyMaskedItems`

**Comment by vzhen** [comment] 2017-02-25 08:54
I have excatly same issue
https://github.com/react-community/react-navigation/issues/156#issuecomment-282449223

**Comment by vzhen** [comment] 2017-02-26 02:42
@stief510 `ListMyMaskedItems` is 1 of the router under `MainNavigator` so it means when user is logged in, it will reset to `MainNavigator` stack

**Comment by jpaas** [comment] 2017-03-03 01:10
I've also been unable to get this same strategy working using the reset action. I run into the problem described in #199

**Comment by ronnyhartenstein** [comment] 2017-03-03 07:59
I tried another approach: real parallel navigators within a react component - selected by a Redux state "login". I guess the reset is more direct, because its not a nested navigation with root navigation.
Here is the Gist https://gist.github.com/ronnyhartenstein/1ef30c90f530f99430969925198d6970

**Comment by fabriciovergal** [comment] 2017-03-05 10:50
I'm using a single navigator and watching auth and unauth route with redux-saga.
I'm still doing some test and probably will watch react-navigation navigate action to execute redirectFlow.

https://gist.github.com/fabriciovergal/fecad2389adbb1086a2d458e88f36a3d

**Comment by ronnyhartenstein** [comment] 2017-03-06 13:56
@fabriciovergal Good idea! So TLDR it stays one Top-Navigation with 3 routes - noauth with onboarding screens, auth with the app, and index which forwards hards to one of the others depending on login-status (and has no own content).

**Comment by devdlx** [comment] 2017-03-19 22:53
Hi all, I too have been experiencing the same or similar issue when you get an error: ''. For me it happens when my app goes to sleep or when you hit the back button to close (android). @fabriciovergal 's suggestions works great. However I did have to make some changes to better suit my app's resources, mainly because I have a "Splash" screen thaht shows first. I'd advise taking a look at it especially if you use redux and/or firebase (similar) for you state changes.

[gist](https://gist.github.com/devdlx/039cf28a7ea49c4b691f69a6ab380997)

BTW, i didnt include the pages themselves or the actions for redux. But basically when the state updates, the <navigator/> will switch between different navs

**Comment by taiki-t** [comment] 2017-03-20 07:16
Here is another workaround. https://sketch.expo.io/BkUwkWpje

Separating a child navigation from a parent and passing the parent navigation to the child navigation via screenProps. When you want to navigate to a screen in a parallel navigator, just call methods on the parent navigator.
This is really just a workaround but I hope some people find this pattern useful in some cases for now.

**Comment by quadsurf** [comment] 2017-08-25 10:50
I found a temporary workaround... consolidate all your stacks into a single stack... it's definitely less than ideal, but this lib invites all sorts of hacky workarounds. There is the option also to reset using route key, but this feature is useless if it's needed in a child component of a nested stack, even if you've passed screenProps, it throws this error: Cannot get routeName from 'config' ... instead of failing, there should be a default behavior where the reset action automatically navigates to the initial Root route and assumes index 0, which is basically what the true meaning of "popToTop" is anyway!

**Comment by spencercarli** [comment] 2017-08-28 01:34
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:34 UTC
Labels: Type: Question

**Comment by kaelumania** [comment] 2017-11-16 08:22
@spencercarli I think this is still more of an issue than a question. The described `navigator` structure is very useful/familiar to many apps, thus there should be a good solution/best practice for that.

**Comment by spencercarli** [comment] 2017-11-17 21:25
@kaelumania I believe this PR will solve this issue https://github.com/react-community/react-navigation/pull/1384

And I think there's another issue out there that this duplicates (could be wrong though)
