### ISSUE TITLE
Android tabNavigation switch has a delay of hundreds of milliseconds

### ISSUE THREAD

**Issue by shifeng1993** [react-community/react-navigation#2631] opened 2017-09-21 08:41 UTC
android tabbar switch will appear hundreds of milliseconds delay

this is my router code

```javascript 
import React, {Component} from 'react';
import {StyleSheet, Dimensions, Platform} from 'react-native';
import {StackNavigator, TabNavigator} from 'react-navigation';
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStack/CardStackStyleInterpolator';
// 引入页面容器
import {
  Home,
  Cart,
  My,
  Login,
  SignIn,
  SignUp
} from '../containers';

// 设置常量
const {height, width} = Dimensions.get('window');

const tabbar = TabNavigator({
  Home: {
    screen: Home,
    navigationOptions: {
      tabBarLabel: '主页',
      tabBarIcon: ({tintColor}) => (<IonIcon name="ios-home" size={28} color={tintColor}/>)
    }
  },
  Cart: {
    screen: Cart,
    navigationOptions: {
      tabBarLabel: '购物车',
      tabBarIcon: ({tintColor}) => (<IonIcon name="ios-cart" size={28} color={tintColor}/>)
    }
  },
  My: {
    screen: My,
    navigationOptions: {
      tabBarLabel: '我的',
      tabBarIcon: ({tintColor}) => (<IonIcon name="ios-person" size={28} color={tintColor}/>)
    }
  }
}, {
  tabBarPosition: 'bottom',
  swipeEnabled: false,
  animationEnabled: false,
  lazy: true,
  backBehavior: 'initialRoute',
  tabBarOptions: {
    style: {
      height: (Platform.OS === 'ios')
        ? width / 8
        : width / 7 - 5,
      backgroundColor: '#fff',
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: '#e4e4e4'
    },
    labelStyle: {
      fontSize: width / 35
    },
    iconStyle: {
      height: width / 20
    },
    indicatorStyle: {
      height: 0
    },
    scrollEnabled: false,
    activeBackgroundColor: '#fff',
    activeTintColor: '#ff6600',
    inactiveBackgroundColor: '#fff',
    inactiveTintColor: '#444444',
    showLabel: true,
    showIcon: true
  }
});

const AppNavigator = StackNavigator({
  Main: {
    screen: tabbar,
    navigationOptions: {
      header: null
    }
  },
  Login: {
    screen: Login,
    navigationOptions: {
      header: null,
      gesturesEnabled: false
    }
  },
  SignIn: {
    screen: SignIn,
    navigationOptions: {
      header: null
    }
  },
  SignUp: {
    screen: SignUp,
    navigationOptions: {
      header: null
    }
  }
}, {
  initialRouteName: 'Main',
  transitionConfig: () => ({screenInterpolator: CardStackStyleInterpolator.forHorizontal}),
  // onTransitionStart: () => ({screenInterpolator: CardStackStyleInterpolator.forHorizontal}),
  onTransitionEnd: () => ({screenInterpolator: CardStackStyleInterpolator.forInitial})
});

export default AppNavigator;
```

**Comment by linkinmedo** [comment] 2017-09-21 22:16
yes it's slow on debug build but it works as expected in release builds, try creating a release build.

**Comment by matthamil** [comment] 2017-09-22 02:01
Can you create a [Snack](https://snack.expo.io/) or repo reproducing this?

**Comment by kelset** [comment] 2017-12-17 15:47
Closing because of duplication. Refer to the [README](https://github.com/react-community/react-navigation#my-app-is-really-slow)

**Closed by kelset** 2017-12-17 15:47 UTC
Labels: needs more info
