### ISSUE TITLE
i use TabNavigator,when i change item it's a little delay

### ISSUE THREAD

**Issue by lrain-lv** [react-community/react-navigation#2781] opened 2017-10-18 08:57 UTC
i use TabNavigator,when i change item it's a little delay。Here's my code:

const tabN = TabNavigator({
        Home: {
            screen: HomeView, navigationOptions: {
                tabBarLabel: '首页',
                tabBarIcon: ({tintColor, focused}) => (
                    <Image resizeMode='contain'
                           style={{width: 25, height: 25}}
                           source={focused ? require('../../image/icon_home_select.png') : require('../../image/icon_home.png')}
                    />
                )
            }
        },
        Mall: {
            screen: MallView, navigationOptions: {
                tabBarLabel: '对赌商城',
                tabBarIcon: ({tintColor, focused}) => (
                    <Image resizeMode='contain'
                           style={{width: 25, height: 25}}
                           source={focused ? require('../../image/icon_mall_selected.png') : require('../../image/icon_mall_unselected.png')}
                    />
                )
            }
        },
        Mine: {
            screen: MineView, navigationOptions: {
                tabBarLabel: '我的',
                tabBarIcon: ({tintColor, focused}) => (
                    <Image resizeMode='contain'
                           style={{width: 25, height: 25}}
                           source={focused ? require('../../image/icon_mine_select.png') : require('../../image/icon_mine.png')}
                    />
                )
            }
        }
    },
    {
        tabBarPosition: 'bottom',
        lazy: true,
        initialRouteName: 'Home',
        swipeEnabled: false,
        backBehavior: 'none',
        animationEnabled: false,
        tabBarOptions: {
            activeTintColor: '#00aaf6', // 文字和图片选中颜色
            inactiveTintColor: '#888888',
            showIcon: true,
            pressOpacity: 0.8,
            style: {
                height: 48,
                backgroundColor: '#ffffff',
            },
            labelStyle: {
                fontSize: 10,
                marginTop: 2
            }
            ,
            iconStyle: {
                marginTop: -2
            }, 
            tabStyle: {
                backgroundColor: '#ffffff',
            },
        }
    }
    )
;

**Comment by kelset** [comment] 2017-10-20 15:54
Closing this since it's technically a duplicate of #739. Moreover I highly suggest that you check out my comments at the bottom of #608.

**Closed by kelset** 2017-10-20 15:54 UTC
