### ISSUE TITLE
StackNavigator renders nothing on first time in Android

### ISSUE THREAD

**Issue by dotansimha** [react-community/react-navigation#2887] opened 2017-11-02 18:04 UTC
Hi,

I'm having an issue with the latest version of the package (beta 16).

I have a StackNavigator defined with 3 screen, and on the first transition for any screen, I'm getting a kind of transparent screen. the Inspector can see the items and I can pick them, but the actual screen does not display at all. on the second time and on - it works.

Live example: (first click shows empty blue screen, but the second click shows the real screen)

![nov-02-2017 20-02-11](https://user-images.githubusercontent.com/3680083/32342331-c00c947e-c008-11e7-931e-a4984c451063.gif)

And indication for the existing elements - the inspector can find them:

![image](https://user-images.githubusercontent.com/3680083/32342425-001db6ec-c009-11e7-89b7-fe88a65334e4.png)

I'm having multiple StackNavigators in my app - and they all behave the same way, only for Android.
Tested in:
- Google Nexus 5X (Genymotion) - 6.0.0, API 23
- Google Nexus 6P (Genymotion) - 7.1.0, API 25
- Google Nexus 6P (Device) - 8.0.0
- LG G4 (Device) - 6.0.0

Few things I noticed:
* iOS works great
* Tried with, and without Redux - result is the same.
* Switching to `DrawerNavigator` works!

---

### Current Behavior
See GIF

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.16
| react-native     | 0.49.5

**Comment by kelset** [comment] 2017-11-02 18:51
Hey thanks for your report.
Currently `beta.16` has some known bugs, but your looks a bit different. Anyway, have you perhaps tried to point to `master` to see if it fixes your issue?

If not, could you share your code for the Stack Navigator? Or create a repo / [snack expo](snack.expo.io) that reproduces the issue? (btw I've never seen that "radio menu", maybe it's related to the way you control the stack with it?)

**Comment by dotansimha** [comment] 2017-11-02 19:41
@kelset 
The radio button is just a custom component, that uses Redux to trigger changes in view. 

The reducer and the definition of the StackNavigator is:

```
import React from 'react';
import { addNavigationHelpers, StackNavigator } from 'react-navigation';
import { connect } from 'react-redux';
import { EMainActions } from '../main/main.actions';
import { Text } from "react-native";

export const profileNavigation = {
  Chat: {
    screen: () => <Text>Screen 1</Text>,
  },
  FriendsList: {
    screen: () => <Text>Screen 2</Text>,
  },
};

export const ProfileNavigator = StackNavigator(profileNavigation, {
  headerMode: 'none',
});

const DEFAULT_STATE = ProfileNavigator.router.getStateForAction(ProfileNavigator.router.getActionForPathAndParams('Chat'));

export const profileNavigationReducer = (state = DEFAULT_STATE, action) => {
  if (action.type === EMainActions.NAVIGATE_CHILD && action.routeName && profileNavigation[action.routeName]) {
    return ProfileNavigator.router.getStateForAction(ProfileNavigator.router.getActionForPathAndParams(action.routeName), state) || state;
  }

  return state;
};

export const ProfileNavigation = connect(state => ({
  navigation: state.profileNavigationReducer,
}))(({ dispatch, navigation }) => (
  <ProfileNavigator navigation={addNavigationHelpers({ dispatch, state: navigation })} />
));

```

> The reducer uses custom action to trigger changes...

**Comment by dotansimha** [comment] 2017-11-02 19:42
@kelset 
I just found out that a specific line in my radio button caused this issue.

I had the following:
```
LayoutAnimation.configureNext(LayoutAnimation.Presets.spring);
```

inside `componentWillReceiveProps` of my side menu. somehow, removing it solves this issue. 
Not sure why..

**Comment by kelset** [comment] 2017-11-02 21:11
Uhm, really weird.
Tbh when I saw that it was related to the Animation.Spring I can only think of one person that could help with it @skevy (here's the reason why https://github.com/facebook/react-native/pull/15322).

**Comment by skevy** [comment] 2017-11-02 21:19
The work I did on Animated.spring is unrelated to LayoutAnimation's spring animation.

I'm not too familiar with the intricacies of LayoutAnimation on Android...but is there any chance you could change your animation logic to use `Animated` instead (with `useNativeDriver` so the animations still run on the main thread)?

**Comment by kelset** [comment] 2017-11-03 08:57
Ah gotcha, though those two things were related. Sorry ><'

(anyway yeah @dotansimha what he asks may be a way to go)

**Comment by dotansimha** [comment] 2017-11-03 12:30
Got it. Thanks.

Currently just changing the `LayoutAnimation` to animate `update` only did the trick for me, because my UI actually just updates.
To be more specific, the specific issue happens when animating `delete` and `create` with `LayoutAnimation`, during `componentWillReceiveProps`.

**Comment by vonovak** [comment] 2017-11-03 23:11
@dotansimha I'm going to close this because it seems you fixed the issues and also because it doesn't seem to be related to this lib. One quirk with using `LayoutAnimation` is that it not only animates the component where you're using it - it animates *everything*, that is, it animates your entire screen, which may sometimes behave differently from what one expects.

**Closed by vonovak** 2017-11-03 23:11 UTC
Labels: Status: Needs More Info, Type: Bug

**Comment by dotansimha** [comment] 2017-11-04 07:01
@vonovak sure, no problem. Thank you!
