### ISSUE TITLE
back button arrow will disappear after some operation

### ISSUE THREAD

**Issue by skyworld** [react-community/react-navigation#1178] opened 2017-04-23 08:16 UTC
normal 
![image](https://cloud.githubusercontent.com/assets/4318550/25311971/e9eca0ec-283f-11e7-991f-6bc240aabfb4.png)

after some operation
![image](https://cloud.githubusercontent.com/assets/4318550/25311984/158105cc-2840-11e7-8469-87ca8fad7b55.png)

**Comment by AlanFoster** [comment] 2017-04-25 09:46
@skyworld Is there more context to this issue? Do you have a minimal reproducible code sample?

**Comment by spencercarli** [comment] 2017-08-15 02:36
Without a reproduction we can't help. Going to close this issue.

**Closed by spencercarli** 2017-08-15 02:36 UTC

**Comment by samuela** [comment] 2018-01-06 06:29
I'm also experiencing this. AFAICT, it occurs at random. Very concerning. It makes me think that there's no way I can deploy my app with react-navigation if the back button arrows will suddenly disappear for users.

**Comment by AlanFoster** [comment] 2018-01-06 16:09
@samuela If you're able to provide a reproducible project for this bug, it will be possible to resolve this issue

**Comment by samuela** [comment] 2018-01-06 22:02
@AlanFoster Understood. If I end up finding a repro I'll certainly provide an update. In any case, I can confirm that this is a real issue.

**Comment by MartinMasek** [comment] 2019-02-04 16:24
The repro for me is stopping the Expo dev server

**Comment by brentvatne** [comment] 2019-02-04 20:19
@MartinMasek - that makes sense and it should happen because the image is no longer available if the server is closed
