### ISSUE TITLE
Header Icon Button

### ISSUE THREAD

**Issue by Clowning** [react-community/react-navigation#1989] opened 2017-06-26 19:12 UTC
Hey, 

I need to put an Icon in the left corner of my Header but, how can i link onPress with a method of my Component ?

I've tried a lot of code but nothing work! 

So, if you have already did that, if you have some code piece 👍 

Thanks :)

**Comment by matthamil** [comment] 2017-06-27 23:05
Can you post what you've tried?

You can use `headerLeft` https://reactnavigation.org/docs/navigators/stack#headerLeft to render a custom component.

```js
static navigationOptions = ({ navigation }) => ({
  headerLeft: <MyCustomComponent>
});
```

**Comment by lucianomlima** [comment] 2017-07-16 22:14
@matthamil Seizing this issue, when I set a custom button in the headerLeft in a StackNavigator, the back button is no longer displayed.

How can I add a button in headerLeft and keep the back button when a new view is pushed?

**Comment by vonovak** [comment] 2017-10-19 22:46
closing since the original question is a duplicate of https://github.com/react-community/react-navigation/issues/145

**Closed by vonovak** 2017-10-19 22:46 UTC
Labels: Type: Question

**Comment by lylest** [comment] 2019-04-28 10:40
how to add onpress event to that <Component> this was added to headerLeft?

**Comment by lylest** [comment] 2019-04-28 10:44
> ```js
> static navigationOptions = ({ navigation }) => ({
>   headerLeft: <MyCustomComponent>
> });
> ```

how to add functionality to it

**Comment by matthamil** [comment] 2019-04-28 15:26
@lylest , check out this page in the docs: https://reactnavigation.org/docs/en/header-buttons.html#adding-a-button-to-the-header.

Here's an example of adding an `onPress` to a header button:

```jsx
class YourScreenComponent extends React.Component {
  static navigationOptions = ({ navigation }) => {
    return {
      headerLeft: (
        <Button
          onPress={navigation.getParam('onPressHeaderButton')}
        />
      ),
    };
  };

  componentDidMount() {
    this.props.navigation.setParams({ onPressHeaderButton: this.showAlert });
  }

  showAlert = () => {
    Alert.alert('Huzzah!', 'You pressed a button in the header!')
  };

  render() {
  // ...
}
```
