### ISSUE TITLE
Nesting TabNavigator in StackNavigator will cause the inside of the TabNavigator view can not be displayed properly on Android

### ISSUE THREAD

**Issue by monotv** [react-community/react-navigation#3112] opened 2017-12-11 16:48 UTC
Nesting TabNavigator in StackNavigator will cause the view inside of the TabNavigator view not be displayed properly. The TabNavigator view will be collapsed and not visible.

> "react-native": "0.49.3",
> "react-navigation": "^1.0.0-beta.15",

This related issue was closed: https://github.com/react-community/react-navigation/issues/1058

But the 'fix' is to disable a feature which can not be the final solution because people really would like to use the it:

> adding animationEnabled:false and swipeEnabled:false also worked for me.

https://github.com/react-community/react-navigation/issues/1058#issuecomment-324595705

**Comment by kelset** [comment] 2017-12-11 18:08
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-11 18:08 UTC
