### ISSUE TITLE
Resetting navigation state on v1.0.0-beta.22 ，get params erro

### ISSUE THREAD

**Issue by TimeLetter** [react-community/react-navigation#3178] opened 2017-12-23 10:16 UTC
![image](https://user-images.githubusercontent.com/27766759/34318874-dc792c04-e80c-11e7-81a9-5feaaa5d7431.png)

![image](https://user-images.githubusercontent.com/27766759/34318878-f458a390-e80c-11e7-98bb-4a87fd119061.png)

![image](https://user-images.githubusercontent.com/27766759/34318857-6562a92e-e80c-11e7-887e-d9673959a37e.png)

**Comment by aMarCruz** [comment] 2017-12-23 20:36
@TimeLetter maybe because #3094

**Comment by kelset** [comment] 2017-12-23 21:37
Duplicate of https://github.com/react-community/react-navigation/issues/3149

**Closed by kelset** 2017-12-23 21:37 UTC
