### ISSUE TITLE
Tab Bar position absolute not visible

### ISSUE THREAD

**Issue by mattjfong** [react-community/react-navigation#1680] opened 2017-05-24 22:27 UTC
### Code

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import { TabNavigator } from 'react-navigation'

class Index extends Component {
  render() {
    return <View style={styles.container}>
      <Text style={styles.welcome}>
        Welcome to React Native!
      </Text>
      <Text style={styles.instructions}>
        To get started, edit index.android.js
      </Text>
      <Text style={styles.instructions}>
        Double tap R on your keyboard to reload,{'\n'}
        Shake or press menu button for dev menu
      </Text>
    </View>
  }
}

const routeConfig = {
  index: {screen: Index}
}

const tabBarConfig = {
  tabBarOptions: {
    style: {position: 'absolute', flex: 1}
  }
}

export const AppNavigator = TabNavigator(routeConfig, tabBarConfig)

export default class ReactNavigationTest extends Component {
  render() {
    return <AppNavigator />
  }
}
```

### Current Behavior
TabBarComponent won't display on Android. Setting fixed width, height, position doesn't change anything. 

### Expected Behavior
TabBarComponent should be visible. This worked fine in  ` 1.0.0-beta.9`. Doesn't work in  `1.0.0-beta.10` or  `1.0.0-beta.11`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.0
| node             | 
| npm or yarn      |

**Comment by leanminmachine** [comment] 2017-05-25 11:04
I have the same problem too on iOS, tried this for a TabNavigator but the tabs disappear when I changed the position to 'absolute' from the default 'relative'

`
      tabBarOptions: {
        style: {
          position: 'absolute',
          top: 100
        }
    }`

Seems to be able to work when I used the default relative instead of absolute though.

**Comment by faceyspacey** [comment] 2017-05-25 19:10
Not sure if this really worked in older versions--because I had this same issue in older versions--but basically you can't absolute position it using the default navigators and tab bar components. Flexbox expects to flow the Views together in a certain way. 

You're gonna have to accept that and make a custom TabBar. It's not that hard, especially for a TabNavigator (it's the StackNavigator that is very hard). 

You have 2 options:

- EASIER: create a custom TabBar and pass it to the `tabBarComponent` option. I suggest copy/pasting the code from React Navigation's implementation and then customizing. TIP: you can import from `src/views/Etc.js`. I.e. you can import anything.

- HARDER: follow what this guy recently did where he made his own navigator using the default TabRouter:

https://github.com/react-community/react-navigation/issues/1686

**Comment by mattjfong** [comment] 2017-05-25 19:24
```
class TabBar extends Component {
  render() {
    return <View style={{position: 'absolute', height: 100, width: 100, backgroundColor: 'red'}} />
  }
}

const tabBarConfig = {
  tabBarComponent: TabBar
}
```

We use a custom tab bar for our app. The result is the same. Its visible in `1.0.0-beta.9` but not in `1.0.0-beta.11`.

**Comment by faceyspacey** [comment] 2017-05-25 19:31
are you using React Native Debugger? Inspect the component tree and see what View is the culprit. Then find where in the React Navigation source code the problem is, then compare beta 9 to beta 10 and provide a PR setting it back etc etc.

**Comment by agarant** [comment] 2017-06-10 18:31
I have the same issue. By investigating, I found that the change that is causing the issue is the react-native-tab-view version bump. More precisely, the changes introduced in 0.0.63 from [this commit](https://github.com/react-native-community/react-native-tab-view/commit/c80fdff7bdb59b281c324bb6fb0dd1f213c1aae6).

**Comment by kidequinox** [comment] 2017-08-30 00:43
was this fixed ? running into the same issue on android `1.0.0-beta.11`

**Comment by kelset** [comment] 2017-11-04 09:05
Pinging OP @mattjfong since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment] 2017-11-12 10:25
Hi there @mattjfong ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-11-12 10:25 UTC
Labels: 7 days countdown, question
