### ISSUE TITLE
Wrong bottom tabs style on iOS 11+

### ISSUE THREAD

**Issue by brunolemos** [react-community/react-navigation#2828] opened 2017-10-25 22:17 UTC
### Current Behavior
Screen shot from iOS 11:
![image](https://user-images.githubusercontent.com/619186/32026063-66347860-b9c1-11e7-8930-dddfa34f8459.png)

Probably related to https://github.com/react-community/react-navigation/commit/36ffc4f31a6c9e3a87ff808eba66e0020f7c16b1 cc @spencercarli 

### Expected Behavior
Screen shot from iOS 9:
![image](https://user-images.githubusercontent.com/619186/32026051-568b731e-b9c1-11e7-9003-5c6698cc6079.png)

### Current workaround
Downgrading to `1.0.0-beta.12` fix the problem

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | 0.49.3
| node             | 7.10.1
| npm or yarn      | yarn

**Comment by spencercarli** [comment] 2017-10-26 01:20
Duplicate of #2805.

**Closed by spencercarli** 2017-10-26 01:20 UTC

**Comment by spencercarli** [comment] 2017-10-26 01:29
Checkout that issue. A few people have said they saw this issue but no one has been able to provide a repro
