### ISSUE TITLE
Maximum callstack exceeded when referencing existing `getStateForAction` inside of custom `getStateForAction`

### ISSUE THREAD

**Issue by tomjamesallen** [react-community/react-navigation#323] opened 2017-02-13 18:58 UTC
Overriding a Navigator's `getStateForAction` method as per instructions on https://github.com/react-community/react-navigation/blob/master/docs/api/routers/Routers.md leads to recursive reference to new `getStateForAction` method rather than referencing old one, resulting in maximum callstack exceeded error. Can easily be fixed as follows:

```JS
const prevGetStateForAction = MyApp.router.getStateForAction;
MyApp.router = {
  ... MyApp.router,
  getStateForAction(action, state) {
    // Do custom stuff here...
    return prevGetStateForAction(action, state);
  },
};
```

**Comment by grabbou** [comment] 2017-02-14 13:21
Duplicate of #294

**Closed by grabbou** 2017-02-14 13:21 UTC
