### ISSUE TITLE
number of renders/switching in tab navigator when nesting of stack and tab navigator 

### ISSUE THREAD

**Issue by patilrevansidh** [react-community/react-navigation#3083] opened 2017-12-06 06:37 UTC
thank you for such awesome library.
Somewhat similar to #1369 which closed no solution provided
I faced problem in IOS in below scenario but works fine in android:
stacknavigator : 
     

```
  - auth Page1
       - auth Page2
       - tab page
```

```
tab page -
       -tab1
       -tab2
       -tab3
       -tab4 (its Stacknavigator)
          -stack page1
          -stack page2
          -stack page3
```

Problme ONLY IN IOS not android:
      when i click to tab4 is continously switch between tab3 and tab4 many times and stop on either tab. Code of same:
```
`     AppHomeScreen: {screen: AppHomeScreen, navigationOptions:{...navOptions, title:'home'}},
        Messages : { screen: MessageScreeen,  navigationOptions:{...navOptions, title:'messages'}},
        Trades: { screen: TradeScreen, navigationOptions:{...navOptions, title:'trades'}},
        more : {
            screen: StackNavigator(
                {
                    MoreHome :{ screen : MoreOptions, navigationOptions:{...screenWithoutHeaderNavOptions}},
                    History : {screen : History, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'HISTORY'}},
                    pay : {screen : pay, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'pay}},
                    Settings : {screen : Settings, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'SETTINGS'}},
                    HowToPlay : {screen : HowToPlay, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'HOW  LINK  WORKS'}},
                    ContactUs : {screen : ContactUs, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'CONTACT  US'}},
                    Terms : {screen : Terms, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'TERMS'}},
                    Privacy : {screen: Privacy, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'PRIVACY'}},
                    ConfirmationScreen : {screen : ConfirmationScreen, navigationOptions: {...screenWithoutHeaderNavOptions, title:'CONFIRMATION'}},
                    MyInformation :{screen : MyInformation, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'MY  INFORMATION'}},
                    MyCommunity :{screen : MyCommunity, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'MY  COMMUNITY'}},
                    MyBusiness :{screen : MyBusiness, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'MY  BUSINESS'}},
                    InviteConfirmation :{screen : InviteConfirmation, navigationOptions:{...screenWithoutHeaderNavOptions,title:'CONFIRMATION'}},
                    DependLimit :{screen : DependLimit, navigationOptions:{...screenWithoutHeaderNavOptions,title:'DEPENDENT  LIMIT'}},
                    VerifyAccount : {screen : VerifyAccount, navigationOptions:{...screenWithLeftHeaderNavOptions,title:'VERIFY  ACCOUNT'}},

                    AuthHomePage : {screen:AuthHomePage, navigationOptions:{tabBarVisible:false}}

                },
               {
                    headerMode: 'none',
                    navigationOptions : {
                        tabBarLabel:'more',
                        title:'MORE  OPTIONS',        
                        tabBarLabel: 'more',
                        tabBarIcon: ({tintColor,focused }) => (
                            <Icon size={20} name='more-horiz'  color={focused ? stringConstants.APP_COLOR : stringConstants.INACTIVE_ICON_COLOR}/>
                        ),                       
                    }
               }
            ),````



another thing clicking on a home tab not moves screen but sliding does, slow render when sliding but perfectly fine in tab press

**Comment by kelset** [comment] 2017-12-06 09:29
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-06 09:29 UTC

**Comment by patilrevansidh** [comment] 2017-12-06 09:53
[https://github.com/react-community/react-navigation/issues/1369](url)
closed url
