### ISSUE TITLE
FEATURE REQUEST: Global-scoped navigate function 

### ISSUE THREAD

**Issue by dmr07** [react-community/react-navigation#2169] opened 2017-07-17 23:04 UTC
When working with multiple stacks, some of them nested, this library requires that I pass the navigation object associated with the scope of the stack into the component that needs it. For example, if I want to navigate from M2 to T2, I need to pass the ModalStack's as a `screenProp`.

TabStack
  - T1
  - T2

ModalStack
  - M1
  -M2

Another scenario I've encountered is having to pass second navigation object into `action` property of the navigate dispatch. 
 
It would be much better if there is a globally scoped navigate function that I can call no matter what layer I'm on.

**Comment by kelset** [comment] 2017-11-25 09:06
Pinging OP @dmr07 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I think it's a duplicate of https://github.com/react-community/react-navigation/issues/88

**Comment by kelset** [comment] 2017-12-03 09:58
Hi there @dmr07 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-12-03 09:58 UTC
Labels: 7 days countdown, feature request
