### ISSUE TITLE
Wrong Tab bottom style while enabled bold text on iOS device.

### ISSUE THREAD

**Issue by Obooman** [react-community/react-navigation#2569] opened 2017-09-12 02:00 UTC
When iOS accessibility -> bold text enabled the tab navigator render the wrong way:it render the normal icon with a RANDOM one of the tav icons cover.

### Expected Behavior
Render tab bottom icon the right way.

### Your Environment
macOS 10.12.6 (16G29)

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.11
| react-native     |0.45.1
| node             | v7.8.0
| npm or yarn      | npm@5.3.0 yarn@0.15.1

| Normal | Error         
| ---------------- | -------
|![normal style](https://user-images.githubusercontent.com/9863282/30304581-cafbcd80-9733-11e7-9c1e-a33aea53e00f.png)|![bold text error](https://user-images.githubusercontent.com/9863282/30304580-caf9528a-9733-11e7-8c8b-6e971632baab.png)

**Comment by spencercarli** [comment] 2017-09-13 14:19
How can we reproduce this? Is it something we can do via the example app in the repo? What steps would we need to take to recreate this?

**Comment by Obooman** [comment] 2017-09-14 15:32
Hi, I have [this gist](https://gist.github.com/Obooman/0f1f2378550089d0b330d15f9dcd6d18) for example code,I tried expo way and the issue has not been reproduce.

I copy most of the demo code from [reactnavigation.org](https://reactnavigation.org) docs,and the issue will be reproduce every time when I run it on any iOS device with "Bold Text" option enabled.

## Reproduce

```bash
$ react-native init DemoProject
$ yarn add react-navigation
```

replace `index.ios.js` with [this gist](https://gist.github.com/Obooman/0f1f2378550089d0b330d15f9dcd6d18), run in iOS device.

**Comment by kelset** [comment] 2017-12-10 12:57
Pinging OP @Obooman since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment] 2017-12-17 15:33
Hi there @Obooman ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-12-17 15:33 UTC
Labels: 7 days countdown, bug, needs more info
