### ISSUE TITLE
action: NavigationActions.navigate. dispatch not working

### ISSUE THREAD

**Issue by nishantonline1** [react-community/react-navigation#2937] opened 2017-11-09 08:01 UTC
Below is the code which i wrote for nested stack navigators. when i'm trying to navigate from screen four to screen three, it get navigated to screen two instead of three. Anyone work around this???

import React from 'react';
import {
  Text,
  View,
  navigationOptions,
  Platform,
  props,
  StyleSheet,
  TouchableOpacity
} from 'react-native';

import {StackNavigator,NavigationActions} from 'react-navigation';
import one from './screens/screenone'
import two from './screens/Screentwo'
import three from './screens/Screenthree'
import five from './screens/Screenfive'
class four extends React.Component {

  constructor(props) {
    super(props);
    //console.log(this.props);
  }

navigate=()=>{
  const navigateAction = NavigationActions.navigate({

    routeName: 'one',

    params: {},

    action: NavigationActions.navigate({ routeName: 'three'})
  })

  this.props.navigation.dispatch(navigateAction)
}

  render() {
    let {navigate}=this.props.navigation
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.navigate}><Text>Screenfour</Text></TouchableOpacity>
      </View>
    );
  }
}

const NesNavigation = StackNavigator({
  two: {screen: two},
  three: {screen: three},
  five:{screen: five},
},{
  cardStyle: {
      paddingTop: Platform.OS === 'ios' ? 0 : 0
    },
});

class Screenone extends React.Component {
  static navigationOptions = {
    header: null // Hide header
  };
  render() {
    return (
      <NesNavigation screenProps={this.props.navigation}/>
    );
  }
}

const Navigation = StackNavigator({
  four: {screen: four},
  one: {screen:Screenone},
  
},{
  cardStyle: {
      paddingTop: Platform.OS === 'ios' ? 0 : 0
    },
});
Navigation.router=NesNavigation.router

export default class app extends React.Component {
  
  constructor(props) {
    super(props);
    this.state={
      appLoading:true
    }
  }
  setAppLoading=()=>{
    this.setState({appLoading:false})
  }
  render(){
    var passProps={
      loading:this.state.appLoading,
      setLoading:this.setAppLoading,
    }
    return(<Navigation screenProps={passProps}/> );
  }
};
//Export all your root navigator as the root component
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by kelset** [comment] 2017-11-09 09:35
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-09 09:35 UTC

**Comment by pranjal-goswami** [comment] 2019-02-27 10:22
If you are using react-navigation 3.x, you can follow the docs here : https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html
