### ISSUE TITLE
Reload screen when reset to home

### ISSUE THREAD

**Issue by mongveasna** [react-community/react-navigation#3065] opened 2017-12-02 05:29 UTC
Hi guys, I want to back to home screen but it reload the screen
here is my code

   const resetAction = NavigationActions.reset({
            index: 0,
            actions: [NavigationActions.navigate({routeName: 'Home'})]
        })
        this
            .props
            .navigation
            .dispatch(resetAction)

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11
| react-native     | 0.45.1

**Comment by kelset** [comment] 2017-12-02 18:34
Closing because:
1. you haven't followed the template
1. you are using a really old version of the lib and of RN
1. it's a duplicate of https://github.com/react-community/react-navigation/issues/3062

**Closed by kelset** 2017-12-02 18:34 UTC
