### ISSUE TITLE
TabNavigator randomly switches tab after a few seconds

### ISSUE THREAD

**Issue by dht** [react-community/react-navigation#3066] opened 2017-12-02 11:13 UTC
We have a TabNavigation in our React Native app and we experience a peculiar behaviour in which 3 seconds after the app loads the active tab is switched to a random tab with no action fired. Anybody came across such behaviour?

```js
TabNavigator({
        shifts: {
            screen: ScreenShift,
            navigationOptions: {
                tabBarLabel: getKey("shifts"),
            }
        },
        availabilities: {
            screen: ScreenAvailabilities,
            navigationOptions: {
                tabBarLabel: getKey("availabilities"),
            }
        },
        news: {
            screen: ScreenFeed,
            navigationOptions: {
                tabBarLabel: getKey("news"),
            }
        },
        chat: {
            screen: ScreenChat,
            navigationOptions: {
                tabBarLabel: getKey("chat"),
            }
        },
        admin: {
            screen: ScreenAdmin,
            navigationOptions: {
                tabBarLabel: getKey("admin"),
            }
        },
    }, {
        tabBarPosition: 'bottom',
        animationEnabled: false,
        swipeEnabled: false,
        tabBarOptions: {
            showIcon: true,
            activeTintColor: colors.colorBk,
            inactiveTintColor: '#999999',
            style: {
                backgroundColor: '#ffffff',
                shadowOffset: {width: 1, height: -0.5},
                shadowOpacity: 0.2,
                shadowRadius: 1,
                shadowColor: '#333'
            },
            labelStyle: {
                fontSize: 9,
                position: 'relative',
                top: -5,
                fontFamily: 'Gotham',
            },
            indicatorStyle: {
                backgroundColor: 'white'
            },
        }
    }
```

**Comment by kelset** [comment] 2017-12-02 18:35
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-02 18:35 UTC

**Comment by dht** [comment] 2017-12-03 06:52
Solved. Apparently a call to setParams changed the active tab.

**Comment by feliperaul** [comment] 2018-05-08 04:01
@dht we started experiencing this issue right after we made some code changes that used setParams. Could you elaborate your fix?

**Comment by brentvatne** [comment] 2018-05-08 17:19
can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!
