### ISSUE TITLE
StackNavigator have no Header in a TabRouter

### ISSUE THREAD

**Issue by tiaaaa123** [react-community/react-navigation#1686] opened 2017-05-25 14:22 UTC
Hi!

I made myself a custom TabBar with gradient background and stuff with `TabRouter` (because you can't make one with `TabNavigator` right?). But one of my tab is a `StackNavigator` and it doesn't display the navBar on top of the screen. Do I need to manually add it the CustomTabView?

Shouldn't the `ActiveScreen` handle the navBar if it's a StackNavigator?

```
const Tabs = TabRouter(
  {
    Main: {
      screen: StackNavigator({             //My StackNavigator which should have a navBar on top...
        Dashboard: {
          screen: Dashboard,
          title: 'Dashboard',
        },
        Wallet: { screen: Wallet },
        Deck: { screen: Deck },
        EnterpriseProfile: { screen: EnterpriseProfile },
      }, {
        initialRouteName: 'Dashboard',
      }),
    },
  },
  {
    initialRouteName: 'Main',
    swipeEnabled: false,
    animationEnabled: false,
    backBehavior: 'none',
  },
);

const CustomTabView = ({ router, navigation }) => {
  const { routes, index } = navigation.state;
  const ActiveScreen = router.getComponentForState(navigation.state);

  return (
    <View style={{ flex: 1, paddingTop: Platform.OS === 'ios' ? 20 : 0 }}>
      <ActiveScreen
        navigation={addNavigationHelpers({
          ...navigation,
          state: routes[index],
        })}
      />

     // My Custom TabBar because I don't want the default one from TabNavigator
      <View style={styles.tabContainer}>
        {routes.map(route => (
          <TouchableOpacity key={route.routeName} onPress={() => navigation.dispatch({ type: 'Navigation/BACK' })}
          >
            <TabItem />
          </TouchableOpacity>
        ))}
      </View>
    </View>
  );
};

const TabBar = createNavigationContainer(createNavigator(Tabs)(CustomTabView));

export default TabBar;
```

**Comment by emusgrave** [comment] 2017-05-25 15:31
I'm struggling with the same issue right now. I am not sure if it's a complete solution yet, but I at least got the header to display by swapping out
```
const ActiveScreen = router.getComponentForState(navigation.state);
```
For
```
const ActiveScreen = router.getComponentForRouteName(
    navigation.state.routes[navigation.state.index].routeName
  );
```

Take a look into `TabView._renderScene` to see where I am deriving this from.

Overall I'm worried about the approach because this custom tab bar seems to take a fairly different code path from the default source. For example, the HOC called `withCachedChildNavigation` is not used in the CustomTab example.

**Comment by faceyspacey** [comment] 2017-05-25 18:13
What is the value of your `ActiveScreen` and if you manually put your `<MainStackNavigator />` where `<ActiveScreen />` is, does it work? 

If the issue is like @emusgrave says, then it's likely a bug, as both`getComponentForState` and `getComponentForRouteName` should return the same component.

My hunch is somehow the `childRouter` does not exist in `tabRouters[routeName]` in the TabRouter code for `getComponentForState`:

```js
getComponentForState(
      state: NavigationState,
    ): NavigationScreenComponent<*, NavigationTabScreenOptions> {
      const routeName = order[state.index];
      invariant(
        routeName,
        `There is no route defined for index ${state.index}. Check that
        that you passed in a navigation state with a valid tab/screen index.`,
      );
      const childRouter = tabRouters[routeName];
      if (childRouter) {
        return childRouter.getComponentForState(state.routes[state.index]);
      }
      return getScreenForRouteName(routeConfigs, routeName);
    },
```

Step into that in the debugger and see.

**Comment by faceyspacey** [comment] 2017-05-25 18:17
At the top of `TabRouter.js` the `tabRouters` map is built based on whether your screens have a `router` property:

```js
if (routeConfig.screen && routeConfig.screen.router) {
      tabRouters[routeName] = routeConfig.screen.router;
    }
```

I'm willing to bet that in your customization of these tools somehow that connection was lost.

**Comment by faceyspacey** [comment] 2017-05-25 18:23
Also, I would try this: `const ActiveScreen = Tabs.getComponentForState(navigation.state)` just to insure the correct router is being used. 

Then if that doesn't work, manually create the state that you think should work and pass it to it. Step through the code in the debugger as you do this and you'll see exactly what's happening. There's something small and stupid you gotta get to the bottom of because what you made should work.

**Comment by tiaaaa123** [comment] 2017-05-26 17:13
The only thing that worked is @emusgrave solution, but simply giving a field (title for example) to an element of the StackNavigator doesn't do anything. I need to use `configuationOptions` in each of my screen.

```
    Main: {
      screen: StackNavigator({
        Dashboard: {
          screen: Dashboard,
          title: 'Dashboard',
          configurationOptions = ({}) => ({ title: 'Dashboard'})
        },
      }, {
        initialRouteName: 'Dashboard',
      }),
    },
  },
```

@faceyspacey 
The problem I'm facing right now is that I need to customize the navBar (custom gradient background) and stuff. Is there a way to make a general header to the StackNavigator and it would place the headerRight, headerLeft, etc.. like the default navBar?

**Comment by faceyspacey** [comment] 2017-05-26 17:37
yea, read the docs. u dont specify title where u specify screen. u specify it in several other places. 

...u gotta use the `header` option and replace the whole thing. the styling options throughout React Navigation are kinda *all or nothing*. Study the docs in-and-out. Your answers are all there. 

...as for the original question--something's wrong if u couldn't do it the correct way. u should get to the bottom of that or it will likely cause u more problems. The component should simply be here: `const ActiveScreen = router.getComponentForState(navigation.state)`. Step through it and find out what's wrong.

**Comment by spencercarli** [comment] 2017-08-30 02:26
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-30 02:26 UTC
Labels: Type: Question
