### ISSUE TITLE
Add the option to add a header on a TabNavigator

### ISSUE THREAD

**Issue by timhonders** [react-community/react-navigation#2176] opened 2017-07-18 13:50 UTC
**Use case** 

We have an app with a DrawerNavigator as root navigator and TabNavigator wrapped in a StackNavigator like suggested in https://github.com/react-community/react-navigation/issues/741.

We wan't to have the Tab link directly in the drawer but when i trace the menu items and routes in the drawer:

![rwact-navigation1](https://user-images.githubusercontent.com/1888761/28319780-2cc85c80-6bcf-11e7-9acc-2f136e3b1feb.png)

But when i remove the StackNavigator it works like expected, and i can add the links in the drawer. 

![rwact-navigation2](https://user-images.githubusercontent.com/1888761/28319793-31306e52-6bcf-11e7-87c3-4e799f9afd05.png)

So it would be very nice if we have an option to add a header to the TabNavigator lik the StackNavigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.1

**Comment by kelset** [comment] 2017-11-25 09:11
Pinging OP @timhonders since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I think it's a duplicate of #1933

**Comment by timhonders** [comment] 2017-11-27 12:16
The outcome of  #1933 wil fix our problem, i thunk it is a better solution.

So u can close this one

**Closed** 2017-11-27 12:34 UTC
Labels: 7 days countdown, feature request
