### ISSUE TITLE
NavigationActions.navigate() returns null

### ISSUE THREAD

**Issue by laoqiren** [react-community/react-navigation#1209] opened 2017-04-24 15:48 UTC
with redux, I tried to navigate between routes by dispatching actions:

`this.props.navigation.dispatch(NavigationActions.navigate({routeName: 'Completed'}))`

and in my reducer:
```
const initialNavState = {
    index: 1,
    routes: [
        {key: 'InitB',routeName: 'Completed'},
        {key: 'InitA',routeName: 'Home'}
    ]
}

export default function(state=initialNavState,action){
    switch(action.type) {
        case 'Login':
            return AppNavigator.router.getStateForAction(NavigationActions.back(),state);
        case 'Logout':
            return AppNavigator.router.getStateForAction(NavigationActions.navigate({routeName: 'Completed'}),state)
        default:
            return  AppNavigator.router.getStateForAction(action,state);
    }
}
```

however there comes the error:
`null is not an object(evaluating 'navigation.state.routes')`

the error comes out not when I call `this.props.navigation.dispatch(NavigationActions.navigate({routeName: 'Completed'}))` it's just when the app runs.

I alert the result of `NavigationActions.navigate({routeName: 'Completed'})` ,it's null.

I don't have any idea to solve it. Hope your reply.

**Comment by grabbou** [comment] 2017-04-24 15:52
That looks like a duplicate of #857.

**Closed by grabbou** 2017-04-24 15:52 UTC

**Comment by laoqiren** [comment] 2017-04-24 15:56
@grabbou  but I have connect the nav store to the navigator

**Comment by grabbou** [comment] 2017-04-25 12:49
@laoqiren the return value of `navigate()` is what `dispatch()` of Redux returns. Undefined is perfectly valid when you don't have any custom middlewares.

Your issue is a duplicate of https://github.com/react-community/react-navigation/issues/857. Note that in its description, it also mentions `null is not an object(evaluating 'navigation.state.routes')`

**Comment by laoqiren** [comment] 2017-04-25 12:52
@grabbou  I think it's a bug of TabNavigator using with redux, I tried to edit the given example to change the StackNavigator to TabNavigator, the same error comes out

**Comment by grabbou** [comment] 2017-04-25 12:53
@laoqiren the default example (`ReduxExample`) we have in the repo works pretty well for Redux so I don't believe it's an issue. 

Anyway, the error you are getting is as described in #857 so let's keep discussion there.

**Comment by laoqiren** [comment] 2017-04-25 12:54
@grabbou  have you tried to change StackNavigator to TabNavigator?

**Comment by grabbou** [comment] 2017-04-25 12:54
I didn't, but folks here https://github.com/react-community/react-navigation/issues/485 did.

**Comment by grabbou** [comment] 2017-04-25 12:55
Check if your `this.props.nav` is properly defined (what's its content), and this file: https://github.com/react-community/react-navigation/blob/master/examples/ReduxExample/src/reducers/index.js which has updated reducer.

**Comment by laoqiren** [comment] 2017-04-25 12:56
@grabbou  I dispatch the back() works well. Could you please have a loot at my code? I think there is no problem.

**Comment by grabbou** [comment] 2017-04-25 12:58
Can you try taking the `reducer` example I linked above? Change the way `initialRouteState` is defined. Maybe there's the problem. Is `pushing` another route works?

How do you create `AppNavigator`?

**Comment by laoqiren** [comment] 2017-04-25 12:59
App navigator:
```
export const AppNavigator = TabNavigator(AppRouteConfigs,{
    tabBarPosition: 'bottom',
    tabBarOptions: {
        showIcon: true
    }
});

@connect(state=>({
    nav: state.nav
}))
class App extends Component {
    componentDidMount(){
        SplashScreen.hide();
    }
    render(){
        return (
            <AppNavigator navigation={addNavigationHelpers({
                dispatch: this.props.dispatch,
                state: this.props.nav
            })}/>
        )
    }
}
export default App; 
```

**Comment by grabbou** [comment] 2017-04-25 13:01
And your `AppRouteConfigs`?

**Comment by laoqiren** [comment] 2017-04-25 13:01
@grabbou const AppRouteConfigs = {
    Home: {
        screen: HomeView
    },
    Completed: {
        screen: CompletedView
    }
}

**Comment by grabbou** [comment] 2017-04-25 13:01
As I said, please check the default Redux example. `getStateForAction` will
return `null` if it doesn't find a matching route and doesn't know how to
handle action.

In the example I linked we have `|| initialState` to avoid that case.

**Comment by laoqiren** [comment] 2017-04-25 13:04
@grabbou  
```
const AppRouteConfigs = {
Home: {
screen: HomeView
},
Completed: {
screen: CompletedView
}
}
```

**Comment by laoqiren** [comment] 2017-04-25 13:08
@grabbou  just the `NavigationActions.navigate()` returns null , others like `NavigationActions.back()` works well.  I eidit the given redux example to change the StackNavigator to TabNavigator the same error comes .

**Comment by laoqiren** [comment] 2017-04-25 13:37
@grabbou  just run `alert(AppNavigator.router.getStateForAction(NavigationActions.navigate({routeName:'Login'}), state))` comes the error.
