### ISSUE TITLE
can't passing parameter to another screen

### ISSUE THREAD

**Issue by salateeq** [react-community/react-navigation#2823] opened 2017-10-25 14:10 UTC
Hi 
i'm using react navigation and trying to send parameter from second screen to third screen 

First Screen (App.js)
`        this.props.navigation.navigate('Index1',{userid1:this.state.studentsS});`
Second Screen (Index.js)
`      this.props.navigation.navigate('MyDealOffer',{userid3:this.props.navigation.state.params.userid1});`
**when i check the value for (this.props.navigation.state.params.userid1) it's having the correct number**
Third Screen(MyDealOffer.js)
```
componentDidMount(){
    this.setState({
      parmstudentid:this.props.navigation.state.params.userid3,
    })
    var x = this.props.navigation.state.params.userid3;
    var url = `http://***:82/wasily/MyDealOffer.php?UserID=${this.props.navigation.state.params.userid3}`
fetch(url,{method:"POST"}).then((response)=>response.json()).then((responseJson)=>{
      var ds = new ListView.DataSource({rowHasChanged:(r1,r2)=>r1!=r2});

      this.setState({
      isLoading:false,
      cloneStudent:ds.cloneWithRows(responseJson),
});
   })
  }

  render() {
    if(this.state.isLoading){
      return(
        <View><Text>Wait</Text></View>
      )
    }
    return (
  <View style={styles.container}>
  <Text>User Details</Text>
  <ListView
  dataSource={this.state.cloneStudent}
  renderRow={(rowData)=>
    <Text>Username : {rowData.Price} , User ID:{rowData.Price} </Text>
  }
  />
  </View>
```
output : "user details without any data"

========================But======================
when i change in the second screen the below line 
`      this.props.navigation.navigate('MyDealOffer',{userid3:this.props.navigation.state.params.userid1});`
to
`      this.props.navigation.navigate('MyDealOffer',{userid3:4});`
it's showing correct data in the third screen

**Comment by salateeq** [comment] 2017-10-26 09:47
still same issue

**Comment by vonovak** [comment] 2017-11-18 01:38
I'm closing this since the description is not very clear and it seems to be a usage question, not an bug. If your issue persists, please open up a new issue and attach a snack reproduction. Thanks :)

**Closed by vonovak** 2017-11-18 01:38 UTC
Labels: help wanted, question
