### ISSUE TITLE
Unable to observer TabNavigator route change 

### ISSUE THREAD

**Issue by thomasbruketta** [react-community/react-navigation#347] opened 2017-02-15 21:10 UTC
In `react-native-tab-view` there was the ability to know when a tab was going to change via `onRequestChangeTab` is there any way to know that a tab has changed? Or are there any hooks / events exposed from the API? Thanks.

**Comment by ElliottJRo** [comment] 2017-02-15 22:47
hey @thomasbruketta you want to do something similar to [this](https://github.com/react-community/react-navigation/issues/348#issuecomment-280164995) which is an example implementation of [custom routers](https://reactnavigation.org/docs/routers/api).

Basically you want to add your hook to the `TabNavigator` router `getStateForAction` method.. At least I think that is how you would do it

**Comment by grabbou** [comment] 2017-02-24 08:58
Duplicate of #51

**Closed by grabbou** 2017-02-24 08:58 UTC
