### ISSUE TITLE
threshold issue for routing (navigate)

### ISSUE THREAD

**Issue by mayurkothule** [react-community/react-navigation#3084] opened 2017-12-06 12:26 UTC
if user click same button twice accidentally screen get pushed number of time to stack whenever we navigate using button click, it is because it take more time to push new screen to stack. To solve this problem, recognizing the touch is also not good option and also tried to showing the loader before navigate but it's not solved this problem. 
this.props.navigation.navigate does not have callback too by which we can overcome this problem.  
If any one has faced same problem and have solution then please share.

**Comment by kelset** [comment] 2017-12-06 13:09
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-06 13:09 UTC
