### ISSUE TITLE
Nested Navigators and Props

### ISSUE THREAD

**Issue by Slooowpoke** [react-community/react-navigation#169] opened 2017-02-03 13:41 UTC
While using React-Native 0.40, and the master branch of this project.

I've got most of my navigation sorted, there is only one issue. When navigating from a StackNavigator back to a TabNavigator, I can't seem to pass the props. I thought this would just follow through the dispatch?

I have a StackNavigator, inside it is a TabNavigator. I pass the prop from the initial TabNavigator to the StackNavigator and then I want to pass it to the second tab in the TabNavigator.

I can Navigate between them all, pass the prop from the TabNavigator to the StackNavigator, its just the last step that I can't seem to crack.

From my preview scene, which comes from the StackNavigator and has been passed down from the TabNavigator.

```
this.props.navigation.dispatch({
      type: 'Navigation/NAVIGATE',
      routeName: 'Home',
      params: {fileToUpload:this.state.filename},
      action: {
         type: 'Navigation/NAVIGATE',
         routeName: 'Uploader',
         params: {fileToUpload:this.state.filename},
      }
})
```

Should I be using a custom navigator? Or a router? They seemed a bit overkill?
Or am I looking at this in the wrong way? Is a Modal a better option?

To clarify I'm trying to pass `this.state.filename`.

**Comment by ericvicenti** [comment] 2017-02-03 17:04
This seems to be a pretty common use case, and I think the only problem is that `TabRouter.getStateForAction` does not seem to merge the params for the navigate action.

It looks like this may fix it:
https://github.com/react-community/react-navigation/pull/134

Can you see if this fix helps?

**Comment by Slooowpoke** [comment] 2017-02-03 17:22
Sorry, doesn't seem to help. The props under state are still just the key and routeName.

**Comment by ericvicenti** [comment] 2017-02-03 17:28
Hm, it can be hard for me to tell whats wrong. Maybe you can write a test for the routers that demonstrate the expected behavior and shows the bug?

**Comment by Slooowpoke** [comment] 2017-02-03 17:42
I'm not even particularly sure if it's even a bug or me just using the whole thing wrong.
I've narrowed it down to being a problem passing props between two navigators (Stack and Tab). I'll have a look on Monday.

I pretty much need to pass the props from a tab to a stack and then back to the second tab. 

The debugger shows that props under state are only key and routeName, but under the new state bit (shown by Navigation Dispatch) the props are there. I feel I'm just missing something small.

**Comment by Slooowpoke** [comment] 2017-02-06 09:38
Okay I have some pictures to help explain the issue a bit more. The state variable shown in the debugger shows the following when passing props from the first scene to Summary it works. This is passing it out of a TabNavigator to a StackNavigator. 

![summaryscene](https://cloud.githubusercontent.com/assets/1674449/22641573/2f716792-ec4f-11e6-96f1-9f9d2da06a0f.png)

However when I want to pass the props back from the StackNavigator to a TabNavigator (which requires the following code to get there).

```
this.props.navigation.dispatch({
      type: 'Navigation/NAVIGATE',
      routeName: 'Home',
      params: {fileToUpload:this.state.filename},
      action: {
         type: 'Navigation/NAVIGATE',
         routeName: 'Listen',
         params: {fileToUpload:this.state.filename},
      }
})
```
The state variable only has the second action's name and the props aren't passed down.

![browsescene](https://cloud.githubusercontent.com/assets/1674449/22641597/488be32e-ec4f-11e6-8cf2-7a26b7cb9259.png)

Is that any clearer?

**Comment by chrissm79** [comment] 2017-02-14 23:01
@Slooowpoke Running into this same issue... did you find any type of work around?

**Comment by Slooowpoke** [comment] 2017-02-14 23:04
I ditched this navigator for another one. Probably not the answer you were hoping for sorry. (react-native-router-flux). If this does get solved I'll probably switch back as it was the only major drawback I encountered. This one is a really fast navigator.

**Comment by chrissm79** [comment] 2017-02-14 23:22
@Slooowpoke Thanks for the honesty! It looks like RNRF [may be rebuilt](https://github.com/aksonov/react-native-router-flux/issues/1595) (at some point) w/ `react-navigation` with v4. I've used it before myself, pretty solid

**Comment by matpaul** [comment] 2017-02-22 16:05
Any fixes for it ? real big trouble =(

**Comment by grabbou** [comment] 2017-02-23 20:39
Are you guys sure it's not similar to #80 and #42? I believe we can close it and keep the entire discussion under single issue. Since Drawer uses TabNavigator, these will be the same.

**Comment by matpaul** [comment] 2017-02-23 20:49
I think it's the same
As i understand if i have nested TabNavigator, StackNavigator and i want to navigate with params from one navigator to another i should do something like this
```js
const navigationAction = NavigationActions.navigate({
  routeName: 'Portfolio', // <==== this is stackNavigator
  action: NavigationActions.navigate({
    routeName: 'PortfolioScreen', // <===== this is defaultScreen for Portfolio
    params: {name: 'hello'}
  })
});
this.props.navigation.dispatch(navigationAction);
```

**Closed** 2017-02-24 06:07 UTC

**Comment by jeffreymendez1993** [comment] 2017-02-24 13:20
@grabbou Why do you close the issue when no solution has been found yet? We could resort to using a global for the Stacks that need params passed.

**Comment by ldipasquale** [comment] 2017-03-30 04:34
@matpaul did you find an approach for this issue?

**Comment by EstebanMarin** [comment] 2018-06-27 17:50
The params are passed, however, they are deeply nested for a code that looks like this:

`this.props.navigation.navigate('NewPaymentScheduler', {
                            type: 'Navigate',
                            routeName: 'NewPaymentScheduler',
                            params: { testParam: 'testParam' },
                          })`

I found my params 3 levels deep as such:

![screen shot 2018-06-27 at 12 48 50 pm](https://user-images.githubusercontent.com/13613037/41990652-b2af6594-7a08-11e8-9eb2-b573886956b6.png)
