### ISSUE TITLE
screenProps causing re-render of screens

### ISSUE THREAD

**Issue by HannanShaik** [react-community/react-navigation#3138] opened 2017-12-16 19:18 UTC
### Current Behavior
I am using a stack navigator. In order to make my screens aware of internet connectivity, I have added the listener in my custom Navigation Component and passing the `screenProps` which can be accessed in all screens.

```
render() {
    const { dispatch, state } = this.props;
    const { isInternetConnected } = this.state;
    return (
      <AppNavigation
        navigation={
          addNavigationHelpers({ dispatch, state })
        }
        screenProps={{ isInternetConnected }}
      />
    );
  }
```

It works great. However, in one of my scenarios I have a Screen with nested component which also uses `redux` for API calls and computation. I am passing the navigation method via props to the child component.

```
class MyScreen extends Component {
....
render(){
return(
   <ChildComponent 
      onNext={()=> this.props.navigation.navigate('NextScreen');
   />
);
}
....
} 
```

When my child component is calling the method `this.props.onNext()` in its `componentWillReceiveProps` method. The screen ends up in a loop, it keeps calling the navigate method and loops forever.

However, if I remove `screenProps` from the root component. It all works.

I have been struggling from 3 days behind this issue. Please help.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.48.1
| node             | 8.9.1
| npm or yarn      | 5.6.0

**Comment by kelset** [comment] 2017-12-17 15:13
Duplicate of https://github.com/react-community/react-navigation/issues/2625

**Closed by kelset** 2017-12-17 15:13 UTC

**Comment by HannanShaik** [comment] 2017-12-18 07:31
@kelset Hey this is not related to #2625. This has nothing to do with navigationParams. 

I am simply navigating to another screen from the nested component and it's causing re-render of the screen.

**Comment by adirzoari** [comment] 2017-12-28 14:50
the same issue, any solution?

**Comment by satya164** [comment] 2017-12-28 15:05
You're passing a new object for `screenProps` every time in render. Make sure you pass the same object unless the value changes and it won't trigger a re-render.

**Comment by adirzoari** [comment] 2017-12-28 15:09
I sent object that not changed

>                         <Main screenProps={{'test':'1234'}} onNavigationStateChange={this.onNavigationStateChange.bind(this)} ref={(ref) => { ref ? NavigationStore.setNavigation(ref._navigation) : null }} />

**Comment by satya164** [comment] 2017-12-28 15:16
```js
screenProps={{'test':'1234'}}
```

Here, on every render you're creating a new object: `{'test':'1234'}`. The contents of the object don't change, but the reference changes.

```js
var a = {'test':'1234'};
var b = {'test':'1234'};

console.log(a === b); // false
```

You need to maintain the reference instead of creating a new object. There are 2 ways to do so:
1. Use `lodash/memoize` to memoize te result
2. Put the whole object in state

**Comment by HannanShaik** [comment] 2018-01-12 06:29
@satya164 Could you please explain by what you mean by 

`2. Put the whole object in state`

My Code is 

```
<AppNavigation
        navigation={
          addNavigationHelpers({ dispatch, nav })
        }
        screenProps={{ isInternetConnected: this.state.isInternetConnected }}
      />
```
