### ISSUE TITLE
StatusBar Color is not changing with tabbar on android

### ISSUE THREAD

**Issue by j3rin** [react-community/react-navigation#3087] opened 2017-12-06 20:45 UTC
I'm not able to change the StatusBar color, I already tried 
        StatusBar
           barStyle="light-content"
          backgroundColor="blue"
         t
It's white background and white icon color. 
Any help would be great, thank you! 

tabbar settings. 
{
      tabBarPosition: "top",
      tabBarOptions: {
        style: {
          backgroundColor: '#202d3d',
        },

        activeTintColor: '#fff',
        showLabel: true,

        labelStyle: {
          fontSize: 12,
        }
      }
  },

**Comment by kelset** [comment] 2017-12-07 09:19
Closing because you haven't followed the issue template; moreover it's a duplicate of https://github.com/react-community/react-navigation/issues/12.

**Closed by kelset** 2017-12-07 09:19 UTC
