### ISSUE TITLE
Unable to goBack and setParams

### ISSUE THREAD

**Issue by alphasp** [react-community/react-navigation#288] opened 2017-02-10 21:07 UTC
Hi,

I am trying to setParams on screen B then go back to screen A with updated params, but currently params will not be set.
I have following navigation setup:
Stack navigation
```
const AppNavigator = StackNavigator({
  Main: { 
    screen: MainNavigator,
    navigationOptions: {
      header: ({ state, setParams }) => ({
        visible: false,
      })
    },
  },
  Filter: {
    screen: FilterScreen,
    navigationOptions: {
      title: "Display Options",
    },
  }
}, {
  headerMode: 'screen',
});
```
Tabs navigation
```
const MainNavigator = TabNavigator({
  Home: { 
    screen: HomeScreen,
  },
  UserProfile: { 
    screen: UserProfileScreen,
  },
  Setting: { 
    screen: SettingScreen,
  },
}, {
  headerMode: 'none',
  swipeEnabled: false,
  tabBarPosition: 'bottom',
});
```
A button in home screen that will be navigate to filter screen on press
```
const MyNavScreen = ({ navigation, banner }) => (
  <ScrollView>
    <Text>{banner}</Text>
    <Button
      onPress={() => {
        navigation.navigate("Filter", {
          onPressFilterButton: () => {
            console.log('apply filter and go back')
            navigation.goBack(null)
            navigation.setParams({filterField: { x: true, y: 123 }});
          }
        })
      }}
      title="Go to filter page"
    />
    <Button
      onPress={() => {
        navigation.goBack(null);
      }}
      title="Go back"
    />
    <Text>{JSON.stringify(navigation.state, null, 2)}</Text>
  </ScrollView>
);

const HomeScreen = ({ navigation }) => (
  <MyNavScreen
    banner="Home Screen"
    navigation={navigation}
  />
);
```
When i press Apply Filter button on filter screen, the `onPressFilterButton` callback will be call, it will navigate back to previous screen (home) but the params that I set (`filterField`) will not be pass back to home screen
```
//Full screen page
const FilterScreen = ({ navigation, banner }) => {
  return (
    <ScrollView>
      <Text>{banner}</Text>
      <Button
        onPress={navigation.state.params.onPressFilterButton}
        title="Apply filter"
      />
    </ScrollView>
  )
};
```
Full code in gist https://gist.github.com/alphasp/d1c4d75672480ea50a89ba4d3134fa52

**Comment by alphasp** [comment] 2017-02-11 06:45
OK, figured out a hacky solution, need to add some delay before calling setParams, 
Is there any alternative better way to fix this?
```
    <Button
      onPress={() => {
        navigation.navigate("Filter", {
          onPressFilterButton: () => {
            console.log('apply filter and go back')
            navigation.goBack(null)
            setTimeout(() => navigation.setParams({filterField: { x: true, y: 123 }}), 10)
            //navigation.setParams({filterField: { x: true, y: 123 }});
          }
        })
      }}
      title="Go to filter page"
    />
```

**Comment by ericvicenti** [comment] 2017-02-13 16:53
If you have an action that should change some state and also navigate, you probably want to override you router's `getStateForAction`,  and support your custom action.

**Comment by dodgecm** [comment] 2017-02-14 03:50
I'm running into a related issue.  I want to pass an object from the child component in a stack to the parent component.  A modal "pick an object from the list, and then dismiss" kind of deal.

Right now I'm using setParams in the child component with the key of the parent component to set an object, and then dispatching a Back action.  After the setParams action is dispatched, the object shows up in the params, but after the Back action, the object mysteriously vanishes.

**Comment by ericvicenti** [comment] 2017-02-14 04:27
@dodgecm, this sort of thing is probably an easy fix, if you can produce a test case for it. Otherwise it can be hard to see what exactly is broken, and it can be hard to verify that it continues to work forever. If you submit a PR with just the failing test where the back action causes the previous screen to loose params, we are very likely to see the obvious bug and fix it.

**Comment by ericvicenti** [comment] 2017-02-14 04:27
To produce a test case, fork the library and follow instructions in the contributors guide: https://reactnavigation.org/docs/guides/contributors

**Comment by dodgecm** [comment] 2017-02-14 21:18
@ericvicenti I'm still working on reproducing the exact conditions for the issue.  I believe it has to do with nested navigators (drawer inside stack), since the goBack action is pulling from an out-of-date previous state.

**Comment by dodgecm** [comment] 2017-02-14 23:59
@ericvicenti Okay, I managed to track down the specific issue.  I was triggering the goBack action right after the dispatch for setParams, creating a race condition, but I needed to wrap the goBack action in setTimeout.  So it seems like my issue essentially reduces to what @alphasp was using earlier.  

I don't know if this behavior is unintended or interesting at all; I created an minimal example inside NavigationPlayground that you can look at.

[https://github.com/dodgecm/react-navigation/commit/49cbe3fe0045da242ced57a005fb351419e8a09a](url)

**Comment by pxue** [comment] 2017-04-03 15:58
Running into same issue. Is setTimeout currently the best / most-correct option?

**Comment by cooperka** [comment] 2017-04-30 15:43
I haven't tried it, but it sounds like this PR might help: https://github.com/react-community/react-navigation/pull/1313

**Comment by debrice** [comment] 2017-07-17 07:29
I know it's old but @alphasp, for that use case, when you navigate from A to B and you want B to communicate information back to A you can pass a callback (here `onSelect`):

```jsx
import React from "react";
import { Button, Text, View } from "react-native";

class ViewA extends React.Component {
  state = { selected: false };
  onSelect = data => {
    this.setState(data);
  };

  onPress = () => {
    this.props.navigate("ViewB", { onSelect: this.onSelect });
  };

  render() {
    return (
      <View>
        <Text>{this.state.selected ? "Selected" : "Not Selected"}</Text>
        <Button title="Next" onPress={this.onPress} />
      </View>
    );
  }
}
```
```jsx
import React from "react";
import { Button } from "react-native";

class ViewB extends React.Component {
  goBack() {
    const { navigation } = this.props;

    navigation.goBack();
    navigation.state.params.onSelect({ selected: true });
  }

  render() {
    return <Button title="back" onPress={this.goBack} />;
  }
}
```

**Comment by spencercarli** [comment] 2017-08-28 01:34
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:34 UTC
Labels: Type: Question

**Comment by SurajMDurgad** [comment] 2018-02-15 06:31
@debrice 
Hey,
I followed your method but for me it throws an error saying "Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op."
Any work around?

**Comment by gre** [comment] 2018-03-23 08:08
The solution to pass-in a callback to the `navigate()` params feels very hacky to me.
To me, the whole idea of a navigation/routing library is to manage screens in a stateless way. If you start passing callback reference, it means your routes stack no longer is serializable (so it can't work if you re-set your root stack from a deeplink for instance).

Is there plan to introduce a way to goBack() with a result to the previous parent screen?

A solution could be that the "parent" screen would to "listen" to some result coming from back (`navigation.listenResultFromChild(({...msg}) => ...doYourThing)` that you could call at componentDidMount time), and for the child screen we could have a `goBackWithResult({...msg})`

**Comment by brentvatne** [comment] 2018-04-03 21:56
@gre - I believe https://github.com/react-navigation/rfcs/blob/master/text/0004-less-pushy-navigate.md helps with this a bit in cases where you know upfront what the previous route will be.

if the screen you can go back to is determined at runtime and you want to avoid passing a callback (as you should), you can pass the route state in params:

```
// In your component that you want to go back to
const { navigation } = this.props;
navigation.navigate('SomeForm', { returnToRoute: navigation.state });

// In the other thing
onComplete = (data) => {
  const { navigation } = this.props;
  const { routeName, key } = navigation.getParam('returnToRoute');
  navigation.navigate({routeName, key, params: data});
}
```

**Comment by morgan666** [comment] 2018-08-11 02:52
Instead of using goBack() which does not allow to pass params, just navigate to that route using standard navigate function:
```javascript
this.props.navigation.navigate("Home", {
    param: paramValue, 
    param2: paramValue2
});
```
It looks like it does exactly what goBack() would do, works for me

**Comment by gre** [comment] 2018-08-15 15:40
yeah, I think this is solved since v2 ;)

**Comment by jdnichollsc** [comment] 2018-11-29 19:17
thanks @brentvatne, you save my day! 🍻

**Comment by Dror-Bar** [comment] 2019-02-10 10:07
But, if you navigate (back) from screen 'B' to screen 'A' and send params, how would you set those params in the state of screen 'A' without passing a callback?

**Comment by jdnichollsc** [comment] 2019-02-10 15:34
This is the best solution, you don't need to remove the subscription manually https://reactnavigation.org/docs/en/navigation-events.html

**Comment by Dror-Bar** [comment] 2019-02-10 15:38
Thanks jdnichollsc. But how is it different than subscribing to navigation lifecycle events? other than the fact you don't need to unsubscribe (which is no biggie 😉);

**Comment by Skylnt** [comment] 2019-04-09 07:25
@debrice thankyou verymuch! <3 <3

**Comment by bscaspar** [comment] 2019-05-01 00:22
I'm running into this problem as well but would prefer to continue using goBack so I don't have to specify the route I want to navigate to - it's used in a common component so needs to remain generic. Is there any workaround other than a timeout or using navigation.navigate?

**Comment by Dror-Bar** [comment] 2019-05-01 17:42
@bscaspar 
You have 2 options.
1. Use Redux.
2. The solution offered in this thread [here](https://github.com/react-navigation/react-navigation/issues/288#issuecomment-315684617) will work for you. Just make sure to pass the method onSelect (or however you wish to call it) from every screen that navigates to your common component.

**Comment by lucaspiressimao** [comment] 2020-03-18 13:35
I`m  facing this problem with navigation 5. But setting a function as a param is not working .. any ideias?

**Comment by TommyLeong** [comment] 2020-08-14 06:04
> I know it's old but @alphasp, for that use case, when you navigate from A to B and you want B to communicate information back to A you can pass a callback (here `onSelect`):
> 
> ```js-jsx
> import React from "react";
> import { Button, Text, View } from "react-native";
> 
> class ViewA extends React.Component {
>   state = { selected: false };
> 
>   onSelect = data => {
>     this.setState(data);
>   };
> 
>   onPress = () => {
>     this.props.navigate("ViewB", { onSelect: this.onSelect });
>   };
> 
>   render() {
>     return (
>       <View>
>         <Text>{this.state.selected ? "Selected" : "Not Selected"}</Text>
>         <Button title="Next" onPress={this.onPress} />
>       </View>
>     );
>   }
> }
> ```
> 
> ```js-jsx
> import React from "react";
> import { Button } from "react-native";
> 
> class ViewB extends React.Component {
>   goBack() {
>     const { navigation } = this.props;
>     navigation.goBack();
>     navigation.state.params.onSelect({ selected: true });
>   }
> 
>   render() {
>     return <Button title="back" onPress={this.goBack} />;
>   }
> }
> ```

You're the man! Your solution still save people at 2020, hats off!

**Comment by danieldauk** [comment] 2020-09-22 11:34
If someone is still interested in how to do it in 2020: "[you can use the navigate method, which acts like goBack if the screen already exists](https://reactnavigation.org/docs/params/#passing-params-to-a-previous-screen)"

**Comment by Anujmoglix** [comment] 2021-02-09 19:23
> I know it's old but @alphasp, for that use case, when you navigate from A to B and you want B to communicate information back to A you can pass a callback (here `onSelect`):
> 
> ```js-jsx
> import React from "react";
> import { Button, Text, View } from "react-native";
> 
> class ViewA extends React.Component {
>   state = { selected: false };
> 
>   onSelect = data => {
>     this.setState(data);
>   };
> 
>   onPress = () => {
>     this.props.navigate("ViewB", { onSelect: this.onSelect });
>   };
> 
>   render() {
>     return (
>       <View>
>         <Text>{this.state.selected ? "Selected" : "Not Selected"}</Text>
>         <Button title="Next" onPress={this.onPress} />
>       </View>
>     );
>   }
> }
> ```
> 
> ```js-jsx
> import React from "react";
> import { Button } from "react-native";
> 
> class ViewB extends React.Component {
>   goBack() {
>     const { navigation } = this.props;
>     navigation.goBack();
>     navigation.state.params.onSelect({ selected: true });
>   }
> 
>   render() {
>     return <Button title="back" onPress={this.goBack} />;
>   }
> }
> ```

 true, message: "Reported", status: "200", errors: Array(0), warnings: null}
ReasonScreen.js:119 TypeError: _this2.props.navigation.state.params.onSelect is not a function

**Comment by waynedunkley** [comment] 2021-02-25 02:42
I have been looking for a solution to pass values back from modals and @debrice has finally saved me!! Thank you.

For anyone else that's looking to achieve the same thing, here is a slightly adapted version of the original solution using hooks and React Navigation V5. Key takeaway here is that `params` are on the `route` property.

```
import React from "react";
import { Button, Text, View } from "react-native";

const ViewA = ({ navigation }) => {
  const [selected, setSelected] = React.useState(false)
  
  const onSelect = data => {
    this.setState(data);
  };

  return (
    <View>
      <Text>{selected ? "Selected" : "Not Selected"}</Text>
      <Button title="Next" onPress={() => navigation.navigate("ViewB", { onSelect })} />
    </View>
  );
}
```

```
import React from "react";
import { Button } from "react-native";

const ViewB = ({ navigation, route }) => {
  const goBack = () => {
    navigation.goBack();
    route.params.onSelect({ selected: true });
  }

  return <Button title="back" onPress={this.goBack} />;
}
```

**Comment by brentvatne** [comment] 2021-02-26 01:47
pass in the route name that you're going back to in a param, then navigate to it

```js
navigation.navigate(params.returnRouteName, { someParams: '123' });
```
