### ISSUE TITLE
Not support screen slide in from right and fade in from the left in Android

### ISSUE THREAD

**Issue by joeyzhao0113** [react-community/react-navigation#512] opened 2017-02-28 11:44 UTC
I can make the navigation happens on android device but how I can make the screen slide in from the right and fade in from the left.
More information please see below link:
http://stackoverflow.com/questions/42465530/react-native-navigation-for-android

**Comment by lee-you** [comment] 2017-02-28 15:57
This problem has been bothering me a lot of days, can someone answer in detail

**Comment by grabbou** [comment] 2017-03-01 11:26
I think it's a duplicate of #124

**Closed by grabbou** 2017-03-01 11:26 UTC
