### ISSUE TITLE
1.0.0-beta.12: Navigation only working when Debug Remote JS is active

### ISSUE THREAD

**Issue by raarts** [react-community/react-navigation#2201] opened 2017-07-20 22:59 UTC
### Current Behavior

When I enable Debug Remote JS navigation works. If I don't and navigate to the same screen, I get an out of memory error.

This happens when I navigate from the Settings Screen to the Phone Number Screen.
The DevTools console does not report errors, when debugging is enabled. Navigation just works.

### Expected Behavior

Should work either way.

### Your Environment

Navigation structure:

```
const PhoneNumberScreenNavigator = StackNavigator({
  PhoneNumbers: { screen: PhoneNumbersScreen },
  EditPhoneNumber: { screen: EditPhoneNumberScreen },
},{
  mode: 'modal',
});

const HomeScreen = TabNavigator({
  ContactsScreen: {screen: ContactsScreen},
  RecentsScreen: {screen: RecentsScreen},
  SettingsScreen: {screen: SettingsScreen },
});

export var RootNavigator = StackNavigator({
  Home: { screen: HomeScreen },
  PhoneNumbers: { screen: PhoneNumberScreenNavigator },
});
```

Versions:
```
   "expo": "^18.0.1",
    "native-base": "2.2.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-native-clean-form": "^0.4.1",
    "react-native-elements": "^0.13.0",
    "react-native-extended-stylesheet": "^0.6.0",
    "react-native-i18n": "git+https://github.com/xcarpentier/ex-react-native-i18n.git",
    "react-native-swipe-list-view": "^0.4.1",
    "react-native-swipeout": "^2.1.3",
    "react-native-toaster": "^1.1.1",
    "react-navigation": "^1.0.0-beta.12",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^2.13.2",
    "redux-form": "^6.8.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.8.0",
    "redux-saga": "^0.15.4"
```

I can't try earlier versions, because I could not get nested navigation to work at all with those.

**Comment by Ragnar-H** [comment] 2017-09-21 09:09
@raarts are you experiencing this issue on Android and iOS?

We're experiencing a similar "only works with Debug Remote JS" issue, but only on Android 🤔

**Comment by JoseArceDev** [comment] 2017-11-03 13:11
I have the same issue on both devices, only working when Debug Remote JS is active.

**Comment by kelset** [comment] 2017-11-03 20:28
This is quite a weird bug. 😶

Can you please try with the latest version and to create a repo/[expo snack](https://snack.expo.io/) that reproduces the issue?

**Comment by kelset** [comment] 2017-11-25 09:16
Hi there @raarts,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-11-25 09:16 UTC
Labels: bug

**Comment by karlmosenbacher** [comment] 2018-06-07 15:54
@brzonsea Cant believe that worked ! Thank you for sharing!

**Comment by kesha-antonov** [comment] 2018-11-20 06:46
Thanks! @brzonsea

**Comment by NathanNovak** [comment] 2019-03-11 18:32
@brzonsea Thank you that worked!

**Comment by eazeye** [comment] 2019-03-19 23:54
@brzonsea  Works for me as well like this.
So has there been no discussion or attempt to fix this issue? As indicated by how subtle it is, it seems this bug can cost a lot of productivity if developers don't know to look out for it.

**Comment by brentvatne** [comment] 2019-03-20 16:40
the problem goes beyond what this lib can do, it depends on react-native itself using a different debugging mechanism

**Comment by eazeye** [comment] 2019-03-20 17:14
Absolutely, had that thought a bit ago as well. Is there somewhere you think would be appropriate to add a note/comment regarding the issue of `console.*` statements and their impact?

**Comment by brentvatne** [comment] 2019-03-20 17:16
https://github.com/react-native-community/discussions-and-proposals/issues/69 could be a good spot

**Comment by Gigasz** [comment] 2019-03-28 11:45
> @raarts I had the same error, and it was gone after I deleted my `console.log()`

Dude. I would never think of that. Thank you so much

**Comment by xmanemran** [comment] 2019-05-16 07:06
In my case, I logged a reference component which was a redux HOC. 
> reference
```
<ReportForm
 images={images}
 ref={ref => (this.errorFormRef = ref)}>
  //children
</ReportForm>
```

> case the error

```
onSubmitComplete = () => { 
 const { pop } = this.props.navigation;
 console.log(this.errorFormRef)
 pop();
};
```

> solution
```
onSubmitComplete = () => { 
 const { pop } = this.props.navigation;
 console.log('in onSubmitComplete')
 pop();
};
```

**Comment by PankoArtem** [comment] 2022-01-30 20:39
I have an opposite problem. When i try debug app with react-native-debugger 
`import 'react-native-gesture-handler';
import React from 'react';
import {SafeAreaView, Text} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createDrawerNavigator} from '@react-navigation/drawer';

const Drawer = createDrawerNavigator();

const Home = () => {
  return <Text>Home</Text>;
};

const App = () => {
  return (
    <SafeAreaView style={{flex: 1}}>
      <NavigationContainer>
        <Drawer.Navigator initialRouteName={'Home'}>
          <Drawer.Screen name={'Home'} component={Home} />
        </Drawer.Navigator>
      </NavigationContainer>
    </SafeAreaView>
  );
};

export default App;
`

but when i stop debugging, and it logs to my shell all works correct
