### ISSUE TITLE
switch non-adjacent tab in tabNavigator on Android

### ISSUE THREAD

**Issue by zxb407** [react-community/react-navigation#3172] opened 2017-12-22 02:47 UTC
I have a TabNavigator with five screens in my app. I have a question on android.The second , the third and the fourth tabButton display selected icon in sequence when I press the fifth tabButton directly from the first one。At the same time,   componentDidMount and render in other screen run in sequence。  How can I avoid the bad  experience?

**Comment by kelset** [comment] 2017-12-22 16:58
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-22 16:58 UTC
