### ISSUE TITLE
StackNavigator has performance issues and renders too many screens

### ISSUE THREAD

**Issue by zhaoyi0113** [react-community/react-navigation#706] opened 2017-03-16 04:45 UTC
I am using below version of `react-native` and `react-navigation` on Android.

```
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.39.2
```

`"react-navigation": "^1.0.0-beta.6"`

When call `navigate(...)` method, it usually take 1 second to navigate to the next screen. It has no problem on `simulator` only happens on Android device. Is there any way to configure it?

**Comment by blizzardzheng** [comment] 2017-03-20 13:37
i have the same issue ,is there any solution?

**Comment by laalaguer** [comment] 2017-03-20 13:37
We have the same issue here

**Comment by zhaoyi0113** [comment] 2017-03-22 06:03
Not sure whether this can be resolved or not? I don't know what the root cause is. The `Tab Navigator` works perfect only problem is on `Stack Navigator`.

**Comment by zhaoyi0113** [comment] 2017-03-24 23:15
After some deeper investigate, this performance issue happens on nested stack navigator. I have defined one Tab Navigator at the top level and each of the tab has its own nested stack navigator. In this case, the stack navigate method works very slow on Android device. Not sure whether there is a solution for that.

**Comment by laalaguer** [comment] 2017-03-25 02:28
It is because of the "recursive" calling thing. Deeply nested stack navigators are slow in this case. Not sure why it is so obvious on Android.

**Comment by zhaoyi0113** [comment] 2017-03-25 05:30
My case is not deeply nested stack. It is slow for the first stack navigator.

**Comment by adogor** [comment] 2017-03-27 13:28
Same for me, to reproduce this, just init a new project and make a StackNavigator with 1 screen and a button to navigate to itself. After stacking more than 5 screens it's noticeable (on my Nexus 5 at least), and more you navigate slower it is.

If i enable debugging in chrome I don't have this problem (or at least not before 90 screens ...).

I was unable to find the problem, unfortunately we might have to "use ex-navigation" or another navigator because or app is too slow on Android.

**Comment by zhaoyi0113** [comment] 2017-03-27 22:20
Does `ex-navigation` give better performance on Android? If yes, I am going to have a try on it. Otherwise my app performance can't be accepted by users.

**Comment by geekvijay** [comment] 2017-03-29 11:32
i am also facing same problem, its hurting the user experience.

**Comment by sexykodo** [comment] 2017-03-29 13:43
same problem, on android any screen besides the first of the stack has poor performance  :(

**Comment by nico1510** [comment] 2017-04-01 17:40
I also noticed this so I did some tests in the [layout inspector](http://tools.android.com/tech-docs/layout-inspector) and noticed that the StackNavigator still paints all elements from previous routes. The DrawerNavigator doesn't do this. Following are 2 example screens. The first one is a screen in a DrawerNavigator: 
![drawer](https://cloud.githubusercontent.com/assets/5033050/24580944/2fe10a8c-1712-11e7-85ef-c835dfc29344.png)
and here the same screen in a StackNavigator: 
![stack](https://cloud.githubusercontent.com/assets/5033050/24580946/3311ca48-1712-11e7-8b38-054ab7302147.png)
As you can see there are multiple Views from previous routes present. Is this intentional @satya164  ? If yes, would it be possible to add an option to disable this ? Because it seems multiple people have performance problems. https://github.com/react-community/react-navigation/issues/672 may be related too.

**Comment by xilonxiao** [comment] 2017-04-01 19:43
I'm the guy from the #672 . Although my problem isn't exactly with the transitions, it is probably related. Right now I'm working on other issues on my project, but as I am testing my application on both android device and ios simulator, maybe my experiments can bring some light here. I'll try to do some more tests and post the results here.

**Comment by andreialecu** [comment] 2017-04-10 10:26
I'm seeing the same problem. 

Additionally, suspending the app and resuming it takes over 5+ seconds to rerender on my Android device. If I enable the JS perf monitor, I can see that the JS thread drops to 0 fps (sometimes even **minus 2**, which I'm not sure if is a reporting bug of some sort, or an indication of a more serious problem)

The 0 fps drop usually takes several seconds to correct itself. 

In the simulator it seems fine, just the physical device has problems (Android 5.0.1).

**Comment by andreialecu** [comment] 2017-04-10 11:14
Additional note: Enabling the JS debugger makes it slightly faster than without it.

I'm using redux with redux-logger, and one thing I noticed is that the `Navigation/NAVIGATE` action displayed in the log is also delayed by 1+ second after the tap. Once the log line appears, the screen, so it might be a bottleneck somewhere else along the way.

**Comment by andreialecu** [comment] 2017-04-11 09:45
Update: I had my `navigate` calls wrapped in `requestAnimationFrame` in my `onPress` handlers. Removing the wrapper made it navigate instantly when using `Remote JS Debugging`. It seems like using `requestAnimationFrame` made it add a delay for the 1 second that `TouchableOpacity` takes to animate.

However, when not using `Remote JS Debugging`, it is still super slow, on the realm of 1-2 seconds to navigate anywhere including the back button in the top left corner exhibiting the same behavior. I also see the fps frop to `-2.1` while the transition happens. With js debugging enabled, fps stays at 60fps.

Has anyone else had further progress with this?

**Comment by andreialecu** [comment] 2017-04-11 23:39
I believe this was caused by `redux-logger`. Apparently there is a serious bug with `console.log` statements, as noted here: https://github.com/evgenyrodionov/redux-logger/issues/32 

Once I cleared up my console.logs and disabled redux-logger, everything started working much better.

**Comment by andreialecu** [comment] 2017-04-11 23:41
Also related: https://github.com/react-community/react-navigation/issues/360

**Comment by sibelius** [comment] 2017-04-14 20:59
this could help to disable all `console.`

```jsx
if (!__DEV__) {
  // eslint-disable-line no-undef
  [
    'assert',
    'clear',
    'count',
    'debug',
    'dir',
    'dirxml',
    'error',
    'exception',
    'group',
    'groupCollapsed',
    'groupEnd',
    'info',
    'log',
    'profile',
    'profileEnd',
    'table',
    'time',
    'timeEnd',
    'timeStamp',
    'trace',
    'warn',
  ].forEach(methodName => {
    console[methodName] = () => {
      /* noop */
    };
  });
}
```

**Comment by CiralaDevelopment** [comment] 2017-04-19 15:59
This could be fixed by making the navigator only render a couple of scenes instead of all of them (which it currently does). I created my own navigator to get rid of that issue, I only render the current screen and the 2 scenes right next to it in the stack. My renderScene function looks like this:

```
    renderScene = (transitionProps, scene) => {
        const { position } = transitionProps;
        const { index } = scene;

        const offset = position.interpolate({
            inputRange: [index - 1, index, index + 1],
            outputRange: ['100%', '0%', '0%'],
        });

        if (Math.abs(position._value - index) > 1) {
            return;
        }

        const Scene = this.props.router.getComponentForRouteName(scene.route.routeName);

        return (
            <Animated.View style={{
                position: 'absolute',
                top: 0,
                left: offset,
                height: '100%',
                width: '100%',
            }} key={scene.key}>
                <Scene navigation={this.props.navigation} />
            </Animated.View>
        );
    }
```

The interesting bit is:

```
    if (Math.abs(position._value - index) > 1) {
        return;
    }
```

If the current scene is not active or neighbouring the active scene, don't render it.

Not too sure if this approach is good or bad, but it works great for our app. Maybe it could be implemented in the StackNavigator?

**Comment by ms88privat** [comment] 2017-04-22 15:05
related https://github.com/react-community/react-navigation/issues/1132 ?

**Comment by ms88privat** [comment] 2017-04-22 15:09
@CiralaDevelopment Could you please post the whole file of the navigator? I would love to use it too :)

**Comment by CiralaDevelopment** [comment] 2017-04-27 10:18
@ms88privat That would be quite a paste, you should be fine by copy-pasting code from the docs and just replacing the renderScene function with the one I provided above

**Comment by AlanFoster** [comment] 2017-05-02 22:07
Feeling similar performance issues for Android with two stack navigators and having TouchableOpacity elements on the topmost stack

**Comment by dantman** [comment] 2017-05-18 18:58
> Not too sure if this approach is good or bad, but it works great for our app. Maybe it could be implemented in the StackNavigator?

unmounting scenes deeper in the stack would cause state to be destroyed – scroll position and any data stored in the state such as list data fetched over the network would be destroyed/reset. Meaning when you hit back your screens won't look the way they did when you left them.

Rather than completely unmounting them it would be reasonable to use `shouldComponentUpdate` to make react not re-render the old routes deeper in the stack. ex-navigation does this on drawers using `StaticContainer` ([react-static-container](https://www.npmjs.com/package/react-static-container)).

We probably may want a 1 screen delay (ie: the 1 screen before the active one would also be allowed to render) to give the screen room to look at `navigation.state` and do a render when it looses focus. Or maybe we can do this with a `shouldComponentUpdate` that returns true if `isActive || current.isActive !== prev.isActive || current.params !== prev.params` so a component will get updates when active, once when it stops being active, and whenever params change even if inactive.

**Comment by CiralaDevelopment** [comment] 2017-05-23 08:08
@dantman Interesting idea, I'll try to implement it in my app and will come back with the results

**Comment by streco** [comment] 2017-05-25 19:03
Did anyone have any update on this? I have a Nested StackNavigator inside a TabNavigator. The very odd thing for me is that with remote js debugging ON, it is a non-issue. With it OFF, there is a solid 2 second delay.

**Comment by boliveira** [comment] 2017-05-25 19:50
Have you tried with JS Dev mode disabled? I have no problems when it's disabled. Disable it in dev settings and try it again.

**Comment by streco** [comment] 2017-05-25 20:30
No real difference with dev settings disabled either unfortunately.

**Comment by boliveira** [comment] 2017-05-25 20:40
Strange, I was having the same problem and after I disabled it, everything
flies now. Have you tried a release build?

**Comment by streco** [comment] 2017-05-25 20:47
Yeah, release is better, but still has a slight delay. Doesn't quite field instant like switching tabs, or when using a non-nested StackNavigator

**Comment by streco** [comment] 2017-05-25 21:32
I resolved it. Somehow, by calling the navigate() in a binded method from the onpress, it was creating a delay. When calling navigate directly in the onpress, it's fine. Im my case, this was more of a Javascript issue opposed to a react-navigation one .

With Delay:
`onPress={() => this.onLearnMore('val')}
  
  onLearnMore(record){
     this.props.navigation.navigate('FavoriteItem', record);
   }
`

Without Delay:
`
onPress={() => this.props.navigation.navigate('FavoriteItem', 'test')}
`

**Comment by WillyRamirez** [comment] 2017-06-05 16:40
@streco's fix works for me. 
Im using custom tabbar, which was basically a fork from the default one. I changed JumpToIndex to navigation.navigate and my app works fine again. Still some delay, but i expect that to disappear with a release.

**Comment by WillyRamirez** [comment] 2017-06-13 13:42
@boliveira  your fixed worked for me, turns out Reactotron was causing the delay

**Comment by shirbr510** [comment] 2017-06-14 14:44
@streco 's trick didn't work for me...
both solutions are equal in length and both are very slow.
transitions are extremely slow with the `-2.1` JS frame rate
no nested stacks, one stack to rule them all

**Comment by ganmor** [comment] 2017-06-20 16:08
[Warning ] this is only useful if you are using redux.
We manager to get smooth transitions by doing the following changes 

On every navigation cardstack is calling render on all the mounted scenes
https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L363-L368
```
<View {...handlers} style={styles.container}>
        <View style={styles.scenes}>
          {scenes.map((s: *) => this._renderCard(s))}
        </View>
        {floatingHeader}
      </View>
```

You should wrap you top level components so they do not forward screenprops and navigation if not needed.
because cardstack is adding them automatically
```
  <SceneView
        screenProps={this.props.screenProps}
        navigation={navigation}
        component={SceneComponent}
      />
```
Since navigation is not a plain object, event if you screen is connected with react redux and navigation has not changed it will rerender you component on every navigation.

If you wrap your components like this, you remove props from being forwarded

```
MyScreenWrap1 => <Screen1 />
MyScreenWrap2 => <Screen2 />

StackNavigator(
  Screen1: { screen: MyScreenWrap1 },
 Screen2: { screen: MyScreenWrap2 } 
)}
```
You connect function will thus not be tricked by the navigation props (that is not a plain object) and avoind rerender if nothing has changed.

**Comment by ganmor** [comment] 2017-06-24 08:08
There seems to be a "type: undefined" property that gets added to route object in the navigation state passed to SceneView.
This breaks the default shallow compare.
Also when screenProps is null a new object is created on every rerender, also breaking shallow compare.
We might temporary use custom shouldcomponent update https://github.com/beedeez/react-navigation/commit/684f21a79f49262faaadfe23e7f5cd834dd60dd5

**Comment by elizamaria** [comment] 2017-06-27 10:03
@boliveira it worked for me also. I have to say on my Nexus 5x it worked fine, I didn't have to do the change, only on an older version of Android it was necessary (4.4)

**Comment by dantman** [comment] 2017-07-01 07:11
This performance issue can be a problem when you need to use setParams frequently. eg: When implementing multi-select using state.params because you need to keep a "# items selected" title in the header updated.

**Comment by jordanmkoncz** [comment] 2017-07-05 00:28
I'm having the same issue as @streco and @andreialecu. When my app is running on a real device and running a production build (distributed via TestFlight), and when my app is running in the iOS simulator with Remote JS Debugging disabled, I have this 1-2 second delay before transitioning to a new screen after pressing a button which triggers navigating to that screen. If I enable Remote JS Debugging, the delay completely goes away and the new screen is displayed instantly after pressing the button.

This is happening when I'm on the 'first' / 'default' screen in a StackNavigator, and I'm trying to navigate to another screen in that same StackNavigator (the first screen is a contact list, and the screen I'm navigating to is a contact detail screen that displays the specific contact that the user has clicked on in the contact list). When Remote JS Debugging is enabled, the navigation happens smoothly and instantly, and in the Performance Monitor the UI and JS threads both maintain 60 FPS consistently. But when Remote JS Debugging is disabled, after pressing on a contact in the contact list, the touch is recognised immediately (the `TouchableOpacity` reacts to the touch), but then nothing happens for 1-2 seconds, and then finally the new screen loads in. In the Performance Monitor, the UI thread maintains 60 FPS but the JS thread drops to around 20 FPS in-between pressing on a contact, and the new screen eventually being loaded; once the new screen is loaded the JS thread comes back up to 60 FPS again. If I repeatedly navigate back and forth between the contact list and contact detail screens, the JS thread's FPS spikes up and down between 20-40 FPS.

I have tried @sibelius's solution of disabling all `console` functionality but that doesn't seem to have any effect.

Any ideas what's going on here? Why would this 1-2 second delay be happening, and why does enabling Remote JS Debugging fix this?

**Comment by Jacse** [comment] 2017-07-05 10:05
@jordanmkoncz I imagine enabling remoje js debugging seems to fix it because the JS is run in the browser instead of on the device. In many cases this will mean faster JS execution because the browser has more power. I suppose thats why the issue is less prevalent when enabling debugging.

**Comment by boliveira** [comment] 2017-07-05 10:12
@jordanmkoncz 

It's exactly as @Jacse said. Instead of remote debugging, you can try with JS Dev mode disabled. 
Disable it in dev settings and try it again (or run a production build, it will have the same effect).
This way your javascript code will run faster in your device and you can see if the problem still persists or not.

**Comment by jordanmkoncz** [comment] 2017-07-06 01:13
@Jacse @boliveira I see, I was not aware that enabling Remote JS Debugging caused the JS to be run in the browser instead of the device, but that makes sense.

So is the delay I'm experiencing caused by some performance issue with react-navigation, or a performance issue with the way I'm using react-navigation or with the components that are being navigated to?

The delay still happens when running the app on an iPhone 6 Plus from a production build distributed via TestFlight, so I assume this build of the app itself would be fully optimised (i.e. JS dev mode / dev settings would be disabled)?

The strange thing is that this delay does not happen for other navigation actions in my app, such as navigating between tabs in a TabNavigator. So it's not like react-navigation is just performing poorly in general, it's just in this particular place where there's this very noticeable delay.

**Comment by boliveira** [comment] 2017-07-06 07:50
@jordanmkoncz that is very strange. I have tested on Xiaomi Redmi Note 4 that is far less powerful than the iPhone 6 Plus and it works beautifully. Maybe you are not using a production build? Try running with react-native run-ios and open the react native developer menu, go to Dev Settings, uncheck JS Dev Mode and try again. If it still continues, check if there are any console.log statements, that slows down considerably.

**Comment by amed-kino** [comment] 2017-07-12 08:42
As @jordanmkoncz described, the app that currently working on was build with

`react-native 0.42.3`
`react-navigation 1.0.0-beta.7`

After upgrading both versions to latest, we had the issue were navigating through whole app was very slow. (Navigation which contains Tab and Stack navigation)

The devices that were used to diagnose the issue:
- iPhone6 which was extremely slow
- iPhone7 was ok, but not like the experience before upgrade. (a bit slower)
- Android - multiple devices: was noticeable that the  experience is not like the previous version.
Both versions were build and downloaded through TestFlight and AlphaChannel.

**Comment by amed-kino** [comment] 2017-07-20 09:05
**Suloution**:
The App used [Sentry](https://sentry.io) to track errors, `Stacktrace` was getting effect by the new version. 

https://github.com/getsentry/react-native-sentry/issues/158

**Comment by jordanmkoncz** [comment] 2017-07-21 01:47
Thanks @amed-kino for finding the source of this issue. I was also using Sentry in my app to track errors, and after deactivating the stacktrace merging functionality in Sentry, the issue I was having with the 1-2 second delay before transitioning to a new screen appears to be fixed!

**Comment by listatt** [comment] 2017-07-21 09:27
How to prevent this annoying screens duplicating? When I use navigation.navigate(a) every time rerendering new but old component not deleting

**Comment by dantman** [comment] 2017-07-21 09:33
@listatt navigate adds a new screen to the stack, it doesn't replace screens. For that you need [`NavigationActions.reset`](https://reactnavigation.org/docs/navigators/navigation-actions#Reset).

**Comment by listatt** [comment] 2017-07-21 09:40
@dantman Thanks, but NavigationActions.reset has nasty back animation or?

**Comment by jslz** [comment] 2017-07-21 18:25
(@lisatt I do have that trouble with the reset having an unfortunately animation result. When the reset happens, we see each and every previous page of the stack being animated away. Whereas we want it to just immediately switch to the new route, and not show anything being cleared out.)

**Comment by voidstarfire** [comment] 2017-08-30 13:56
Is this project dead? the original issue was raised Mar 16.

**Comment by caltv** [comment] 2017-09-01 10:26
is there a definitive fix for this? I still see a 2 second delay with a StackNavigator on Android, I've tried turning iff logging etc...seems pointless to use this unless fixed..

**Comment by saeedvaziry** [comment] 2017-09-03 09:48
I have the same problem. no fixes yet?

**Comment by aidan2129** [comment] 2017-09-04 10:31
Still getting -2.1 fps and noticeable delay on release build any solution?

**Comment by koenpunt** [comment] 2017-09-04 10:56
Not sure about all causes of the delays, but I managed to get them far below the 2 seconds people are mentioning here.

One of the causes for us was response parsing; navigating to screen invokes a network request (using React Apollo), and until the response of this request was parsed, the app would hang. This only happened on android btw, iOS had no problem doing this while transitioning to the screen.

**Comment by kelset** [comment] 2017-09-11 19:34
Hi guys, since this issue has been already reported in #608, I’ve taken some time to write a longer response there - please go there to check [my comment](https://github.com/react-community/react-navigation/issues/608#issuecomment-328635042).

I’ll close this issue since it’s a duplicate imho.

**Closed by kelset** 2017-09-11 19:34 UTC
Labels: Type: Enhancement

**Comment by crsunik** [comment] 2018-01-17 12:20
@kelset  Not sure if it is duplicated. In my case transitions are ok, but the scenes have some performance issues. If I navigate from Main Menu to the screen it has 'ok' fps (ui 60 and js 40-50 with debugger in the background), but if I navigate through my whole path consisting of 8 (or in some cases 9 screens) the same screen has ui 30 and js 20 fps. Render methods of the previous screens are not called (I've added console.log as you've mentioned in your comment to check it)

**Comment by DarkSector** [comment] 2018-03-14 22:57
I had a simple Action creator call before I navigated to the next screen in a stack, but it doesn't contain any network calls. I tested by removing the action creator call entirely. But the navigation transition on Android begins after 1-2 seconds. I am using Expo 24 with React-navigation v1.5.2

I am using TouchableOpacity in renderRow method of ListView. It works with significantly less delay on iOS
This is the snippet from my ListView component
```
// SCREEN A
renderRow(thread) {

        if (thread.from_number && thread.last_message_timestamp && thread.to_number) {

            return (
                <View style={{marginBottom: 1}}>
                    <TouchableWithoutFeedback
                        onPressIn={() => {console.log("onPressIn called at ", moment().format("HH:mm:ss:SS"))}}
                        onPressOut={() => {console.log("onPressout called at ", moment().format("HH:mm:ss:SS"))}}
                        onPress={() => {
                            console.log("Button pressed at ", moment().format("HH:mm:ss:SS"));
                            // this.props.setThread(thread);
                            // No network call in here
                            console.log("setThread action called ", moment().format("HH:mm:ss:SS"));
                            this.props.navigation.navigate('conversation', {
                                start: moment(thread.last_message_timestamp).subtract(60, "days"),
                                stop: moment(thread.last_message_timestamp)
                            });
                            console.log("Navigation complete at ", moment().format("HH:mm:ss:SS"));
                        }}
                    >
                        <View>
                            <MessageListItem
                                fromNumber={thread.from_number}
                                timestamp={thread.last_message_timestamp}
                                toNumber={thread.to_number}
                                unread={thread.messages_since_last_checked}
                            />
                        </View>
                    </TouchableWithoutFeedback>

                </View>
            );

        }
        else {
            // return an empty view because it has to return something
            return <View/>
        }
```
The network call exists on Screen B under `componentWillMount()` I tried moving that to `componentDidMount()` as instructed by @kelset in his comment on the other thread, but no change. 

Here is my nested tab/stack navigation

```
// MainNavigator.js
const MainNavigator = TabNavigator(
    {
        // welcome: {screen: WelcomeScreen},
        auth: {screen: LoginScreen},
        mainApp: {screen: InnerAppNavigator}
    },
    OUTER_TABBAR_STYLING
);
```

```
// InnerAppNavigator.js
const InnerAppNavigator = TabNavigator(
    {
        smsThreads: {
            screen: AppNavigator,
            navigationOptions: (props) => {
                // console.log(props);
                return {
                title: "SMS",
                tabBarIcon: <Icon name="activity"/>

            }},
        settings: {
            screen: SettingsScreen,
            navigationOptions: ({navigation}) => {
                // console.log(navigation);
                return {
                title: "SETTINGS",
                tabBarIcon: <Icon style={{color: navigation.activeTintColor}} name="settings"/>
            }}
        },
    },
    OUTER_TABBAR_STYLING
);
```

```
// AppNavigator.js
const AppNavigator = StackNavigator(
    {
        smsThreads: {
            screen: SMSThreadListScreen,
            navigationOptions: ({navigation}) => ({
                tabBarLabel: "SMS"
            })

        },
        conversation: {
            screen: ConversationScreen,
            navigationOptions: ({navigation}) => ({
                tabBarVisible: false,
                tabBarLabel: "SMS"
            })
        },
        newConversation: {
            screen: NewConversationScreen,
            navigationOptions: ({navigation}) => ({
                tabBarVisible: false,
                tabBarLabel: "SMS"
            })
        },

        newConversationPreStart: {
            screen: NewConversationPreStartScreen,
            navigationOptions: ({navigation}) => ({
                tabBarVisible: false,
                tabBarLabel: "SMS"
            })
        },


    },
    STACK_STYLING
);

```

Interestingly, under `AppNavigator.js` navigating from `SMSThreadListScreen` to `NewConversationScreen` works flawlessly and so does going from `NewConversationScreen` to `NewConversationScreen`. It seems this delay only shows up on the screen with the `ListView`.

**Comment by tnguyen-lh** [comment] 2018-03-23 00:51
why is this issue closed, I will experienced the problem with latest version 
"react-navigation": "^1.5.8"
