### ISSUE TITLE
Unable to disable easily the ios statusBar padding in header

### ISSUE THREAD

**Issue by slorber** [react-community/react-navigation#2147] opened 2017-07-14 16:26 UTC
Hi,

Suppose I'm building a StackNavigation, but it's not the top-level app component and it's nested.

I'm fine with defaults of the stack navigation, except the header paddingTop of 20px on iOS

By default the stack navigation will add this padding to all iOS devices, but it only makes sense when the stack navigation is at the top of the screen.

Currently this padding is hardcoded into the Header component. I think it would be great if this padding was customizable from the outside (keeping current behavior as default) without having to duplicate the Header component

It would also be very convenient to have ability to customize this behavior directly on the StackNavigation level in a single boolean property, like `addStatusBarPaddingIOS: false`

If this idea is approved I can submit a PR

**Comment by msageryd** [comment] 2017-09-14 13:13
I agree on this. It seems (to me) that the only way to customise StatusBar on iOS is to put a View under it. But this view will push other views downwards 20px. As react-navigation also adds 20px, I end upp with my navigation header 40px down instead of just the StatusBar height of 20px.

There are quite some issues regarding this. A simple boolean property in the NavigationOptions would solve it for me.

**Comment by vonovak** [comment] 2017-11-04 00:30
@slorber in the original issue you're saying 

>By default the stack navigation will add this padding to all iOS devices, but it only makes sense when the stack navigation is at the top of the screen.

I believe what you wanted to say "By default the stack navigation will add this padding to all iOS devices, but it only makes sense when the StatusBar is at the top of the screen."

There were some major changes done to the padding, so that iphone X support as well as different status bar behaviors (based on orientation) work well. Since the issue is now outdated, I will close it, but please open an issue if you find problems with the latest version.

**Closed by vonovak** 2017-11-04 00:30 UTC
Labels: Type: Feature Request

**Comment by dannycochran** [comment] 2018-02-06 16:55
@vonovak I believe this is still an issue, even in the latest release. (1.0.0-beta.30).

I have an extra padding of 20 pixels at the top of all my navbar headers on iOS. I have the status bar hidden in my app by doing <StatusBar hidden={true} /> at the top level of my app. But even unhiding the status bar, the padding is still there:

With statusbar hidden:

<img width="376" alt="screen shot 2018-02-06 at 8 52 13 am" src="https://user-images.githubusercontent.com/1217178/35872279-443e403c-0b1b-11e8-9638-1148b3128964.png">

With statusbar visible:

<img width="376" alt="screen shot 2018-02-06 at 8 53 23 am" src="https://user-images.githubusercontent.com/1217178/35872297-4d221b24-0b1b-11e8-9ab0-d0179152ee95.png">

I believe this line of code is the culprit:

https://github.com/react-navigation/react-navigation/blob/154aa85f70ef4339cb1751c4797550df20a1cc39/src/views/SafeAreaView.js#L82

**Comment by gusgard** [comment] 2018-02-07 23:55
@dannycochran Thanks!

@vonovak This method `SafeAreaView.setStatusBarHeight` should be in the `docs` 
Should I create a PR to update https://reactnavigation.org/docs/handling-iphonex.html ?

**Comment by vonovak** [comment] 2018-02-08 07:42
@gusgard yes, the iPhoneX documentation for SafeAreaView should be updated, also see https://github.com/react-navigation/react-navigation.github.io/issues/32

if you can come up with a PR that would be appreciated

**Comment by Cadyshack** [comment] 2018-07-05 20:23
Got it working by adding the following

```javascript
navigationOptions: {
  headerForceInset: {top: 'never'},
  ...
}
```

**Comment by kirkol** [comment] 2018-07-27 08:47
navigationOptions:{
        header: null,
}

Works for me ;)

**Comment by slorber** [comment] 2021-06-25 13:15
In case anyone looking for this, in 4.x this worked for me:

```js
    defaultNavigationOptions: {
      safeAreaInsets: {
        top: 0,
      },
    },
```
