### ISSUE TITLE
Use a custom component to render the Header

### ISSUE THREAD

**Issue by Kerumen** [react-community/react-navigation#570] opened 2017-03-04 11:51 UTC
I know it's possible to use a custom React Element for the left, right and title properties.
But is it possible to fully render the Header with a custom element?

I want my header to be a search bar with my logo:

<img width="639" alt="screen shot 2017-03-04 at 12 50 12" src="https://cloud.githubusercontent.com/assets/5436545/23578528/2d6b44e2-00d9-11e7-9726-13896a67038b.png">

**Comment by nihgwu** [comment] 2017-03-04 14:54
There is a rework of header.bar on the way #470

**Comment by ajonno** [comment] 2017-03-09 22:46
I really need this too. Has it been released as yet ?

**Comment by ronal2do** [comment] 2017-03-14 02:50
+1

**Comment by sinxwal** [comment] 2017-03-14 11:35
The best approach for now is to completely disable header.

  static navigationOptions = {
    header: {
      visible: false
    }
  };

And then you can render your own header in the Screen component.

**Comment by ajonno** [comment] 2017-04-07 14:05
setting that navigation option ```header.visible``` false isn't doing anything for me in a simple test app; the nav bar still renders. do you have a more complete example ? more generally just really need #470 rolled out !

**Closed** 2017-04-26 11:34 UTC

**Comment by deepforge** [comment] 2017-07-04 05:39
I'm new to React Native and Navigation, so I just ran into this issue.  I found the workaround by looking at TypeDefinitions.js. Line 226 is:

` header?: ?(React.Element<*> | (HeaderProps => React.Element<*>)),`

... which means the header navigationOption accepts a React component.  So, for example, by defining a version of react-native-material-ui Toolbar and adding the JSX into your StackNavigtor like so:

`const myapp = StackNavigator({
  Home: { screen: Home },
  Calendar: { screen: CalendarView }
}, {
  navigationOptions: {
    header: <ThemeProvider uiTheme={uiTheme}><Toolbar
      leftElement="menu"
      centerElement="Searchable"
      searchable={{
        autoFocus: true,
        placeholder: 'Search',
      }}
    /></ThemeProvider>
  }
});`

You'll override the default header for all screens with whatever element you use.  My actual version in code uses a custom component that ships actions to routers and redux for toolbar elements, but you get the point.

This is a hack, though.  I wish the team would push fixes to NPM.  forcing everyone to accept the git commit mean we have to accept all unstable code (dependent libraries) into production projects, which isn't acceptable.

**Comment by ixje** [comment] 2017-07-08 09:30
@deepforge Note; you don't need to override it for all screens. Instead of putting it in the StackNavigatorConfig you can also only override the header per screen in the [RouteConfig](https://reactnavigation.org/docs/navigators/stack#RouteConfigs) or in the 'static navigationOptions' of the screen itself (note I have not tested the latter, only the former).

**Comment by deepforge** [comment] 2017-07-08 15:19
@ixje I use the common override StackNavigatorConfig because is common to most of my screens, then using the screen-level override where differences apply. That's what makes sense for my app, but I get your point.

The point I would make is that it would be nice to have this noted in the documentation so that new developers don't have to read the source to find a solution for what would most likely be a common need.  The documentation could also convey best practice so developers are assured their solution is a good, supported one.

**Comment by Ajith-Pandian** [comment] 2017-07-18 11:09
@Kerumen You can use navigationOptions to set Custom Header.

```
MyScreen.navigationOptions={
header:(// Your custom header
     <View style={{
            height:80,
           marginTop:20// only for IOS to give StatusBar Space
      }}>
             <Text>This is my HEADER</Text>
     </View>
)}
```

**Comment by dincozdemir** [comment] 2017-07-27 19:05
How do i decide when to render a back button for the custom header in this case? Do i have access to the route stack?

**Comment by Ajith-Pandian** [comment] 2017-07-28 08:02
@dincozdemir If you want to render a back button. You can do like this,

```
MyScreen.navigationOptions = ({ navigation }) => {
  header:    // Your custom header
  <View
    style={{
      flexDirection: "row",
      height: 80,
      marginTop: Platform.OS == "ios" ? 20 : 0 // only for IOS to give StatusBar Space
    }}
  >
    <TouchableOpacity onPress={() => navigation.goBack()}>
      <Text> BACK </Text>
    </TouchableOpacity>
    <Text> My Header </Text>
  </View>;
};
```

**Comment by dincozdemir** [comment] 2017-07-28 09:22
@Ajith-Pandian Thank you for the answer, but i still cant decide whether to **render** the back button or not on that example.

It turns out there is a way; I can pass the **navigation.state.routes** array inside the header props to the header element to let it decide if there are routes on the stack to go back to. If so i render the button.

I still would like to know if there is a more conventional way to achieve this though.

```javascript
MyScreen.navigationOptions = ({ navigation }) => {
  header: props =>    // Your custom header
  <View
    routes={props.navigation.state.routes}
    style={{
      flexDirection: "row",
      height: 80,
      marginTop: Platform.OS == "ios" ? 20 : 0 // only for IOS to give StatusBar Space
    }}
  >
    <TouchableOpacity onPress={() => navigation.goBack()}>
      <Text> BACK </Text>
    </TouchableOpacity>
    <Text> My Header </Text>
  </View>;
};
```

**Comment by Ajith-Pandian** [comment] 2017-07-28 10:46
@dincozdemir  If you wanna decide back button render by routes size, you can simply use **navigation** property.
```
MyScreen.navigationOptions = ({ navigation }) =>{
 // above {navigation} is equal to props.navigation 
  header:  // Your custom header
  <CustomHeader
    renderBackButton={navigation.state.routes.length > 1}
    style={{
      flexDirection: "row",
      height: 80,
      marginTop: Platform.OS == "ios" ? 20 : 0 // only for IOS to give StatusBar Space
    }}
  />
```

**Comment by dincozdemir** [comment] 2017-07-30 18:15
@Ajith-Pandian Totally missed that, thanks! Is there a way to achieve this when i set the **header:null** to use a custom component inside the component instance?

```javascript
class MyScreen extends React.Component {
 static navigationOptions = ({ navigation }) =>{
  header:  null
 }
renderHeader() {
  return (
  <CustomHeader
    renderBackButton={?? > 1}
    style={{
      flexDirection: "row",
      height: 80,
      marginTop: Platform.OS == "ios" ? 20 : 0 // only for IOS to give StatusBar Space
    }}
    />
   )
}
```

**Comment by Tom29** [comment] 2017-08-11 18:50
@Ajith-Pandian How do i use `this` inside `navigationOptions`?
I want to call to component function like this:

```
header: <Navigator showBackButton='1' 
				backButtonPress={() => this.props.screenProps.rootNavigation.goBack(null)} 
				onSearch={(keyword) => this.onSearch(keyword)} 
				onSearchCancel={() => this.onSearchCancel()} 
				searchKeyword={this.state.fetchParams.searchKeyword}
				/>,
```

but it doesn't work. Thank you

**Comment by sebringj** [comment] 2017-08-25 18:44
I am having trouble as well with accessing "this" of the instance using it in the static header as by design it shouldn't allow it. How I **hacked** around it was to use an eventEmitter that is a singleton declared in the scope of the class file as I cannot go "Next" unless some form elements are there.

```
const emitter = require('event-emitter')({});

class myView extends React.Component {
  static navigationOptions = ({ navigation, screenProps }) => ({
    header: (
      <TopBar
        onNext={() => { emitter.emit('next') }}
        />
    )
  })
  handleNext = () => {
    // "this" works as expected
  }
  componentWillMount() {
    emitter.on('next', this.handleNext)
  }
  componentWillUnmount() {
    emitter.off('next', this.handleNext)
  }
}
```
Yes this is a hack but it allows for some nice escapes when you are in a pinch until you figure out the right way.

**Comment by firstplacelabs** [comment] 2017-09-13 02:53
@sebringj You can use navigation params instead of event-emitter
```

class myView extends React.Component {
  static navigationOptions = ({ navigation, screenProps }) => ({
    header: (
      <TopBar
        onNext={() => { navigation.state.params.handleNext() }}
        />
    )
  })
  handleNext = () => {
    // "this" works as expected
  }
  componentWillMount() {
    this.props.navigation.setParams({handleNext: this.handleNext});
  }
}


```

**Comment by faahmad** [comment] 2017-09-20 15:06
When I render a custom header, it renders at the bottom of the screen. Anyone else facing this issue?

My StackNavigator is nested inside a TabNavigator.

**Comment by JayricMok** [comment] 2017-10-04 07:53
@Ajith-Pandian thanks for your anwser, I tried and it worked ! However I use my custom style for those components it cannot found my style. Or it really need to do a inline style ?

**Comment by Ajith-Pandian** [comment] 2017-10-04 07:59
@JayricMok Custom style will work without any problem. Provide some snippet so that I can get a clear idea about your problem.

**Comment by JayricMok** [comment] 2017-10-04 08:03
@Ajith-Pandian 

this is part of my code and I getting this error `Cannot read property 'topcontainer' of undefined`

      const mySimpleApp = StackNavigator({
        Home: { 
          screen: mainNav,
          navigationOptions: {
            header: (
              <View style={styles.topcontainer}>
                <Image 
                  source={{uri:'https://myprofileimage.com/myimgblablabla'}}
                  style={styles.smallpropic}
                />
                <View style={styles.applogocontainer}>
                  <Image 
                  source={require('./resources/logo.png')}
                    style={styles.applogo}
                  />
                </View>
                <Image 
                  source={require('./resources/profileicon.png')}
                  style={styles.profilestyle}
                />
              </View>
            ),
          },
        },
        Chat: { screen: ChatScreen },
      })

    const styles = StyleSheet.create({
      topcontainer:{
        flex: 1,
        flexDirection:'row',
        position:'absolute',
        left:0,
        top:0,
        width:Dimensions.get('window').width,
        height:120,
      },
      smallpropic:{
        resizeMode: Image.resizeMode.cover,
        width:40,
        height:40,
        borderRadius:100,
        position:'absolute',
        left:20,
        top:20,
      },
      applogocontainer:{
        flex: 1,
        justifyContent: 'center', 
        alignItems: 'center',
        position:'absolute',
        left:0,
        right:0,
        top:15,  
      },
      applogo:{
        width:150,
        height:50
      },
      profilestyle:{
        resizeMode: Image.resizeMode.cover,
        width:40,
        height:40,
        borderRadius:100,
        position:'absolute',
        right:20,
        top:20,   
      }
    });

**Comment by Ajith-Pandian** [comment] 2017-10-04 08:48
@JayricMok The problem here is both **StackNavigator** and **styles** are variables. You need to declare a variable before using it. If you are accessing a variable within a function, it can access it. 
The solution for your problem,

1. Move **styles** over StackNavigator
````
const styles = StyleSheet.create({//your implementation})
const SimpleApp = StackNavigator({//your implementation})
````
2. Use a _function_ to create StackNavigator.
````
const SimpleApp = () => {
  let Nav = StackNavigator({//your implementation})
  return <Nav />;
};
const styles = StyleSheet.create({//your implementation})
````

**Comment by JayricMok** [comment] 2017-10-04 08:54
@Ajith-Pandian Thanks ! Solution 1 work like charm !

**Comment by jlf123** [comment] 2017-12-01 20:26
@Ajith-Pandian Thanks for your solution, I would recommend using `paddingTop: 20` rather then marginTop on the header's style so that the status bar can have the same color as the header.

**Comment by Ajith-Pandian** [comment] 2017-12-07 07:45
@jlf123 Thanks for the suggestion. Using `paddingTop:20` would be cool. I would recommend using  `StatusBar` component from 'react-native' to get a clean design. Hence it has many options like backgroundColor, barStyle to customize up to our needs.

**Comment by devanshsadhotra** [comment] 2018-01-11 12:32
@Ajith-Pandian , what if i had to write a function on a button press, how can i access the function written in class?
`MyScreen.navigationOptions = ({ navigation }) => {
  header:    // Your custom header
  <View
    style={{
      flexDirection: "row",
      height: 80,
      marginTop: Platform.OS == "ios" ? 20 : 0 // only for IOS to give StatusBar Space
    }}
  >
    <TouchableOpacity onPress={() => this.performSomething()}>
      <Text> BACK </Text>
    </TouchableOpacity>
    <Text> My Header </Text>
  </View>;
};`

**Comment by Ajith-Pandian** [comment] 2018-01-17 12:13
@devanshsadhotra You can use `withHeaderAndClassProps` from [react-navigation-utils](https://www.npmjs.com/package/react-navigation-utils).

```js
/* add following import at the top */
import {
  withHeaderAndClassProps,
  getNestedObject,
  CLASS_METHODS
} from "react-navigation-utils";

/* add custom header and access class methods via props*/

const MyNewScreen = withHeaderAndClassProps(MyScreen, props => {
  let classMethods = getNestedObject(props, CLASS_METHODS);
  return (
    <View
      style={{
        flexDirection: "row",
        height: 80,
        marginTop: Platform.OS == "ios" ? 20 : 0 // only for IOS to give StatusBar Space
      }}
    >
      <TouchableOpacity
        onPress={() => (classMethods ? classMethods.performSomething() : null)}
      >
        <Text> BACK </Text>
      </TouchableOpacity>
      <Text> My Header </Text>
    </View>
  );
});
````
To use MyScreens's methods(`performSomething` in this example) you should bind them. For more details visit [react-navigation-utils](https://www.npmjs.com/package/react-navigation-utils)

**Comment by devanshsadhotra** [comment] 2018-01-17 13:11
@Ajith-Pandian  , 

Now i am facing an issue , 
 there is a function in my componentWillMount , and response from that function is a certain value which i need to display in header and this is not happening. is there anyway u can suggest?

**Comment by Ajith-Pandian** [comment] 2018-01-17 13:16
@devanshsadhotra Can you provide a code snippet?  So that I can get a better understanding of your problem.

**Comment by devanshsadhotra** [comment] 2018-01-17 13:24
```
static navigationOptions=({naviagtion})=>{
return{
headerLeft:(<View><Text>{global.MembersCount) Members</Text></View>),
headerMode:'Float'
}
}
```
My ComponentWillMount has a API call , which gives me the value of  Global.MembersCount . But that value is not getting reflected in my headerLeft till i tap on it

**Comment by cosmosof** [comment] 2018-01-18 04:35
I was able to insert a logo to title property if that all you need.

<img width="389" alt="screen shot 2018-01-17 at 11 32 56 pm" src="https://user-images.githubusercontent.com/7368238/35080949-ecd9d432-fbde-11e7-95d4-90e7da86a6a0.png">

```
 title: <View style={{ width: 79, height: 22}}>
      <Image source={Images.peerler} style={{width: 79, height: 22}} />
    </View>
```

**Comment by defrian** [comment] 2018-02-26 13:16
Thanks to the discussion in this issue combined with [issue 1886](https://github.com/react-navigation/react-navigation/issues/1886) and [issue 716]( https://github.com/react-navigation/react-navigation/issues/716) I was able to integrate the Toolbar of [react-native-paper](https://github.com/callstack/react-native-paper) and with react-navigation.

As I am quite new to react-native development I am unsure if I might have broken some don`ts. Would like to receive feedback. I am also unsure about the prop-types I have defined. 

Feedback much appreciated.

here is my code:
```
import * as React from 'react';
import { Platform, StatusBar } from 'react-native';
import PropTypes from 'prop-types';
import { StackNavigator } from 'react-navigation';
import { Toolbar, ToolbarContent, ToolbarBackAction } from 'react-native-paper';
import Home from '../screens/Home';
import First from '../screens/First';

const CustomHeader = (props) => {
  const { getScreenDetails, scene, navigation } = props;
  const details = getScreenDetails(scene);

  return (
    <Toolbar dark statusBarHeight={Platform.OS === 'ios' ? 20 : StatusBar.currentHeight}>
      {navigation.state.routes.length > 1 && <ToolbarBackAction onPress={() => navigation.pop()} />}
      <ToolbarContent title={details.options.title} />
    </Toolbar>
  );
};

CustomHeader.propTypes = {
  getScreenDetails: PropTypes.func.isRequired,
  scene: PropTypes.shape({
    isActive: PropTypes.bool,
  }).isRequired,
  navigation: PropTypes.shape({
    state: PropTypes.object,
  }).isRequired,
};

const Stack = StackNavigator(
  {
    Home: {
      screen: Home,
      navigationOptions: () => ({
        title: 'Home Screen',
        header: props => <CustomHeader {...props} />,
      }),
    },
    First: {
      screen: First,
      navigationOptions: () => ({
        title: 'First Screen',
        header: props => <CustomHeader {...props} />,
      }),
    },
  },
  {
    initialRouteName: 'Home',
  },
);

```

**Comment by jilb1992** [comment] 2018-02-28 20:36
@Ajith-Pandian can u help me? I am investigating what it would be the way to archive an header like Tinder, where the icons seems to move with an interpolation in base of the screen content transition between main state, menu (to the left) and chat (to the rigth). Any help would be great!. Tnxs.

**Comment by ravindermahajan890** [comment] 2018-03-05 07:54
@cosmosof  does not work.. try headerTitle instead.

**Comment by brentvatne** [comment] 2018-03-06 00:44
this is covered in docs now: https://reactnavigation.org/docs/headers.html#replacing-the-title-with-a-custom-component

if you run into any problems please create a new issue
