### ISSUE TITLE
StackNavigator[screenb,TabNavigator] screenb reset TabNavigator ,the params get undefined

### ISSUE THREAD

**Issue by Mscynol** [react-community/react-navigation#2989] opened 2017-11-16 12:32 UTC
## 
const resetAction = NavigationActions.reset({

      index: 0,

      actions: [

            NavigationActions.navigate({routeName: 'ScreenA', params: { foo: 'bar' }})

    ]

})
this.props.navigation.dispatch(resetAction);
It can get the value by the way of 'this.props.navigation.state.params.foo'
But ?
if screenA in tab, that is, screenB reset TabNavigator, I cann‘t get the value of the past

so ,I have a look for the solutions  #2073

---

MainStackNavigator
ScreenB
TabNavigator
it does not work for me ScrenB reset TabNavigator by the "The way?"
reset: (props, routeName, paramsValue) => {
console.log(The params--------->${JSON.stringify(paramsValue)});
const resetAction = NavigationActions.reset({
index: 0,
actions: [NavigationActions.init({
routeName: routeName,
params: paramsValue
})]
})
props.navigation.dispatch(resetAction);
}
it‘s wrong

![1510834592489](https://user-images.githubusercontent.com/13941582/32891351-2c7c926c-cb0d-11e7-9737-11c4aba65cce.jpg)
How can I do ?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "^1.0.0-beta.19"
| react-native     | 0.50.2
| node             |
| npm or yarn      |

**Comment by kelset** [comment] 2017-11-17 15:12
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-17 15:12 UTC
