### ISSUE TITLE
Cannot hide header backTitle

### ISSUE THREAD

**Issue by jomaint** [react-community/react-navigation#671] opened 2017-03-13 16:52 UTC
Hi, 
I have been having difficult hiding my backTitle of a few Screens. Anyone else facing this issue or am i doing something wrongly here?

`    static navigationOptions = {
        title: 'title',
        header: {
            backTitle: null,
        }
    };
`

**Comment by ThomsCass** [comment] 2017-03-14 14:42
It's working for me like this :

```javascript
static navigationOptions = {
        header: (navigation, defaultHeader) => ({
          ...defaultHeader,
          visible: true,
          title: 'Liste des proteges',
          backTitle: null,
      })
    }
```

**Comment by MrHubble** [comment] 2017-03-21 23:56
@jomaint I am also experiencing this issue, did you find out the cause?

I tried what @ThomsCass supplied but it did not work for me.

**Comment by navjeetc** [comment] 2017-03-22 01:07
I need to do the same and this solution did not work for me either.

**Comment by navjeetc** [comment] 2017-03-22 01:28
BTW The solution mentioned https://github.com/react-community/react-navigation/issues/689 worked.

**Comment by gie3d** [comment] 2017-03-26 16:21
Let's say you have 2 pages page1 and page2. When you navigate to page2 and about to render the back button, it will look at your previous page navigation option and get backTitle from that. So you may need to add backTitle at the previous page too. 

At Header.js

```javascript
const tintColor = this._getHeaderTintColor(props.navigation);
const previousNavigation = addNavigationHelpers({
  ...props.navigation,
  state: props.scenes[props.scene.index - 1].route,
});
const backButtonTitle = this._getBackButtonTitle(previousNavigation);
```

Sorry, I'm very new to this component, not sure if this is expected?

**Comment by smkhalsa** [comment] 2017-03-31 16:28
I'm experiencing this issue as well. @satya164 @grabbou any ideas? Code and screenshot below.

```
  CollectionDetails: {
    screen: CollectionDetailsContainer,
    path: '/collections/:collectionId',
    navigationOptions: {
      header: ({ state }) => ({
        title: <NavHeaderTitle type="Collection" params={state.params} />,
        right: <CollectionOptionsButton collectionId={state.params.collectionId} />,
        backTitle: 'Back',
      }),
    },
  },
```

![img_1142](https://cloud.githubusercontent.com/assets/6362903/24559619/39a85684-15f4-11e7-9508-e8d9daf03f76.PNG)

**Comment by gie3d** [comment] 2017-04-01 04:47
@smkhalsa have you tried set backTitle in the Practice page? (either 'back' or null) then when you navigate to 'Experience Your Pow...' page, it should use what you set

**Comment by navjeetc** [comment] 2017-04-01 14:53
@smkhalsa the solution I applied was to set left to null, if you do want to show the link on top left. See my comment above.

**Comment by smkhalsa** [comment] 2017-04-03 16:28
@gie3d this doesn't work for me, because there may be a number of pages that can navigate to this page. 

@navjeetc I tried setting left to null, but then it simply shows nothing at all on the left side.

**Comment by amitava82** [comment] 2017-04-05 13:27
Same issue here.

**Comment by DomiR** [comment] 2017-04-05 14:18
It's because the backTitle is fetched from the `previousNavigation`, so set `backTitle: null` on the Route that is pushing.

Source: https://github.com/react-community/react-navigation/blob/7edd9a79aab07a5da969be2d4e254f7524faad03/src/views/Header.js#L156

**Comment by smkhalsa** [comment] 2017-04-05 22:19
This seems like a poor design choice.

**Comment by dpmooney** [comment] 2017-04-12 16:01
As @DomiR said, the _backTitle_ is gotten from the _previousNavigation_.  In my case, I had a StackNavigator with nested StackNavigators and TabNavigators.  The solution was to set _backTitle_ on the originating StackNavigator.  All that remains is a left chevron.

**Comment by spencercarli** [comment] 2017-08-17 19:27
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Closed by spencercarli** 2017-08-17 19:27 UTC

**Comment by rahulnainwal107** [comment] 2020-01-24 10:05
I am also getting this issue [
![Screen Shot 2020-01-24 at 3 17 53 PM](https://user-images.githubusercontent.com/36499090/73061022-3362a580-3ebf-11ea-8d7c-4fd3df858353.png)
](url)

**Comment by GuvanchBayryyyev** [comment] 2020-08-29 09:24
Hi all. I have solved by adding   `headerBackTitleVisible: false`

For example: 
```
<Stack.Screen
          name="SearchReceiptScreen"
          component={SearchReceiptScreen}
          options={{
            title: 'Search receipt',
            headerBackTitleVisible: false
          }}
        />
```
