### ISSUE TITLE
How would I capture on entering a screen event

### ISSUE THREAD

**Issue by JLLLinn** [react-community/react-navigation#1131] opened 2017-04-20 05:03 UTC
Upon entering a screen I need to do something, how would I track this event? Looks like none of componentDidMount or componentDidUpdate or render is called when navigating back.

**Comment by Andreyco** [comment] 2017-04-20 06:54
Given `componentWillMount`, and/or `componentDidMount` won't be called on navigation back event I suppose you are talking about `StackNavigator`, correct?

This is expected behaviour, since component is mounted already, even when navigating back.

Instead, [look here](https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig) at `onTransitionStart` / `onTransitionEnd ` event handlers

**Comment by grabbou** [comment] 2017-04-22 06:20
This is duplicate of #51

**Closed by grabbou** 2017-04-22 06:20 UTC
