### ISSUE TITLE
View controller-based status bar appearance

### ISSUE THREAD

**Issue by PvanHengel** [react-community/react-navigation#2736] opened 2017-10-12 10:43 UTC
Any plans to support the suggested yes mode?

We are trying to use a library that requires see this issue it https://github.com/PSPDFKit/react-native/issues/30 and https://github.com/facebook/react-native/issues/11710

**Comment by kelset** [comment] 2017-10-21 12:09
Hi @PvanHengel! It looks like this is a feature that is not even available in `react-native`, as you posted. Moreover, this library is JS-based, so it doesn't rely on native code.

What is the effect you would like to obtain?

(I'll close this issue since it's not a bug nor a viable feature, but maybe there are other ways to create the same effect so feel free to explain further; tbh probably the best place to talk about this would be in the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question)

**Closed by kelset** 2017-10-21 12:09 UTC
Labels: Status: On Hold
