### ISSUE TITLE
tabBarOnPress inconsistent behavior between iOS and Android

### ISSUE THREAD

**Issue by p-syche** [react-community/react-navigation#3044] opened 2017-11-24 11:55 UTC
I am working on an animated hidden menu, that would open on touching a tab. Based on [this dribble](https://dribbble.com/shots/3208361-Plus-expanded).

My TabNavigator looks like this:
```
const RootNavigation = TabNavigator({
  Home: {
    screen: Home,
     navigationOptions: {
      tabBarLabel: ({focused, tintColor }) => (
        <Text>Home</Text>
      )
    },
  },
  Search: {
    screen: Search,
     navigationOptions: {
      tabBarLabel: ({focused, tintColor }) => (
        <Text>Search</Text>
      )
    },
  },
  PlusTab: {
    screen: PlusTab,
    navigationOptions: {
      tabBarLabel: ({focused, tintColor }) => (
        <PlusContainer />
      ),
      tabBarOnPress: (scene, jumpToIndex) => (
        console.log('the plus tab was touched')
      )
    },
  },
  Faves: {
    screen: Faves,
     navigationOptions: {
      tabBarLabel: ({focused, tintColor }) => (
        <Text>Faves</Text>
      )
    },
  },
  Profile: {
    screen: Profile,
     navigationOptions: {
      tabBarLabel: ({focused, tintColor }) => (
        <Text>Profile</Text>
      )
    },
  },
}, {
  tabBarPosition: 'bottom',
  animationEnabled: false,
  swipeEnabled: false
});
```

The PlusContainer Component looks like so:
```
class PlusTouch extends React.Component {
    render() {
       const { toggleMenu } = this.props;
       return (
        <View style={styles.plusMenuContainer}>
          <TouchableOpacity 
            onPress={toggleMenu}
            style={styles.toucheable}>
              <Text style={styles.plusHorizontal}>|</Text>
          </TouchableOpacity>
        </View>
       )
   }
} 
```

Expected behavior:
- when 'PlusTab' is clicked the PlusTab should NOT open
- label of this tab contains the component with the TouchableOpacity, `onPress` should be triggered

Problems:
 - no easy way to `preventDefault` behavior on tab press -> the console.log inside `tabBarOnPress` is sort of a work around
 - works only on iOS
- on Android -> only functions written explicitly in the `tabBarOnPress` are run, for example if I write an `alert()`, it's triggered correctly. But the TouchableOpacity in the label component is NOT triggered
- when I remove `tabBarOnPress` : 
     - iOS: TouchableOpacity `onPress` is still triggered correctly
     - Android TouchableOpacity `onPress` is not triggered

**Comment by kelset** [comment] 2017-11-24 12:03
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

Moreover, I am confused by why this should be related to `tabBarOnPress` since you say the "wrong behaviour" is experienced also when you remove it.

**Closed by kelset** 2017-11-24 12:03 UTC
