### ISSUE TITLE
header Hidden changes top of ScrollViews to -20 on iOS11 

### ISSUE THREAD

**Issue by chenweigh** [react-community/react-navigation#2992] opened 2017-11-17 10:22 UTC
react native 0.46.4
simulator ios 11
ScrollView top -20:
react-navigation:1.0.0-beta.15
------
please help me! how to fix it?

**Comment by kelset** [comment] 2017-11-17 15:13
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-17 15:13 UTC
