### ISSUE TITLE
Set tabBarVisible to be false in tabNavigator cause navigating crash

### ISSUE THREAD

**Issue by Marswang92** [react-community/react-navigation#1398] opened 2017-05-05 16:54 UTC
### Current Behavior
I've got a screen which has a `navigationOption` as follows:
```
  static navigationOptions = {
    tabBarVisible: false,
    tabBarIcon: ({ tintColor }) => (
      <Icon
        name={ 'camera-iris' }
        color={ tintColor }
        size={60}
        style={{
          marginBottom: 30,
        }}
      />
    )
  };
```
Once I call `this.props.navigation.goBack()` in my screen, the App crash and give following error message. If I change `tabBarVisible` back to true, everything works properly. Anybody can help me with it?

![screen shot 2017-05-05 at 9 55 15 am](https://cloud.githubusercontent.com/assets/14301745/25755743/fc0fae1c-3178-11e7-8268-6e80003818b0.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  react-native
| react             | 16.0.0-alpha.6

**Comment by Marswang92** [comment] 2017-05-05 17:04
Actually just solved by setting `animationEnabled` to be false in `tabBarConfiguration`, but is this behavior expected?

**Comment by matthamil** [comment] 2017-05-05 18:12
Does this still crash when you remove `tabBarIcon`? Taking a guess that it could be a conflict between rendering the tab bar icon and also declaring that no tab bar should be present.

**Comment by acomito** [comment] 2017-05-09 12:34
Is this for android?

**Comment by Marswang92** [comment] 2017-05-09 16:05
@matthamil I haven't tried that yet but yep I think that can be the cause. Will test that out later today.

@acomito It just happened to me on iOS but I'll test it on Android once I've got time.

**Comment by hbar-digital** [comment] 2017-05-10 19:21
I am experiencing the same issue even when removing `tabBarIcon`. This started occurring after upgrading from `1.0.0-beta.6` to `1.0.0-beta.9`.

**Comment by matthamil** [comment] 2017-05-10 19:23
@hbar-digital Can you confirm that this does or does not happen when you remove `tabBarIcon` when you flag `tabBarVisible` as `false`?

**Comment by hbar-digital** [comment] 2017-05-10 19:25
I am getting this error regardless of whether `tabBarIcon` is set. If `tabBarVisible` is set as false, I am unable to navigate (`goBack` or `navigate`).

**Comment by hbar-digital** [comment] 2017-05-10 20:53
Looks like the issue is here:

https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabView.js#L164

Commenting out this line seems to solve the issue. What's the reason for setting `renderPager` to `TabViewPagerPan` when `animationEnabled` and `swipeEnabled` are false?

**Comment by mariotacke** [comment] 2017-06-28 06:10
Related: https://github.com/react-community/react-navigation/issues/1584

**Comment by kelset** [comment] 2017-10-28 14:08
Closing this in favor of #1584 to reduce redundancy.

**Closed by kelset** 2017-10-28 14:08 UTC
Labels: Type: Bug
