### ISSUE TITLE
gesturesEnabled not working 

### ISSUE THREAD

**Issue by JayricMok** [react-community/react-navigation#2922] opened 2017-11-07 10:24 UTC
I would like to dismiss a screen when swiping screen around, I added `gesturesEnabled: false` in `ThreeScreen` , when I swiping still showing the `ThreeScreen`.

    const mainNav = TabNavigator({
      One: { 
        screen: OneScreen,
      },
      Two: {
       screen: TwoScreen,
      },
      Three: {
       screen: ThreeScreen,
       navigationOptions:{
        gesturesEnabled: false,
       }
      },
      Four: {
       screen: FourScreen,
      },
      Five: {
       screen: FiveScreen,
      },
    } );

**Comment by kelset** [comment] 2017-11-07 10:59
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-07 10:59 UTC
