### ISSUE TITLE
Set tabBarVisible to false on android device, cause a blank screen with beta.8

### ISSUE THREAD

**Issue by mdeprezzo** [react-community/react-navigation#1163] opened 2017-04-21 17:49 UTC
Hi guys,
i've read some other issue, about something similar. But, anyway, i'm working on my android device. 
I'm trying to set not visible the tabbar, but when i set tabBarVisible to false, this cause to have a blank screen. 
And i'm using expo to build my app, and expo use sdk 16, and if i would change release of react navigation from beta.8 to beta.7, i cannot, because this case an error during npm install. 
This is my code:

```
export const MainNavigator = TabNavigator({
 welcome: { screen: WelcomeScreen },
 auth: { screen: AuthScreen },
 ...
  }, { 
   tabBarPosition: 'bottom'
  })
 }
}, {
 navigationOptions: {
  tabBarVisible: false
 },
 lazyLoad: true,  
 tabBarPosition: 'bottom',
 tabBarOptions: {
  style: {
   width: SCREEN_WIDTH
  }
 }
});
```

am i missing something ?

**Comment by grabbou** [comment] 2017-04-22 06:01
CC: @satya164

**Comment by acomito** [comment] 2017-04-24 16:30
Same here. The screen works when on android `tabBarVisible: true` (the default). It works on iOS with `tabBarVisible: false`, but on android it will causes a blank screen.

**Comment by acomito** [comment] 2017-04-26 20:17
@mdeprezzo did you ever figure this one out?

**Comment by mdeprezzo** [comment] 2017-04-27 09:38
@acomito I'm still trying to figure out why in beta 8 doesn't works.

**Comment by jsierles** [comment] 2017-04-28 15:30
I still see this on beta 9.

**Comment by Gys** [comment] 2017-05-01 12:14
I also still have this problem with beta 9.

**Comment by mdeprezzo** [comment] 2017-05-01 12:15
Thisis strange. For me works fine. How looks your navigator?

Il 1 mag 2017 14:14, "Gys" <notifications@github.com> ha scritto:

**Comment by Gys** [comment] 2017-05-01 14:02
@mdeprezzo Good question :-)

Below the navigation that I have now.

Problem: The 'Register' screen should have tabBarVisible = false, but then on Android only a blank screen is rendered.

The 'Register' screen is shown from screen 'EventsList' in case no user info is found:
    componentWillMount() {
        // redirect to registration page if no user is known
        if (persistent.data.userID == 0) {
            this.props.navigation.navigate('Register');
            return
        }
    }

I found that if the tabBarVisible setting of the 'EventsList' screen is set to false as well, the 'Register' screen is rendered correctly ! But I want the tabBarVisible = true for that screen.

router.js:
`
export const EventsStack = StackNavigator({
  EventsList: {
    screen: pageEventsList,
    navigationOptions: {
      title: 'Events',
      // tabBarVisible: false, // IF VISIBLE = TRUE THEN SCREEN 'REGISTER' IS SHOWN CORRECTLY
    },
  },
  Register: {
    screen: pageRegister,
    navigationOptions: {
      title: 'Register',
      tabBarVisible: false,
    },
  },
});

export const Tabs = TabNavigator({
  Feed: {
    screen: EventsStack,
    navigationOptions: {
      tabBarLabel: 'Events',
      tabBarIcon: ({ tintColor }) => <Icon name="list" size={35} color={tintColor} />
    },
  },
  Me: {
    screen: pageProfile,
    navigationOptions: {
      tabBarLabel: 'Me',
      tabBarIcon: ({ tintColor }) => <Icon name="account-circle" size={35} color={tintColor} />
    },
  },
});

export const Root = StackNavigator({
  Tabs: {
    screen: Tabs,
  },
}, {
    mode: 'modal',
    headerMode: 'none',
  });
`

**Comment by mdeprezzo** [comment] 2017-05-01 14:22
But, are you trying to set tabbarvisible inside stacknavigator ? I mean, that option may only available for TabNavigator. Or am i missing something ?

**Comment by Gys** [comment] 2017-05-01 14:37
Well it works for me on iOS. But not for Android. So is it a bug or a feature ?!

**Comment by lsps9150414** [comment] 2017-05-02 11:37
Having the problem on Android but not iOS with beta 9 too.
Here's my nav structure:
```
mainTab
|- tab 1
|  |- stack 1
|      |-screen 1
|      |-screen 2 (trying to hide tab bar here)
|- tab 2
```

I set the `tabBarVisible` on `screen 2`'s navigationOptions.

**Comment by jsierles** [comment] 2017-05-02 12:10
This example shows the problem on beta 9 on Android.

https://gist.github.com/jsierles/24a425630a713d329c3013411e4c167f

**Comment by NachtRitter** [comment] 2017-05-03 14:54
@grabbou, will it be fixed in the coming release. This behavior is very necessary for our application. I was very confused by this case during migration from react-native-router-flux

**Comment by satya164** [comment] 2017-05-03 15:46
I can't give a timeline. If you want to investigate why this happens, feel free to check and send a PR if possible.

**Comment by mindk** [comment] 2017-05-04 17:07
@satya164 Fixed in https://github.com/react-native-community/react-native-tab-view/pull/233

**Comment by NachtRitter** [comment] 2017-05-08 13:45
@satya164 , hi again) When are you going to make release of navigation with new fixed version of react-native-tab-view? It's very necessary for our application because testing was stopped while we are waiting for release.

**Comment by satya164** [comment] 2017-05-08 14:32
@NachtRitter you can workaround this in your app with following:

```js
tabBarComponent: props => <View collapsable={false}><TabBarTop {...props} /></View>
```

**Comment by NanIsNotANum** [comment] 2017-05-14 03:42
Hi @satya164, I can confirm the same result from @lsps9150414.

I manually updated my react-native-tab-view with your workaround 
**tabBarComponent: props => <View collapsable={false}><TabBarTop {...props} /></View>**

On Android, the page now renders, however tabbar is still visible.
On iOS, everything works fine!

**Comment by NachtRitter** [comment] 2017-08-28 04:13
@spencercarli , issue isn't reproduced on beta.11, so it could be closed.

**Comment by mstrk** [comment] 2017-09-04 15:01
@NachtRitter it is with `1.0.0-beta.11`

screens only shows with:
```
  tabBarOptions: {
    style: {
      width: SCREEN_WIDTH // any value will work here
    }
  }
```
and the problem comes back with:
```
  navigationOptions: {
    tabBarVisible: false
  }
```

this issue only happens on android tho.

**Comment by kelset** [comment] 2017-09-04 15:58
Hi @mstrk thanks for pointing out that the blank was caused by `alignItems` & `justifyContent` to `center` - it's an issue that happens not only with tabs but in some cases even with other `react-native` components, so be careful when having them ;)

**Closed by kelset** 2017-09-04 15:58 UTC
