### ISSUE TITLE
onLayout transition is not smooth

### ISSUE THREAD

**Issue by itswaze** [react-community/react-navigation#2436] opened 2017-08-21 13:54 UTC
I have a onLayout on a Gallery screen, but when I rotate the screen, when it calls the onLayout it's not smooth at all. Even on a real device it's laggy. Here is a video showing the problem: https://vid.me/hhE3A

I can even see part of other screen when rotating. Is there any other way to make the screen rotate smoothly? I don't really know if it's a problem with the navigation, but since its react-navigation that controls the transitions...

My onLayout is pretty straightforward:

onLayout:
```
  onLayout = event => {
    const { width, height } = Dimensions.get('window')
    this.setState({width, height})
  }
```

then I have onLayout on my container view. And on other views and images, I have a conditional render.

For example:
`height:(height > width) ? 500 : responsiveHeight(80)`

First screen is the only one that renders correctly, the children screens always lag. The deeper the stack, the slower the animation.

EDIT: I noticed that if I create a simple example, with 3-5 screens deep in stack it won't lag. Maybe is the amount of libraries that each screen loads or something?

**Comment by spencercarli** [comment] 2017-08-21 23:12
Are you doing "expensive" operations on previous screens?

> The deeper the stack, the slower the animation.
Previous screens aren't unmounted so if there's logic in them that could be causing issues that could be the culprit.

Event though the example app may not perfectly demonstrate the issue it may still help in giving some tips to you (and anyone else who comes across this issue)

**Comment by itswaze** [comment] 2017-08-22 08:43
Previous screens are mostly making API calls and showing data. And some libraries (maybe that could also be the cause?)

About the example, it will only be helpful if I can somehow show the slow animation.

**Comment by CptFabulouso** [comment] 2017-10-18 12:18
This same behaviour can be seen in the example app in Tabs Example (running on device iPhone 5). Even thought it's almost not noticeable in release mode, it has pretty simple design and with more complicated design it's gonna become noticeable. 
After some research I see the problem is that the render of page is dependent on width of screen obtained from onLayout method (this does react-native-tab-view library). So when screen rotates, everything is rerendered in the old way, then onLayout gets called, new width of screen is obtained and layout is rerendered once again now with the new correct width. So the flicker is unavoidable and is gonna be more noticeable with more complicated layouts. Also more deeper in stack we are, more layouts have to be rerendered and more slow it's all gonna be. 
It's just weird there is no issue on this in react-native-tab-view, but it happens in their example too (if you download it and allow rotation)
It does not happen in Custom Tabs, because it seems to me, that only the current screen is rendered and nothing else around.

**Comment by itswaze** [comment] 2017-10-18 13:23
@CptFabulouso finally someone that noticed it too! It is strange that no one talked about it. I must not be the only one with this issue. And it is really annoying  because my apps have image viewing in landscape. 
And since there is no issues about it, I don't think there will be any fixes soon :(

What do you mean with Custom Tabs?

**Comment by CptFabulouso** [comment] 2017-10-18 13:46
Yes, I find it weird too. I come here from router-flux (which now uses this library) and no one talks about it there neither.
Custom Tabs is name of one page in the example app. Code is 
[here](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js). And [here](https://github.com/react-community/react-navigation/blob/1b761cf9d1a82a62255976080c81612e25bc896f/examples/NavigationPlayground/js/CustomTabs.js#L64-L78) is what gets rendered. It seems to me, that by this approach you loose the ability to swipe between tabs, because only current page gets rendered based on current route.

**Comment by itswaze** [comment] 2017-10-19 11:15
It would be nice to have a solution for this, or at least more people noticing it.

**Comment by CptFabulouso** [comment] 2017-10-19 11:44
I have some idea, I will try to implement it into react-native-tab-view, possibly create the issue there.
I think it should be possible to render the current page normally, translate surrounding pages away with transform using bigger screen dimension as distance (so it is always out of view)  and once user starts scrolling (pan responder will fire), we translate screens right next to the current screen and user does not notice anything. I actually have that prepared, when I was creating my own tab view and it works nicely, just didn't have time to implement other stuff around.

**Comment by itswaze** [comment] 2017-10-19 11:53
When you have that ready I'm willing to give it a try!

**Comment by CptFabulouso** [comment] 2017-10-20 12:12
Ok, I have it ready, it was quite easy to implement. Note that some optimization might be useful, but so far it is working fine in my project. 
I am not sure how to distribute it to you, because I made changes to react-native-tab-view and also react-navigation (so it uses my changes) and I guess implementing it in here officially would take quite a time. I've also not worked with gitHub other way than clone projects, so forking and other stuff around is pretty much unknown to me. Any ideas?
I created new file in react-native-tab-view and did some minor changes to use the file, in any time you can always come back to original solution by changing one line.

**Comment by itswaze** [comment] 2017-10-20 12:23
it was fast ahah
That's pretty much the use I give to GitHub too... But you can share the code here with the changes I need to do. Other than that, you can create a PR on each repository (react-navigation and react-native-tab-view) but that would be more complicated I guess :p

**Comment by CptFabulouso** [comment] 2017-10-20 13:20
Ok, I'll post it here for now.
So in react-native-tab-view/src create file TabViewPagerPanSimple.js with:

```
/* @flow */

import React, { PureComponent, Children } from 'react';
import PropTypes from 'prop-types';
import {
  Animated,
  PanResponder,
  Platform,
  StyleSheet,
  View,
  I18nManager,
  Dimensions
} from 'react-native';
import { SceneRendererPropType } from './TabViewPropTypes';
import type {
  SceneRendererProps,
  Route,
  TransitionConfigurator,
} from './TabViewTypeDefinitions';

type GestureEvent = {
  nativeEvent: {
    changedTouches: Array<*>,
    identifier: number,
    locationX: number,
    locationY: number,
    pageX: number,
    pageY: number,
    target: number,
    timestamp: number,
    touches: Array<*>,
  },
};

type GestureState = {
  stateID: number,
  moveX: number,
  moveY: number,
  x0: number,
  y0: number,
  dx: number,
  dy: number,
  vx: number,
  vy: number,
  numberActiveTouches: number,
};

type GestureHandler = (event: GestureEvent, state: GestureState) => void;

type DefaultProps = {
  configureTransition: TransitionConfigurator,
  swipeDistanceThreshold: number,
  swipeVelocityThreshold: number,
};

type Props<T> = SceneRendererProps<T> & {
  configureTransition: TransitionConfigurator,
  animationEnabled?: boolean,
  swipeEnabled?: boolean,
  swipeDistanceThreshold: number,
  swipeVelocityThreshold: number,
  onSwipeStart?: GestureHandler,
  onSwipeEnd?: GestureHandler,
  children?: React.Element<any>,
};

const DEAD_ZONE = 12;

const DefaultTransitionSpec = {
  timing: Animated.spring,
  tension: 300,
  friction: 35,
};

export default class TabViewPagerPanSimple<T: Route<*>> extends PureComponent<
  DefaultProps,
  Props<T>,
  void
> {
  static propTypes = {
    ...SceneRendererPropType,
    configureTransition: PropTypes.func.isRequired,
    animationEnabled: PropTypes.bool,
    swipeEnabled: PropTypes.bool,
    swipeDistanceThreshold: PropTypes.number.isRequired,
    swipeVelocityThreshold: PropTypes.number.isRequired,
    onSwipeStart: PropTypes.func,
    onSwipeEnd: PropTypes.func,
    children: PropTypes.node,
  };

  static defaultProps = {
    configureTransition: () => DefaultTransitionSpec,
    initialLayout: {
      height: 0,
      width: 0,
    },
    swipeDistanceThreshold: 120,
    swipeVelocityThreshold: 0.25,
  };

  componentWillMount() {
    this._panResponder = PanResponder.create({
      onMoveShouldSetPanResponder: this._canMoveScreen,
      onMoveShouldSetPanResponderCapture: this._canMoveScreen,
      onPanResponderGrant: this._startGesture,
      onPanResponderMove: this._respondToGesture,
      onPanResponderTerminate: this._finishGesture,
      onPanResponderRelease: this._finishGesture,
      onPanResponderTerminationRequest: () => true,
    });
    this.state = {movingHorizontally: false}
  }

  componentDidMount() {
    this._resetListener = this.props.subscribe('reset', this._transitionTo);
  }

  componentDidUpdate(prevProps: Props<T>) {
    if (prevProps.navigationState.index !== this.props.navigationState.index) {
      this._transitionTo(this.props.navigationState.index);
    }
  }

  componentWillUnmount() {
    this._resetListener.remove();
  }

  _panResponder: Object;
  _resetListener: Object;
  _pendingIndex = null;
  _lastValue = null;
  _isMoving = null;
  _startDirection = 0;

  _isIndexInRange = (index: number) => {
    const { routes } = this.props.navigationState;
    return index >= 0 && index <= routes.length - 1;
  };

  _isMovingHorizontally = (evt: GestureEvent, gestureState: GestureState) => {
    return (
      Math.abs(gestureState.dx) > Math.abs(gestureState.dy * 3) &&
      Math.abs(gestureState.vx) > Math.abs(gestureState.vy * 3)
    );
  };

  _isReverseDirection = (gestureState: GestureState) => {
    if (this._startDirection > 0) {
      return gestureState.vx < 0;
    } else {
      return gestureState.vx > 0;
    }
  };

  _getNextIndex = (evt: GestureEvent, gestureState: GestureState) => {
    const currentIndex =
      typeof this._pendingIndex === 'number'
        ? this._pendingIndex
        : this.props.navigationState.index;

    let swipeVelocityThreshold = this.props.swipeVelocityThreshold;

    if (Platform.OS === 'android') {
      // on Android, velocity is way lower due to timestamp being in nanosecond
      // normalize it to have the same velocity on both iOS and Android
      swipeVelocityThreshold /= 1000000;
    }

    if (
      Math.abs(gestureState.dx) > this.props.swipeDistanceThreshold ||
      Math.abs(gestureState.vx) > swipeVelocityThreshold
    ) {
      const nextIndex =
        currentIndex -
        gestureState.dx /
          Math.abs(gestureState.dx) *
          (I18nManager.isRTL ? -1 : 1);
      if (this._isIndexInRange(nextIndex)) {
        return nextIndex;
      }
    }
    return currentIndex;
  };

  _canMoveScreen = (evt: GestureEvent, gestureState: GestureState) => {
    if (this.props.swipeEnabled === false) {
      return false;
    }
    const { navigationState: { routes, index } } = this.props;
    const canMove =
      this._isMovingHorizontally(evt, gestureState) &&
      ((gestureState.dx >= DEAD_ZONE && index >= 0) ||
        (gestureState.dx <= -DEAD_ZONE && index <= routes.length - 1));
    if (canMove) {
      this._startDirection = gestureState.dx;
    }
    return canMove;
  };

  _startGesture = (evt: GestureEvent, gestureState: GestureState) => {
    if (typeof this.props.onSwipeStart === 'function') {
      this.props.onSwipeStart(evt, gestureState);
    }
    this._lastValue = this.props.getLastPosition();
    this.props.position.stopAnimation();
    this.setState({movingHorizontally: true})
  };

  _respondToGesture = (evt: GestureEvent, gestureState: GestureState) => {
    const { layout: { width } } = this.props;
    const currentPosition =
      typeof this._lastValue === 'number'
        ? this._lastValue
        : this.props.navigationState.index;
    const nextPosition =
      currentPosition - gestureState.dx / width * (I18nManager.isRTL ? -1 : 1);
    if (this._isMoving === null) {
      this._isMoving = this._isMovingHorizontally(evt, gestureState);
    }
    if (this._isMoving && this._isIndexInRange(nextPosition)) {
      this.props.position.setValue(nextPosition);
    }
  };

  _finishGesture = (evt: GestureEvent, gestureState: GestureState) => {
    if (typeof this.props.onSwipeEnd === 'function') {
      this.props.onSwipeEnd(evt, gestureState);
    }

    const currentIndex = this.props.navigationState.index;
    const currentValue = this.props.getLastPosition();
    if (currentValue !== currentIndex) {
      if (this._isMoving && !this._isReverseDirection(gestureState)) {
        const nextIndex = this._getNextIndex(evt, gestureState);
        this._transitionTo(nextIndex);
      } else {
        this._transitionTo(currentIndex);
      }
    }
    this._lastValue = null;
    this._isMoving = null;
  };

  _transitionTo = (toValue: number) => {
    const lastPosition = this.props.getLastPosition();
    const currentTransitionProps = {
      progress: lastPosition,
    };
    const nextTransitionProps = {
      progress: toValue,
    };

    this._pendingIndex = toValue;

    if (this.props.animationEnabled !== false) {
      const transitionSpec = this.props.configureTransition(
        currentTransitionProps,
        nextTransitionProps
      );
      const { timing, ...transitionConfig } = transitionSpec;

      timing(this.props.position, {
        ...transitionConfig,
        toValue,
      }).start(({ finished }) => {
        if (finished) {
          this.setState({movingHorizontally: false})
          this.props.jumpToIndex(toValue);
          this._pendingIndex = null;
        }
      });
    } else {
      this.props.position.setValue(toValue);
      this.props.jumpToIndex(toValue);
      this._pendingIndex = null;
    }
  };

  renderPages(){
    const { layout, position, navigationState, children } = this.props;
    const currentIndex = navigationState.index;
    const { routes } = navigationState;
    const { width } = layout;
    const biggerScreenWidth = Math.max(Dimensions.get('window').width, Dimensions.get('window').height);

    const inputRange = [currentIndex-1, currentIndex, currentIndex+1]
    const outputRange = [width, 0, -width] 

    const translateX = position.interpolate({
      inputRange,
      outputRange,
    });

    const screenDistance = this.state.movingHorizontally ? width : biggerScreenWidth

    return Children.map(children, (child, index) => {
      const distance = index - currentIndex;
      let pageStyle;
      if(distance === 0){
        return (
          <Animated.View 
            style = {{
              flex:1, 
              transform: [
                {translateX}
              ]
            }}
            testID={navigationState.routes[index].testID}
            key={navigationState.routes[index].key}
          >
          {child}
          </Animated.View>
        )
      }
      return (
        <Animated.View 
          style = {{
            flex: 1,
            position: "absolute",
            top:0,
            bottom:0,
            left: screenDistance * distance,
            width,
            transform: [
              {translateX}
            ]
          }}
          testID={navigationState.routes[index].testID}
          key={navigationState.routes[index].key}
        >
        {child}
        </Animated.View>
      )
    })
  }

  render() {
    return(
      <View style = {{
        flex:1, 
        }} 
        {...this._panResponder.panHandlers}
      >

        {this.renderPages()}
      </View>
    )
  }
}

const styles = StyleSheet.create({
  sheet: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
});
```

It' almost identical to TabViewPagerPan in the library, I just added state to track if page is in motion and changed the render method (maybe there is already a prop from parent tracking this, there are some prepared callbacks in panResponder methods, but I think parent (TabViewAnimated) does not implement them). Downside to this approach might be the need of rerender on every _startGesture and _finishGesture in panResponder.

Then in index.js export the file by adding 
```
get TabViewPagerPanSimple() {
    return require('./TabViewPagerPanSimple').default;
},
```

then, in react-navigation/src/views/TabView/TabView.js
add TabViewPagerPanSimple and Platform into imports
```
import { View, StyleSheet, Platform } from 'react-native';
import { TabViewAnimated, TabViewPagerPanSimple, TabViewPagerPan } from 'react-native-tab-view';
```

and change _renderPager method (line around 132) to look like this. You can modify this as you want, but because I have not tested this on android (I have different navigation on android) I change the pager just for ios. I also don't know what reason does this library have to change the pager from it's defaults (default is TabViewPagerAndroid for android and TabViewPagerScroll for ios, this can be seen in react-native-tab-view/src/TabViewAnimated.js, on line 50 is switch statement)
```
_renderPager = (props: *) => {
    if(Platform.OS === "ios"){
      return <TabViewPagerPanSimple {...props} />
    }
    return <TabViewPagerPan {...props} />
  }
```

I think that's all I did, I will try to suggest this changes to authors, when I discover how

**Comment by itswaze** [comment] 2017-10-20 14:39
Thank you so much! It's wayyyyy better than before! Haven't tried on Android though, but on iOS it's way better!

I really suggest you make a PR! :)

**Comment by kelset** [comment] 2017-10-20 14:58
Thanks for your solution @CptFabulouso , I am quite sure @satya164 is already working on a huge fix for react-native-tab-view but we'll surely keep your suggestion in consideration :)

**Comment by satya164** [comment] 2017-12-04 11:46
The issue is not actionable for me. If I could skip `onLayout`, there’s no reason I wouldn’t, but I need to know the screen width to properly animate things and determine the current position.

The way you handles rotation changes for the image preview seems weird to me since you could just use flexbox there instead of using `onLayout`.

> It's just weird there is no issue on this in react-native-tab-view, but it happens in their example too

This is a non-issue in react-native-tab-view because most people don’t need to implement `onLayout` for handling orientation changes and flexbox is enough most of the time. And for the time when you need layout information, react-native-tab-view passes the layout information it had obtained through `onLayout` to it’s `renderScene` callback, so you never need to add an extra `onLayout` callback. Which is different with react-navigation since it doesn’t pass layout info to the screens. Many people also don't handle orientation changes at all and lock the orientation to portrait because it can be tricky to handle orientation changes where you need to calculate things

React Native doesn’t do sync layout, things depending on layout info are always delayed until the info is available and sent to JS via the bridge. These cases are tricky to handle, e.g. I do some trickery so that I can make the screen appear before layout info is available, and the delay in layout is invisible to the user. This is unavoidable in some circumstances though, like the tab indicator needs to wait till the layout info is available. This will probably not be much of an issue if `Animated` supported percentages, but it doesn’t.

Regarding your code,

- `const biggerScreenWidth = Math.max(Dimensions.get('window').width, Dimensions.get('window').height);`, by the time this piece of code executes, the layout info should already be available in `this.props.layout`, so you don’t get any new info here. Probably just a side effect of your nested `onLayout` which recursively trigger re-render. You need to reuse `onLayout` info from parent instead of adding it on children to avoid delays.
- Bigger one doesn’t always mean width, and entirely depends on the screen’s aspect ratio and orientation.
- Relying on `Dimensions` makes it a non-generic solution since it’s not guaranteed that the tab view always occupies the window width. e.g. - on tablets you might wanna render it in a smaller viewport.
- Doing `setState` when gesture starts and ends can have a visible performance impact while you’re swiping, especially on Android, even if the screens are not complex.
- You're using `TabViewPagerPan`, which does gestures in JS thread. So it's less smoother than the other pagers.

**Comment by CptFabulouso** [comment] 2017-12-07 11:41
> This is a non-issue in react-native-tab-view because most people don’t need to implement onLayout for handling orientation changes and flexbox is enough most of the time

It doesn't matter what you do in your application. The react-native-tab-view handles orientation changes with onLayout, that's why I wrote the change, to get rid off the dependency on onLayout (well, for the selected page that does matter). In my implementation the visible (selected) page is a regular View with flex:1, there's no width specified.

>Many people also don't handle orientation changes at all and lock the orientation to portrait 

Well, screw those people who do I guess? Seems to me like many people ignore responsive design altogether, like we have one device in portrait and that is all, it drives me enormously insane (had to get it out of me)

> This is unavoidable in some circumstances though, like the tab indicator needs to wait till the layout info is available

can be avoided with some trickery.

Regarding my code:
- layout props from parent could be used, yes. What you mean by "your nested onLayout"? I don't see any onLayout in my code.
- that's why it is surrounded with Math.max? I don't understand.
- value from Dimensions just makes sure the view is always moved out of bigger visible area, so it never appears during rotation before rerender, it doesn't matter if it is edge case (right next to visible screen / window) or even further away. When user starts interacting with the screen, width from props.layout is used to place it right next to visible (selected) screen.
- yeah, I think it could be possible to use Animated API and just apply translation
- feel free to implement this or other solution using scrollView or anything else, I don't know how. It's also pain in the ass to work with scrollView, it's mess.

I think you don't understand what the code does properly (not blaming you), let me add some comments to renderPages method to maybe clear some things out.

```
renderPages() {
    const { layout, position, navigationState, children } = this.props;
    const currentIndex = navigationState.index;
    //current width from parent props
    const { width } = layout; 
    //the biggest width that can ever happen on this device
    const biggerScreenWidth = Math.max(
      Dimensions.get('window').width,
      Dimensions.get('window').height
    );

    const inputRange = [currentIndex - 1, currentIndex, currentIndex + 1];
    const outputRange = [width, 0, -width];

    const translateX = position.interpolate({
      inputRange,
      outputRange,
    });

    /*
      screenDistance value will be used to move surrounding pages, choose whether to use 
      - real width, if we are moving between screens, so they are right next to each other, or 
      - the biggest screen width, if we are not moving between scenes, so in case of device rotation, 
      they do not appear on screen in any situation.
      If we start moving between scenes, setState is called inside _startGesture, 
      and here we move scenes next to each other based on current width. That is reversed in _finishGesture 
    */
    const screenDistance = this.state.movingHorizontally
      ? width
      : biggerScreenWidth;

    return Children.map(children, (child, index) => {
      const distance = index - currentIndex;
      if (distance === 0) {
        //render selected page, use just flex to fill the screen
        return (
          <Animated.View
            style={{
              flex: 1,
              transform: [{ translateX }],
            }}
            testID={navigationState.routes[index].testID}
            key={navigationState.routes[index].key}
          >
            {child}
          </Animated.View>
        );
      }
      return (
        //render other pages, move them away
        <Animated.View
          style={[
            styles.nextPage,
            {
              left: screenDistance * distance, //move scene away
              width,
              transform: [{ translateX }],
            },
          ]}
          testID={navigationState.routes[index].testID}
          key={navigationState.routes[index].key}
        >
          {child}
        </Animated.View>
      );
    });
  }
```

**Comment by satya164** [comment] 2017-12-07 12:06
I don't understand what you mean by "view is always moved out of bigger visible area". Can you post a video/gif?

Anyway, I'm closing this issue because there's nothing actionable here. If you have ideas on addressing the issue in a generic way, open a PR in [react-native-tab-view repo](https://github.com/react-native-community/react-native-tab-view).

**Closed by satya164** 2017-12-07 12:06 UTC
Labels: bug, component: Tabs
