### ISSUE TITLE
_reactNative.Dimensions.addEventListener is not a function

### ISSUE THREAD

**Issue by yusisi** [react-community/react-navigation#2836] opened 2017-10-27 08:51 UTC
## The issue list is reserved for bugs and feature requests, not for questions.

For usage questions, try to:

- [Read the docs](https://reactnavigation.org/)
- [Ask on the Reactiflux (#react-navigation)](https://discord.gg/reactiflux)
- [Look for / ask questions on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior
- _If describing a bug, tell us what happens. Please provide a repository with code and steps to reproduce the bug. **Not providing code that other people can run makes is significantly harder to fix your bug.** Provide a screenshot when possible_
- _If suggesting a change/improvement, explain the difference from current behavior_

### Expected Behavior
- _If you're describing a bug, tell us what should happen_
- _If you're suggesting a change/improvement, tell us how it should work_

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11 && 1.00-beta.15
| react-native     | 0.42.3
| node             |  v6.11.3
| npm or yarn      | npm3.10.10

**Comment by yusisi** [comment] 2017-10-27 08:57
if dismiss the question it cames the problem that navigation in headbar can't go back

**Comment by yusisi** [comment] 2017-10-27 09:13
the problem might comes out from src/view/withOrientation.js handleOrientationChange function

**Comment by kelset** [comment] 2017-10-27 09:29
1. you haven't respected the issue template
1. it's a duplicate of #2824
1. you are running a version of `react-native` which is **7 versions** behind current. (and soon to be 8)
1. you are running an old version of `node`
1. you are running an old version of `npm`

Thanks for pinpointing where the issue comes from, but again, the way to fix is update `react-native`. There's a reason why both `react-native` & this lib haven't reached `stable 1.0` yet and it's because development moves fast.

**Closed by kelset** 2017-10-27 09:29 UTC
