### ISSUE TITLE
Header delay after changing tab on TabNavigator

### ISSUE THREAD

**Issue by agarciaguillo** [react-community/react-navigation#1230] opened 2017-04-25 19:25 UTC
When I Switch between different tabs in TabNavigator, the header takes a while to render.

#### Source code:

```javascript
const Tabs = TabNavigator({
	One: {
		screen: One, navigationOptions: { title: 'One', header: { title: 'First' } }
	},
	Two: {
		screen: Two, navigationOptions: { title: 'Two', header: { title: 'Second' } }
	},
	Three: {
		screen: Three, navigationOptions: { title: 'Three', header: { title: 'Third' } }
	},
	Four: {
		screen: Four, navigationOptions: { title: 'Four', header: { title: 'Fourth' } }
	}
});

const RouterComponent = StackNavigator({
	Tabs: { screen: Tabs },
	OneB: { screen: OneB, navigationOptions: { title: 'OneB' } },
	TwoB: { screen: TwoB, navigationOptions: { title: 'TwoB' } }
});
```

#### And this is how it works:

![navigation](https://cloud.githubusercontent.com/assets/16135348/25403334/511307b2-29fc-11e7-83bb-6c4e66daf075.gif)

#### My Environment:

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.7
| react-native     |  0.42.3
| react             |  15.4.2

What is the reason? Is there any solution?

**Comment by grabbou** [comment] 2017-04-25 19:32
Duplicate of #578 

CC: @satya164

**Closed by grabbou** 2017-04-25 19:32 UTC

**Comment by grabbou** [comment] 2017-04-25 19:52
I believe this is fixed now in recent tabBar update.
