### ISSUE TITLE
StackNavigator on Android is unusable due to performance issues. Alternative?

### ISSUE THREAD

**Issue by caltv** [react-community/react-navigation#2540] opened 2017-09-06 09:44 UTC
IMHO StackNavigator is unusable on Android, there is a 2 second delay when moving between screens. Is there an alternative way of connecting screens on Android using react-navigation?

This issue has been referenced in numerous other places, including [706] (https://github.com/react-community/react-navigation/issues/706) and [608](https://github.com/react-community/react-navigation/issues/608)

**Comment by kelset** [comment] 2017-09-06 13:12
Can you share any code snippets?
I have an app in prod with multiple StackNavigators and I don't have the mentioned issue.

**Comment by caltv** [comment] 2017-09-06 13:15
Sure:

App.js

`const MainApp = StackNavigator({
  App: { screen: App, },
  Home: { screen: HomeScreen, },
  Grade: { screen: GradeScreen, },
  Decks: { screen: DeckSelect },
  Game: { screen: GameScreen },
  Results: { screen: ResultsScreen },
  Definition: { screen: DefinitionScreen },
  Info: { screen: InfoScreen, 
    navigationOptions: {
        header: null,
    }, 
    
  },
  
});`

Example moving screens:
`this.props.navigation.navigate('Grade')`

Sample header in Grade.js

`static navigationOptions = ({ navigation }) => ({
    title: `${navigation.state.params.title}`,
    cirData: `${navigation.state.params.mre}`,
    headerRight: (
      <View >
      <TouchableOpacity onPress={() => navigation.navigate( 'Info' )}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
          <Image
            style={styles.imageForButtonInfo}
            source={require('../img/info.png')}
          />
        </View>
      </TouchableOpacity> 
      </View>
    ),
    headerLeft: (
      <TouchableOpacity onPress={() => navigation.dispatch({ type: 'Navigation/BACK' })}>
        <View style={styles.homeButton}>
          <Image
            source={require('../img/home.png')}
          />
        </View>
      </TouchableOpacity>
    ),
    headerStyle: styles.header,
    headerTitleStyle :styles.headerTXT,
    
  });`

**Comment by kelset** [comment] 2017-09-06 13:37
Ok, I was more concerned about the lifecycle of the component you are going to render, maybe you have a lot of data loading during the `componentDidMount` of the new component?

That said, is the issue present both when `Debug JS` is enabled/disabled? Also when you create the production build?

btw, which version of the lib are you using? Which version of `react-native`?

(protip: you can use "\```js" and " \```"  to wrap your code get better formatting from github, I've edited your comment to make it more readable)

**Comment by caltv** [comment] 2017-09-06 13:44
The issue is the same with Debug JS enabled & disabled, and also in the production build. I don't have much happening in componentDidMount, all my data is local and I'm just drawing some buttons on the screen...The issue is unique to devices only, on the emulator it works fine...

Below is my dependencies

```
  "dependencies": {
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.46.4",
    "react-native-page-control": "^1.0.7",
    "react-native-simple-router": "^0.12.0",
    "react-native-sound": "^0.10.3",
    "react-native-video": "^1.0.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-native-sensors": "^2.3.1"
  }, ```

**Comment by kelset** [comment] 2017-09-06 14:50
Ok thanks for sharing that list.

Probably there's some process "overloading" the JSCore in your app logic; as an example, check [this comment](https://github.com/react-community/react-navigation/issues/706#issuecomment-326933259) from one of the issues you mentioned (and here's [another example](https://github.com/react-community/react-navigation/issues/608#issuecomment-327190221) from the other issue).

I can understand it may be hard to find these bottlenecks, and I'd love to be able to help you more: as a rule of thumb, consider everything that is requiring "native processing" in your app, like query the sensors; the actual bottleneck may be there.

(I won't close this issue right away even if it's technically a duplicate of the other two, I hope you can find the bottleneck and feel free to maybe DM me if you need help into finding the bottleneck)

**Comment by alfonsogoberjr** [comment] 2017-09-07 18:17
Can confirm that StackNavigator becomes unusably slow after a few taps, I am implementing shouldComponentUpdate and disabling console.logs, my views aren't particularly heavy, and on iOS it takes more time to slow down but even there eventually grinds to a halt.

**Comment by tavriaforever** [comment] 2017-09-07 22:39
The same problem, 

1. Every screen it is a container with redux connect() and usually in componentDidMount I fetch date for this screen. 
```
class InfoPostScreen extends Component {
  constructor(props) {
    super(props);
    this.state = {
      imageWidth: width,
      imageHeight: scale(155),
      webViewWidth: width - styleConst.ui.verticalGap,
    };
  }

  static navigationOptions = ({ navigation }) => ({
    headerTitle: 'Об акции',
    headerStyle: styleHeader.common,
    headerTitleStyle: styleHeader.title,
    headerLeft: <HeaderIconBack navigation={navigation} />,
    headerRight: <View />,
  })

...

export default connect(mapStateToProps, mapDispatchToProps)(InfoPostScreen);
```

2. I add shouldComponentUpdate and check props. Didn`t help.

3. Also I tried to use `runAfterInteractions` – didn`t help.
```
componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      const {
        posts,
        navigation,
        fetchInfoPost,
      } = this.props;

      const id = navigation.state.params.id;
      const post = posts[id];

      if (!post) {
        fetchInfoPost(id);
      }
    });
  }
```

I don`t know why it is so slow. And one more thing, the more transitions between screens, the more retards.

**Comment by kelset** [comment] 2017-09-11 19:34
Hi guys, since this issue has been already reported in #608, I’ve taken some time to write a longer response there - please go there to check [my comment](https://github.com/react-community/react-navigation/issues/608#issuecomment-328635042).

I’ll close this issue since it’s a duplicate imho.

**Closed by kelset** 2017-09-11 19:34 UTC
Labels: Type: Bug
