### ISSUE TITLE
navigate does not complain about non existing routes 

### ISSUE THREAD

**Issue by Morriz** [react-community/react-navigation#2513] opened 2017-09-01 16:50 UTC
`navigation.navigate('route_with_typo', ...`

does not complain and does nothing, but I expect it to throw/log an error or warning. Right? This cost me quite some time to figure out :|

**Comment by matthamil** [comment] 2017-09-01 18:05
Duplicate of https://github.com/react-community/react-navigation/issues/1890

**Closed by matthamil** 2017-09-01 18:05 UTC
