### ISSUE TITLE
Navigator not rendered when use screenProps

### ISSUE THREAD

**Issue by capsule5** [react-community/react-navigation#643] opened 2017-03-10 14:21 UTC
```
const MainScreenNavigator = TabNavigator({
  TabA: { screen: TabA },
  TabB: { screen: TabB },
}, TabNavigatorConfig);

export default class Navigation extends Component {
  render() {
    return (
        <MainScreenNavigator screenProps={{foo: 'bar'}}/>
    );
  }
}
```

adding screenProps={{foo: 'bar'}} nothing will be rendered

**Comment by peterorum** [comment] 2017-03-11 11:39
I have the same problem. A warning shows in the console, but no screen renders. 
"Behaviour of screenProps has changed from initial beta. Components will now receive it as `this.props.screenProps` instead.
This warning will be removed in future."

**Comment by peterorum** [comment] 2017-03-11 11:52
Fixed in beta 7.

**Comment by spencercarli** [comment] 2017-08-15 02:21
@capsule5 if the issue isn't fixed please let me know.

**Closed** 2017-08-15 02:20 UTC
