### ISSUE TITLE
How to use transitioner?

### ISSUE THREAD

**Issue by arnsa** [react-community/react-navigation#514] opened 2017-02-28 12:41 UTC
Hello,

documentation for Transitioner is really confusing and I can't wrap my head around on how do I need to use it? I've tried like this, but it throws an error: "Cannot read property 'index' of undefined" in Transitioner.js file.

```
class RouterContainer extends React.Component {
  _render(transitionProps, prevTransitionProps) {
    const scenes = transitionProps.scenes.map(scene => this._renderScene(transitionProps, scene));
    return (
      <View style={styles.stack}>
        {scenes}
      </View>
    );
  }

  _configureTransition(transitionProps, prevTransitionProps) {
    return {
      // duration in milliseconds, default: 250
      duration: 500,
      // An easing function from `Easing`, default: Easing.inOut(Easing.ease)
      easing: Easing.bounce,
    }
  }

  render() {
    return (
      <Transitioner
        configureTransition={this._configureTransition}
        navigation={this.props.router}
        render={this._render}
        onTransitionStart={this.onTransitionStart}
        onTransitionEnd={this.onTransitionEnd}
      />
    );
  }
}

const mapStateToRouterContainerProps = (state) => {
  return {
    router: state.RouterReducer,
  };
};

export default RouterContainer = connect(mapStateToRouterContainerProps, null)(RouterContainer);
```

I suppose it's because this.props.router contains only an index property and routes array? How can I fix that? I only need to remove that "white opacity" on screen transitions :(.

**Comment by arnsa** [comment] 2017-03-01 08:33
Okay, I manage to get rid of almost all the errors, except for this one: "There is no route defined for key router. Must be one of: "Schedule","Speakers","Live","Map","More"". I am not sure why is this happening?

Here's some code:

```
const TabBar = TabNavigator({
  Schedule: { screen: ScheduleTab, path: '/schedule' },
  Speakers: { screen: SpeakersTab, path: '/speakers'},
  Live: { screen: LiveContainer, path: '/live' },
  Map: { screen: MapTab, path: '/map' },
  More: { screen: MoreTab, path: '/more' },
}, {
  tabBarOptions: {
    showIcon: true,
    showLabel: false,
    style: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      backgroundColor: colors.darkGrey,
      shadowColor: colors.black,
      shadowOpacity: 0.8,
      shadowRadius: 2,
      shadowOffset: {
        height: 1,
        width: 0
      },
    },
    indicatorStyle: {
      height: 0,
    }
  },
  tabBarPosition: 'bottom',
  tabBarComponent: TabView.TabBarBottom,
});

export default Routes = StackNavigator({
  router: {
    screen: TabBar,
    path: '/schedule',
    initialRouteName: 'schedule',
  },
}, {
  headerMode: 'none',
});
```

And the render method:

```
render() {
    const navigation = addNavigationHelpers({
      dispatch: this.props.dispatch,
      state: this.props.router
    });
    const Router = createNavigationContainer(createNavigator(Routes)(RouterTransitioner));

    return (<Router navigation={navigation}/>);
  }
```

However if I Routes looks something like this, it seems to be working (even tho I can't see any animations for some reason):

```
const ScheduleTab = StackNavigator({
  Schedule: {
    screen: ScheduleContainer,
    path: '/schedule',
  },
  Talk: {
    screen: TalkContainer,
    path: '/schedule/talk/:id',
  },
  Favorites: {
    screen: FavoritesContainer,
    path: '/schedule/favorites',
  },
  Filters: {
    screen: FiltersDrawer,
    path: '/schedule/filters',
  },
}, {
  headerMode: 'none',
});
```

**Comment by grabbou** [comment] 2017-03-01 10:57
It's duplicate of #250. PRs are welcome :)

**Closed by grabbou** 2017-03-01 10:57 UTC

**Comment by arnsa** [comment] 2017-03-01 11:10
@grabbou are there any other ways to overwrite scene animations besides using Transitioner? I am pretty sure if anyone is willing to update the docs, it's still going to take a few days and I am afraid I don't have that much time.

**Comment by lintonye** [comment] 2017-03-01 15:24
You should pass in a [`navigation`](https://reactnavigation.org/docs/navigators/navigation-prop) object to the Transitioner instead of a `router`.

```jsx
      <Transitioner
        ...
        navigation={this.props.navigation}
      />
```

RE custom animations, check this out: https://github.com/react-community/react-navigation/issues/175

**Comment by arnsa** [comment] 2017-03-09 05:39
@lintonye the problem is that the top-most component doesn't have navigation prop.

**Comment by Jose4gg** [comment] 2017-04-28 15:27
Where I should render the transitioner, the first screen does not have the navigations props, so where I should render it?

**Comment by kumarpatel** [comment] 2017-08-22 14:46
https://github.com/react-community/react-navigation/issues/619#issuecomment-315080300
Add this to your StackNavigator
```
cardStyle: {
        backgroundColor: 'rgba(0,0,0,0.5)',
      }
```
