### ISSUE TITLE
NavigationActions.reset causes error when there are nested StackNavigator

### ISSUE THREAD

**Issue by wjwzwy** [react-community/react-navigation#1123] opened 2017-04-19 21:53 UTC
I tried to reset the state to show a view, which only exists in one StackNavigator, and this call will cause error. 

Is this by design? It seems like a big issue to me.

**Comment by konrad-marzec** [comment] 2017-04-21 11:02
Can you show error message and code?

**Comment by grabbou** [comment] 2017-04-22 06:23
Duplicate of #1127

**Closed by grabbou** 2017-04-22 06:23 UTC
