### ISSUE TITLE
NavigationActions.reset() does not rebuild navigation state correctly

### ISSUE THREAD

**Issue by Thorbenandresen** [react-community/react-navigation#1894] opened 2017-06-16 00:40 UTC
I *think* this is an issue.

This my current navigation structure

```
RootNav -> StackNavigator / mode: 'modal'
  Tabs -> TabNavigator
      Feed -> StackNavigator
        MessageList -> Screen
        ChatRoom -> Screen
      Me -> Screen  
  Compose -> Screen
```

Want to reset from `Compose` to `ChatRoom`, but my NavigationActions.reset() actions do not behave as expected. 

### Version 1 

```js
 headerLeft: (
        <TouchableOpacity
          onPress={() => {
            navigation.dispatch(
              NavigationActions.reset({
                index: 0,
                key: null,
                actions: [
                  NavigationActions.navigate({
                    routeName: "Tabs",
                    action: NavigationActions.navigate({
                      routeName: "MessageList",
                      action: NavigationActions.navigate({
                        routeName: "Details",
                        params: { ...users[0] }
                      })
                    })
                  })
                ]
              })
            );
          }}
        >
          <Text style={{ color: "red" }}>Start Chat1</Text>
        </TouchableOpacity>
      ),
```
This action produces this state: 
```
RootNav -> StackNavigator / mode: 'modal'
  Tabs -> TabNavigator
      Feed -> StackNavigator
        ChatRoom -> Screen
        ChatRoom -> Screen
      Me -> Screen  
  Compose -> Screen
```
**Issue:  ChatRoom is pushed twice**
### Version 2
```js
      headerRight: (
        <TouchableOpacity
          onPress={() => {
            navigation.dispatch(
              NavigationActions.reset({
                index: 0,
                key: null,
                actions: [
                  NavigationActions.navigate({
                    routeName: "Tabs",
                    action: NavigationActions.navigate({
                      routeName: "Details",
                      params: { ...users[0] }
                    })
                  })
                ]
              })
            );
          }}
        >
          <Text style={{ color: "red" }}>Start Chat2</Text>
        </TouchableOpacity>
      )
```
This action produces this state: 
```
RootNav -> StackNavigator / mode: 'modal'
  Tabs -> TabNavigator
      Feed -> StackNavigator
        Details -> Screen
        Details -> Screen
      Me -> Screen  
  Compose -> Screen
```
**Issue: Details Screen is pushed twice**

## Expected Behavior

This action should this state: 

```
RootNav -> StackNavigator / mode: 'modal'
  Tabs -> TabNavigator
      Feed -> StackNavigator
        MessageList -> Screen
        ChatRoom -> Screen
      Me -> Screen  
  Compose -> Screen
```

Is this a legit issue or am I doing something wrong? 

## Your Environment

Here is a [link to the repo](https://github.com/Thorbenandresen/react-navigation-issue) (which is based on [this react-navigation example](https://hackernoon.com/getting-started-with-react-navigation-the-navigation-solution-for-react-native-ea3f4bd786a4))

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.43.3

**Comment by jcaspian** [comment] 2017-06-18 13:47
Have you tried the below?

```jsx
headerRight: (
  <TouchableOpacity
    onPress={() => {
      navigation.dispatch(
        NavigationActions.reset({
          index: 0,
          actions: [
            NavigationActions.navigate({
              routeName: "Details",
              params: { ...users[0] }
            })
          ]
        })
      );
    }}
  >
    <Text style={{ color: "red" }}>Start Chat2</Text>
  </TouchableOpacity>
)
```

I've been using this method to reset my navigation state, with the action straight to the screen I want.

**Comment by ZHT131** [comment] 2017-06-22 08:28
+1

**Comment by ZHT131** [comment] 2017-06-22 08:29
#1620

**Comment by DCKT** [comment] 2017-07-03 15:52
Hey, I got the same issue when I use : 
```javascript
NavigationActions.reset({
  index: 0,
  key: null,
  actions: [NavigationActions.navigate({ routeName: 'deliveries' })]
})
```
The `deliveries` route is pushed **twice**.

```
case ROUTES.DELIVERIES:
  return AppNavigator.router.getStateForAction(
    NavigationActions.reset({
      index: 0,
      key: null,
      actions: [NavigationActions.navigate({ routeName: 'deliveries' })]
    }),
    state
  )
```

Anyone still have an idea ?

**Comment by scarlz** [comment] 2017-07-04 16:05
I am seeing something similar, and it seems to occur due to the initial route on a nested StackNavigator. For example:

```
const bStack = StackNavigator({
  b1: { screen: B1 },
  b2: { screen: B2 }
}, {
  initialRoute: 'b2'
});

const AppNavigator = StackNavigator({
  a1: { screen: A1 },
  b:  { screen: bStack }
}, {
  headerMode: 'none'
});
```
Calling `navigation.navigate('b1')` from within `a1` will push the `b2` route and then the `b1` route. It seems as though the `initialRoute` of the stack is always triggered, so when the route navigated to is the same as the initial route, the result is that the route is pushed twice.

**Comment by DCKT** [comment] 2017-07-06 08:03
Any news about this ?

**Comment by utpal-patel** [comment] 2017-09-12 17:31
Any Updates on this??

**Comment by nonameolsson** [comment] 2017-10-25 22:47
I'm getting this issue also :S

**Comment by kelset** [comment] 2017-11-12 11:20
Pinging OP @Thorbenandresen since this issue has not been active for a while, and it's related to an old version of the lib. Moreover it's sort of a duplicate of https://github.com/react-community/react-navigation/issues/1127

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by Thorbenandresen** [comment] 2017-11-12 19:13
@kelset I am not using react-navigation any longer so I can't tell. Thanks for following up!

**Closed** 2017-11-13 00:04 UTC
Labels: 7 days countdown, bug, related: reset

**Comment by mbret** [comment] 2018-01-13 18:04
Issue still present with latest version ^1.0.0-beta.23

**Comment by mmazzarolo** [comment] 2018-02-07 13:48
I can confirm that the issue is still present on `"react-navigation": "^1.0.0-beta.27"`.  
@scarlz detailed it perfectly in the post above.

**Comment by kelset** [comment] 2018-02-07 13:58
@mmazzarolo @mbret @scarlz can you please test with 1.0 and if still present open a new issue?

**Comment by kot-ezhva** [comment] 2018-02-09 05:02
Hi all. I have some issue. All navigation stack called twice before dispatch. In ver. `"react-navigation": "^1.0.0-beta.21"` and `1.0`
Example:
```
const resetAction = NavigationActions.reset({
            index: 0,
            actions: [
                NavigationActions.navigate({routeName: 'Root'})
            ],
            key: null
        })
        this.props.navigation.dispatch(resetAction)
```
Any solutions?

**Comment by stevenleeg** [comment] 2018-02-26 14:41
I've been facing this issue pretty consistently as well. Any updates here?

**Comment by brentvatne** [comment] 2018-03-07 00:11
can someone please create a new issue with a repro case for this? thanks!

**Comment by huynhtansi** [comment] 2018-03-09 10:29
I created: https://github.com/react-navigation/react-navigation/issues/3697

**Comment by brentvatne** [comment] 2018-03-09 19:19
no direct action can be taken until someone gives a clean and straightforward repro case

**Comment by hanselsen** [comment] 2018-03-12 11:05
It seems I have the same issue. I have this part of my navReducer:  

```
case navActionTypes.SET_ROOT:
	const rootPageAction = DoccNavigator.router.getActionForPathAndParams(data.page);
	const stack = [rootPageAction];
	if(data.param && data.param.path && Screens[data.param.path]) {
		stack.push(DoccNavigator.router.getActionForPathAndParams(data.param.path));
	}

	const resetAction = NavigationActions.reset({
		index: stack.length - 1,
		actions: stack
	}); //this value is as expected
	const newState = DoccNavigator.router.getStateForAction(resetAction); //this value always has the same path (which is my initial path)

	return {
		...state,
		routeName: rootPageAction.routeName,
		param: data.param,
		navState: newState
	};
```

So for example if I want to navigate to set the settings page as my root (and my profile page as active page, so a nav stack of 2) I get a state with only one route and that is path "Login",

**Comment by brentvatne** [comment] 2018-03-13 17:52
locking this issue because it's going nowhere. please create a new issue and *provide a reproducible example that we can run in snack.expo.io or clone and run from a github repo*
