### ISSUE TITLE
Drawer navigator re-render on goBack()

### ISSUE THREAD

**Issue by poptocrack** [react-community/react-navigation#2507] opened 2017-08-31 12:51 UTC
This issue has been reported multiple times but i will try to do it well with the issue template .

I've got two screens in my DrawerNavigator. HomePage screen with a map in it, and ProfilePage with a simple button activating the navigation.goBack() function.

### Current Behavior
On the app startup, the HomePage is displayed. Open the Drawer and select the ProfilePage. Click on the goBack Button. Then the ProfilePage is unmounted and the HomePage is completely remounted. Easely testable with:
```
componentWillMount() {
   console.log("Basic Test");
} 
```

### Expected Behavior
Same steps than above but the HomePage is not completely remounted and the `componentWillMount()` does not display anything.

### Your Environment
Using Expo sdk 20.0.0, Galaxy S7 but the bug is here is every other tested phone.

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11
| Expo     | 20.0.0
| npm      | 5.0.3

**Comment by jjdp** [comment] 2017-09-08 07:27
can reproduce

**Comment by kelset** [comment] 2017-12-10 12:37
Pinging OP @poptocrack since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by poptocrack** [comment] 2017-12-12 10:34
Hi,
I'm using react-navigation ^1.0.0-beta.21, and the problem is still here.

**Comment by kelset** [comment] 2017-12-12 11:31
Actually just realized it's a duplicate of https://github.com/react-community/react-navigation/issues/2277 - gonna close this in favour of that to keep the redundancy low

**Closed by kelset** 2017-12-12 11:31 UTC
Labels: 7 days countdown, bug, component: Drawer
