### ISSUE TITLE
 The react-navigation picture resource may cause a package error？

### ISSUE THREAD

**Issue by liuweiGL** [react-community/react-navigation#1976] opened 2017-06-23 19:59 UTC
```
01:22:43.077 [DEBUG] [org.gradle.api.Project] ERROR: D:\Android\wlApp\android\app\build\intermediates\res\merged\release\drawable-hdpi\node_modules_reactnavigation_src_views_assets_backicon.png uncompiled PNG file passed as argument. Must be compiled first into .flat file.
01:22:43.077 [DEBUG] [org.gradle.api.Project] ERROR:  failed parsing overlays
01:22:43.077 [ERROR] [org.gradle.api.Project] ERROR: D:\Android\wlApp\android\app\build\intermediates\res\merged\release\drawable-hdpi\node_modules_reactnavigation_src_views_assets_backicon.png uncompiled PNG file passed as argument. Must be compiled first into .flat file.
ERROR:  failed parsing overlays

01:22:43.078 [ERROR] [org.gradle.api.Task] Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:803)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:547)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:299)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:74)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:168)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:303)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:295)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:177)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:303)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:295)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:177)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:611)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:566)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.AaptException: AAPT2 link failed:
aapt2 link -I
```

**Comment by tmxdyf** [comment] 2017-07-03 06:04
我也遇见相同的问题...不知如何为解决

**Comment by tmxdyf** [comment] 2017-07-03 06:04
我也遇见相同的问题...不知如何解决

**Comment by n8ebel** [comment] 2017-07-14 18:29
I don't know if `react-navigation` is necessarily the root cause, but I'm seeing this issue as well

**Comment by ssputay** [comment] 2017-08-25 09:27
Getting same error on Android Studio 3.0.
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
>classpath  'com.android.tools.build:gradle:3.0.0-beta3'

**Comment by agrosner** [comment] 2017-08-25 19:51
for now in your top-level gradle.properties file add this line: `android.enableAapt2=false` which essentially uses the old aapt for resources.

**Comment by xMikeTx** [comment] 2017-08-29 15:40
using this workaround leads to:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processProductionReleaseResources'.
.....
.....
Caused by: org.gradle.tooling.BuildException: Failed to execute aapt
```
So at least for me this only shifted the issue

> distributionUrl=https://services.gradle.org/distributions/gradle-4.1-all.zip
> classpath 'com.android.tools.build:gradle:3.0.0-beta3'

**Comment by agrosner** [comment] 2017-08-29 15:42
what is rest of the error. probably something else in your project causing the true error

**Comment by xMikeTx** [comment] 2017-08-29 15:47
Seems like this only happens on production builds, so maybe it has something todo with proguard.
tried already disabeling 
`shrinkResources true`

[crashlog.txt](https://github.com/react-community/react-navigation/files/1260859/crashlog.txt)

**Comment by jeveloper** [comment] 2017-09-19 23:15
Gradle  tool 3.0.0 beta 6 and android.enableAapt2=false  flag in properties now works like a charm

**Comment by kelset** [comment] 2017-10-30 16:04
Quick update: the error is still present with the freshly released Android Studio 3.0, gradle 4.1 & gradle tools 3.0.0 (build tools 26.0.2).

I'm investigating on why it happens, it's clearly related to `node_modules_reactnavigation_src_views_assets_backicon.png`, but the error `uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.` doesn't really say much to me... nor apparently anywhere around the internet: most of the issues/SO answers I found around all declared as solution to "go back" to APPT via `android.enableAapt2=false`.

It's clearly related to AAPT2, the new version present in [gradle tools 3.0](https://developer.android.com/studio/build/gradle-plugin-3-0-0.html) - but even the [migration guide](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#aapt2) doesn't seem to offer an explanation for this kind of error. This [SO answer](https://stackoverflow.com/questions/42082352/how-to-use-aapt2-where-is-the-document) seems to provide some more details but, yeah, until better explanations, please keep using `android.enableAapt2=false`.

**Comment by jcampalo** [comment] 2017-10-31 00:26
I'm having same issue, but `android.enableAapt=false` doesn't work for me, where did you put that? in gradle.properties files?

**Comment by kesha-antonov** [comment] 2017-11-01 12:12
+

**Comment by figgcoder** [comment] 2017-11-07 06:40
We are facing same issues even after setting 
android.enableAapt2=false in gradle.properties. 

Do I need to do something else after setting property to make it work? Appreciate any help.

**Comment by xMikeTx** [comment] 2017-11-07 07:05
@figgcoder Does this happen only in the release build? For me it did.

I think that happens because you added the mentioned resource files in the react project and in the android project.

I solved it by removing all images that are used in the react bundle from the android project. This leads however to that behavior that the resources are not showing in the debug build, but at least the production build works.

**Comment by xMikeTx** [comment] 2017-11-07 07:30
Okay, same here, also my first and last ;) project.
I have a folder structure like

project
  ->node_modules
  ->resources[1]
  -> ...
  ->android -> app -> src -> main -> res -> drawableXXXX [2]

I added my resources to the resources[1] and also in one of the drawable[2] folders which caused my problem. So I removed all duplicate resources from the drawable[2] folders

**Comment by rtman** [comment] 2017-11-09 10:09
I encountered this issue as well, but the `android.enableAapt2=false` in `gradle.properties` has fixed it. Don't really like having to do this, so hopefully a real fix comes through.

**Comment by rochapablo** [comment] 2017-11-14 13:05
What exactly should I do with the ```app/src/main/res/drawable``` folders? delete or just edit each file?

I have add ```android.enableAapt2=false``` but still getting

```
...node_modules_reactnavigation_src_views_assets_backicon.png: error: Duplicate file.
...node_modules_reactnavigation_src_views_assets_backicon.png: Original is here. The version qualifier may be implied.
```

**Comment by sujayjaju** [comment] 2017-11-16 07:16
This is what I discovered:
* Only happens for release builds.
* This issues seems to stem from duplicate assets in the drawable folder: fails with the error "Duplicate file"

To make it work, before running ```gradlew assembleRelease``` delete all images from 
* 'android/app/src/main/res/drawable-mdpi'
* 'android/app/src/main/res/drawable-hdpi'
* 'android/app/src/main/res/drawable-xhdpi'
* android/app/src/main/'res/drawable-xxhdpi' and
* 'android/app/src/main/res/drawable-xxxhdpi'

Or, generate signed APKs using android studio. That works as well for some reason.

**Comment by kelset** [comment] 2017-11-16 08:05
Hi @sujayjaju thanks for your comment - does you app works smoothly without the assets in those folders?

**Comment by sujayjaju** [comment] 2017-11-16 08:11
@kelset Yes, the assets do carry over and the app works smoothly.

**Comment by kelset** [comment] 2017-11-16 08:14
Ok so I guess that we could try removing those assets completely? Will investigate/test.

**Comment by rochapablo** [comment] 2017-11-16 10:20
@sujayjaju, generate signed APKs using android studio was the best alternative until now.

**Comment by soundstage** [comment] 2017-11-20 21:23
Still having this issue. Any ETA for a proper fix instead of workaround?

**Comment by kelset** [comment] 2017-11-21 14:17
> ETA for a proper fix

Currently, I can't understand why this happens in the first place, as I said here https://github.com/react-community/react-navigation/issues/1976#issuecomment-340493501 - so @soundstage if you have any insight please share it.

**Comment by Almouro** [comment] 2017-11-27 12:16
Posted a similar issue on React Native here: https://github.com/facebook/react-native/issues/16906, but no good answer yet.

When Android Studio and Gradle are up to date, requiring images on Android fails.

**Comment by afilp** [comment] 2017-11-28 11:39
I added `android.enableAapt2=false`, but now I get this message (when doing 'assembleRelease') for all packages and fails:

```
  > Could not resolve project :react-native-fetch-blob.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fetch-blob:
```

**Comment by afilp** [comment] 2017-11-28 11:59
Indeed, when I removed the `releaseStaging` buildType, it worked. 

This should not be the right approach though... I understand that when we do `assembleRelease` then it tries to create both `release` and `releaseStaging` apks?

**Comment by PaperMonster** [comment] 2017-11-30 10:08
Adding `android.enableAapt2=false` did solve the problem for me. Thanks a lot!

@afilp I think your problem is a different one. Newer Gradle plugin versions requires all app's build configurations to match dependencies'. Google suggested adding `matchingFallbacks=[<build configs>]` to any custom build configurations that dependencies don't have so they have alternatives to fallback to. Example brought from [docs](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#resolve_matching_errors):
````
// In the app's build.gradle file.
android {
    buildTypes {
        debug {}
        release {}
        staging {
            // Specifies a sorted list of fallback build types that the
            // plugin should try to use when a dependency does not include a
            // "staging" build type. You may specify as many fallbacks as you
            // like, and the plugin selects the first build type that's
            // available in the dependency.
            matchingFallbacks = ['debug', 'qa', 'release']
        }
    }
}
````

**Comment by gengjiawen** [comment] 2017-12-06 09:27
Enable `android.enableAapt2=false` is not a best solution, it will crash your app if you use vector drawable on pre-lollipop devices.

**Comment by Ilario17** [comment] 2017-12-08 11:49
I'm having the same issue and I can't generate signed release apk and this is a BIG issue.

The error is:
```
uncompiled PNG file passed as argument. Must be compiled first into .flat file..
failed parsing overlays
```

relative to:` ../android/app/build/intermediates/res/merged/release/drawable-hdpi/node_modules_reactnavigation_src_views_assets_backicon.png`

setting `android.enableAapt2=false` NOT solve the issue

There is a workaround?? **I have a deadline and I can not create the apk**

**Comment by kelset** [comment] 2017-12-08 12:07
@Ilario17 in the previous comments there are some other "workarounds". Like https://github.com/react-community/react-navigation/issues/1976#issuecomment-344878958

**Comment by Ilario17** [comment] 2017-12-08 12:09
@kelset  I already test the previous workaround and none seem to works

**Comment by gengjiawen** [comment] 2017-12-08 12:16
You need put it to the right location and try to build it using command.

**Comment by Ilario17** [comment] 2017-12-08 12:39
@gengjiawen the file node_modules_reactnavigation_src_views_assets_backicon.png is automatically created during the build.. so I'm not putting it in the wrong position

**Comment by gengjiawen** [comment] 2017-12-08 12:46
I mean the `gradle.properties`, it's in android root project.

**Comment by Ilario17** [comment] 2017-12-08 12:47
@gengjiawen Can you explain how I should edit gradle.properties

**Comment by kelset** [comment] 2017-12-08 12:51
@Ilario17 https://github.com/react-community/react-navigation/issues/1976#issuecomment-325019683

**Comment by Ilario17** [comment] 2017-12-08 12:52
@kelset @gengjiawen ok maybe you are not reading my post well.

**Comment by kelset** [comment] 2017-12-08 13:01
>  ok maybe you are not reading my post well.

What do you mean? Your first comment https://github.com/react-community/react-navigation/issues/1976#issuecomment-350245303 is literally detailing the same error that started this issue and that I re-commented here https://github.com/react-community/react-navigation/issues/1976#issuecomment-340493501

And `android.enableAapt2=false` is the current workaround.
You could not use Gradle Tools 3, since that's what's causing it.

**Comment by Ilario17** [comment] 2017-12-08 13:08
In my first comment I have already said that android.enableAapt2=false does not work for me.

It doesn't works because it generates a lot of other errors. 

This is the only workaround?

**Comment by kelset** [comment] 2017-12-08 13:13
> In my first comment I have already said that android.enableAapt2=false does not work for me.

Reason why me and @gengjiawen tried to help you figure out why it doesn't work for you, by assuming you were writing `android.enableAapt2=false` not in the right place, or not cleaning up the build before trying again.

I suggest you investigate your Android Studio configuration and your gradle file.

**Comment by gengjiawen** [comment] 2017-12-08 13:13
what's the new error?

**Comment by Ilario17** [comment] 2017-12-08 13:22
I'm putting android.enableAapt2=false in the right place. 

the new errors: 

```
../android/app/build/intermediates/res/merged/release/drawable-hdpi/node_modules_reactnavigation_src_views_assets_backicon.png
Error:error: Duplicate file.
Error:java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process /Users/Ilario/Library/Android/sdk/build-tools/26.0.2/aapt with arguments {package -f --no-crunch -I /Users/Ilario/Library/Android/sdk/platforms/android-26/android.jar -M /Users/Ilario/Desktop/proj/android/app/build/intermediates/manifests/full/release/AndroidManifest.xml -S /Users/Ilario/Desktop/proj/android/app/build/intermediates/res/merged/release -m -J /Users/Ilario/Desktop/proj/android/app/build/generated/source/r/release -F /Users/Ilario/Desktop/proj/android/app/build/intermediates/res/release/resources-release.ap_ --custom-package com.mypackage -0 apk --output-text-symbols /Users/Ilario/Desktop/proj/android/app/build/intermediates/symbols/release --no-version-vectors}
Error:com.android.ide.common.process.ProcessException: Error while executing process /Users/Ilario/Library/Android/sdk/build-tools/26.0.2/aapt with arguments {package -f --no-crunch -I /Users/Ilario/Library/Android/sdk/platforms/android-26/android.jar -M /Users/Ilario/Desktop/proj/android/app/build/intermediates/manifests/full/release/AndroidManifest.xml -S /Users/Ilario/Desktop/proj/android/app/build/intermediates/res/merged/release -m -J /Users/Ilario/Desktop/proj/android/app/build/generated/source/r/release -F /Users/Ilario/Desktop/proj/android/app/build/intermediates/res/release/resources-release.ap_ --custom-package com.mypackage -0 apk --output-text-symbols /Users/Ilario/Desktop/proj/android/app/build/intermediates/symbols/release --no-version-vectors}
Error:org.gradle.process.internal.ExecException: Process 'command '/Users/Ilario/Library/Android/sdk/build-tools/26.0.2/aapt'' finished with non-zero exit value 1
Error:Execution failed for task ':app:processReleaseResources'.
> Failed to execute aapt
```

**Comment by kelset** [comment] 2017-12-08 13:29
have you tried to delete the content as proposed here? https://github.com/react-community/react-navigation/issues/1976#issuecomment-344836523

Or to simply go into your node_modules/react-navigation/... folder and remove those image assets?

**Comment by Ilario17** [comment] 2017-12-08 13:33
Yes I tried to remove images from app/src/main/res but every time I build the images are recreated so.. 

removing from node_modules does not create problems with the module itself?

Are the other errors related to Duplicate files?

**Comment by kelset** [comment] 2017-12-08 13:36
Are the other errors related to Duplicate files?

"Error:error: Duplicate file." 2nd line.

> removing from node_modules does not create problems with the module itself?

It depends, I think it's worth a try in your case, since apparently the standard way doesn't work.

If that doesn't work, can you post your build.gradle file? both of them? and the gradle.properties?

**Comment by Ilario17** [comment] 2017-12-09 09:08
@kelset @gengjiawen Ok I re-delete images from app/src/main/res and this time they did not recreate themselves, but I don't know if it depends on the fact that build the project always fails, this time with this error:

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/arch/lifecycle/BuildConfig;
```

I have already looked at all the dependencies of play-services (used only by one module)
All modules have the same compileSdkVersion (26) and the same buildToolsVersion (26.0.2)

This is my dependencies inside my build.gradle:

```
dependencies {
    compile project(':react-native-sensitive-info')
    compile project(':react-native-camera')
    compile project(':react-native-media-meta')
    compile project(':react-native-video')
    compile project(':react-native-vector-icons')
    compile (project(':react-native-push-notification')) {
        exclude group: 'com.google.android.gms:play-services-gcm:10.+'
    }
    compile ('com.google.android.gms:play-services-gcm:10.+') {
        force = true;
    }
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-fbsdk')
    compile project(':react-native-default-preference')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.1.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by gengjiawen** [comment] 2017-12-09 10:10
The crash problem is with fbsdk, not related to this project.

**Comment by Ilario17** [comment] 2017-12-09 10:12
Yes now for sure is not related to this project. I've only update my situation

**Comment by gengjiawen** [comment] 2017-12-09 10:48
The debug problem : you are not config fbsdk right. release problem : you are import some library twice.

**Comment by Ilario17** [comment] 2017-12-09 10:58
I don't know what happening, now I have the old issue. this is really frustrating

**Comment by kelset** [comment] 2017-12-09 13:01
@Ilario17 it really looks like, as I already said, you have your Android configuration misconfigured.

You are using this issue as a chat, which pollutes the overall flow of keeping track of the issue and workarounds.
I highly suggest you move to [Discord's Reactflux](https://www.reactiflux.com/) for your conversation with @gengjiawen and maybe even other people there that may help. I'm going to close this issue and open a new one - so that will be easier for everyone to check for workarounds and us to keep track of the issue without scrolling these many comments.

**Comment by kelset** [comment] 2017-12-09 13:15
Closing in favor of #3097

**Closed by kelset** 2017-12-09 13:15 UTC
Labels: bug, help wanted, needs more info

**Comment by 1c7** [comment] 2017-12-15 08:40
@agrosner solution work for me!
> for now in your top-level gradle.properties file add this line: android.enableAapt2=false which essentially uses the old aapt for resources.

Now I can finally Generating Signed APK for Android.
using React Native 0.51
