### ISSUE TITLE
Route 'Home' should declare a screen

### ISSUE THREAD

**Issue by sbdm05** [react-community/react-navigation#3047] opened 2017-11-24 23:57 UTC
I have an error message: 
Route 'Home should declare a screen. 
I can't see where I got it wrong

Here is the routes component

```
    import React from 'react';
    import {TabNavigator} from 'react-navigation';
    import Deputies_List from '../components/deputies_list';
    import DeputyDetail from '../components/deputy_detail';
    
    
    
    const Tabs = TabNavigator({
      Home:{
        screen: Deputies_List,
      },
    });
    
    
    export default Tabs;
```

It is imported in the App.js like so : 

   ```
 import Tabs from './config/routes';
    import {StackNavigator,TabNavigator
     } from 'react-navigation';

    render() {
        return (
          <View style={styles.container}>
            <Tabs/>
          </View>
        );
      }
```

**Comment by kelset** [comment] 2017-11-25 08:24
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

Moreover, I think that it's your `Deputies_List` component that is not properly defined.

**Closed by kelset** 2017-11-25 08:24 UTC

**Comment by redbar0n** [comment] 2018-03-05 20:41
Yes, you might have messed up your export. Like I did when I got the same error message. Leaving this explanation here for anyone else stumbling upon this question when coming from Google.

In `/components/deputies_list` you might have done (if it was a functional component):

```
// named export
export const Deputies_List = () => (
  // ...
);
```

instead of what you should have done:
```

const Deputies_List = () => (
  // ...
);
// unnamed default export
export default Deputies_List;
```

Default exports only export a value, not a name. The export default `Deputies_List` only refers to the function referenced by it. When you import it in the routes component you designate the default exported value to a variable name, which here coincidentally happened to be the same name: `Deputies_List`.
