### ISSUE TITLE
what is addNavigationHelpers for?

### ISSUE THREAD

**Issue by wangzhe890703** [react-community/react-navigation#615] opened 2017-03-08 14:48 UTC
I tried to follow this example to integrate redux but I consistently get exception: "cannot read property routes of undefined"

https://github.com/react-community/react-navigation/blob/master/docs/guides/Redux-Integration.md

However, I am able to integrate navigation state into redux without applying addNavigationHelpers. At least, I have the navigation state in the redux state tree when I console.log(store.getState()). 

Can anyone tell me what is addNavigationHelpers used for? Is it required or optional?

**Comment by matthamil** [comment] 2017-03-08 15:44
Can you post your code?

**Comment by grabbou** [comment] 2017-03-08 20:17
It is required. As you can see from the source code, it is used to add necessary `navigation helpers`, like `navigate` etc. Thanks to that, you, as user, only have to supply `dispatch` and `store` function. That makes it easy to replace built-in state management with e.g Redux.

Your issue looks different to me (and I am pretty sure I've seen these errors already).

**Comment by grabbou** [comment] 2017-03-08 20:17
Duplicate of #485

**Closed by grabbou** 2017-03-08 20:17 UTC
