### ISSUE TITLE
Back button is always "Back" if screen title is long enough

### ISSUE THREAD

**Issue by Tiendq** [react-community/react-navigation#1702] opened 2017-05-27 07:34 UTC
### Current Behavior
1. First screen's title: `First`
2. Second screen's title: `Long Enough Title`
- Second screen's back button is `Back` on iPhone 5 (320px width)
- Second screen's back button is `First` (correct) on iPhone 6 (375px width)

### Expected Behavior
Second screen's back button is always`First` on all devices.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.9 
| react-native     |  0.44

**Comment by vonovak** [comment] 2017-06-05 11:13
this is not a bug but a feature

**Comment by Tiendq** [comment] 2017-06-06 00:46
Inconsistent feature?

**Comment by vonovak** [comment] 2017-11-03 23:34
I am going to close this, because like I said, I believe this is a feature - if there is enough space, the previous' screen title is rendered. If not, 'back' is rendered. Also, there is a config option for this https://reactnavigation.org/docs/navigators/stack#Screen-Navigation-Options

**Closed by vonovak** 2017-11-03 23:34 UTC
Labels: Type: Feature Request

**Comment by SamiChab** [comment] 2018-01-08 15:18
Works with the `headerBackTitle` option (if not too long as well)
