### ISSUE TITLE
HOW TO: pass params from parent to child screens StackNavigator ?

### ISSUE THREAD

**Issue by veljkomatic** [react-community/react-navigation#1684] opened 2017-05-25 13:11 UTC
I navigate to ADD screen ( ADD :  StackNavigator({ with screens}) )  with  params, how  can I pass that params to screens inside ADD .. if I  navigate to screen inside ADD  with params, that screen is open twice dont know why ? and yes params are dynamically.. so I cant use initialRouteParams 
Thanks a lot

**Comment by faceyspacey** [comment] 2017-05-25 18:45
I can't quite figure out exactly what you're asking, but I can guess: 

- you have a nested navigator within another nested navigator
- you are setting params on the parent navigator, but you want the child navigator to receive them
- if you navigate a 2nd time within the nested navigator, the screen is opened twice (which is basically the expected behavior by the way--although I have a PR https://github.com/react-community/react-navigation/pull/1515 that should prevent that if the screen is duplicate [i.e. has the same routeName + params])

...Basically the solution may be as simple as dispatch/navigate just to the "screens inside ADD". For example if you have this:

```js
TabNavigator({
    ADD: StackNavigator({
         FOO: { screen: FooScreen }
    }, options)
}, options)
```

Then what you want to do is the following from **ANYWHERE** in your navigator component tree:

```js
navigation.navigate('FOO', { bar: 'baz })
```

or:

```js
dispatch(NavigationActions.navigate({ routeName: 'FOO', params: { bar: 'baz } })
```

**Comment by kirakik** [comment] 2017-06-06 22:57
@faceyspacey your solution doesn't seem to work for me, my params are not being passed to my nested screens. This is my structure:

``` js
MAIN: {
    screen: TabNavigator({
        PROFILE: { 
            screen: StackNavigator({
                FOO: { screen: FooScreen },
                BAR: { screen: BarScreen }
            }, options)
        }
    )}
}
```

`FOO` is expecting an object called `user` to be passed to it. Whether I call `navigation.navigate('FOO', { user: user }` or `navigation.navigate('PROFILE', { user: user }`, I am still getting an error saying that `user` is undefined

**Comment by faceyspacey** [comment] 2017-06-07 00:10
That's exactly how it's supposed to work. I don't know what to tell you. Run the examples in this repo, and use one of the examples nested in the same way. This whole system is made to allow you to dispatch to recursively through nested navigators to the deepest child that matches. 

Why are you getting an error? Before the error occurs, try logging the params. Log the entire `navigation` object. Put logging everywhere until you find the problem. 

...also keep in mind ur nested navigators must be nested with nothing in between. It must look like what u posted above. U can't break the chain by wrapping `StackNavigator` in another component. `PROFILE.screen` must equal `StackNavigator`, which itself has its router at: `StackNavigator.router`. ...I'm also not sure what `MAIN` is in your example. 

Another thing to try: use Redux + the Redux Devtools and looks closely at the actions dispatched and the derived state. The clues are there if u have tools helping u with the observability of what's really going on.

**Comment by KyleKhalaf** [comment] 2017-07-07 19:05
sorry but how do you manage to access a screen in the child navigator, from a screen in the parent navigator?

For example, if I want to access `FooScreen` from some other screen in `PROFILE`

**Comment by JakeCoxon** [comment] 2017-08-22 19:23
This doesn't seem to work correctly for me.

If you have a situation like this

```
StackNavigator({
  FOO: { screen: BarScreen },
  BAR: StackNavigator({
      BAZ: { screen: BazScreen }
  })
})

```

If I'm looking at FOO screen (state is [FOO]) and then call `navigation.navigate('BAZ', { user: user });` then I end up with two BAZ screens in the stack (state is [FOO, BAR [BAZ BAZ]]). I just want [FOO, BAR [BAZ]] but it seems that the BAR stack is initializing and also navigating to BAZ

Am I doing something wrong?

**Comment by spencercarli** [comment] 2017-08-28 01:31
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:31 UTC
Labels: Type: Question

**Comment by adkl** [comment] 2017-09-14 14:40
The same problem here.

**Comment by scue** [comment] 2017-10-24 03:53
+1

**Comment by zLoneWolf** [comment] 2018-03-07 06:09
+1 The same problem here

**Comment by zLoneWolf** [comment] 2018-03-07 06:42
Okay everyone, after a while I have finally found a hack around this, just add a check inside navigationOptions, something like this: 
Medical: {
            screen: Medical_Record_Screen,
            navigationOptions: ({navigation}) => {
                **if(navigation.state.params) {**
                    console.log(navigation)
                    return {
                        title: navigation.state.params.title,
                        headerLeft: <Drawer_Button nav={navigation} />
                    }
                }
               return {}
            }
        },

The reason is the react-navigation always has the main routes with an id, when passing a param, the packages doesn't override the main routes but add another routes with the same routeNames but diffrent id.

**Comment by hlbp** [comment] 2018-03-28 17:48
@zLoneWolf  do you know how can i pass params through react-navigation with redux? i mean
in my reducer i have

 case LOGGED_IN:     
       nextState = AppNavigator.router.getStateForAction(
         NavigationActions.navigate({ routeName: 'MainAppView', params: {'myParam': 'Helmer'} }),
         state,
    );
then i could extract props in the view im passing the params with this line of code
const { params } = this.props.navigation.state;
but the params are not been passed. do you have any idea? thanks!

**Comment by nanopowered** [comment] 2020-01-17 15:12
You could reach the parent's params from the child using this :
`this.props.navigation.dangerouslyGetParent().getParam('toto');`
