### ISSUE TITLE
after exp detach, react-navigation initial route has been constructed twice

### ISSUE THREAD

**Issue by xiaocjin** [react-community/react-navigation#3166] opened 2017-12-21 05:41 UTC
i am using the latest react-navigation&expo, running app on an ios simulator. before exp detach, everything is fine.

**Comment by justinobney** [comment] 2017-12-21 18:28
see #2599 and #2904

**Comment by kelset** [comment] 2017-12-22 16:55
Duplicate of https://github.com/react-community/react-navigation/issues/2599

**Closed by kelset** 2017-12-22 16:55 UTC
