### ISSUE TITLE
ios bottom tabBar icons now showing 

### ISSUE THREAD

**Issue by ezha86** [react-community/react-navigation#2900] opened 2017-11-04 13:41 UTC
i have upgraded react-navigation from 1.0.0-beta.13 to 1.0.0-beta.19 and my bottom tab icons disappeared (iphone X modulator and iphone 6 modulator - ios 11.0)
btw android works fine
if i move back to react-navigation from 1.0.0-beta.13 - icons show up

[gist with my tabs config](https://gist.github.com/ezha86/190f69b8f0243de3f4cd6df9ddad6d00)

  

any thoughts ? 
Thanks 

adit: the problem is cuz TabBarIcon has lost all styles

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.19
| react-native     |0.44.2
| node             |8.1.4
| npm or yarn      |

**Comment by kelset** [comment] 2017-11-04 14:43
Closing because you haven't respected the issue template. Moreover, I think it's a duplicate of https://github.com/react-community/react-navigation/issues/2805

**Closed by kelset** 2017-11-04 14:43 UTC
