### ISSUE TITLE
undefined is not an object (evaluating '_this2.props.navigation')

### ISSUE THREAD

**Issue by TestTitans** [react-community/react-navigation#1022] opened 2017-04-13 13:04 UTC
Every navigation.navigate function generate this warning. 
all warnig is:
Posible unhanded Promise Rejection (id:0):undefined is not an object (evaluating '_this2.props.navigation')

**Comment by grabbou** [comment] 2017-04-13 14:29
Can you turn on `uncaught exceptions` in Chrome Debugger and tell where exactly it throws?

**Comment by biancanalien** [comment] 2017-04-21 20:57
I'm with this same error, did you resolve it?

**Comment by grabbou** [comment] 2017-04-24 09:52
Can anyone include a reproduction here?

**Comment by AlanFoster** [comment] 2017-04-24 20:25
@grabbou Been playing around, and I've gotten a full stack trace:

```
undefined is not an object (evaluating '_props[registrationName]')
getListener    EventPluginHub.js:150:23
listenerAtPhase    EventPropagators.js:32:21
accumulateDirectionalDispatches    EventPropagators.js:48:33
traverseTwoPhase    ReactTreeTraversal.js:105:7
accumulateTwoPhaseDispatchesSingle    EventPropagators.js:66:6
forEachAccumulated    forEachAccumulated.js:32:12
accumulateTwoPhaseDispatches    EventPropagators.js:119:21
setResponderAndExtractTransfer    ResponderEventPlugin.js:352:50
extractEvents    ResponderEventPlugin.js:504:8
extractEvents    EventPluginHub.js:184:10
handleTopLevel    ReactEventEmitterMixin.js:33:6
<unknown>    ReactNativeEventEmitter.js:113:8
fiberBatchedUpdates    ReactGenericBatching.js:27:12
performFiberBatchedUpdates    ReactGenericBatching.js:33:29
perform    Transaction.js:149:24
batchedUpdates    ReactDefaultBatchingStrategy.js:65:33
batchedUpdates    ReactUpdates.js:96:41
batchedUpdates    ReactGenericBatching.js:38:29
batchedUpdatesWithControlledComponents    ReactGenericBatching.js:51:26
_receiveRootNodeIDEvent    ReactNativeEventEmitter.js:111:40
receiveTouches    ReactNativeEventEmitter.js:200:8
__callFunction    MessageQueue.js:244:47
<unknown>    MessageQueue.js:108:26
guard    MessageQueue.js:46:4
callFunctionReturnFlushedQueue    MessageQueue.js:107:10
```

I have a ScrollView within a StackNavigator. I can trigger the exception by scrolling randomly up and down. My content is less than the size of the scroll view - but I'm not sure if that's related. I'd be tempted to say it's a react/fiber issue, but I can poke further if it's not immediately obvious what the problem is @grabbou

**Comment by grabbou** [comment] 2017-04-26 06:01
Closing as there's no reproduction. Please search existing issues before re-opening. If you are using `Redux`, make sure your state is connected and you pass navigation prop correctly.

**Closed by grabbou** 2017-04-26 06:01 UTC

**Comment by priyesh-jft** [comment] 2017-05-23 07:09
Getting same error

**Comment by AlanFoster** [comment] 2017-05-23 08:19
@pronevich hey, could you post the full stack trace, reproduction code, version numbers, Screenshot, etc. This will help us understand more about the issue to resolve it.

**Comment by GuyZwer** [comment] 2017-09-26 18:11
Hi, I had the same error, I found that the error occur only if I navigate from page that already navigated.
In my case I have in index.android.js the following setting:
```

import React, { Component } from 'react';
import { AppRegistry, View, Image, StyleSheet, Text, Button, TouchableOpacity } from 'react-native';
import { StackNavigator } from 'react-navigation';

import ComponentBookSelector from './app/components/ComponentBookSelector';

export default class ComponentLevels extends Component {
  render() {
    return (
      <TouchableOpacity onPress={() => **this.props.navigation.navigate**('BookSelector')}>
        <View style={styles.button}>
        <Text style={styles.buttonText}>BookSelector</Text>
        </View>
      </TouchableOpacity>

const NachRiddles = StackNavigator({
  BookSelector: { screen: BookSelectorScreen },
},
  { headerMode: 'screen' }
);
```

on BookSelector component I have another navigator and that I had to face with the '_this2.props.navigation' error

```
            <TouchableOpacity onPress={() => **this.props.navigation.navigate**('Riddles')}>
              <View style={styles.container2}>
                 <Image
                   style={styles.backdrop}
                   source={require("../img/open-book2.png")}>
                     <View style={styles.backdropView}>
                       <Text style={styles.headline}>Riddles</Text>
                     </View>
                 </Image>
               </View>
            </TouchableOpacity>
```

As you can see I'm trying to navigate from navigated page
I have no Idea how to workaround this issue

**Comment by sntnmjones** [comment] 2018-03-31 03:05
[https://monsieurbricole.wordpress.com/2017/12/27/undefined-is-not-an-object-evaluating-_this2-props-navigation-navigate/](url)

**Comment by mikeumus** [comment] 2018-05-16 20:28
@sntnmjones, your link is down ^

**Comment by lylest** [comment] 2019-08-09 14:01
someone post  a really solution please

**Comment by sntnmjones** [comment] 2019-08-09 14:12
[try this](https://monsieurbricole.wordpress.com/2017/12/27/undefined-is-not-an-object-evaluating-_this2-props-navigation-navigate/)
