### ISSUE TITLE
Nested navigation: DrawerNavigation inside StackNavigation

### ISSUE THREAD

**Issue by shivrajkumar** [react-community/react-navigation#2071] opened 2017-07-05 13:42 UTC
I have this model.
-StackNavigator
       --LoginScreen
      --DrawerNavigator
          ---HomeScreen - initialScreen
          ---OthersScreens
From drawer i navigate to othersScreens.
I have an option to logout from DrawerScreen i.e, navigate back to LoginScreen.
How do i achieve this

**Comment by Andreyco** [comment] 2017-07-06 06:55
I would split navigation into two separate routers/screens

1. LoginScreen
1. DrawerNavigator
    1. Homescreen
    1. Screen2 (might be StackNavigator)
    1. Screen3 (might be StackNavigator)
    1. ...

Render either `LoginScreen` or root `DrawerNavigator` conditionally, based on whether user is authenticated or not.

**Comment by shivrajkumar** [comment] 2017-07-06 07:06
Yes, but how do i navigate back to LoginScreen after i am in DrawerNavigation.
navigation of LoginScreen is lost to me once i get into DrawerNavigation.

**Comment by shivrajkumar** [comment] 2017-07-06 07:09
What i have is, Login screen, from where i navigate to HomeScreen. There i have a Button to open drawer menu. From drawer menu, i want option to navigate to other Screens, say Screen1, Screen2 and also go back option to LoginScreen.

**Comment by Andreyco** [comment] 2017-07-06 07:20
To show login screen, I expect user is not authenticated. User should log out to see login screen.

**Comment by shivrajkumar** [comment] 2017-07-06 07:25
Yes, But how do get the navigation props of both StackNavigation and DrawerNavigation in Drawer side Menu

**Comment by shivrajkumar** [comment] 2017-07-06 07:26
@Andreyco Here's the code repo https://github.com/GeekyAnts/native-base-boilerplate

**Comment by Rebaiahmed** [comment] 2017-07-06 08:54
Hi @shivrajkumar  i want to make SideBar that contain the Login Screen and the Home Screen , my initial route is not the Login Component , what i should do :/ ?

**Comment by jainniket** [comment] 2017-07-07 10:07
@shivrajkumar use `this.props.navigation.navigate('<LoginScreen routename>');`

**Comment by jainniket** [comment] 2017-07-07 10:08
@Rebaiahmed can you explain your problem in detail along with some code snippet

**Comment by spencercarli** [comment] 2017-08-29 02:22
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-29 02:22 UTC
Labels: Type: Question

**Comment by sfm2222** [comment] 2017-12-21 13:59
I have sort of similar issue, can anyone provide a clean solution to resolve this =( I want to show back button on top on iOS and on android navigate to last screen using hardware back button.

Drawer Navigator

/* @flow */

import React from "react";
import { DrawerNavigator } from "react-navigation";

import Home from "./components/home/";
import SplashPage from "./components/splashscreen/";
import SideBar from "./components/sidebar";
import Contact from "./components/Contact/";



const Drawer = DrawerNavigator(
  {
   Home: { screen: Home },
    Contact: { screen: Contact},
  },
  {
    navigationOptions: {
      gesturesEnabled: false
    },
  initialRouteName: "Home",
    contentOptions: {
      activeTintColor: "#e91e63"
    },
    drawerPosition: 'right',
    contentComponent: props => <SideBar {...props} />
  }
);



export default Drawer;
Stack Navigator

/* @flow */

import React from "react";

import { Platform } from "react-native";
import { Root } from "native-base";
import { StackNavigator} from "react-navigation";
import Drawer from "./Drawer";
import Contact from "./components/Contact"
import Register from "./components/Register"
import Home from "./components/home/";

const AppNavigator = StackNavigator(
    {
        Drawer: {screen: Drawer},
       Home: { screen: Home },
        Register: {screen: Register},
    },
    {
        initialRouteName: "Home",
           headerMode: Platform.OS == "android" ? "none" : "float",
        header: (navigation) => ({
            left: (
                <Button
                  title="Back"
                  onPress={ () => navigation.goBack() }  
                />
              )
          })
    }
);

export default () =>
    <Root>
        <AppNavigator />
    </Root>;

**Comment by GaudamThiyagarajan** [comment] 2018-03-27 14:52
use reset

      const reset = NavigationActions.reset({
        key: null, // must have
        index: 0,
        actions: [NavigationActions.navigate({ routeName: 'LoginScreen' })],
      });
      navigation.dispatch(reset);

**Comment by mohammadusman123** [comment] 2019-01-01 22:03
@shivrajkumar did you find the solution? I am in the similar situation. Thanks.

**Comment by gabriel-TheCode** [comment] 2019-01-24 11:44
SAAAAME ! 😩😩😩

**Comment by mohammadusman123** [comment] 2019-01-24 11:49
I figured it out, what's the exact problem you are facing.

**Comment by gabriel-TheCode** [comment] 2019-01-24 12:14
I have this model.
- StackNavigator
-- SplashScreen
-- LoginScreen
-- 2 DrawerNavigator (user & admin)
--- HomeScreen - initialScreen
--- OthersScreens
From drawer i navigate to othersScreens.
I have an option to logout from DrawerScreen i.e, navigate back to LoginScreen.

If I open app when I'm already connected I should navigate to DrawerScreen directly depending of the type of user. The problem is that I dont know how to do that  🤕 Configure the routes give me headaches

**Comment by mohammadusman123** [comment] 2019-01-24 12:20
Can't you have middle screen for the both cases and check where to go next after evaluating the user status, the middle screen has no view of it self but a checkpoint where to go next.

**Comment by gabriel-TheCode** [comment] 2019-01-24 12:49
I check user status on SplashScreen then I move to the concerned page. My problem is principally how to manage that properly because I get route errors

**Comment by marcespinoza** [comment] 2020-07-05 00:42
There is solution there? i have the same problem
