### ISSUE TITLE
How to navigate to specific tab of TabNavigator

### ISSUE THREAD

**Issue by sckoh** [react-community/react-navigation#1089] opened 2017-04-18 08:24 UTC
I have 

```
const Tab = TabNavigator(
  {
    Home: { screen: Home },
  },
  {
    Market: { screen: Market },
  },
  {
    Profile: { screen: Profile },
  },
);
```

I tried to dispatch

```
NavigationActions.reset({
    index: 0,
    actions: [
      NavigationActions.navigate({
        routeName: 'Tab',
        action: NavigationActions.navigate({
          routeName: 'Market',
        }),
      }),
    ],
  });
```

to go to Market tab after navigate to Tab but it is not working. It still stay at Home tab.
there is only 1 reset action dispatched in redux-logger.

**Comment by ovarunendra** [comment] 2017-04-18 11:18
you should try this
```
const Tab = TabNavigator(
  {
    Home: { screen: Home },
    Market: { screen: Market },
    Profile: { screen: Profile },
  },
  {
     initialRouteName: 'Market',
   }
);
```

**Comment by sckoh** [comment] 2017-04-20 09:35
but I want my default initialRouteName to be Home.

**Comment by teafn** [comment] 2017-04-24 03:21
got the same requirements

**Comment by ofairfoul** [comment] 2017-05-11 17:10
I am also having the same problem. how to reset to a specific tab?

**Comment by kozillla** [comment] 2017-05-18 13:36
Have the same problem.

**Comment by rnowm** [comment] 2017-05-18 22:43
Same problem here

**Comment by luigi-agosti** [comment] 2017-05-23 15:09
+1

**Comment by Miniplop** [comment] 2017-05-24 10:09
+ 1

**Comment by RatFou** [comment] 2017-05-28 08:25
+1

**Comment by rafaelmotta** [comment] 2017-05-29 19:37
+1

**Comment by nimish-gupta** [comment] 2017-06-02 19:45
+1

**Comment by dioxide** [comment] 2017-06-02 22:33
+1 in nested route

**Comment by luangch** [comment] 2017-06-03 04:37
+1

**Comment by podvipodvert** [comment] 2017-06-08 12:45
+1

**Comment by jaredmharris** [comment] 2017-06-13 18:33
I need to dynamically set initialRouteName. Can you pass in props somewhere to set the active tab?

**Comment by chetankotkar** [comment] 2017-06-15 06:03
try `this.props.navigation.navigate('Market');`  you will navigate to Market tab in tab navigator.

**Comment by bobzhen** [comment] 2017-06-15 09:37
+1

**Comment by jaredmharris** [comment] 2017-06-15 14:40
@chetankotkar you can only call this.props.navigation from within one of the views that you define in TabNavigator.  I want to pass a prop to the view where I define TabNavigator and tell it where to go. 

The workaround I am using is to call navigate from the first view I define in TabNavigator. Which is not ideal since it loads a view I potentially don't want and then navigates to the one I do want.

```
componentWillMount() {
    this.props.navigation.navigate(this.props.whereyouwanttogo);
  }
```

**Comment by zmGitHub** [comment] 2017-06-18 09:16
+1 any idea

**Comment by vagnerSl** [comment] 2017-07-06 14:46
+1

**Comment by chetankotkar** [comment] 2017-07-12 06:59
@jaredmharris if you are using redux you can define initial navigation state in reducer. Depending on your condition set the intial navigation state in Reducer so you wont need props.navigation.navigate() at start.  
refer  redux example [here](https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample)

**Comment by couldhll** [comment] 2017-07-28 06:04
+1

**Comment by linhnh123** [comment] 2017-08-11 10:49
@sckoh You can see my example: https://github.com/linhnh123/TabDemo

It can go to the special tab after navigate to Tab. I just used the `screenProps` to pass params.

**Comment by thachpv91** [comment] 2017-08-21 10:08
+1

**Comment by spencercarli** [comment] 2017-08-28 01:33
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:33 UTC
Labels: Type: Question

**Comment by xilibro** [comment] 2017-11-03 06:51
I am also having the same problem. how to reset to a specific tab which is not the initial?

**Comment by JorgeCeja** [comment] 2017-11-23 21:02
This is a very hacky way but it worked for me:

```
onPress={() =>
Promise.all([
  navigation.dispatch(
    NavigationActions.reset({
      index: 0,
      // TabNav is a TabNavigator nested in a StackNavigator
      actions: [NavigationActions.navigate({ routeName: 'TabNav' })]
    })
  )
]).then(() => navigation.navigate('specificScreen'))
}
```

But it might lead to a better temporary solution. Hope it helps

**Comment by ou2s** [comment] 2017-11-28 12:59
thanks for sharing @JorgeCeja...

Anyone else thinking that is a critical feature missing from a navigation library? It should be added to v1 roadmap IMO.

**Comment by brentvatne** [comment] 2018-03-06 23:41
basic example - go from tab a to tab b and vice versa: https://snack.expo.io/@react-navigation/navigate-to-tab-by-name

> @chetankotkar you can only call this.props.navigation from within one of the views that you define in TabNavigator. I want to pass a prop to the view where I define TabNavigator and tell it where to go.

you can dispatch a navigate action on the ref from the top-level navigator: https://snack.expo.io/@react-navigation/navigate-to-tab-from-parent

if this isn't what you meant, and you have something like StackNavigator A -> TabNavigator -> StackNavigator B and you want to be able to go to a particular tab, the same thing applies -- just call navigate. the route name needs to be unique, though.

as you can see there's no difference if a stacknavigator is involved: https://snack.expo.io/@react-navigation/navigate-to-tab-from-parent-and-with-stacks

if someone can explain exactly what their issue is here and why the examples i mentioned above don't handle that case, please create a new issue with a reproducible example. thanks!
