### ISSUE TITLE
runAfterInteractions no longer works after using swipe gesture to go back

### ISSUE THREAD

**Issue by lprhodes** [react-community/react-navigation#1722] opened 2017-05-30 01:25 UTC
runAfterInteractions continues to work fine if you use the back button in a navigation stack however if you use a gesture then runAfterInteractions becomes blocked.

You can see the issue by running the following method in the root component of a navigation stack then navigating down into the stack and back up using gestures.

```
  testInteractions () {
    InteractionManager.runAfterInteractions(() => {
      console.log('runAfterInteractions')
    })

    setTimeout(() => {
      this.testInteractions()
    }, 1000)
  }
```

react-navigation: v1.0.0-beta.11
react-native: v0.44.1

**Comment by lprhodes** [comment] 2017-05-30 02:11
It doesn't occur in the core code - it's an issue with PR #1308

**Comment by lyxia** [comment] 2017-06-02 08:54
Is there any solution? I encountered the same problem.

**Comment by lprhodes** [comment] 2017-06-02 09:01
Are you using the improv d animation code I wrote? If not it's unrelated

**Comment by spencercarli** [comment] 2017-08-30 01:54
Going to close this since it's not a bug in core

**Closed by spencercarli** 2017-08-30 01:54 UTC

**Comment by seanyusa** [comment] 2018-03-23 15:19
I am actually experiencing this issue on core. If you use the back swipe gesture too quickly before runAfterInteractions has executed then runAfterInteractions no longer works again until the app is restarted. Any ideas on why this is happening and how to fix?

**Comment by jiasongs** [comment] 2018-05-22 09:52
+1
