### ISSUE TITLE
Decouple "Header" from StackNavigator and rename current StackNavigator-only "Header" to "StackNavigatorHeader"

### ISSUE THREAD

**Issue by RobIsHere** [react-community/react-navigation#2151] opened 2017-07-15 10:31 UTC
Header is coupled very tight with StackNavigator. Although it is a general purpose component by its name. In the real world you would have headers everywhere. (Not even to speak of header-transitions)

My current use case is to make tabnavigator work with a custom header. The header from react-navigation is beyond repair for that use case. I'm going to create my own.

My expectation would be a REUSABLE Header base class that is decoupled and has basic support for animations. This base class could then be extended to get a specific StackNavigatorHeader class.

The base expectation is: Rename Header to StackNavigatorHeader because that's what it is now. I wasted a huge amount of time on finding out things like this, as it is my first time with react-navigation.

Note the NavigationStackScreenOptions references. That could be better designed for a general purpose navigation lib.

```
export type HeaderProps = NavigationSceneRendererProps & {
  mode: HeaderMode,
  router: NavigationRouter<
    NavigationState,
    NavigationAction,
    NavigationStackScreenOptions
  >,
  getScreenDetails: NavigationScene => NavigationScreenDetails<
    NavigationStackScreenOptions
  >,
  style: Style,
};
```

**Comment by kelset** [comment] 2017-11-25 08:50
Pinging OP @RobIsHere since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I think it's a duplicate of https://github.com/react-community/react-navigation/issues/1933

**Comment by RobIsHere** [comment] 2017-11-25 09:01
To describe my use case:
We wanted to have the same header like in our Stack Navigator also in the Tab Nav. Which wasn't possible easily at the time of  writing this.

If it's posible now or the other issue will solve this use case, I'm happy with closing this.

**Closed** 2017-12-03 09:56 UTC
Labels: 7 days countdown, feature request
