### ISSUE TITLE
Tabbar Android image not overflow

### ISSUE THREAD

**Issue by Ilario17** [react-community/react-navigation#3092] opened 2017-12-07 14:09 UTC
The central button is higher than the Tabbar, on iOS works well but on Android the upper part of the button is cut, see the images:

iOS
![tab_ios](https://user-images.githubusercontent.com/33326791/33719219-551bbb9a-db60-11e7-8e5c-ad0bd8a1d653.png)

Android
![tab_android](https://user-images.githubusercontent.com/33326791/33719227-5a8c8a46-db60-11e7-9f40-a964fb44c7d1.png)

This is the style of the Tabbar Social component:

```
const BtnTabbarSocial = (props) => {
    const source = ...
    return (
        <View style={styles.container}>
            <Image
                source={source} 
            />
        </View>
    );
};

const styles = {
    container: {
        width: 64,
        height: 60,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 30,
        paddingBottom: 5,
        position: 'absolute',
    }
};
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0.beta-19
| react-native     | 0.49
| npm or yarn      | nom 5.3.0

**Comment by kelset** [comment] 2017-12-07 14:44
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

Moreover, I think you are actually reporting a known issue with Android in RN:
* https://github.com/facebook/react-native/issues/3198
* https://github.com/facebook/react-native/issues/6802
* https://react-native.canny.io/feature-requests/p/add-overflow-support-to-android

**Closed by kelset** 2017-12-07 14:44 UTC

**Comment by Ekhui** [comment] 2018-01-26 09:06
how did you sloved it ?

**Comment by Ilario17** [comment] 2018-01-26 09:22
@Ekhui I have not solved it yet

**Comment by Ilario17** [comment] 2018-06-07 07:51
@wuyunqiang No :(

**Comment by wuyunqiang** [comment] 2018-06-07 09:00
other way make like that
![react-navigation](https://user-images.githubusercontent.com/13480948/41089270-0c820d5a-6a74-11e8-87af-c5f1c75122a9.png)
https://github.com/wuyunqiang/RNApp

**Comment by brentvatne** [comment] 2018-06-07 20:50
react-native android doesn't support overflow on views

**Comment by Hotsuyuki** [comment] 2018-06-23 13:57
Hi @wuyunqiang , thank you for suggesting your solution. Which code snipet in your repository (https://github.com/wuyunqiang/RNApp) is the code that achieve this overflow feature? Could you please point it for me?

**Comment by wuyunqiang** [comment] 2018-06-24 11:03
@Hotsuyuki   src/component/Tab.js

**Comment by tokinonagare** [comment] 2018-09-20 03:06
@wuyunqiang  Thanks for your code! 
Now it's perfect for my project.

https://gist.github.com/tokinonagare/f1d2978e41b3bf300f842718d9dc12c7
