### ISSUE TITLE
Android app gets totally restored after minimizing it + some small amount of time

### ISSUE THREAD

**Issue by ferrannp** [react-community/react-navigation#767] opened 2017-03-21 15:14 UTC
We know that an Android app gets killed when using the back button which is OK and expected.

But if I use the middle button (from the Android bottom NavBar), what I do is minimize the app. So I can re-open it again clicking the app icon or going to the list of opened apps by Android. It seems to work when you do it right away but after some time (less than a minute), when opening the app, it gets totally restored (main route and so on). I suspect this is caused because high memory usage due JS?

Apps that are not react native can be in the background for hours (even days), you re-open them and they are where you left them (like route X and drawer open).

I start to think that the solution to this might not be trivial. Maybe using `AppState`, to detect when the app goes into the background, save all necessary state into `AsyncStorage` and restore it even if app gets killed.

Maybe this is not even related to this library or maybe it should be a nice part in docs, just throwing ideas here.

**Comment by ashconnell** [comment] 2017-03-22 01:44
@ferrannp I cant reproduce this, can you provide a minimal app with steps to reproduce? Also what kind of phone are you using?

My assumption would be that its something outside of react-navigation

**Comment by satya164** [comment] 2017-03-22 02:05
I'm closing this since it's not specific to React Navigation. React Native apps usually use more memory and it's normal for Android to kill the apps when in background.

**Closed by satya164** 2017-03-22 02:05 UTC

**Comment by douglasjunior** [comment] 2018-03-14 14:17
I had a similar problem, I fixed putting the property `android:launchMode="singleTop"` in my Activity tag in AndroidManifest.xml.
