### ISSUE TITLE
When nest DrawerNavigator in StackNavigator, getStateForAction not worked properly

### ISSUE THREAD

**Issue by xiongxiong** [react-community/react-navigation#1942] opened 2017-06-20 04:10 UTC
### Current Behavior
I put a DrawerNavigator in a StackNavigator, and set its path, like this:
```
const DrawerScreen = DrawerNavigator({
    Home: {
        screen: HomeScreen
    }
});
DrawerScreen.navigationOptions = {
    header: null
}
export const AppNavigator = StackNavigator({
    Home: {
        screen: DrawerScreen,
        path: 'home'
    },
    Login: {
        screen: LoginScreen,
        path: 'login'
    },
    AddCar: {
        screen: AddCarScreen,
        path: 'addCar'
    },
    AddLicense: {
        screen: AddLicenseScreen,
        path: 'addLicense'
    }
}, {
    headerMode: 'screen'
});
```
I want to navigate to 'home', so I get navigator state like this:
```
AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('home'));
```
And ran into this error:
![image](https://user-images.githubusercontent.com/3443704/27315946-4725f19a-55af-11e7-9a0c-afda27cc3027.png)

I debugged, the error occurred at line 109 of TabRouter.js:
```
 // Let the current tab handle it
 const activeTabLastState = state.routes[state.index];
```
Here, state.routes & state.index are all undefined, according to the comment, I think the DrawerNavigator is seen as a TabNavigator.

### Expected Behavior
The StackNavigator should navigate to the DrawerNavigator use its path 'home'.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | 7.8.0
| npm or yarn      | 0.22.0

**Comment by jcaspian** [comment] 2017-06-20 12:20
Could it be the typo here 

`AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('home'));`

where **h**ome should be **H**ome?

**Comment by xiongxiong** [comment] 2017-06-21 01:16
@jcaspian According to the document,  the path should be passed to getActionForPathAndParams, and when I passed 'login', 'addCar', 'addLicense', it's all ok. I can also set DrawerScreen's path to 'hello', the error is same.

**Comment by vincent1988** [comment] 2017-06-21 07:21
same issues! I also use TabNavigator in StackNavigator, the result was same

**Comment by RobIsHere** [comment] 2017-07-16 20:00
Maybe part of the problem is that you have 2 times "Home" as key, so it's not unique anymore?

```
const DrawerScreen = DrawerNavigator({
    Home: {
        screen: HomeScreen
    }
});
export const AppNavigator = StackNavigator({
    Home: {
        screen: DrawerScreen,
        path: 'home'
    },
    and so on
}
```
=>
```
const DrawerScreen = DrawerNavigator({
    Home: {
        screen: HomeScreen
    }
});
export const AppNavigator = StackNavigator({
    HomeContainer: {
        screen: DrawerScreen,
        path: 'home-container'
    },
    and so on
}
```

also I had to call getActionForPathAndParams() on the router of the navigator where it is defined, otherwise I got null back.

AppNavigator.router.getStateForAction(DrawerScreen.getActionForPathAndParams("Home"))

**Comment by vinhtq** [comment] 2017-08-10 10:20
+1 for this. I think for tempo solution you should make a fake splash screen which check the auth state then decide which page to display

**Comment by kelset** [comment] 2017-11-12 11:41
Pinging OP @xiongxiong  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment] 2017-11-19 10:07
Hi there @xiongxiong ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-11-19 10:07 UTC
Labels: 7 days countdown, bug, component: Drawer
