### ISSUE TITLE
React-navigation error when pushing new screen

### ISSUE THREAD

**Issue by somsin** [react-community/react-navigation#3027] opened 2017-11-22 07:57 UTC
https://stackoverflow.com/questions/47420481/react-navigation-error-when-pushing-new-screen

**Comment by somsin** [comment] 2017-11-22 07:58
ISSUE: issue is not coming in compile time , if its compile time then some thing wrong with syntax but its coming when I am pushing , and controls not reach to next screen means render and constructor .so issue at when I am pushing using navigation. some thing wrong to make push new screen but whats issue how to fix.

I am getting some error when trying to push new screen . same screen I am pushing from other screen its working fine , but I have added custom header in navigationOptions and setParams for custom action , all action working fine , now I am trying to go another screen from this screen getting issue not able to find what is issue ,

I am using "react-navigation": "1.0.0-beta.11",

**Comment by vonovak** [comment] 2017-11-22 08:29
I answered the stackoverflow question: the title should not be an empty string, use `title: ' '`, or upgrade to latest version to solve the problem.

closing, please reopen if the problem is somewhere else.

**Closed by vonovak** 2017-11-22 08:29 UTC
