### ISSUE TITLE
Header hiding the phone status bar like Time , wifi icons

### ISSUE THREAD

**Issue by jpca999** [react-community/react-navigation#2785] opened 2017-10-18 15:29 UTC
After using react - navigation I realize that phone status bar like Time , wifi icons are hiding. 
How can I fix it  i.e  It should be showing all the icons ?

![image](https://user-images.githubusercontent.com/1026325/31727271-2ba7a3c2-b3f7-11e7-9084-cf57f75f5476.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^1.0.0-beta.11",
| react-native     | https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz
| node             |  8.6.0
| npm or yarn      | 1.1.0

**Comment by sanjayholla94** [comment] 2017-10-20 10:06
Please post some code so that we can understand what the problem is. Also, I suggest you to post the issue on StackOverflow and link it back here as this doesn't look like a bug of the library.

**Comment by jdmunro** [comment] 2017-10-20 15:18
You've got the status bar style set to white - I think you probably wanted the dark variant. You can set the style using this: https://facebook.github.io/react-native/docs/statusbar.html#barstyle

**Comment by kelset** [comment] 2017-10-20 15:53
This is not an issue, so I'll close it. Moreover @jdmunro 's comment provides the solution, which is related to react native ;)

**Closed by kelset** 2017-10-20 15:53 UTC

**Comment by jpca999** [comment] 2017-10-29 14:59
@jdmunro 

where do i provide the folloing code in my code 
barStyle?: enum('default', 'light-content', 'dark-content') #

my code :  

[



    static navigationOptions = ({ navigation }) => {
      const {state, setParams} = navigation;
      return {
        tabBarLabel: 'Students',
        // headerTitleStyle: { color: '#018080', fontFamily: 'rounded' },
        headerTitleStyle: { color: '#018080', fontFamily: 'rounded', fontSize: 28 },
        tabBarIcon:  ({ tintColor }) => {
                return <Icon name="contacts" size={25} color={tintColor} />;
        },
        headerBackTitleStyle: {
              // color: '#018080',
              fontFamily: 'rounded'
          },
        headerTitle: 'Today',
        headerRight: (
          <Button
            title='Add'
            // headerTitleStyle: { color: '#018080', fontFamily: rounded' },
            onPress={() => navigation.navigate('newStudent')
             }
          />
        ),
      };
    };



](url)
