### ISSUE TITLE
Screens appear twice when accidentally double clicking(touching)

### ISSUE THREAD

**Issue by cmrichards** [react-community/react-navigation#350] opened 2017-02-15 23:54 UTC
If you accidentally touch a navigation button twice to jump to the next screen then the next screen will appear twice.

Is there some kind of inbuilt mechanism to stop this behaviour?

Great library btw!

**Comment by satya164** [comment] 2017-02-16 08:44
Duplicate of #271

**Closed by satya164** 2017-02-16 08:44 UTC
