### ISSUE TITLE
Tabbar wrong position with Stack and Tabbar

### ISSUE THREAD

**Issue by Clowning** [react-community/react-navigation#2036] opened 2017-06-30 18:43 UTC
### Current Behavior
Hey,

I've an application with a Tabbar with few tab and Stack into it. When i navigate to a view with a Stackview, my tabbar is not at the same position that when i'm on a simple Tabbar page. 

![screenshot_20170630-203728](https://user-images.githubusercontent.com/2753799/27749638-a3f3f61a-5dd4-11e7-807e-6edaf7121812.png)
![screenshot_20170630-203739](https://user-images.githubusercontent.com/2753799/27749639-a3fecd60-5dd4-11e7-9a1b-6328384861b0.png)

If i put my tabbar at the position, is follow my keyboard when it is open... It's very annoying !

On my first screenshot it's on a tabbar page and the second on a stack page!

### Expected Behavior
My tabbar need to stay at the same place into my app, whatever where i am into it !

### Your Environment
Mac OS to compile
Android 7 for my app

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | v6.9.1
| npm or yarn      | 4.1.2

**Comment by matthamil** [comment] 2017-07-01 06:19
I'm not sure I fully understand your question. Can you provide a .gif or video showing the problem? Can you post a code snippet too?

**Comment by Clowning** [comment] 2017-07-01 07:25
@matthamil  Yes i'm sorry, i'm not very fluent in English aha ! 

Here there is a gif 

![tabbarheaderbug](https://user-images.githubusercontent.com/2753799/27760082-131e13b2-5e3f-11e7-860d-038b52ba273e.gif)

Yes here my router :

```
import React from 'react';
import {
  StyleSheet,
  View,
  Text
} from 'react-native';

import {
  Home,
  Login,
  Notifications,
  Events,
  Messages,
  PrivateProfil,
  Settings,
  CreateEvent
} from '@Pages';

import { Header } from '@Components';

import IconIonicons from 'react-native-vector-icons/Ionicons';
import IconMaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
import IconMaterialIcons from 'react-native-vector-icons/MaterialIcons';

import {
  StackNavigator,
  TabNavigator,
  NavigationActions
} from 'react-navigation';

const headerConfig = {
    headerTintColor: '#95A5A6',
    headerStyle: {
      backgroundColor: '#E4E8E9'
    },
    headerBackTitleStyle: {
      color: '#95A5A6',
      },
  };

const tabbarConfig = {
    activeTintColor: '#f39c12',
    inactiveTintColor: '#95a5a6',
    showIcon: true,
    showLabel: false,
    style: {
      height: 60,
      backgroundColor: '#ECF0F1',
      borderColor: '#ECF0F1',
    },
    iconStyle: {
      top: -10,
      width: 40,
      height: 60
    },
    indicatorStyle: {
      backgroundColor: 'transparent',
    }
};

const Profil = StackNavigator({
  MyProfil: {
    screen: PrivateProfil,
    navigationOptions: { title: 'Profil' }
  },
  Settings: {
    screen : Settings,
    navigationOptions: { title: 'Settings' }
  }
},{ mode: 'modal', navigationOptions: headerConfig });

const MyEvents = StackNavigator({
  MyEvents: {
    screen: Events,
    navigationOptions: { title: 'Events' }
  },
  CreateEvent: {
    screen : CreateEvent,
    navigationOptions: { title: 'Create an event' }
  }
},{ mode: 'modal', navigationOptions: headerConfig });

inApp = TabNavigator({

  Home: {
    screen: Home,
    navigationOptions: { title: 'MyApp' }
  },
  Notifications: {
    screen: Notifications,
    navigationOptions: { title: 'Notifications' }
  },
  Events: {
    screen: MyEvents,
    navigationOptions: {
      header: null,
      tabBarIcon: ({tintColor}) => (  <IconMaterialIcons size={25} color={tintColor} name="event" />)
    }
  },
  Messages: {
    screen: Messages,
    navigationOptions: { title: 'Messages'  }
  },
  PrivateProfil: {
    screen: Profil,
    navigationOptions: {
      header: null,
      tabBarIcon: ({tintColor}) => (<IconMaterialCommunityIcons size={28} color={tintColor} name="account" />)
    }
  },
},
{
  tabBarOptions: tabbarConfig,
  navigationOptions: headerConfig,
  initialRouteName: 'Home',
  animationEnabled: false,
});

Beewent = StackNavigator({
  Login: {
    screen: Login,
    navigationOptions: {header: null}
  },
  inApp: {
    screen: inApp,
  },
}, {
  initialRouteName: 'inApp',
});

const navigateOnce = (getStateForAction) => (action, state) => {
  const {type, routeName} = action;
  return (
    state &&
    type === NavigationActions.NAVIGATE &&
    routeName === state.routes[state.routes.length - 1].routeName
  ) ? null : getStateForAction(action, state);
  // you might want to replace 'null' with 'state' if you're using redux (see comments below)
};

Profil.router.getStateForAction = navigateOnce(Profil.router.getStateForAction);
MyEvents.router.getStateForAction = navigateOnce(MyEvents.router.getStateForAction);


export default Beewent;
```

**Comment by bennygenel** [comment] 2017-07-02 18:30
Hi;
If I understand the problem correctly, problem is that your "Header" is not showing in the right place not your TabBar.
Problem is caused by that you set `{title: "Events"}` on your StackNavigator and other titles on your TabNavigator. So header shows in different places.
I'm not sure how can you achieve what you are looking for but at least maybe I could help you to figure out the problem.

**Comment by Clowning** [comment] 2017-07-19 12:30
Ok but your answer doesn't help me aha ! 

I can't remove 'title' into my stackNavigator and set it in my tabNavigator because if i do that, my header is not updated when i naviguate into my Stack so i need to set my header to null in my TabNavigator :/

**Comment by spencercarli** [comment] 2017-08-29 02:22
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-29 02:22 UTC
Labels: Type: Question
