### ISSUE TITLE
statusbar covering the tabs in expo app on android

### ISSUE THREAD

**Issue by manjeets12** [react-community/react-navigation#1168] opened 2017-04-22 16:38 UTC
I am just started to work with expo and just installed [example expo app](https://expo.io/@community/react-navigation-playground) on my android 5.1. In that my statusbar is covering some parts of tabs and I am not sure how to resolve this

expo/react-navigation example screenshots
![screenshot_2017-04-22-21-58-16 1](https://cloud.githubusercontent.com/assets/17762875/25306275/76c19160-27a7-11e7-9a9c-fd438db21a82.png)
![screenshot_2017-04-22-21-58-37 1](https://cloud.githubusercontent.com/assets/17762875/25306277/81ee0104-27a7-11e7-8604-c950650f7927.png)

and now here is screenshot from expo/ex-navigation example app

![screenshot_2017-04-22-22-03-02 1](https://cloud.githubusercontent.com/assets/17762875/25306292/c5eb6964-27a7-11e7-95ae-867dcb7e1e91.png)
![screenshot_2017-04-22-22-03-09 1](https://cloud.githubusercontent.com/assets/17762875/25306303/e157c990-27a7-11e7-8c32-18d3d704c76a.png)

and see now how good it is looking, what changes should I do to make it look like same

**Comment by dantman** [comment] 2017-04-24 09:31
Expo implicitly sets the StatusBar to translucent. You'll need to add `paddingTop` to `headerStyle` on Android to accommodate the status bar size.

**Comment by k15a** [comment] 2017-04-24 09:36
There is [`Constants.statusBarHeight`](https://docs.expo.io/versions/v16.0.0/sdk/constants.html#expoconstantsstatusbarheight) from the `expo` package which will be the height of the statusBar.

**Comment by grabbou** [comment] 2017-04-24 09:42
This is a duplicate of #12

**Closed by grabbou** 2017-04-24 09:42 UTC

**Comment by ro-savage** [comment] 2017-08-20 10:50
Code sample, for anyone looking for it:

```js
const App = StackNavigator({
  Home: { screen: HomeScreen },
  About: { screen: AboutScreen },
  }, {
    navigationOptions: {headerStyle: { marginTop: Expo.Constants.statusBarHeight } }
  })
```

**Comment by noamnelke** [comment] 2017-11-14 21:34
Small tweak to @ro-savage's code sample, so it doesn't break ios:

```javascript
const App = StackNavigator({
  Home: { screen: HomeScreen },
  About: { screen: AboutScreen },
}, {
  navigationOptions: { headerStyle: { marginTop: (Platform.OS === 'ios') ? 0 : Expo.Constants.statusBarHeight } }
})
```

**Comment by fc** [comment] 2018-04-03 20:48
If you're using native-base, set the headerMode to `none` for the `StackNavigator` then set the `container` style to set the `marginTop` identical to what is above.

```

export default StackNavigator({
    Home: {
      screen: HomeScreen
    },
    // ...
  }, {
    //...
    headerMode: 'none'
  });
```

Example container style:
```
const styles = StyleSheet.create({
    container: {
        flex: 1,
        marginTop: Platform.OS === 'ios' ? 0 : Expo.Constants.statusBarHeight
    },
});
```

**Comment by EL-MEHDI-ESSAADI** [comment] 2023-09-28 16:12
rendring status bar wtih translucent equal false fix the problem for me

```
import { View, Text, StatusBar } from "react-native";

function Layout() {

  const isFontsLoaded = useInitFonts();

  if (!isFontsLoaded) return null;

  return (
    <>
      <Tabs screenOptions={{ headerShown: false }}>
        <Tabs.Screen name="index" />
      </Tabs>
      <StatusBar translucent={false} />
    </>
  );
}
```

**Comment by rahul8864** [comment] 2024-06-29 15:26
```
import { SafeAreaProvider } from "react-native-safe-area-context";
<SafeAreaProvider>
<View>
<Text>I do like this it working fine. for me</Text>
</VIew>
</SafeAreaProvider>
```

https://docs.expo.dev/develop/user-interface/safe-areas/
