### ISSUE TITLE
goBack is always taking me to the first screen

### ISSUE THREAD

**Issue by kheraprabhat** [react-community/react-navigation#2898] opened 2017-11-03 21:59 UTC
Please help me with this!

https://stackoverflow.com/questions/47094753/goback-always-taking-to-home-first-screen-in-react-navigation

```
import React from 'react';
import { DrawerNavigator } from 'react-navigation';
import { Button, StyleSheet } from 'react-native';

class one extends React.Component {
  static navigationOptions = {
    drawerLabel: 'one',
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack(null)}
        title="Go back notifications"
      />
    );
  }
}

class MyHomeScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Home',
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('Notifications')}
        title="Go to notifications"
      />
    );
  }
}

class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Notifications',
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('one')}
        title="Go to one"
      />
    );
  }
}

const styles = StyleSheet.create({
  icon: {
    width: 24,
    height: 24,
  },
});

const MyApp = DrawerNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
  one: {
    screen: one
  }
});

export default MyApp;

```
I am not sure if this is the standard behaviour or not. I have tried it with goBack(null) but no luck.

Version:

    "react": "16.0.0-beta.5",
    "react-native": "0.49.5",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.18"

**Comment by kelset** [comment] 2017-11-03 22:02
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-03 22:02 UTC
