### ISSUE TITLE
set Transition mode for each view

### ISSUE THREAD

**Issue by Blackscr33n** [react-community/react-navigation#605] opened 2017-03-07 18:14 UTC
Hey guys!

Is it possible to set the mode of a transition for each component?
Only found the config as example in the StackNavigator - `StackNavigatorConfig `

but I would like to set the mode in the navigationOptions, is this possible?

Greets,
Bernhard

**Comment by grabbou** [comment] 2017-03-07 22:50
Duplicate of #124

**Closed by grabbou** 2017-03-07 22:50 UTC
