### ISSUE TITLE
Problem passing params on navigation

### ISSUE THREAD

**Issue by nicolit** [react-community/react-navigation#3144] opened 2017-12-17 16:53 UTC
I have found a weird bug. when I try to pass params to next screen, in the render function it receives the params in navigation.state but the app crashes. code snippet:
navigation.navigate('screenA', { param1: true});
----- or
const navigateAction = NavigationActions.navigate({
                  routeName: 'screenA',
                  params: { param1: true }, });
navigation.dispatch(navigateAction);
screenshot is attached. and yes I have searched in SOF and other issues here as well with no clue.
![photo5888786160573066112](https://user-images.githubusercontent.com/10170174/34081774-0c85e66e-e35b-11e7-9ecc-91b7531b5cd3.jpg)

**Comment by kelset** [comment] 2017-12-17 17:31
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-17 17:31 UTC
