### ISSUE TITLE
Header title overlapping left and right on Android

### ISSUE THREAD

**Issue by seantempesta** [react-community/react-navigation#758] opened 2017-03-21 03:18 UTC
"react-navigation": "^1.0.0-beta.7"

Just using a normal title (in this screenshot it's supposed to say "My Account") and left, right are just normal Facebook Button components.  Works fine in iOS.  

Also, is the status bar supposed to overlap the header?  I've never used Android before so I don't know their default styles.  

<img width="481" alt="screen shot 2017-03-21 at 11 03 57 am" src="https://cloud.githubusercontent.com/assets/726276/24130892/47cfbb38-0e26-11e7-8860-d923aa15d060.png">

<img width="613" alt="screen shot 2017-03-21 at 11 13 50 am" src="https://cloud.githubusercontent.com/assets/726276/24131190/08a66086-0e28-11e7-8a12-e662908edb6a.png">

**Comment by jakallergis** [comment] 2017-03-22 09:56
I've tackled this problem with paddingLeft on the title (titlteStyle inside header in navigationOptions). Does the job for now

**Comment by seantempesta** [comment] 2017-03-22 11:34
Good to know it's not just me. I plan on doing the padding like you said, but someone more familiar with the code base should probably fix this.

**Comment by seantempesta** [comment] 2017-03-22 11:34
Oops. Didn't mean to close it.

**Comment by wasa4587** [comment] 2017-05-08 18:35
yeah, i have the same issue

**Comment by windhost** [comment] 2017-07-28 08:40
+1

**Comment by paulohenriquesg** [comment] 2017-08-13 07:14
+1

**Comment by kelset** [comment] 2017-10-14 18:59
Pinging OP @seantempesta since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment] 2017-10-21 11:36
Hi there @seantempesta ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-10-21 11:36 UTC
Labels: Status: Help Wanted, Type: Question

**Comment by beausmith** [comment] 2018-09-17 22:49
Anyone able to find a non-hack solution to this title overlapping left/right issue? 

My header looks like this:
![image](https://user-images.githubusercontent.com/28444/45654440-7e310980-ba90-11e8-8bd9-31364f75ec99.png)

The leaf icon is passed into the `headerTitle` of `navigationOptions`.

cc: @seantempesta, @wasa4587, @windhost, @paulohenriquesg

**Comment by beausmith** [comment] 2018-09-17 23:31
Ok, I guess I'm realizing that this is by design. Using the [`headerLayoutPreset: 'left'` has a fixed width for the back action](https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/Header/Header.js#L24-L25) and such I'm going to use icons instead of text.
