### ISSUE TITLE
FlatList breaks when using with StackNavigator

### ISSUE THREAD

**Issue by phouse512** [react-community/react-navigation#2135] opened 2017-07-13 17:42 UTC
Hello, I've run into an issue when using `StackNavigator` in combination with `FlatList` that I cannot figure out. As a note, I've read through #2012 and #1898 but the fixes described there have not worked for me.

Here is my screen component that I am trying to render:
```
class FactoryScreen extends React.Component {
  static navigationOptions = {
    title: 'testing',
  };

  constructor(props) {
    super(props);

    this.state = {
      datasource: [
        {id: 21, machine_key: 'f', clamp_id: 'c0'},
        {id: 22, machine_key: 'f', clamp_id: 'c1'},
        {id: 23, machine_key: 'f', clamp_id: 'c2'}
      ]
    };
  }

  render() {
    return (
      <View>
        <FlatList
          removeClippedSubviews={false}
          style={{backgroundColor: 'white'}}
          data={this.state.datasource}
          renderItem={({item}) => {
            console.log(item);
            return (<Text style={{flex: 1, height: 50}}>{item.clamp_id}</Text>);
          }}
        />
      </View>
    );
  }
}

export default class App extends React.Component {
  render() {
    return (
      <View>
        <FactoryScreen />
      </View>
    );
  }
}
```

When I put that directly into my app and render it as the root and only element, it displays correctly. However when I put it into `StackNavigator` as shown below, nothing displays for me, even though no error is shown.

```
const SimpleApp = StackNavigator({
  Main: {screen: FactoryScreen},
});
export default class App extends React.Component {
  render() {
    return (
      <View>
        <SimpleApp />
      </View>
    );
  }
}
```

I would expect that the `FlatList` displays as it did previously, but no dice.  Any help would be appreciated.

I have also attached a [snack.expo.io link](https://snack.expo.io/H1IJxVSS-) that shows the issue as well.  If you change `FactoryScreen` in the root view to the `SimpleApp` stack navigator component, it then breaks.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             |  6.7
| npm or yarn      | 3.10.3

**Comment by Amurmurmur** [comment] 2017-07-13 18:06
+1

**Comment by lorenzsell** [comment] 2017-07-13 19:37
I'm not sure what the issue is but I have a flatList running inside a stack navigator with no problems.

**Comment by lorenzsell** [comment] 2017-07-13 19:38
I was having a problem where it would only show after scrolling the view, but removeClippedSubviews={false} fixed the issue.  It seems you've already added that.

**Comment by phouse512** [comment] 2017-07-14 00:22
@lorenzsell unfortunately it did not work here. just to confirm, to fix your issue you placed that prop on `FlatList` and not its children or its parent?

**Comment by lorenzsell** [comment] 2017-07-14 01:48
Yes.  This is what mine looks like:

```
<FlatList
          data={this.props.spaceList}
          renderItem={item => this.renderItem(item, this.props.navigation)}
          keyExtractor={item => item.id}
          removeClippedSubviews={false}
/>
```

**Comment by Amurmurmur** [comment] 2017-07-14 02:14
@lorenzsell That did fix my issue! 👍  Thank you :)

Tho don't you think it might affect the performance of the scroll? Since it wont remove clipped subview once they disappear from the screen :/ ?
Even tho the official docs suggest to use  `removeClippedSubviews={true}` at your own risk Im kind confused if it will affect the scroll much, if items are full width of the screen images and texts, and might be 100+ items ?

**Comment by lorenzsell** [comment] 2017-07-14 02:52
Not sure.  Test it and let me know :-)

**Comment by fabriziogiordano** [comment] 2017-07-14 03:27
By adding `flex=1` to the exported class view seems to fix the issue.
It is not required to use `removeClippedSubviews={true}` as well.
Here the [snack](https://snack.expo.io/ry5FtnSSZ).

```
export default class App extends React.Component {
  
  render() {
    return (
      //The view needs to be flexed
      <View style={{flex:1}}>
        <SimpleApp />
      </View>
    );
  }
}
```

**Comment by Amurmurmur** [comment] 2017-07-14 11:09
@fabriziogiordano I've tried that, didnt help :/ All my views have `flex:1`
Only `removeClippedSubviews={false}` works. Otherwise as described above, the FlatList or SectionList will only appear after a slight scroll.

**Comment by phouse512** [comment] 2017-07-14 16:06
@fabriziogiordano unfortunately that did not work for me either. I'm starting to wonder if I have a version mismatch with `react-native`, `react-navigation`, or somewhere else. Do you know how to check the library versions with snack.expo?

**Comment by benyanir** [comment] 2017-10-01 15:16
+1
Same here, non of the above worked for me.

**Comment by NirBenya** [comment] 2017-10-01 15:18
+1
Same here, none of the above worked for me.

**Comment by aaronkchsu** [comment] 2017-10-08 06:53
Same! :(

**Comment by vonovak** [comment] 2017-11-04 00:20
@phouse512 the solution to the problem is not to wrap the `SimpleApp` in the `View`, ie.

```js
export default class App extends React.Component {
  
  render() {
    return (
        <SimpleApp />
    );
  }
}
```

I will close this issue because it is now solved. If the other people still experience problems, I ask them to open another issue and attach a reproduction in a snack.

**Closed by vonovak** 2017-11-04 00:20 UTC
Labels: Type: Bug
