### ISSUE TITLE
Is there a way to fix my StatusBar problem on iPhone X?

### ISSUE THREAD

**Issue by XavierColombel** [react-community/react-navigation#2874] opened 2017-11-01 23:41 UTC
I'm updating my app for iPhone X. It seems my StatusBar is now large and white, do you know how to fix that? Thanks.

![preview](https://img4.hostingpics.net/pics/571824Capturedecran20171102a002625.png)

**Comment by tsangwailam** [comment] 2017-11-02 03:48
Did you have same problem on other iphone? I updated to 1.0.0-beta.16 and RN 0.49.5. The status bar always show white in stack navigation.

![screen shot 2017-11-02 at 11 45 42 am](https://user-images.githubusercontent.com/3538066/32308999-abd4782c-bfc3-11e7-8745-f9673174c39c.png)

**Comment by danstepanov** [comment] 2017-11-02 04:35
My status bar is also an off-white regardless of what I do

**Comment by MikeFvv** [comment] 2017-11-02 04:57
我也有这个问题， 状态栏为白色， 求解决办法

**Comment by XavierColombel** [comment] 2017-11-02 07:46
@tsangwailam yes, I just test on other iPhone and you're right, I've got a white StatusBar now... Awful ! 😱

**Comment by tsangwailam** [comment] 2017-11-02 07:48
The problem is <Header> have a paddingTop:20. But I can''t set via headerStyle.

**Comment by kelset** [comment] 2017-11-02 09:22
We are working on this issue, on master there's already a first fix. We'll release a new update soon.
If you need more control over the header follow this issue #2875. Closing this since it's duplicate (of #2854

**Closed by kelset** 2017-11-02 09:22 UTC
