### ISSUE TITLE
Android Header Text Not Centered

### ISSUE THREAD

**Issue by quangas** [react-community/react-navigation#544] opened 2017-03-02 12:25 UTC
Is there anyway to center the header text in Android? I noticed in the HeaderStyle.js that if its not ios, it is automatically set to "left". How can we override this without changing the HeaderStyle.js source?

I have the following.

```
static navigationOptions = {
    header: ({ navigate }) => ({
      visible: true,
      title: 'Discussion',
      left: (
        <Button onPress={() => navigate('PageTwo')} >Prev</Button>
      ),
      right: (
        <Button onPress={() => navigate('PageThree')} >Next</Button>
      ),
      style: {
        paddingLeft: 5,
        paddingRight: 0,
        backgroundColor: '#000',
      },
      tintColor: '#ffffff'
    })
  };
```

Even without the left/right buttons, the title is always aligned left. I have tried using

```
titleStyle: {
 textAlign: 'center'
}
```

But no luck either.

**Comment by RobertSheaO** [comment] 2017-03-02 13:18
I just tried it and it works. Here's the code I used.

```JS
static navigationOptions = {
  title: ({ state }) => (state.params ? state.params.title : ''), // state.params is undefined on init
  header: ({ navigate }) => { // eslint-disable-line arrow-body-style
    return {
      style: { backgroundColor: grey800},
      titleStyle: {
        color: white,
        textAlign: 'center'
      },
      left: <TopNav navigate={navigate} />,
    };
  },
  drawer: () => ({
    label: 'Taco',
    icon: ({ tintColor }) => (
      <Icon name="home" style={{height: 24, width: 24}} />
    ),
  }),
};
```

**Comment by quangas** [comment] 2017-03-02 13:24
What version of react-navigation do you have?

**Comment by RobertSheaO** [comment] 2017-03-02 13:54
I'm still on `v1.0.0-beta.5`Looks like it broke in `beta.6`, perhaps in this commit. https://github.com/react-community/react-navigation/commit/02a388073cd520d94c30ffc5f01d2e1754e93c9c

**Comment by quangas** [comment] 2017-03-02 13:56
Ah right, im on v1.0.0-beta.6, perhaps that is the reason.

**Comment by hasLandon** [comment] 2017-03-02 19:42
I have the same issue

**Comment by RobertSheaO** [comment] 2017-03-02 19:44
Adding `backgroundColor` confirmed my suspicions. In beta.5, the background takes up the entire area between the left and right items; however, in beta.6, the background only takes up as much space as the text, which is why `textAlign` center does nothing. In fact, I commented out that entire line in `HeaderTitle.js` and it made no difference.

Logging out the styles coming into `HeaderTitle.js` reveals the difference between beta.5 and beta.5 is the presence of `'flex: 1` being added. Apparently the header was converted over to using flexbox in this commit, which is why it's all messed up right now.

https://github.com/react-community/react-navigation/commit/79f21277cbec2a684edc6f2073ff36530d093f41#diff-7a1b35ffbe830ce647e620ea2b07b52a

**Comment by dmhood** [comment] 2017-03-02 22:20
dupe of https://github.com/react-community/react-navigation/issues/445

**Comment by quangas** [comment] 2017-03-02 23:02
Even with no buttons or just left or just right, the header text isn't centered. It's just not the case of left and right button present.

**Comment by quangas** [comment] 2017-03-03 02:59
I ended up doing this as a temporary fix, it will depend on how many buttons you have and also how wide your buttons are, and also and left or right padding. The style below should cover 2 buttons at most and should handle no buttons or just one. Note it doesn't cater for switching orientations, the project I'm working on is all Portrait. Don't forget to include `Dimensions`.

```
header_title: {
    backgroundColor: '#f00',
    color: '#fff',
    height: 55,
    textAlign: 'center',
    fontSize: 16,
    paddingTop: 18,
    width: Dimensions.get('window').width - 110 // width of both buttons + no left-right padding
  }
```

```
static navigationOptions = {
    header: ({ navigate }) => ({
      visible: true,
      title: <Text style={styles.header_title}>The Title</Text>,
      style: {
        paddingLeft: 0,
        paddingRight: 0,
        backgroundColor: '#f00',
      },
      tintColor: '#ffffff'
    })
  };
```

**Closed** 2017-03-03 10:16 UTC

**Comment by ldipasquale** [comment] 2017-03-15 23:06
There is no need to implement that workaround.

You can set `alignSelf: 'center' 'to titleStyle and it works.

**Comment by RobertSheaO** [comment] 2017-03-15 23:14
Yes, they reverted the flex layout in the latest release.

**Comment by quangas** [comment] 2017-03-16 23:13
@ldipasquale I just tried using alignSelf: 'center' but doesn't quite center when you have a back button (left arrow). It doesn't take into consideration the size of the back button, so its pushed off center, and closer to the right.

**Comment by dmhood** [comment] 2017-03-21 00:55
Any update here?  I encounter the same issue as @quangas, where having a button on the left/right side causes the center title to be a little off.

**Comment by mavenave** [comment] 2017-04-22 09:58
@dmhood you will have to statically offset the title with the size of the left button. That's what I did. :)

**Comment by Louis345** [comment] 2017-04-26 01:33
@mavenave  Can you maybe produce an example? I am unsure on how to do that. Thanks.

**Comment by laclance** [comment] 2017-05-02 12:14
I added `alignSelf: 'center' `and `headerRight: <View/>` to center title when there is a back button.

**Comment by luhui** [comment] 2017-05-25 03:03
@laclance ‘s solution works for me

**Comment by sujalBandhara** [comment] 2017-07-26 09:53
@laclance and @luhui Can you help me here, how to achieve center title with back button

`  navigationOptions: {
      headerTitle:'HOME',
      headerStyle:{ backgroundColor: '#ffffff'},
      headerTitleStyle:{ color: '#000000',fontFamily:'Montserrat-Regular', alignSelf: 'center' },
   }`

**Comment by luhui** [comment] 2017-07-26 11:04
@sujalBandhara Here is my solution with custom back button

```js
export const AppNavigator = StackNavigator(routeConfig, {
  navigationOptions: ({ navigation }) => ({
    headerStyle: appTheme.styles.navigationBarStyle,
    headerTitleStyle: appTheme.styles.navigationTitleStyle,
    headerLeft: navigation.state.index === 0 ? <View/> : (
      <View style={styles.backBtnContainer}>
        <ImageButton
          hitSlop={{top: 20, left: 20, right: 20, bottom: 20}}
          onPress={() => navigation.dispatch(NavigationActions.back())}
          source={{
            normal: require('assets/btn_backward_normal.png'),
            pressed: require('assets/btn_backward_pressed.png')
          }}
        />
      </View>
    ),
    headerRight: <View />
  })
})
```

**Comment by laclance** [comment] 2017-07-26 12:31
@sujalBandhara try adding a 
`headerRight: <View/>`

**Comment by liorzil** [comment] 2017-11-22 16:09
headerTitleStyle worked for me...

```
static navigationOptions = ({ navigation}) => {
      return {
        title: "Dashboard",
        headerTitleStyle: { alignSelf: 'center' },

```

**Comment by brunoreis** [comment] 2017-12-11 18:58
This worked for me: 

```
headerTitle:<Text style={{
          color:'#dde',
          alignSelf:'center',
          fontFamily: 'avenir-light',
          fontSize:18
      }}>
          Central de Notícias
      </Text>
```

**Comment by kkkelicheng** [comment] 2018-01-03 07:33
I fount that `headerTitleStyle` can not be **covered**.
```
function headerConfig({navigation}) {
    let config = Object.assign({
        headerStyle:{
            backgroundColor:'#c51a26',
        },
        headerTitleStyle:{
            fontSize:18,
            color:'white',
        },
    });
    return config;

}

export const MainNavigator =
    StackNavigator(
        someRoutes,
        {
            navigationOptions:headerConfig
        }
    );
```
The above is **default** `navigationOptions` config.

```
export default class HomePage extends Component {
    static navigationOptions = ({navigation})=>
    {
        return {
            title:"xxx",
            tabBarLabel: 'xxxx',
            headerTitleStyle:{   // not work
                alignSelf: 'center',
                backgroundColor:"yellow"
            }
        };
    }

```
and In special page (HomePage) `headerTitleStyle` will not work.

If I want to set title center,I need to set it in **default** `navigationOptions`
```
function headerConfig({navigation}) {
    let config = Object.assign({
        headerStyle:{
            backgroundColor:'#c51a26',
        },
        headerTitleStyle:{
            fontSize:18,
            color:'white',
            alignSelf: 'center',
        },
    });
    return config;
}
```

**Comment by ahinchliff** [comment] 2018-01-26 11:36
If you are displaying the default back button on every screen except the home screen
`headerRight: navigation.state.index === undefined ? undefined : <View />`

**Comment by programmerRishi** [comment] 2018-02-27 19:23
You can use 
textAlign: 'center',
flexGrow: 1

These properties should be used in ---
 headerTextStyle:
{
textAlign: 'center',
flexGrow: 1
}
It worked for me.

**Comment by rjuevesano** [comment] 2018-03-15 05:07
It worked for me.

```
static navigationOptions = {
    headerTitle: () => (
      <View style={styles.headerWrapper}>
        <Text
          adjustsFontSizeToFit
          style={styles.headerText}>FAVORITES</Text>
      </View>
    )
  }

 headerWrapper: {
    flex: 1
  },
  headerText: {
    textAlign: 'center', // ok
    alignSelf: 'center', // ok
  }
```

**Comment by martineckardt** [comment] 2018-03-16 14:48
If you have only one header button (e.g. a back button) and the title is centered but has a offset due to the button on the left / right on android use an empty view on the other side of the header to have the title perfectly centered:

```js
static navigationOptions = ({ navigation }) => ({
    headerTitle: (
      <NavBarTitle>Title</NavBarTitle>
    ),
    headerLeft: <NavBarBackButton onPress={() => navigation.goBack()} />,
    // Workaround for centered headerTitle on android
    headerRight: (<View/>),
  });
```

And in NavBarTitle
```js
export default props => (
  <View style={styles.container}>
    <Text style={[styles.text, props.style]}>{props.children}</Text>
  </View>
);

const styles = getStyles(COLORS => ({
  container: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  text: {
    // Text Styling
  },
}));
```

**Comment by Oyama87** [comment] 2018-03-27 08:38
Putting a headerRight: ( < View /> ) in navigationOptions object also worked for me to center the title text properly when the left back button is present on the header.

```
static navigationOptions = {
    title: 'My Library',
    headerTitleStyle: {
     flex: 1,
      textAlign: 'center',
      alignSelf: 'center'
    },
    headerRight: (<View />)
  }
```

Thanks to @martineckardt

**Comment by x11joe** [comment] 2018-04-08 05:33
Oyama87, literally out of everyone's answers yours was the only one to work on android and center when you have icons on left AND right! Thank you, thank you, thank you!

**Comment by khan1782** [comment] 2018-04-10 00:38
If you are having trouble centering a custom header  title with a back button on android, I was able to solve this problem by setting headerLeft=null, and building the back button into my custom header title

```	
static navigationOptions = ({navigation}) => ({
		headerTitle: <HeaderTitle
			title={navigation.state.params.title}
			icon='calendar'
			titleContainerStyle={{marginLeft:20,marginRight:20}}
			goBack={navigation.goBack}
		/>,
		headerLeft:null
	})
```
then in HeaderTitle, define a button that has callback to goBack

**Comment by pareksha** [comment] 2018-06-12 07:08
Nothing except https://stackoverflow.com/questions/43326705/how-can-we-center-title-of-react-navigation-header/44239213#44239213 worked for me

**Comment by ufolux** [comment] 2018-08-09 10:26
If you have a `headerLeft` element, this snippet will work
```
navigationOptions: ({ navigation }) => {
    let headerRight = <View />
    const noHeaderRightScenes = [
        'Demo1Scene', 'Demo2Scene', 'Demo2Scene'
    ]
    if (noHeaderRightScenes.includes(navigation.state.routeName)) {
        headerRight = null
    }
    return {
      ...
      headerTitleStyle: {
        flex: 1,
        textAlign: 'center',
      },
      headerRight: headerRight,
      headerLeft: (<NavBackButton onPress={() => AppNavigator.goBack()}/>)
    }
  },
  ...
}
```

**Comment by sorrat** [comment] 2018-09-17 12:15
Another [solution](https://stackoverflow.com/a/52343933/853876):
```js
createStackNavigator({
   { ... // your screens},
   { ...,
     headerLayoutPreset: 'center' // default is 'left'
   })
```

**Comment by rodrigolabs** [comment] 2018-10-19 18:11
Thanks, @sorrat **BEST SOLUTION EVER!**
I was used to add an empty `<View />` to headerRight as mentioned above. But this is the best way.

**Comment by kenoliver** [comment] 2018-10-25 14:22
This worked for me:
static navigationOptions = ({ navigation }) => ({
    headerTitle: 'Title',
    headerTitleContainerStyle:{
      justifyContent:"center"
    }
  })

**Comment by hussain-t** [comment] 2018-11-11 18:36
I have encountered this issue on Android devices. After searching for a while, there were many suggestions to use `alignSelf: 'center'`. However it wasn't fixed with it. But I was able to fix it by `textAlign: 'center' and flex: 1`

You could specify the navigationOptions in your component:

`static navigationOptions = {
    headerTitleStyle: { textAlign: 'center', flex: 1 },
};`

I hope this should work:-)

[You could find my answer posted on StackOverFlow](https://stackoverflow.com/questions/49626664/how-to-use-the-recact-navigation-to-center-head-headings/53251882#53251882)

**Comment by brentvatne** [comment] 2018-11-11 18:45
@hussain-t - use the solution that @sorrat mentioned above, `headerLayoutPreset: 'center'`
