### ISSUE TITLE
When using DrawerNavigator and connecting to redux the store gets cleared when the drawer opens

### ISSUE THREAD

**Issue by rmevans9** [react-community/react-navigation#246] opened 2017-02-09 00:47 UTC
Today I was starting to put together navigation in a app I am beginning working on and wanted to use a drawer. In addition I want to keep the nav state in my redux store. After setting up what I think should be a working drawer navigation I noticed that when I slide open the drawer menu the reducer ends up returning null for its state which then exceptions out complaining that it can't find index on the navigation state object (which is true because the navigation state object is now null). I was able to put together a simple example here:

https://github.com/rmevans9/react-navigation-drawer-redux-test/blob/master/index.ios.js

If you run this and just slide out the drawer you will get a RSOD complaining about the index. I did a little bit of digging in the code and found that the null is being returned from here:

https://github.com/react-community/react-navigation/blob/master/src/routers/TabRouter.js#L158

I am still trying to learn the ins and outs of how React Navigation internals work so I am not sure if a null return is valid (or why it would be valid... typically if you don't want to change state then you return the current state). I am planning to dig more into this tomorrow but wanted to post this up here and see if anyone could either point out where I messed up in my example or if this is actually a bug in React Navigation.

**Comment by rmevans9** [comment] 2017-02-09 12:56
So digging into why this issue shows in a redux setup but does not if using the internal state management I came across this bit of code:

```
dispatch = (action: NavigationAction) => {
    const { state } = this;
    if (!this._isStateful()) {
        return false;
    }
    const nav = Component.router.getStateForAction(action, state.nav);

    if (nav && nav !== state.nav) {
        if (console.group) {
            console.group('Navigation Dispatch: ');
            console.log('Action: ', action);
            console.log('New State: ', nav);
            console.log('Last State: ', state.nav);
            console.groupEnd();
        } else {
            console.log('Navigation Dispatch: ', { action, newState: nav, lastState: state.nav });
        }
        this.setState({ nav });
        return true;
    }
    
    return false;
};
```
from: https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L132

Looking at how it only updated the actual state if the `getStateForAction` returned a value I tried that in a redux reducer that basically just calls the `getStateForAction` method and only returns the updated state if a state is returned:

```
function navWorkaroundReducer(action, state) {
    const newState = {...}.getStateForAction(action, state);

    if (newState) {
        return newState;
    }

    return state;
}
```

And it worked. So the way I see it is there are two options:

1. Update the documentation for redux integration calling this out
2. Stop returning null in getStateForAction (which might break things when not using Redux...)

Thoughts?

**Comment by satya164** [comment] 2017-02-13 12:07
What we discussed in past was returning an object like `{ state, hasChanged }` or similar instead of returning null. Maybe we could do that.

**Comment by rmevans9** [comment] 2017-02-13 12:09
That would work - doing that would allow us to setup the reducer to always just return `{...}.getStateForAction(action, state).state` which I think I like better then having to do the workaround I suggest above.

**Comment by RobertSheaO** [comment] 2017-02-17 22:52
Just ran into this issue today, using `1.0.0-beta.3`, has this been fixed? I'm gonna upgrade to `1.0.0-beta.5` and try it out

**Comment by rmevans9** [comment] 2017-02-17 23:19
Sorry for the examples arguments being switched, wasn't thinking when I put it up... I have it in its own function in my code and I do the switching of the args when I call that function. But you are correct, it hasn't been fixed yet but this work around is working pretty well right now.

**Comment by RobertSheaO** [comment] 2017-02-17 23:36
I simplified it even more:

`return AppRoutes.router.getStateForAction(action, state) || state`

You can reassign state if you're planning on modifying it, which I'm sure you are, since it's a reduced after all!

`state = AppRoutes.router.getStateForAction(action, state) || state`

**Comment by spencercarli** [comment] 2017-08-17 19:16
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Closed by spencercarli** 2017-08-17 19:16 UTC

**Comment by cayodonatti** [comment] 2018-02-26 12:46
Same problem, 1.2 version. Redux store is reset when I open the drawer, crashes my app main page.

**Comment by mav-erick** [comment] 2018-03-06 18:47
@cayodonatti I had the same issue, but the solution above worked for me.

**Comment by rebirthtobi** [comment] 2018-03-20 22:01
Help out here, i discover that my state is mutating in when i use redux with react navigation. please help on this.

```
import Routes from './../Navigation/Routes'
import { NavigationActions } from 'react-navigation'

const initialState = Routes.router.getStateForAction(NavigationActions.init())

const navReducer = (state = initialState, action) => {
  const nextState = Routes.router.getStateForAction(action, {...state})
  return nextState || state
}
export default navReducer
```

**Comment by brentvatne** [comment] 2018-03-22 21:09
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
