### ISSUE TITLE
Bad Drawer performance on Android?

### ISSUE THREAD

**Issue by baba43** [react-community/react-navigation#1395] opened 2017-05-05 14:09 UTC
After upgrading to `1.0.0-beta.9` my Drawer doesn't feel smooth anymore. It looks like a laggy transition whether using it with a toggle button or swipe gesture.

I have started my project with the following versions:
```
"react": "16.0.0-alpha.6",
"react-native": "0.43.4",
"react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"
```
After upgrading to `1.0.0-beta.9` and migrating the breaking changes I find these performance issues on different projects. I have also created a minimal test project with a very simple Drawer to reproduce these issues.

I'm not sure where this issues come from but hopefully someone can reproduce this issues and we can track them down.  Right now my apps feel like webapps.

**Comment by matthamil** [comment] 2017-05-05 15:01
Is it still laggy if you disable remote debugging?

**Comment by baba43** [comment] 2017-05-05 15:02
Yes.

**Comment by baba43** [comment] 2017-05-07 14:53
Found out that #8c9a626 caused this issues.

**Comment by DanielMSchmidt** [comment] 2017-05-07 15:25
I am currently investigating this, feel free to help me with this :)

**Comment by ramsestom** [comment] 2017-05-10 23:21
an update of package.json to use react-native-drawer-layout-polyfill 1.3.0 should fix it (at least it did for me)

**Comment by Jacse** [comment] 2017-05-21 07:12
Most likely this was caused by a bug in `react-native-drawer-layout-polyfill` which loaded the Javascript implementation for Android instead of the native one. Was fixed in `1.3.0`.

**Comment by spencercarli** [comment] 2017-08-30 01:20
Is this still an issue in the latest release?

**Comment by baba43** [comment] 2017-08-30 05:55
For me it seems fine with the latest version.

Thanks you all for your efforts.

**Comment by vonovak** [comment] 2017-10-08 15:01
for me it works fine on both platforms

**Comment by vonovak** [comment] 2017-10-19 22:08
Given there are 2 people reporting this works well, I'm closing this. Fell free to reopen.

**Closed by vonovak** 2017-10-19 22:08 UTC
Labels: Status: Needs More Info, Type: Bug

**Comment by evanjmg** [comment] 2018-03-20 17:52
On android 5.0.0 - the performance is really bad - freezes or crashes app -  I'm not rendering anything else other than opening

**Comment by vonovak** [comment] 2018-03-20 17:53
@evanjmg if you have a problem, please report an issue along with a reproduction. thanks.
