### ISSUE TITLE
Emulate identical animation to React Native's old Navigation component?

### ISSUE THREAD

**Issue by robcalcroft** [react-community/react-navigation#1567] opened 2017-05-17 20:45 UTC
### Current Behavior
The current iOS style scene transition doesn't look very neat when compared to the old Navigation component. The header text seems to arrive before the main body and the shadowing on the left hand edge is a little much.

### Expected Behavior
Is there a way to have the same animation as the old Navigation component to make it look more like the native iOS animation?

Thanks 😄

**Comment by spencercarli** [comment] 2017-08-16 01:56
Duplicate of #729

**Closed by spencercarli** 2017-08-16 01:56 UTC
