### ISSUE TITLE
v1.0.0-beta.22 tabBarIcon does not work

### ISSUE THREAD

**Issue by antakov** [react-community/react-navigation#3155] opened 2017-12-19 08:59 UTC
This configuration gives an invisible icons in tabbar. With beta 13 it works properly. With beta version 14 and later it doesn't work.

ProfileTab: {
      screen: ProfileStack,
      path: '/profile',
      navigationOptions: {
        tabBarIcon: ({ tintColor, focused }) => (
          <Icon name ='untitled-3-11' size={24} color={'#000'} style={{color: tintColor }}/>
        )
      },
    },

| react-navigation  1.0.0-beta.22
| react-native 0.44.3
| node 6.10.3
| npm 3.10.10

**Comment by kelset** [comment] 2017-12-19 09:15
Duplicate of https://github.com/react-community/react-navigation/issues/2805

**Closed by kelset** 2017-12-19 09:15 UTC
