### ISSUE TITLE
Nested TabNavigator is buggy

### ISSUE THREAD

**Issue by BowgartField** [react-community/react-navigation#3101] opened 2017-12-09 21:20 UTC
Hello,
When you use a TabNavigator in a other TabNavigator (nested) the second TabNavigator randomly stop to work. 
The tabNavigator buttons doesn't load the new screen and swipe left or swipe right are disable.
Also the screen content isn't loading randmoly with no particular reasons.

I try to restart packager and reload the app but nothing works.
The only solution that I found to continue to work is to add the `swipeEnabled:false` in TabNavigator's options, but it's not working all time. Sometimes 'true' is working but somethings 'false' works.

[Video link](https://drive.google.com/open?id=1wtD0LjPutU2E5pFhrxubI5GGxWQ-M-0_)

Environment:
react: 16.0.0-beta.5
react-native: 0.49.5
react-navigation: 1.0.0-beta.21

**Comment by kelset** [comment] 2017-12-10 12:26
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-10 12:26 UTC
