### ISSUE TITLE
When using TabNavigation in combination with StackNavigation the FlatList loads slower on navigation between screens

### ISSUE THREAD

**Issue by florinpop17** [react-community/react-navigation#1898] opened 2017-06-16 08:08 UTC
### Current Behavior
I'm currently having two types of navigation in my app: StackNavigation and TabNavigation.
The TabNavigation has 5 screens, and one of it contains a StackNavigation with 3 screens.

The StackNavigation screens 1 and 2 contain a list of data which is displayed with FlatList. The problem that I have is that when I transition from screen 1 to screen 2, the FlatList is not "pre-rendered", and you can see a delay.

This only happens when I export the Tabs. If I only export the StackNavigator it works fast and the list is already there when you switch between screens.

### Expected Behavior
I'd like to be able to have also the TabNavigation and the transition to be smooth between pages.

### Code:
```
const StackScreen = StackNavigator({
    // Contains a list displayed with FlatList
    ScreenOne: {
        screen: ScreenOne,
        navigationOptions: {
            title: 'ScreenOne'
        }
    },
    // Contains another list displayed with FlatList
    ScreenTwo: {
        screen: ScreenTwo,
        navigationOptions: {
            title: 'ScreenTwo'
        }
    },
    ScreenThree: {
        screen: ScreenThree,
        navigationOptions: {
            title: 'ScreenThree'
        }
    }
});

const Tabs = TabNavigator({
    // This tab holds the StackNavigator
    Tab1: {
        screen: StackScreen,
        navigationOptions: {
            title: 'StackScreen'
        }
    },
    Tab2: {
        screen: Tab2,
        navigationOptions: {
            title: 'Tab2'
        }
    },
    Tab3: {
        screen: Tab3,
        navigationOptions: {
            title: 'Tab3'
        }
    },
    Tab4: {
        screen: Tab4,
        navigationOptions: {
            title: 'Tab4'
        }
    },
    Tab5: {
        screen: Tab5,
        navigationOptions: {
            title: 'Tab5'
        }
    }
});

export default Tabs;
```
When I do `export default StackScreen`, everything works well... 

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.0
| node             | 8.0.0
| npm or yarn      | 0.24.5

Any suggestions on what I'm doing wrong and how can I get around this bug?

**Comment by jcaspian** [comment] 2017-06-19 09:26
Have you tried using StackNavigator as the root and wrap TabNavigator in it?

```jsx
const Tabs = TabNavigator({
  Tab1: { screen: ScreenOne },
  Tab2: { screen: Tab2 },
  Tab3: { screen: Tab3 },
  Tab4: { screen: Tab4 },
  Tab5: { screen: Tab5 },
})

const App = StackNavigator({
  Tabs: { screen: Tabs },
  ScreenTwo: { screen: ScreenTwo },
  ScreenThree: { screen: ScreenThree },
})
```

I think wrapping another Navigator in TabNavigator is the cause of your.
TabNavigator has to render all the screens all the time when it is active.
It also has to handle swipe gesture to switch between screens.

**Comment by florinpop17** [comment] 2017-06-19 09:49
@jcaspian The problem is that I need to have the tabs on all my screens. This is why I have my TabNavigator wrapping the StackNavigator.

**Comment by kanzitelli** [comment] 2017-06-28 20:35
@florinpop17 hey there! I have just faced the same behavior with FlatList in StackNavigator that is within the TabNavigator. My problem was that I had `removeClippedSubviews={true}` as prop for FlatList. So I removed it and wrapped each element of FlatList with `React.PureComponent` due to [react-native#13649](https://github.com/facebook/react-native/issues/13649).

**Comment by NikiLee2016** [comment] 2017-08-07 03:23
I was troubled by the same question right now. Is this question solved or not ?

**Comment by Balasnest** [comment] 2017-10-07 08:58
I'm also exactly experiencing an issue with this. Is it solved ? If I ON the "Remote JS Debugging" it works smoothly. But when its OFF, navigation flow gets slow down. Please anyone help me out on this.

**Comment by Balasnest** [comment] 2017-10-09 04:51
Its working by wrapping the renderItem method outside of the component and imported the listItem.

**Comment by kelset** [comment] 2017-11-12 11:22
Pinging OP @florinpop17  since this issue has not been active for a while, and it's related to an old version of the lib. Moreover I suggest you read this for [issues related to performances](https://github.com/react-community/react-navigation#my-app-is-really-slow).

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment] 2017-11-19 10:05
Hi there @florinpop17 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-11-19 10:05 UTC
Labels: 7 days countdown, bug

**Comment by jeffreymendez1993** [comment] 2018-02-15 14:30
Remote debugging on perf is great but when its off it suffers o n tab transitions. I lose about 30 fps.
