### ISSUE TITLE
Tabnavigator issue -- when back quickly from the second tab of tabnavigation

### ISSUE THREAD

**Issue by WeIio** [react-community/react-navigation#2120] opened 2017-07-11 09:39 UTC
Back to previous screen immediately from the second tab of tabnavigator after slide in it,stacknavigator will rerender it, and no parameters will be passed to it. so tabnavigator will fail due to lack of some parameters.
I think this is caused by the second tab haven't complete load yet,  if back ,it will be crashed.
The error like this:
![image](https://user-images.githubusercontent.com/25290093/28062243-dfcdb44e-665f-11e7-83d8-8b516b832d56.png)

Can I get when tabnavigator  load finished?Thanks in advance
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.0
| node             | 8.1.3
| npm or yarn      | 4.6.1

**Comment by adrienthiery** [comment] 2017-07-12 20:47
Hi @WeIio ,

could you provide a bit more of your code (structure of your routes, how do you nest the TabNavigator and Stacknavigator, etc.) please?

Or provide a https://snack.expo.io/ example reproducing it (ex: https://snack.expo.io/H1K3qbNS-) ?

**Comment by WeIio** [comment] 2017-07-13 06:02
@adrienthiery 
Certainly! My code as below:
===
TabNavigator
```
const PayAndReceive =TabNavigator({
    Receive: {screen: Receive},
    Payment: {screen: Payment},
  },
  {
      tabBarOptions: IsAndroid?androidTabBarOptions:iosTabBarOptions,
      tabBarPosition:'top',
      swipeEnabled:true,
      lazy:false,
      backBehavior: 'initialRoute',
      initialRoute:'Receive'
  }
);
```
====
Root structure
```
const IndexRoute =StackNavigator({
    Index: {screen: Index},
    FirstPage: {screen: FirstPage},
    Record:{screen: Record},
    PayAndReceive:{screen:PayAndReceive,navigationOptions:({navigation}) => {
        return{
            title:  navigation.state.params.cointype + ' trade',
            headerLeft:<TouchableOpacity
                onPress={() => {
                    navigation.goBack();
                    navigation.state.params.getTotalFromDB();
                }}
                style={{paddingLeft:10}}>
              <SimpleLineIcons name="arrow-left" size={18} color='#ffffff'/>
            </TouchableOpacity>,
            headerTitleStyle: {
                color: '#ffffff',
                alignSelf: 'center',
                fontWeight: '500',
            },
            headerStyle:{backgroundColor:'#393a3f'},
            headerRight: <TouchableOpacity
                onPress={() => navigation.navigate('Record',{parentParams:navigation.state.params})}><Text style={{color:'white',fontSize: 16,paddingRight:10}}>交易记录</Text></TouchableOpacity>,
        }
    }},
}, {
    // headerMode: 'screen',
    initialRouteName:'Index',
    // initialRouteParams: {},
});
```
That's it! Please give me some ideas,thanks!

**Comment by adrienthiery** [comment] 2017-07-13 13:24
I reproduced your setup (I think) here: https://snack.expo.io/S1m97lSSb

But I can't manage to reproduce the error (I'm trying on Android)... Can you? 

Is it on iOs/Android/both ? 

Eventually, do you think you could take a video of it (https://stackoverflow.com/questions/25797990/capture-ios-simulator-video-for-app-preview) ?

**Comment by WeIio** [comment] 2017-07-14 01:09
@adrienthiery 
I have checked https://snack.expo.io/S1m97lSSb. I think it's performace is so bad that it cannot reproduce my steps so well. 
Additionally,maybe I need to review my code,  check whether any bugs was left.
Anyway , thanks for your help!

**Comment by kelset** [comment] 2017-11-25 08:44
Pinging OP @WeIio since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by mc-tracker** [comment] 2017-11-27 03:22
@kelset Previously , I used `ScrollView` to implement tabs, now I used `drawerNavigator` instead of it and no error occurs anymore. so please feel free to close it

**Comment by WeIio** [comment] 2017-11-27 03:24
May be I need to use this account to reply, haha ,sorry about that
@kelset Previously , I used ScrollView to implement tabs, now I used drawerNavigator instead of it and no error occurs anymore. so please feel free to close it

**Closed** 2017-11-27 10:04 UTC
Labels: 7 days countdown, bug
