### ISSUE TITLE
Back arrow is invisible when the iOS flight-mode is active

### ISSUE THREAD

**Issue by markusguenther** [react-community/react-navigation#555] opened 2017-03-02 21:27 UTC
I found a strange bug and I am not sure why this happens.
First, I thought it is a problem with my app, but I tried it now also with the playground example and it is the same.

When you enable the flight mode on iOS and only on iOS (my Android phones worked) you can not see the back arrow in the navigation header anymore.

But just the icon is missing. If I have also a back title, you can see just the title.

![img_3052](https://cloud.githubusercontent.com/assets/1014126/23527737/67b0aefa-ff97-11e6-8661-01ee7f154093.PNG)
![img_3054](https://cloud.githubusercontent.com/assets/1014126/23527745/6f22dc26-ff97-11e6-9d29-dce8e8f76ab6.PNG)

**Comment by matthamil** [comment] 2017-03-03 02:59
I could not reproduce this in iOS 10.2 iPhone 6 emulator. What iOS version and iPhone model are you using?

**Comment by markusguenther** [comment] 2017-03-03 09:03
I used an iPhoen 6S with latest stable iOS and in the simulator, I also have not this problem.

**Comment by jpaas** [comment] 2017-03-29 15:57
I am seeing this problem with a release build uploaded to Apple testflight. Never saw it in a debug build on my phone. My phone is not in airplane mode either.

Also, on some but not all screens, the word "Back" is also missing. Even with the arrow and the text missing, if I press on the left part of the nav bar, it still navigates back.

**Comment by askarhu** [comment] 2017-08-04 18:18
My debug build is emitting similar behavior on iOS 10.3 on an iPhone 6+. It's odd that it works fine on the simulator but not on the iPhone. Also, it's random, it shows the back arrow sometimes and doesn't other times. Hope there's a fix from the team, it's been a few months since the last person commented and still it's an outstanding issue.

**Comment by markusguenther** [comment] 2017-08-09 06:24
@askarhu I guess the problem is here that it is hard to reproduce the issue. I actually did not have that issue anymore, but I can not describe whats different now in the app. No clue which side effect leads to this behavior.

**Comment by kelset** [comment] 2017-10-08 17:59
Pinging OP @markusguenther since this issue is quite old and related to an old version of the lib (and you say yourself that it doesn't happen anymore). If no answer I'll close in 7 days.

**Comment by kelset** [comment] 2017-10-14 17:53
Hi there @markusguenther,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-10-14 17:53 UTC
Labels: Type: Bug
