### ISSUE TITLE
[v1.0.0-beta9] Dynamic header titles not rendering immediately

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1329] opened 2017-05-01 12:08 UTC
After upgrading to `v1.0.0-beta9`, I noticed that all of my dynamic header titles are not rendering immediately. Params are coming through as `undefined` until the scene finishes transitioning, then they take seem to values. This looks really janky. Sample code:

```jsx
  static navigationOptions = ({ navigation }) => ({
    ...
    headerTitle: `${navigation.state.params.firstName} ${navigation.state.params.lastName}`,
    ...
  });
```

Result:

![untitled](https://cloud.githubusercontent.com/assets/4974609/25579356/2ad7e700-2e45-11e7-92ce-1758eb68668a.gif)

**Comment by cooperka** [comment] 2017-05-02 14:41
I can repro this on the NavigationExample app using `StacksOverTabs`.

1. Check out the small tweak from https://github.com/react-community/react-navigation/pull/1341 so headers are visible
2. Run the NavigationExample app
3. Open the "Stacks over Tabs" demo
4. Open various screens to see how the header behaves
    - The "Navigation" header **works** because the title is hard-coded
    - The "Profile" header has **no title** (it should show "Jordan's Profile!" like in the "Stacks in Tabs" demo, but instead it's blank)

Some combination of actions led to the exact issue in your gif where the header shows the wrong text and then refreshes after the scene finishes transitioning. I can't get it to happen again, but it seems like these issues are related.

**Comment by cooperka** [comment] 2017-05-02 14:58
I've also confirmed that it used to work on `beta.7`: https://github.com/cribspot/react-navigation/commits/better-stacks-example-beta-7

**Comment by spencercarli** [comment] 2017-08-17 19:30
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Closed by spencercarli** 2017-08-17 19:30 UTC

**Comment by sospedra** [comment] 2017-08-31 13:15
Still broken
