### ISSUE TITLE
How to show Drawer above a tab & stack navigator?

### ISSUE THREAD

**Issue by nextriot** [react-community/react-navigation#2649] opened 2017-09-26 22:42 UTC
Hi,

I have a root Tab Navigator, which has a stack navigator with a child drawer navigator there within.
I have no issue showing the drawer above the stack, but I haven't figured out how to show it above the tab bar - is there any configuration options for this?

**Comment by vonovak** [comment] 2017-10-01 20:35
it's hard to help without you sharing any of your code. can you share a runnable code that people can look at? I'm guessing the problem is that you root navigator is the tabNavigator. Then if the drawer is nested in it, it makes sense that the drawer is not shown above tabNavigator.

**Comment by kelset** [comment] 2017-12-17 15:52
Hi there @nextriot,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-12-17 15:52 UTC
Labels: question
