### ISSUE TITLE
when I return a page directly, this.props.navigation is does't work

### ISSUE THREAD

**Issue by lu79931748** [react-community/react-navigation#2380] opened 2017-08-14 03:12 UTC
in root.js
![image](https://user-images.githubusercontent.com/13619151/29256993-25d0e862-80e1-11e7-89f6-721f69b4b9ef.png)
in Index.js
![image](https://user-images.githubusercontent.com/13619151/29257038-696965e0-80e1-11e7-8cd4-234b5d71fb16.png)

**Comment by zckly** [comment] 2017-08-14 05:20
Is it because you put "dataVlaue" instead of "dataValue" in the second image?

**Comment by lu79931748** [comment] 2017-08-14 05:47
@zckly I corrected，but it does't work

**Comment by spencercarli** [comment] 2017-08-15 01:33
Can you confirm that `this.props.navigation` isn't undefined in `root.js`? When you say it doesn't work are you seeing an error or is it just not doing anything?

**Comment by lu79931748** [comment] 2017-08-15 02:14
@spencercarli that's it, in root.js I import react-navigation, and init a StackNavigator, all pages in this StackNav like this
![image](https://user-images.githubusercontent.com/13619151/29299456-4af8304e-81a1-11e7-90e9-f19565b18992.png)
in render method I return <Index dataValue={{navigation:this.props.navigation}}/> directly, but  in Index page alert the 'navigation' is undefined

**Comment by spencercarli** [comment] 2017-08-15 02:52
Can you try to put together a reproduction on [Snack](https://snack.expo.io)? Without it I'm struggling to see what the issue could be, other than the typo previously pointed out.

**Comment by lu79931748** [comment] 2017-08-15 03:23
[Index.js.zip](https://github.com/react-community/react-navigation/files/1224058/Index.js.zip)
[root.js.zip](https://github.com/react-community/react-navigation/files/1224059/root.js.zip)
@spencercarli they are my source code profile

**Comment by lu79931748** [comment] 2017-08-15 03:29
[Index.js.zip](https://github.com/react-community/react-navigation/files/1224069/Index.js.zip)
[root.js.zip](https://github.com/react-community/react-navigation/files/1224073/root.js.zip)
@spencercarli they are my source code file

**Comment by spencercarli** [comment] 2017-08-28 01:20
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:20 UTC
Labels: Type: Question
