### ISSUE TITLE
react native 

### ISSUE THREAD

**Issue by vikram24051992** [react-community/react-navigation#3109] opened 2017-12-11 11:54 UTC
i m trying to go on second page on go button pressing but i got this error
![selection_003](https://user-images.githubusercontent.com/33919712/33829904-2b184968-de98-11e7-9dfb-c292c34bf5a2.png)

**Comment by vikram24051992** [comment] 2017-12-11 11:55
this problem is in android

**Comment by kelset** [comment] 2017-12-11 12:04
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-11 12:04 UTC
