### ISSUE TITLE
react navigator re-renders all screens on tab change

### ISSUE THREAD

**Issue by Crazy-Ivan** [react-community/react-navigation#1197] opened 2017-04-24 09:51 UTC
Every time I change a tab in my app, react navigator passes a new instance of navigation object to all screens. In result, all screens are re-rendered on tab change. I'm not sure if this is an expected behavior...

**Comment by grabbou** [comment] 2017-04-24 11:33
Duplicate of #1185

**Comment by grabbou** [comment] 2017-04-24 16:31
This is actually an issue, will debug

**Comment by jamesisaac** [comment] 2017-04-24 17:54
Surely this is expected behaviour?  Navigation state has changed when the tab changes, so naturally the immutable `navigation` prop will change too.  You'd have to make a custom `componentShouldUpdate` if you want to optimise this out.

**Comment by satya164** [comment] 2017-04-24 18:07
The navigator's state changes, but the state of individual scenes don't change, so they shouldn't receive new navigation objects.

**Comment by jamesisaac** [comment] 2017-04-24 18:14
`navigation.state.index` (reflecting the currently selected tab) will have changed, won't it?  Which is enough to invalidate the whole `navigation` prop.

**Closed** 2017-04-26 11:36 UTC

**Comment by Rebsos** [comment] 2017-05-14 16:31
The screens usually do not rerender on tab change, if everything is set up correctly (This also applies for StackNavigator). Just tested it.

But today my tabs re-rendered suddenly. The problem was that i passed in a screenProp *Object*, the same way like the docs suggest.

`<AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} *screenProps={{...}}* />
`

The object inside die screenProps will be created on every navigation change, this triggers all screens. If you pass in something that doesn't change e.g. screenProps={1}, the screens won't be re-rendered.

**Comment by dstollie** [comment] 2017-10-18 14:15
@Rebsos We're also struggling with the same issue. Is there any progress in this bug or have you found a fix for it?

**Comment by dstollie** [comment] 2017-10-18 14:40
Because we had to go on with our lives we found a hacky way to fix this issue :). If you are also struggling with the issue because it is not yet resolved. Here you go:

```javascript
        const stringifiedObject = JSON.stringify(object);
 
         return (
             <AppNavigator
                 //..
                 screenProps={stringifiedObject}
             />
         );
```

And when you want to do something with the object

```javascript
const object = JSON.parse(stringifiedObject)
```

**Comment by Rebsos** [comment] 2017-10-18 14:47
Yes, I used a selector for the screenProps.

Before I had something like this:

`<AppNavigator navigation={...} screenProps={{strings: strings}} />`

The reference / object you're passing to screenProps will always change on render no matter if 'strings' changes, so all tabs will always rerender.

Now something like this:

`const screenProps = getScreenPropsSelector(state);   //In Container`
...
`<AppNavigator navigation={...} screenProps={screenProps} />`



Your solution works also. In both cases the tabs will only rerender, when the object you're passing to screenProps changed.

**Comment by mameaplus** [comment] 2022-05-31 04:50
Let's use context API
