### ISSUE TITLE
[StackNavigator] gesturesEnabled false not working

### ISSUE THREAD

**Issue by edo1493** [react-community/react-navigation#1505] opened 2017-05-14 16:44 UTC
Hello, 

so I am trying to set this: 

```
  static navigationOptions = {
    header: null,
    gesturesEnabled:false
  };
```

on a view in order to disable gestures. If I do it on a 2nd level route, so the index of the nav is 1, everything works fine and gestures are disabled. 

When I try to do this on a 3rd route, as soon as I touch the border of the screen, the navigator brings me back to the previous. I was expecting to have the gestures disabled, but this behaviour doesn't even resemble the case where the gestures are enabled. 

I am on:
"react-navigation": "^1.0.0-beta.9",
"react-native": "^0.42.0",

**Comment by koenpunt** [comment] 2017-05-16 09:54
`gesturesEnabled` probably works better on navigator level than on screen level. 

But if understand correctly you want a single screen in the stack to have gestures disabled?

**Comment by edo1493** [comment] 2017-05-16 14:18
@koenpunt Yes. I was trying to set it up on a screen level. It's the case of ending up with 5 routes and I want the 4th and 5th to be disabled.

**Comment by huhuanming** [comment] 2017-06-04 18:18
but works for me

**Comment by AbenAllen** [comment] 2017-08-02 08:57
same problem, has any Solution?

**Comment by joshyhargreaves** [comment] 2017-08-02 10:20
I have had no issues disabling gestures for certain screens within a `StackNavigator`, when passing along `NavigationOptions` along with the screen. 

```
const AppNavigator = StackNavigator({
    MyScreen: {
      screen: MyScreen,
      navigationOptions: {
        gesturesEnabled: false
      },
    }
...
}
```

**Comment by kelset** [comment] 2017-10-28 13:17
Pinging OP @edo1493 since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment] 2017-11-04 08:36
Hi there @edo1493 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-11-04 08:36 UTC
Labels: Type: Bug

**Comment by jcxc** [comment] 2018-06-09 12:37
I have same issue for this, is the latest version solve this issue?

**Comment by brentvatne** [comment] 2018-06-09 18:36
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
