### ISSUE TITLE
Share views between Tabs

### ISSUE THREAD

**Issue by davidfloegel** [react-community/react-navigation#1116] opened 2017-04-19 10:43 UTC
Good morning,

I'm wondering what the best practice for sharing screens/views between different tabs.

For example:
I have 3 tabs: `Home`, `Users`, `Account` which all have a nested stack navigator to be able to navigate around within that tab.

I have one shared view called "Profile" which can be accessed from all 3 tabs.

The `Account` Tab has a route called `editProfile` which can be accessed from the `Profile` view.

Any input would be welcome :)

Cheers

**Comment by davidfloegel** [comment] 2017-05-09 06:15
Anyone any idea?

**Comment by jemmyphan** [comment] 2017-05-15 06:43
have you found any workaround or solution yet? @davidfloegel

**Comment by davidfloegel** [comment] 2017-05-15 06:49
well what i've done now is this @jemmyphan 

```const MainRouter = StackNavigator( {
    Main: {
        screen: TabNavigator
    }
    ViewUserProfile: {
        screen: UserProfileView
    }
}, {
    headerMode: 'screen',
    cardStyle: { 
        backgroundColor: BRAND.BRAND_WHITE
    }
} )```


So the tab navigator is nested inside a stack navigator. now you can navigate to `ViewUserProfile` from all routes.
Not sure if this is ideal but it works!

Let me know if it works for you

**Comment by jemmyphan** [comment] 2017-05-16 02:53
thanks @davidfloegel, i'm using this pattern currently.
the problem is the tab is hidden since it's not in the same stack with tabs' stackNavigator

**Comment by spencercarli** [comment] 2017-08-28 01:33
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:33 UTC
Labels: Type: Question
