### ISSUE TITLE
Add Custom Font to labelStyle is Not working

### ISSUE THREAD

**Issue by ibrahim1990** [react-community/react-navigation#3051] opened 2017-11-27 07:35 UTC
when is user custom font in react native is working fine , but is not working in react-navigation DrawerItems 
please any advice ?

**Comment by kelset** [comment] 2017-11-27 10:15
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

Maybe related to https://github.com/react-community/react-navigation/issues/374

**Closed by kelset** 2017-11-27 10:15 UTC
