### ISSUE TITLE
Tab Switch Causes White Flash w/ Lazy Mode

### ISSUE THREAD

**Issue by jasongrishkoff** [react-community/react-navigation#3042] opened 2017-11-24 06:37 UTC
As alluded to in #2829 and #1679, if I have `lazy:true` it causes a quick but noticeable white flash on the screen (revealing my background, I'm guessing?). This happens on both iOS and Android.

I've tried with a "float" header, but even that seems to briefly disappear when I navigate between tabs.  The aforementioned issues were closed without a resolution, so I'd like to re-open the issue.

I'm guessing this has something to do with the way that the components in React Native render.  I would have thought that putting `headerMode:'float'` into the mix might ensure some "visual continuity," but that doesn't seem to be the case.

**Comment by kelset** [comment] 2017-11-24 09:15
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

Moreover: 

>The aforementioned issues were closed without a resolution, so I'd like to re-open the issue.

That's not true, https://github.com/react-community/react-navigation/issues/2829 was closed by OP because he managed to fix his issue / the PR merged probably fixed it / the comments helped him understand why his code was creating that situation (can't really tell since he hasn't explained when closing).

And the other issue you link is related to Stack, so I don't see a correlation with your Tab issue.

**Closed by kelset** 2017-11-24 09:15 UTC
