### ISSUE TITLE
this.props.navigation.reset helper

### ISSUE THREAD

**Issue by tmaly1980** [react-community/react-navigation#2123] opened 2017-07-12 06:30 UTC
Any plans for a reset() helper like there's a navigate() helper in the global navigation property? Resetting screen stacks is a very common operation and it's honestly annoying that I have to write a data structure just to do a simple task like resetting stacks. It's fine if it's how it works under the hood, but I'd rather write:

`<TouchableOpacity onPress={() => this.props.navigation.reset('HomeScreen') }><Text>HOME</Text></TouchableOpacity> `

than:

```
<TouchableOpacity onPress={() => this.props.navigation.dispatch(
      NavigationActions.reset({ index: 0, actions: [ NavigationActions.navigate({ routeName: 'HomeScreen' }) ] })
    ) }><Text>HOME</Text></TouchableOpacity>


```

It can be argued that developers "should" just be able to write out the longer code version but I'm an advocate of making development libraries easy to implement so developers can focus on meeting business objectives rather than working with lower level/abstract code.

**Comment by vonovak** [comment] 2017-11-03 22:51
closing, dupe of #2897

**Closed by vonovak** 2017-11-03 22:51 UTC
Labels: Type: Feature Request
