### ISSUE TITLE
Icon (GIF) bad resolution

### ISSUE THREAD

**Issue by NickKotowski** [react-community/react-navigation#2973] opened 2017-11-13 17:40 UTC
Resolution issues for icon

We recently switched to react navigation. We are using the same icons (png for unselected/gif for selected) like in our own old custom TabBar component. In the react-navigation the resolution for the gif is quite poor, however.

The tabbar is not displaying them with their full potential. Is this on purpose? We would have hoped that we could control the quality of the gifs ourselves

Thanks in advance.

`tabBarIcon: ({ focused }) => (
          focused ?
          <Image source={require('../../images/NameOfIcon.gif')} style={styles.icon} />
          :
          <Image source={require('../../images/NameOfIcon.png')} style={styles.icon} />
        )
`

`
icon: {
    height: 35,
    width: 35,
  },
`

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.15
| react-native     | 0.49.3
| node             | v6.11.0
| npm or yarn      | v0.24.5

**Comment by wuyunqiang** [comment] 2017-11-14 08:07
android?ios?
I set gif is right.

react-navigation | ^1.0.0-beta.15
react-native | 0.49.3

**Comment by NickKotowski** [comment] 2017-11-14 08:46
tested on iOS iPhone 6S

**Comment by kelset** [comment] 2017-11-14 16:39
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-14 16:39 UTC
