### ISSUE TITLE
Question: Implementing a splash screen with React Navigation

### ISSUE THREAD

**Issue by Steviey** [react-community/react-navigation#156] opened 2017-02-02 13:24 UTC
A professional app should start with a splash screen.

There are some 3rd-party libraries on Github for React Native.

But I'm not sure using one of them would still best practice in conjunction with React Navigation.

What would be best practice to realize a splash screen in React Navigation incl. it's router etc?

I would like to involve a web view with a video as splash screen, if it's performant enough.

**Thank you.**

**Comment by mmazzarolo** [comment] 2017-02-02 14:39
Hi @Steviey, 
the simplest way to achieve a splash screen in my opinion is to have a top `StackNavigator` like the following: 
```javascript
export default StackNavigator({
  SplashScreen: { screen: SplashScreen },
  AuthScreen: { screen: AuthScreen },
  MainNavigator: { screen: MainNavigator }
}, {
  headerMode: 'screen',
  navigationOptions: {
    header: { visible: false }
  }
})
```

You should handle all your preloading/app presentation inside the `SplashScreen` component, then you can simply reset the stack redirecting the user to the screen you prefer.  
For example, inside the `SplashScreen` you can do the following:
```javascript
componentDidMount () {
  this.props.initializeApp()
}

componentDidUpdate () {
  if (this.props.isAppReady) {
    if (this.props.isLoggedIn) {
      this._navigateTo('MainNavigator')
    } else {
      this._navigateTo('AuthScreen')
    }
  }
}

_navigateTo = (routeName: string) => {
  const actionToDispatch = NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({ routeName })]
  })
  this.props.navigation.dispatch(actionToDispatch)
}
```  

I used this pattern in several apps and it worked fine so far (it's really flexible).  
However, if you need to replace the native splash screen (the one that appears when you tap on the app icon and that brings you to the app) you'll need to check for other [solutions](https://js.coach/react-native?search=splash).

**Comment by rohit-ravikoti** [comment] 2017-02-02 15:12
@mmazzarolo, noob question-- how do you pass `isLoggedIn` as a prop to the `SplashScreen` component?

**Comment by mmazzarolo** [comment] 2017-02-02 15:19
I'm using redux and have I have connected `SplashScreen` to it:  
```javascript
// @flow
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { StyleSheet, View } from 'react-native'
import { NavigationActions } from 'react-navigation'
import { getIsLoggedIn } from 'src/redux/reducers/auth'
import { getIsAppReady } from 'src/redux/reducers/app'
import actions from 'src/redux/actions'

const mapStateToProps = (state: Object) => ({
  isAppReady: getIsAppReady(state),
  isLoggedIn: getIsLoggedIn(state)
})

type Props = {
  isAppReady: boolean,
  isLoggedIn: boolean,
  initializeApp: () => void,
  navigation: any
}

@connect(mapStateToProps, actions)
export default class SplashScreen extends Component<void, Props, void> {
  static navigationOptions = {
    header: {
      visible: false
    }
  }

  componentDidMount () {
    this.props.initializeApp()
  }

  componentDidUpdate () {
    if (this.props.isAppReady) {
      if (this.props.isLoggedIn) {
        this._navigateTo('MainDrawerNavigator')
      } else {
        this._navigateTo('AuthScreen')
      }
    }
  }

  _navigateTo = (routeName: string) => {
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName })]
    })
    this.props.navigation.dispatch(resetAction)
  }

  render () {
    return (
      <View style={styles.container} />
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF'
  }
})
```  
I'm using Flow in the snippet above, so some parts of it might seem weird to you if you never used it (in e.g.: `Component<void, Props, void>`).

**Comment by rohit-ravikoti** [comment] 2017-02-02 15:53
@mmazzarolo, gotcha! Do you know if there is a way to reset the navigator without using redux?

**Comment by mmazzarolo** [comment] 2017-02-02 16:17
@rohit-ravikoti the snippet you pasted is not using redux, it is just plain `react-navigation` (which uses a pattern similar to the one used in redux).  
I'm using it right now and it is working correctly.  
  
Make sure you're using the `master` branch though!  
1. Remove your current version of react-navigation: `npm uninstall react-navigation`
2. Add the master branch one: `npm install --save https://github.com/react-community/react-navigation.git`
3. Restart the packager `npm run start -- --reset-cache`
4. Fire up your emulator

**Comment by jurgenphotek** [comment] 2017-02-08 11:28
Using the suggestion of a StackNavigator, how do you prevent a user from navigating back to a splash screen? with back button or swipe.

Also I get a left '<' button in the header of the next screen on which of course I don't want. setting 'left' is what I thought I'd do to hide it, but that doesn't appear to work

**Comment by mmazzarolo** [comment] 2017-02-08 11:41
@jurgenphotek, you should reset the Navigator instead of pushing the new screen. 

You can do a reset this way:
```javascript
_navigateTo = (routeName: string) => {
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName })]
    })
    this.props.navigation.dispatch(resetAction)
  }
```

**Comment by jurgenphotek** [comment] 2017-02-08 17:39
@mmazzarolo Thanks! 

Seems NavigationActions are not there in my version 1.0.0-beta.1 but I could just use this as the arg to dispatch
`
(clj->js {:index 0
              :type "Reset"
              :actions [{:routeName (name :welcome)
                               :type "Navigate"}]})
`

**Comment by aroth** [comment] 2017-02-11 16:15
@mmazzarolo How might you navigate back to the AuthScreen if the user signs out?

**Comment by lookeme** [comment] 2017-02-12 17:41
But how to implement Splash Screen without Redux?

**Comment by mmazzarolo** [comment] 2017-02-13 08:18
> How might you navigate back to the AuthScreen if the user signs out?  

As you might have already guessed the idea is to reset the stack to the AuthScreen (just like you do in the splash screen).  
I still have to look into doing it when you're in a sub-stack though.   

> But how to implement Splash Screen without Redux?  

It depends, are you using something else for state management (MobX maybe?) or are you simply storing the state in another component?  (Please mind that this is not related to `react-navigation`)

**Comment by coreyt808** [comment] 2017-02-16 20:50
When reseting the Navigator is there a way to not animate it?

**Comment by mmazzarolo** [comment] 2017-02-16 22:28
@coreyt808 what kind of animation would you expect from a reset action?   
If you're interested I'm using a fadeout - fadein animation that can be achieved easily using react-native's own `Animated` APIs or with `react-native-animatable`.

**Comment by coreyt808** [comment] 2017-02-16 23:51
@mmazzarolo I have a few intro screens that are shown after the Splash screen.  So when the reset action is called those screens fly by like i'm going back.  I'll look into the Animated APIs or find something else for the intro screens.  Thanks!

**Comment by mmazzarolo** [comment] 2017-02-17 09:24
@coreyt808 small protip: the simplest solution would be to use [react-native-animatable](https://github.com/oblador/react-native-animatable) and add the props `animation={'fadeIn'}` to your screens top View.  
Give it a try, it might not be the most flexible solution but is super easy to implement.

**Comment by coreyt808** [comment] 2017-02-18 06:06
@mmazzarolo thanks!  will look into it soon.

**Comment by housseindjirdeh** [comment] 2017-02-22 23:13
@mmazzarolo I had quite a few concerns about setting up an authentication as well as a splash screen and you addressed almost all of them, so thank you :)

**Comment by vzhen** [comment] 2017-02-25 01:37
@mmazzarolo 
I follow your method but there is a problem.
react-navigation version - 1.0.0-beta.5 (latest)

I have a RootNavigation as yours

```
export default StackNavigator({
  SplashScreen: { screen: SplashScreen },
  AuthScreen: { screen: AuthScreen },
  TabNavigator: { screen: TabNavigator }
}
```

then i have 3 tabs in TabNavigator, each tab has their own StackNavigator.
First, I check if user logged in in `SplashScreen`. If logged in then reset to `TabNavigator` using

```
this.props.navigation.navigate('TabNavigator')
```

The problem here, if user navigate to another route in `TabNavigator`, let say `Home Tab > Profile > Setting` after that if user press back button `<` at header it navigate to SplashScreen directly. My expected is  `Setting > Profile > HomeTab`

Another try, reset if user is logged in using
```
_navigateTo = (routeName: string) => {
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName })]
    })
    this.props.navigation.dispatch(resetAction)
  }
```

but it comes to error
`There is no route defined for key TabNavigator`

**Comment by mmazzarolo** [comment] 2017-02-25 14:10
@vzhen that sounds more like an issue of the TabNavigator and its `backBehavior`:
> backBehavior - Should the back button cause a tab switch to the initial tab? If yes, set to initialRoute, otherwise none. Defaults to initialRoute behavior.

**Comment by RobertSheaO** [comment] 2017-02-26 05:45
I have this same exact problem, StackNavigator parent (Loading Screen) that needs to reset between a DrawerNavigator (App) or a StackNavigator (Login).

**Comment by mmazzarolo** [comment] 2017-02-26 10:41
@RobertSheaO , can you provide some info on what issue are you having?  
I'm having your same setup and it is working for me:
```javascript
/* @flow */
import { DrawerNavigator, StackNavigator, TabNavigator } from 'react-navigation';
import AuthScreen from 'src/containers/AuthScreen';
import SplashScreen from 'src/containers/SplashScreen';
import ApplianceListScreen from 'src/containers/ApplianceListScreen';
import ApplianceInfoScreen from 'src/containers/ApplianceInfoScreen';
import UserProfileScreen from 'src/containers/UserProfileScreen';

import AlarmsTab from 'src/containers/ApplianceDetailScreen/AlarmsTab';
import ConfigurationTab from 'src/containers/ApplianceDetailScreen/ConfigurationTab';
import CountersTab from 'src/containers/ApplianceDetailScreen/CountersTab';
import InformationsTab from 'src/containers/ApplianceDetailScreen/InformationsTab';
import VirtualDisplayTab from 'src/containers/ApplianceDetailScreen/VirtualDisplayTab';

import Drawer from 'src/components/Drawer';
import colors from 'src/config/colors';

const ApplianceDetailTabNavigator = TabNavigator(
  {
    AlarmsTab: { screen: AlarmsTab },
    ConfigurationTab: { screen: ConfigurationTab },
    CountersTab: { screen: CountersTab },
    InformationsTab: { screen: InformationsTab },
    VirtualDisplayTab: { screen: VirtualDisplayTab },
  },
  {
    tabBarOptions: {
      activeTintColor: colors.PRIMARY,
    },
    order: ['VirtualDisplayTab', 'AlarmsTab', 'CountersTab', 'ConfigurationTab', 'InformationsTab'],
    animationEnabled: true,
    initialRouteName: 'VirtualDisplayTab',
    backBehavior: 'none',
  },
);

const ApplianceStackNavigator = StackNavigator(
  {
    ApplianceListScreen: { screen: ApplianceListScreen },
    ApplianceInfoScreen: { screen: ApplianceInfoScreen },
    ApplianceDetailTabNavigator: { screen: ApplianceDetailTabNavigator },
  },
  {
    initialRouteName: 'ApplianceListScreen',
    headerMode: 'float',
  },
);

const MainDrawerNavigator = DrawerNavigator(
  {
    ApplianceStackNavigator: { screen: ApplianceStackNavigator },
    UserProfile: { screen: StackNavigator({ UserProfileScreen: { screen: UserProfileScreen } }) },
  },
  {
    initialRouteName: 'ApplianceStackNavigator',
    headerMode: 'screen',
    contentComponent: Drawer,
  },
);

export default StackNavigator(
  {
    SplashScreen: { screen: SplashScreen },
    AuthScreen: { screen: AuthScreen },
    MainDrawerNavigator: { screen: MainDrawerNavigator },
  },
  {
    headerMode: 'screen',
    navigationOptions: {
      header: { visible: false },
    },
  },
);

```

I still need to implement the logout though (which means I haven't dispatched a rest action from a nested screen yet)

**Comment by RobertSheaO** [comment] 2017-02-26 12:03
After much testing, I've discovered that if I name the primary route of the sub navigator the same as named in the main navigator, it works for the most part when I do a reset; however, introduces other oddities.

### Works
##### MainNavigator
```JS
const routes = {
  Splash: { screen: Splash },
  Login: { screen: Login },
  App: { screen: App }
};
const options = {
  headerMode: 'none',
  cardStyle: {
    backgroundColor: white,
  },
};

const SplashRoutes = StackNavigator(routes, options);
```
##### Login
```JS
const routes = {
  Login: { screen: Home },
};
const options = {
  initialRouteName: 'Login',
  headerMode: 'none',
  cardStyle: {
    backgroundColor: white,
  },
};

const LoginRoutes = StackNavigator(routes, options);
```
### Doesn't Work
##### MainNavigator
```JS
const routes = {
  Splash: { screen: Splash },
  Login: { screen: Login },
  App: { screen: App }
};
const options = {
  headerMode: 'none',
  cardStyle: {
    backgroundColor: white,
  },
};

const SplashRoutes = StackNavigator(routes, options);
```
##### Login
```JS
const routes = {
  Home: { screen: Home },
};
const options = {
  initialRouteName: 'Home',
  headerMode: 'none',
  cardStyle: {
    backgroundColor: white,
  },
};

const LoginRoutes = StackNavigator(routes, options);
```

**Comment by vzhen** [comment] 2017-02-26 18:56
@mmazzarolo 
Sorry, i don't get you by what `backBehavior means`. I actually got TabNavgitor works but when I add  `RootNavigator` the problem come.  I recorded 2 gifts please take a look

Without SplashScreen tabs and goback work fine.
![withoutsplashscreen](https://cloud.githubusercontent.com/assets/1941395/23342556/d4ea5f50-fc97-11e6-9d41-0e2a165d7630.gif)


With SplashScreen and use `NavigationActions.reset` the error come
![withsplashscreen](https://cloud.githubusercontent.com/assets/1941395/23342588/2d39283a-fc98-11e6-9d36-16d13dae0485.gif)

**Comment by thorsonmscott** [comment] 2017-02-27 03:45
@mmazzarolo - Thanks for sharing your setup, it makes a lot of sense for my app as well.  It sounds like you're about to run into the same issue with trying to reset the root, parent stack navigator to the auth screen from a child navigator when logging out.  I found at least 4 other issues on this project repo asking for solutions, nothing with much to go off of.  I think when you dispatch the `reset` action it is being delegated to the most nested child router by default, [as mentioned here](https://reactnavigation.org/docs/routers/stack) under 'Supported Actions'.  As a result, the issue is that router can't find a route with a key of `AuthScreen`.

If you've found of have any other helpful information, it would be super helpful to many it seems, myself included!

The only thing I've found that provides the behavior I'm looking for is to dispatch a custom action and handle it in the navigation reducer.

The reducer provided in the docs:

```
const appReducer = combineReducers({
  nav: (state, action) => {
    const newState = AppNavigator.router.getStateForAction(action, state);
    return newState || state 
  },
  ...
})
```

I'm dispatching an action the looks like `{type: 'RESET_TO_ROOT', routeName: 'Authentication'}` and my reducer looks like:

```
const appReducer = combineReducers({
  nav: (state, action) => {
    switch (action.type) {
      case 'RESET_TO_ROOT':
        return {
          index: 0,
          routes: [{key: 'Init', routeName: action.routeName}]
        }
      default:
        const newState = AppNavigator.router.getStateForAction(action, state);
        return newState || state 
  },
  ...
})
```

Just forcing the navigation state into what matches when it's in the state I want it to be.  (Obviously this only works if the project uses Redux to maintain navigation state.)  It does what I want, but it definitely doesn't feel correct and it seems like there should be a more official way of communicating reset/navigation intents back up the router hierarchy.

Let us know if you have any better luck than this!  In the mean time, maybe this is helpful.

**Comment by mmazzarolo** [comment] 2017-02-27 08:40
@thorsonmscott thank you so much, it seems that this repo has a lot of interesting discussions going on in the issues :)
I'll give your code a try soon.  

Also, regarding this:
> I found at least 4 other issues on this project repo asking for solutions, nothing with much to go off of
 
I'm summoning @satya164 in the thread just to be sure that the issue gets seen soon or later 🤙

**Comment by RobertSheaO** [comment] 2017-02-28 06:32
I did some further testing, logging out my state inside my reducer and produced the following results

##### State before reset called
```
{
    "index": 0,
    "routes": [
        {
            "routeName": "Splash",
            "key": "Init"
        }
    ]
}
```

##### State after reset called (and fails)
```
{
    "index": 1,
    "routes": [
        {
            "routeName": "App",
            "key": "Init0"
        },
        {
            "type": "Navigation/NAVIGATE",
            "routeName": "App",
            "key": "id-1488263254805-0"
        }
    ]
}
```

##### Parent route config used
```JS
import Login from './index';
import Splash from './splash';
import App from '../App/connect';

const routes = {
  Splash: { screen: Splash },
  Login: { screen: Login },
  App: { screen: App },
};
const options = {
  initialRouteName: 'Splash',
  headerMode: 'none',
};

const LoginRoutes = StackNavigator(routes, options);
```

**Comment by hose314** [comment] 2017-02-28 10:10
I've moved form `ex-navigation` in assumption that issue will not appears in `react-navigation`. I  think the one options to solve is it to remove login/logout logic from `react-navigation` stacks. I 'm going to test it out and then i will provide feedback.

It will be awesome if one provide best practice how to handle splash/login/tabs logic (due to the it's common case).

**Comment by thorsonmscott** [comment] 2017-02-28 16:16
@RobertSheaO that's what I was looking at and how I landed on my current solve of forcing the state back to how it was at app launch within the reducer and handling my custom action.

Still doesn't seem right, but it's working for me for the time being.

**Comment by ronnyhartenstein** [comment] 2017-03-03 08:03
I tried another approach: real parallel navigators within a react component - selected by a Redux state "login". So the splash-screen + onboarding is a separate `StackNavigator`. And after successful login it'll replaced by a normal `DrawerNavigator`.

Here is the complete example: https://gist.github.com/ronnyhartenstein/1ef30c90f530f99430969925198d6970

**Comment by ElliottJRo** [comment] 2017-03-04 00:09
hey all heres my solution to 'RESET_TO_ROOT' in the reducer function I have a logout action that modifies the state array directly. I simply `shift()` the routes array to pop off the initial route.. pretty fragile IMO but ¯\_(ツ)_/¯ it works for now.

```js
if(action.type === Actions.LOGOUT) {
        if(state.routes.length > 1) {
          return {
            ...state,
            index: 0,
            routes: [state.routes.shift()]
          }
        } else {
          return state;
        }
      }
```

**Comment by MarcelBlockchain** [comment] 2017-04-04 19:31
any new best practices to handle splash/login/tabs logic ?

**Comment by srounce** [comment] 2017-04-19 21:40
> any new best practices to handle splash/login/tabs logic ?
Don't use StackNavigator, in short.

Use a `TabRouter` with two `Navigator`s nested one for authenticated, one for unauthenticated views. Then simply dispatch `NAVIGATE` to `auth` or `unauth`, when the user logs in/out.

Or, if you want to totally skip on the redux you can just have a root view that returns
`isUserLoggedIn ? <AuthNav ... /> : <UnauthNav ... />`

**Comment by bavuongco10** [comment] 2017-04-22 06:39
Thanks @thorsonmscott , your way work perfectly!

**Comment by grabbou** [comment] 2017-04-25 06:10
Can someone submit a PR to add that to `examples`? That would be great!

**Comment by mikhi** [comment] 2017-04-29 09:51
I agree with @grabbou. A full and working example will help allot a newbie like me.

**Comment by magician11** [comment] 2017-05-01 00:42
@grabbou @mikhi I've been playing with Expo a lot. And have integrated most of what was discussed here.

You can view a working demo and all the source code here https://github.com/magician11/expo-tests

Any feedback is welcome!

**Comment by yavorski** [comment] 2017-06-18 08:18
Hi All, 

I think I was able to successfully implement the Splash/Auth/App screens with one root TabNavigator with three `StackNavigators` nested.
This is easy to implement with `TabNavigator` since you can specify `backBehavior: 'none'` as an option. 
One downside though is I don't know to change the sliding aniamtions in the main `TabNavigator`.
Will be happy to review/comment the code:

```jsx
'use strict';

import React, { Component } from 'react';

import {
  Alert,
  AppRegistry,
  Button,
  StyleSheet,
  Text,
  View,
} from 'react-native';

import {
  StackNavigator,
  TabNavigator,
} from 'react-navigation';


class Splash extends Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    setTimeout(() => {
      requestAnimationFrame(() => {
        this.props.navigation.navigate('AuthTab');
      });
    }, 500);
  }

  render() {
    return (
      <View>
        <Text>Splash Screen</Text>
      </View>
    );
  }
}


class SplashScreen extends Component {
  static navigationOptions = {
    header: null
  }

  render() {
    return (
      <Splash navigation={this.props.navigation} />
    );
  }
}


class LoginScreen extends Component {
  login = () => {
    this.props.navigation.navigate('AppTab');
  }

  render() {
    return (
      <View>
        <Text>LoginScreen</Text>
        <Button title="login" onPress={this.login} />
      </View>
    );
  }
}


class RegisterScreen extends Component {
  render() {
    return (
      <View>
        <Text>RegisterScreen</Text>
      </View>
    );
  }
}


class HomeScreen extends Component {
  static navigationOptions = {
    title: 'Home'
  }

  render() {
    const nav = this.props.navigation;

    return (
      <View>
        <Text>This is home screen</Text>
        <Button title="Go to SkyWalker Profile" onPress={() => nav.navigate('Profile', {name: 'SKY'})} />
      </View>
    );
  }
}


class ProfileScreen extends Component {
  static navigationOptions({navigation}) {
    const state = navigation.state;
    const params = navigation.state.params;

    return {
      title: `${params.name} Profile`
    };
  }

  render() {
    const nav = this.props.navigation;
    const params = this.props.navigation.state.params;

    return (
      <View>
        <Text>{JSON.stringify(nav.state)}</Text>
        <Text>This is {params.name} profile screen</Text>
        <Button title="Go Back" onPress={() => nav.goBack()} />
      </View>
    );
  }
}


const AuthNavigator = StackNavigator({
  Login: {
    path: '/login',
    screen: LoginScreen
  },
  Register: {
    path: '/register',
    screen: RegisterScreen
  }
}, {
  initialRouteName: 'Login'
});


const AppNavigator = StackNavigator({
  Home: {
    path: '/home',
    screen: HomeScreen
  },
  Profile: {
    path: '/profile/:name',
    screen: ProfileScreen
  },
}, {
  initialRouteName: 'Home'
});


const TAB_ROUTES = {
  SplashTab: {
    screen: SplashScreen,
    navigationOptions: { title: 'Splash' }
  },
  AuthTab: {
    screen: AuthNavigator,
    navigationOptions: { title: 'Auth' }
  },
  AppTab: {
    screen: AppNavigator,
    navigationOptions: { title: 'App' }
  }
};

const TAB_NAVIGATOR_CONFIG = {
  initialRouteName: 'SplashTab',
  backBehavior: 'none',
  swipeEnabled: false,
  tabBarPosition: 'bottom',
  lazy: true,
  animationEnabled: true,
  tabBarOptions: {
    indicatorStyle: { backgroundColor: '#fff' }
  },
  navigationOptions: {
    tabBarVisible: false
  }
};

const Application = TabNavigator(TAB_ROUTES, TAB_NAVIGATOR_CONFIG);

AppRegistry.registerComponent('ReactApplication', () => Application);
```

**Comment by amitailanciano** [comment] 2017-06-25 03:35
@magician11 thanks for your example, I ended up changing things just a little bit because I had additional props triggering `componentWillUpdate`, causing an unwanted navigation reset -- hope this helps someone

```
...
  componentWillMount () {
    this.props.initializeApp(firebaseConfig)
  }

  componentDidMount () {
    this.props.verifyAuth()
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.isAppInitialized && nextProps.isLoggedIn !== this.props.isLoggedIn) {
      if (nextProps.isLoggedIn) {
        this.navigateTo('MainScreen')
      } else {
        this.navigateTo('LoginScreen')
      }
    }
  }

  navigateTo (routeName) {
    const actionToDispatch = NavigationActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({routeName})],
    })

    this.navigator.dispatch(actionToDispatch)
  }
...
```

**Comment by AunMSheikh** [comment] 2017-07-12 21:01
I am getting an issue with following code: 
` const actionToDispatch = NavigationActions.reset({
            index: 0,
            actions: NavigationActions.navigate('WelcomeScreen')
        })
        this.props.navigation.dispatch(actionToDispatch)
`

my implementation is very simple and does not yet use redux
essentially in my index file i have the following code:
`  constructor(props){
    super(props);
    this.state = {
      isAppReady: false,
    }
  }
  static navigationOptions = {
    header: null,
  }
  componentDidMount() {
    setTimeout(() => {this.setState({isAppReady: true})}, 1000)
  }
  componentDidUpdate() {
    if(this.state.isAppReady){
      this.props.navigation.navigate('Welcome')
    } 
  }

  render() {
    return(
      <SplashScreen />
    )
  }
}

const SplashNavigator = StackNavigator({
    Home: {screen: OnTheSpotRx},
    Welcome: {screen: WelcomeScreen}
});`

I wanted to replace componentDidUpate with the code
` const actionToDispatch = NavigationActions.reset({
            index: 0,
            actions: NavigationActions.navigate('WelcomeScreen')
        })
        this.props.navigation.dispatch(actionToDispatch)
`
so that after navigating to WelcomeScreen the stack resets but i get the error
![screenshot_1499893146](https://user-images.githubusercontent.com/15763563/28139830-bb8ec8f6-6723-11e7-8e47-aea97e167812.png)

Any idea what i am doing wrong?

**Comment by spencercarli** [comment] 2017-08-28 01:34
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:34 UTC
Labels: Type: Question

**Comment by VincentCATILLON** [comment] 2017-10-13 09:42
Just an answer in case of having some people reading your thead:

A splashscreen should be displayed ONLY when the app is launching, and shouldn't be handled in React Native (JS side), but should be native and closed as soon as the app is launched.

Please read this best practice: https://www.bignerdranch.com/blog/splash-screens-the-right-way/

It's exactly the same for iOS...

If you're lazy to implement it, you can use a package doing it for you:
https://www.npmjs.com/package/react-native-splashscreen-dockicon

**Comment by AunMSheikh** [comment] 2017-10-13 13:32
@VincentCATILLON  I have been preoccupied with the project and have not had time to contribute to the conversation, but you are correct, and personally I would rather create the splash screen natively (outside the navigator) instead of using a node module, that said on Android particularly on older devices, there is a white screen that displays for a split second sometimes longer between the splash screen and the time it takes the navigator to set up. That issue seems to persistent with the very basic implementation of the navigator and a splash screen.

**Comment by VincentCATILLON** [comment] 2017-10-13 14:12
I understand. 

Ofc the white screen latency is not user friendly, but it's a `react-navigation` issue which is too long to render the initial screen.

For information, and until `react-navigation` makes it faster, I added a screen (a component in real, but in screens folder) containing the splashscreen in background waiting for the navigator to be ready (`onLayout` callback used) to avoid this visual latency.

Hope this helps some other people reading this

**Comment by cyrsis** [comment] 2017-10-17 10:01
Any ways to get the splash screen with mobx?

**Comment by xilibro** [comment] 2017-11-02 03:58
@mmazzarolo hi, i want to know,  what work does this.props.initializeApp() do, thanks hhaa

**Comment by xstable** [comment] 2018-01-12 15:08
I'm also need to know, what's `this.props.initializeApp()` for. 

If I should guess, I would say, you define something like this (would be fine, if anybody can agree, or else explain why my explanation may wrong): 

You have an App.js where you init the _StackNavigator_ and this mysterious initializeApp-Function:

```JS
import SplashScreen from './components/splashScreen/SplashScreenContainer';

...

const screens = StackNavigator({
    Splash: {
        screen: (props) => <SplashScreen {...props} initializeApp={initializeApp} />,
        navigationOptions: {header: null}
    },
    Login: {
        screen: LoginContainer,
        navigationOptions: {header: null}
    },
}, {headerMode: 'screen',
    initialRouteName: 'Splash',
});

const initializeApp = (text) =>{
  // do stuff to init your App like fetching Data from API or REDUX
console.log("Hi there, I am the INITiator "+text);
}
```
You may or you may not use the spread-Operator to add all current props to your Screen like above, but ... and that's what the important Point here... you paste `initializeApp()` as a Prop to your SplashScreen-Component.

This way, you can keep your Splash-Component clean of any "initializing-Business-Logic", but have it right here in the first mainfile "app.js" (where init-business-logic is expected).

In your SplashScreenContainer, you can now execute this injected Function `initializeApp()` via `this.props.initializeApp("of the App")`.

@mmazzarolo Are my explanation right?

**Comment by mmazzarolo** [comment] 2018-01-12 16:02
> @mmazzarolo hi, i want to know, what work does this.props.initializeApp() do, thanks hhaa 

Sorry @xilibro and @xstable  for being this late, I just saw the post!  
The `this.props.initializeApp()` props does exactly what it says: It is a function that loads all the data needed by the application to works.  
Initializapp may do the following: 
- Check if a user session/token/cookie is stored in the localstorage 
- Fetch the needed data using an HTTP request/API call
- Check device informations, like the connection status or the current location

> Any ways to get the splash screen with mobx?  

@cyrsis I use MobX for most of my applications now, and I'm still following the same pattern.
Here is a super-simplified version of it: 

```javascript
@observer
export default class App extends React.Component {
  @observable isInitialized = false;
  @observable isInitializing = false;
  @observable user = null;

  @action 
  initializeApp = async () => {
    this.isInitializing = true;
    this.user = await AsyncStorage.getItem('USER');
    this.isInitalizing = false;
  }

  render() {
    if (!this.isInitialized) {
      return <SplashScreen />;
    } else if (!this.user) {
      return <routes.UnauthenticatedRouter />;
    } else {
      return <routes.AuthenticatedRouter />;
    }
  }
}
``` 

Please notice you should move all the MobX stuff in its own store since the `user` will probably be the most requested info of your entire application.

**Comment by xstable** [comment] 2018-01-12 16:31
@mmazzarolo Thank you for your answer, but sorry, your answer doesn't clarify it for me.

Does `this.props.initializeApp()` an own created Function or not? Maybe it is something which is defined in "your" App-Context or which is shipped with components you use?

Does my explanations above - with injecting function to Component to make it available in `this.props` -
 right, or completely false ?
Hope you can clarify it a bit to help me understand this.

Thanks in advance.

**Comment by mmazzarolo** [comment] 2018-01-12 16:52
@xstable I hope I'm understanding correctly what you're asking: 

>Does this.props.initializeApp() an own created Function or not? Maybe it is something which is defined in "your" App-Context or which is shipped with components you use?

Yes, `this.props.initializeApp` is a function created by me which does the stuff I wrote in the post above.  

> Does my explanations above - with injecting function to Component to make it available in this.props -
right, or completely false ?

Well, from your example it seems that you're passing the `initializeApp` function down to the `SplashScreen` component itself... but with the pattern showed in this issue the `SplashScreen` component doesn't need it at all. 
The only component that should call the `initializeApp` function is the root component which should 1. call it, 2. check its result and 3. act accordingly by rendering the right component. 

The `initializeApp` could be injected in this component in many different ways: 
- as a prop using Redux injection
- as a prop using MobX injection
- as a prop from an even higher component 
- etc

Let me know if I should explain it even further 👍

**Comment by xstable** [comment] 2018-01-12 21:45
@mmazzarolo ok, thank you for your answer. After a longer break and your explanations, I see now what you mean :)
And the hint not to pass the function via the props to the SplashContainer-Screen is also a good hint.
Thank you.

**Comment by cgomezmendez** [comment] 2018-04-10 02:53
@mmazzarolo  thanks for your code, one question when I get to home with android using home button the app is restarted and splash is launched again but when I change to another app and change back to my app it doesn't happen, should I save the state in another part or is this a bug?

**Comment by mmazzarolo** [comment] 2018-04-10 11:15
@cgomezmendez if you're pressing the home button (and not the back one) it might be an issue with your code/a bug.

**Comment by theapache64** [comment] 2018-05-13 10:56
@mmazzarolo I tried to use the method you suggested to remove the initial screen from the stack.
```javascript
_navigateTo = (routeName: string) => {
  const actionToDispatch = NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({ routeName })]
  })
  this.props.navigation.dispatch(actionToDispatch)
}
```
But am getting `_reactNavigation.NavigationActions.reset is not a function`. Am new in RN.

What am i doing wrong ?

**Comment by Maniae** [comment] 2018-05-16 13:17
@theapache64 I had this issue because I was actually using the react-navigation v2 API. Seeing that you're using Typescript, the react-navigation v2 typings are not available yet.

**Comment by theapache64** [comment] 2018-05-16 13:26
@Maniae I could fix the issue with below code. 

```javascript

     import { NavigationActions, StackActions } from 'react-navigation';
     ....

     const resetAction = StackActions.reset({
        index: 0,
        actions: [NavigationActions.navigate({ routeName: 'Home' })],
      });

      this.props.navigation.dispatch(resetAction);
```

**Comment by slorber** [comment] 2018-10-29 17:51
Hey, for me the simplest solution is to use the ref of the navigation container once it mounts to dispatch the action you need on mount based on props

```ts
import * as React from "react";
import {createSwitchNavigator, NavigationActions, NavigationContainerComponent} from 'react-navigation';
import HomeNavigation from "./home/HomeNavigation";
import AppNavigation from "./app/AppNavigation";


const MainNavigationBase = createSwitchNavigator(
  {
    HomeNavigation,
    AppNavigation,
  },
  {
    initialRouteName: "HomeNavigation",
    backBehavior: "none"
  }
);


interface MainNavigationProps {
  loggedIn: boolean,
}

const MainNavigation = ({loggedIn}: MainNavigationProps) => (
  <MainNavigationBase
    ref={(ref: NavigationContainerComponent) => {
      if (ref && loggedIn) {
        ref.dispatch(NavigationActions.navigate({routeName: "AppNavigation"}))
      }
    }}
  />
);

export default MainNavigation;
```

**Comment by DianaKoenraadt** [comment] 2019-05-03 16:59
> @Maniae I could fix the issue with below code.
> 
> ```js
>      import { NavigationActions, StackActions } from 'react-navigation';
>      ....
> 
>      const resetAction = StackActions.reset({
>         index: 0,
>         actions: [NavigationActions.navigate({ routeName: 'Home' })],
>       });
> 
>       this.props.navigation.dispatch(resetAction);
> ```

@Maniae, can you elaborate? I have this *exact* code snippet, but my splash screen is still in the stack. If I press the back-button, I arrive at my splash screen :(
