### ISSUE TITLE
Drawer item changing depending on what is focused in nested stack

### ISSUE THREAD

**Issue by Tam** [react-community/react-navigation#547] opened 2017-03-02 14:59 UTC
I'm working on an app that uses a DrawerNavigator where each route is a StackNavigator.

```jsx
const news = StackNavigator({
	News: { /* ... */ },
	Article: { /* ... */ },
}, { initialRouteName: 'News' });

const Drawer = DrawerNavigator({
	News: news
}, { 
	initialRouteName: 'News',
	contentComponent: ({ navigation, router, getLabel, renderIcon }) => {
		return (
			<View style={style.container}>
				<View style={style.drawerHeader}>
					<Image source={require('./_images/DrawerLogo.png')} />
				</View>
				<ScrollView style={style.drawerBody}>
					{navigation.state.routes.map((route, index) => {						
						const focused = navigation.state.index === index;
						const scene = { route, index, focused, tintColor: Colours.Primary };
						const icon = renderIcon(scene);
						const label = getLabel(scene);
						
						return (
							<Tap onPress={() => {
									navigation.navigate('DrawerClose');
                                    navigation.navigate(route.routeName);
								}}
							     key={`route_${index}`}>
								<View style={style.drawerButton}>
									{!!icon &&
									<Image
										source={icon}
										style={style.drawerButtonIcon} />}
									<Text style={style.drawerButtonText}>{label}</Text>
								</View>
							</Tap>
						);
					})}
				</ScrollView>
			</View>
		);
	}
});
```

*(Forgive the probably questionable code, it's my first React Native app!)*

The issue is that the item in the Drawer appears to change to whatever the active / focused route is from the stack. Is there a way to specify what route appears in the Drawer, or will I need to manually add the navigation items (as opposed to using `routes.map`)?

[![Click for Bigly Yuge GIF](https://thumbs.gfycat.com/PalatableNeedyCaecilian-size_restricted.gif)](https://gfycat.com/PalatableNeedyCaecilian)
*(This gif is a bit jumpy, click to view original)*

**Comment by RobertSheaO** [comment] 2017-03-03 20:35
Here's an example route for your Drawer Navigator

```JS
Home: {
  screen: Home,
  navigationOptions: {
    drawer: {
      label: () => <Text>Home</Text>,
    },
  },
},
```

**Comment by israel-tolu** [comment] 2017-03-06 12:24
Having the same issue even without a custom drawer , please has anyone gotten a solution to this ?

**Comment by Fenwil** [comment] 2017-03-06 18:40
@Tam I had the same issue that you have but now with the latest release`v1.0.0-beta.6` does works. Give it a try to update your `react-navigation`.

**Comment by RobertSheaO** [comment] 2017-03-06 18:49
@israel-tolu My solution isn't exclusive to a custom drawer. There are several places to specify the title of a page, which will get used for the drawer as a default if one isn't explicitly passed into the drawer when you create it.

You can set a page title in the `static navigationOptions` of a page ([docs](https://reactnavigation.org/docs/intro/headers))

```JS
class MyPage extends PureComponent {
  static navigationOptions {
    title: 'My Page Title' // can only be a string
  }
}
```

You can specify it inside the `header` section of `static navigationOptions`, which will overwrite what you have specified as `title` in the same section ([docs](https://reactnavigation.org/docs/navigators/stack))

```JS
class MyPage extends PureComponent {
  static navigationOptions {
    title: 'My Page Title', // This will be ignored
    header: {
      title: 'The Actual Page Title' // This can also be a react element
    }
  }
}
```

If you have children in a StackNavigation, you can specify the title inside the `StackNavigation` configuration like so ([docs](https://reactnavigation.org/docs/navigators/stack))

```JS
const routes = {
  Notifications: { screen: Notifications, navigationOptions: { title: 'Use This Title Instead' }  },
  Profile: { screen: Profile }, // This will use whatever is specified in `static navigationOptions`
};
const options = {
  initialRouteName: 'Profile',
};

const SettingsRoutes = StackNavigator(routes, options);
```

Of course, what you want is to specify what `label` the `DrawerNavigator` should use for the drawer, which is done like so ([docs](https://reactnavigation.org/docs/navigators/drawer))

```JS
const routes = {
  MyStackRoute: {
    screen: StackRouteConfig,
    navigationOptions: {
      drawer: {
        label: () => 'Drawer Name' // This is how you specify the drawer label
      },
    },
  }
};
const options = {
  initialRouteName: 'MyStackRoute',
};

const DrawerRoutes = DrawerNavigator(routes, options);
```

**Comment by RobertSheaO** [comment] 2017-03-07 20:41
@satya164 I see you added the bug label, is there a bug here? Seems to me the ability to force the drawer to display a certain title is built in and documented. (see the end of my previous comment)

**Comment by ferrannp** [comment] 2017-03-07 21:54
I think he might added it because actually we should not show the drawer in the nested screen...

**Comment by RobertSheaO** [comment] 2017-03-07 22:05
@ferrannp That's a matter of personal preference, and not what this issue is about. If you don't want your child views to have the drawer, then you can organize your app as such.

```
StackNavigation (parent)
-DrawerNavigation
--StackNavigation (Top Level Views)
-StackNavigation (Child Views)
```

Personally though, I'd prefer the ability to disable the drawer for certain views, but again, this issue is the drawer label changing depending on which child view of a StackNavigator you visited inside a DrawerNavigator.

**Comment by israel-tolu** [comment] 2017-03-07 22:22
I think @RobertSheaO is right, without you specifying a label in your stackNavigation, it renders the focused view, Tried it and it worked for me so I don't think its really a bug.

**Comment by grabbou** [comment] 2017-03-07 23:06
It's duplicate of #95, specifically this comment https://github.com/react-community/react-navigation/issues/95#issuecomment-276202687.

This is intended behaviour - when your item is a stack and no `label` is specified - the active screen title is used. 

Also please note that Drawer is just a Tab Navigator with a side menu instead of a tab bar. That means some of the issues / workarounds apply to both (like in this case).

**Closed by grabbou** 2017-03-07 23:06 UTC
Labels: bug

**Comment by grabbou** [comment] 2017-03-07 23:09
PS. If you find this behaviour confusing and would like to suggest a better API, please open an issue with a proposed solution (how it would work) and why you think the current behaviour is rather confusing.

**Comment by pedrojioc** [comment] 2017-08-22 14:00
@RobertSheaO I have tried to use DrawerItems, but I have not been able to set which send parameters in the component, right here <DrawerView.Items {... props} />

Thanks

**Comment by Unforgiven-wanda** [comment] 2017-12-05 08:55
@Tam Could I please trouble you for the full code of your navigator? I am struggling with some issues that your example seems to resolve

**Comment by farhad1372** [comment] 2021-06-05 07:36
just do this :
<Drawer.Screen options={{
                drawerIcon: ({ focused, color }) => {
                    let iconName;
                    focused ? iconName = 'home' : iconName = 'home-filled';
                    return <Icon name={iconName} size={23} color={color} />
                },
                drawerLabel: 'Main Page',

            }} name="main" component={MainPage} />

**Comment by farhad1372** [comment] 2021-06-05 07:37
<Drawer.Screen options={{
                drawerIcon: ({ focused, color }) => {
                    let iconName;
                    focused ? iconName = 'home' : iconName = 'home-filled';
                    return <Icon name={iconName} size={23} color={color} />
                },
                drawerLabel: 'Main Page',

            }} name="main" component={MainPage} />

**Comment by farhad1372** [comment] 2021-06-05 07:38
drawerIcon: ({ focused, color }) => {
                    let iconName;
                    focused ? iconName = 'home' : iconName = 'home-filled';
                    return <Icon name={iconName} size={23} color={color} />
                },
