### ISSUE TITLE
back to tabnavigator need to press twice with back button of android 

### ISSUE THREAD

**Issue by mc-tracker** [react-community/react-navigation#2920] opened 2017-11-07 02:06 UTC
hello, guys, I have a tabnavigator is nested to stacknavigator and  stacknavigator is nested to drawernavigator.
In tabnavigator, there is a child screen of stacknavigator on the right of tab header , let's named it with A. 
The reproduce steps like this:
slide from initial tab to the second tab and navigate to A, then go to back by press back button of device,
after the first press, it does not work , then press again, it works, but tabnavigator's tab is set to initial tab rather than the tab where we come from.
Anyone please help to resolve this issue?

**Comment by kelset** [comment] 2017-11-07 09:10
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-07 09:10 UTC

**Comment by YashGadle** [comment] 2018-04-29 08:12
I am facing this same issue:
1. Yes I am on the latest release.
2. It happens only on android (as there is no hardware back button on iOS).
3. It happens on both release and dev build.
4. It happens when debugger is both on and off.

And this only happens on hardware back button.

Can anyone help?
