### ISSUE TITLE
setParams async issue?

### ISSUE THREAD

**Issue by blackxored** [react-community/react-navigation#987] opened 2017-04-10 21:25 UTC
I wonder if there's an issue here:
I'm using a setParams workaround to set the title (it's set as a function of `navigation`), but what happens here is that even when invoking `setParams` if I do it from a nested route it doesn't reflect on the parent (when navigating back).

Here's what happens:

![](https://www.dropbox.com/s/jsdwxc3hta1zu96/Screenshot%202017-04-10%2023.22.53.png?dl=1)

SET_PARAMS action is correctly set to the relevant piece of the mutation above, however if you `console.log(this.props)` it still has the old props.

I know `setParams` is async, but shouldn't the component re-render when `navigation` changes no matter what?

EDIT: Relevant code for setting the title:

```javascript

const babyNameTitle = ({ state }) => pathOr('APP_NAME', ['params', 'title'], state);

// Somewhere else in a lifecycle method (tried most)
props.navigation.setParams({ title })
```

For clarity, what I'm trying to say it's that the component re-renders with the old props (the ones before `setParams`) and **never** re-renders with the new props.

**Comment by ericvicenti** [comment] 2017-04-13 02:04
Generally bugs are either in the router's `getStateForAction`, or they are in the view. If the bug is in the router, please write a test for it that demonstrates the broken behavior. If the issue is in the view, please describe exactly what is the `navigation.state` going into the navigator component, and when it changes.

**Comment by spencercarli** [comment] 2017-08-15 02:32
Closing this issue since it seems to be abandoned. Please post reproduction steps and we can revisit it. Thanks!

**Closed by spencercarli** 2017-08-15 02:32 UTC
