### ISSUE TITLE
TabNavigator animation issue

### ISSUE THREAD

**Issue by yiky84119** [react-community/react-navigation#2930] opened 2017-11-08 09:44 UTC
Hi:
    I got a bug, when set TabNavigator option ` { animationEnabled: false }` .

![qq20171108-162437-hd](https://user-images.githubusercontent.com/3356845/32542016-56bb69c0-c4ac-11e7-854c-bfe156cc58a5.gif)

![1](https://user-images.githubusercontent.com/3356845/32542041-64a2f242-c4ac-11e7-9c45-25955d7f97a1.jpg)

![2](https://user-images.githubusercontent.com/3356845/32542049-6980792e-c4ac-11e7-975d-ab7c3281082e.jpg)

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.7.0
  Yarn: 1.2.1
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.50.2 => 0.50.2
  react-navigation: ^1.0.0-beta.19

**Comment by kelset** [comment] 2017-11-08 10:15
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

Moreover I think it's a duplicate of https://github.com/react-community/react-navigation/issues/2914

**Comment by kelset** [comment] 2017-11-23 10:05
Check also https://github.com/react-community/react-navigation/issues/3035

**Closed by kelset** 2017-11-23 10:05 UTC
