### ISSUE TITLE
Hide Navigation Bar

### ISSUE THREAD

**Issue by chafzaalahmad** [react-community/react-navigation#803] opened 2017-03-24 10:32 UTC
How to hide top navigation bar?

**Source code:**

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    const { navigate } = this.props.navigation;
	return (
	   <View>
          onPress={() => navigate('LoginView')}
          title="Login"
        />
      </View>
      );
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
  LoginView: { screen: LoginView },
});

AppRegistry.registerComponent('SimpleApp', () => SimpleApp);

**Comment by tempestaddepvc** [comment] 2017-03-24 11:34
In the navigationOptions of HomeScreen
`static navigationOptions = {
    title: 'Welcome',
    header: {
        visible:false
    }
};`

If you want to hide the header as the default behavior, you could instead pass navigationOptions to the navigator
`const SimpleApp = StackNavigator({
Home: { screen: HomeScreen },
LoginView: { screen: LoginView },
},navigationOptions:{
header:{
visible:false
}});`

**Comment by chafzaalahmad** [comment] 2017-03-24 16:37
@tempestaddepvc  Thanks for reply. but this solution not work.

sample code:
import React from 'react';
import { AppRegistry, View, Button, Text} from 'react-native';
import { StackNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = {
    header: { visible:false },
    title: 'Welcome',
  };
  render() {
    const { navigate } = this.props.navigation;
      return (
	   <View>
        <Text>Home Screen</Text>
      </View>
      );
  }
}

const SimpleApp = StackNavigator({   
  Home: { screen: HomeScreen }
});

AppRegistry.registerComponent('ProximateRN', () => SimpleApp);

Screen shot:
[https://cl.ly/2Q1y2Q1p1h3u](url)

**Comment by sigmazen** [comment] 2017-03-24 23:26
Hi .. you also need `headerMode: 'screen'`   set in your StackNavigator:  

    const SimpleApp = StackNavigator({
        Home: { screen: HomeScreen }
      },{ 
        headerMode: 'screen' 
      }
    );

**Comment by chafzaalahmad** [comment] 2017-03-27 04:53
Thanks @sigmazen 
This solution hide navigation bar.

**Comment by jerossh** [comment] 2017-03-30 17:15
Thanks @sigmazen,
It already take whole night to hide the bar

**Comment by xiaokekeT** [comment] 2017-04-11 16:01
my route Stack
```js
const IndexRoute = TabNavigator({
  Index: { screen: Index },
  User: {
    screen: User
  }
}, {
  tabBarComponent: TabView.TabBarBottom,
  tabBarPosition: 'bottom',
  tabBarOptions: {
    activeTintColor: '#41C0E4',
    inactiveTintColor: '#9B9B9B',
    showLabel: false
  },
  // Android
  swipeEnabled: false,
  animationEnabled: false
})

const MainRoute = StackNavigator({
  Splash: { screen: Splash },
  MainTabs: { screen: IndexRoute },
  SchoolDetails: { screen: SchoolDetails }
}, {
  initialRouteName: 'Splash',
  headerMode: 'screen'
})
```

Index Page
```
class Index extends React.Component {
  static navigationOptions = {
    title: 'tab1',
    header: { visible: false },
 }
....
```

**Comment by xiaokekeT** [comment] 2017-04-11 16:19
I want to hide the head of the index page. 
But the problem is that the page will flash.

Route Stack：

```js
const IndexRoute = TabNavigator({
  Index: { screen: Index },
  User: {
    screen: User
  }
}, {
  tabBarComponent: TabView.TabBarBottom,
  tabBarPosition: 'bottom',
  tabBarOptions: {
    activeTintColor: '#41C0E4',
    inactiveTintColor: '#9B9B9B',
    showLabel: false
  },
  // Android
  swipeEnabled: false,
  animationEnabled: false
})

const MainRoute = StackNavigator({
  Splash: { screen: Splash },
  MainTabs: { screen: IndexRoute },
  SchoolDetails: { screen: SchoolDetails }
}, {
  initialRouteName: 'Splash',
  headerMode: 'screen'
})
```

Index Page:
```js
class Index extends React.Component {
  static navigationOptions = {
    header: { visible: false } // !!! Hide Header
  }
}
...
```

User Page:
```js
class User extends React.Component {
  static navigationOptions = {
    title: 'tab2'
  }
}
...
```
![kapture 2017-04-12 at 0 12 11](https://cloud.githubusercontent.com/assets/7436176/24918992/e1573548-1f14-11e7-8812-f39d249c4b0d.gif)

**Comment by grabbou** [comment] 2017-04-24 13:33
Closing as header can be hidden.

As per flashing - see: #1013

**Closed by grabbou** 2017-04-24 13:33 UTC

**Comment by guerjon** [comment] 2017-05-01 20:23
That solution it's not working any more, from the react-navigation doc: 
React Element or a function that given HeaderProps returns a React Element, to display as a header. Setting to null hides header.
`static navigationOptions = { title: 'Welcome', header: null }; hide the header`

**Comment by kamaljit-sharma** [comment] 2017-05-09 09:58
Thanks @guerjon 
Your solution is worked for me :)

**Comment by akajack** [comment] 2017-05-09 11:06
Thanks thanks thanks thanks thanks thanks @guerjon 
WORK!!!!

- "react": "16.0.0-alpha.6"
- "react-native": "^0.44.0"
- "react-navigation": "^1.0.0-beta.9"

**Comment by diegomelo182** [comment] 2017-05-15 03:01
Thanks @guerjon works for me!!!

**Comment by vandaics** [comment] 2017-06-18 06:46
headerMode `none` works for me
```
export const AppNavigator = StackNavigator({
    Splash: { screen: SplashScreen },
    Login: { screen: LoginScreen },
},{ headerMode: 'none' })
```

**Comment by karan101292** [comment] 2017-06-28 10:16
How can I make header hide/show dynamically based on my state. Refer this [StackOverflow](https://stackoverflow.com/questions/44776798/dynamically-hide-show-header-in-react-native) question.

**Comment by alperen** [comment] 2017-07-26 10:06
@guerjon  thank you. it worked for me.

**Comment by saayani** [comment] 2017-07-27 07:04
It gives an error: Objects are not valid as a React child (found: object with keys {visible}). If you meant to render a collection of children, use an array instead.

**Comment by saayani** [comment] 2017-07-27 07:14
Add this on every screen
static navigationOptions = {
		header: null
	};

**Comment by saayani** [comment] 2017-07-27 07:15
`static navigationOptions = {
		header: null // !!! Hide Header
	};`

**Comment by saayani** [comment] 2017-07-27 07:16
Add this on every screen 
`static navigationOptions = {
		header: null 
	};`

**Comment by bertugylmaz** [comment] 2017-07-27 08:36
Hi! Maybe you can solve the problem with that.
Solved my problem :]

>const SimpleApp = StackNavigator({
>    Home: { screen: HomeScreen }
> },{ 
>  headerMode: 'none' 
>  }
>);

**Comment by anckorweb** [comment] 2017-09-09 19:30
Great @sigmazen (work as global), but the solution off @guerjon it's just what I needed! Thanks guys.

**Comment by VarshaJadhav** [comment] 2017-11-21 05:48
`Onboarding: {
		screen: Onboarding,
	    // Optional: Override the `navigationOptions` for the screen
	    navigationOptions: ({navigation}) => ({
	      header: false
	    }),
	},`

This solution works for me

**Comment by rajat1saxena** [comment] 2017-11-30 17:23
How can I hide header on scroll?

**Comment by amittomar287** [comment] 2017-12-05 05:24
just use 

static navigationOptions = {
        header: null,
        title: 'Login',
    };

in any react component where you have to hide

**Comment by AlexandrWhile** [comment] 2017-12-14 17:29
@VarshaJadhav 
Thank you so much!

**Comment by pallavbakshi** [comment] 2017-12-14 20:09
Just a tip, you need to have title parameter otherwise the app will crash.

**Comment by saru2020** [comment] 2017-12-16 07:39
## This works for me:
`const App = StackNavigator({
  Home: { screen: HomeView, navigationOptions: ({navigation}) => ({ header: false })},
  About: { screen: About, navigationOptions: ({navigation}) => ({ header: false }) },
});
export default App;`

**Comment by tuanluu-agilityio** [comment] 2017-12-19 07:22
Thanks @guerjon on comment https://github.com/react-community/react-navigation/issues/803#issuecomment-298422702 , `header: null` work for me 

Set this one on each screen you need hide header:
```sh
static navigationOptions = {
  header: null,
}
```

**Comment by Muedgar** [comment] 2018-03-20 12:31
@guerjon  Thank you very much

**Comment by brentvatne** [comment] 2018-03-22 21:13
sounds like this is resolved

**Comment by brentvatne** [comment] 2018-03-22 21:13
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
