### ISSUE TITLE
Hide tabBar from stackNavigator

### ISSUE THREAD

**Issue by quangas** [react-community/react-navigation#581] opened 2017-03-05 17:33 UTC
I have a TabNavigator and within there I also have a StackNavigator. On one of the pages within the StackNavigator, I wish to hide the tabBar (visible:false) but I cannot seem to do so. Is there a way to hide tabBar in the parent TabNavigator from the child StackNavigator?

I tried the following but doesn't work:

```
const MainNavigator = TabNavigator(
  {
    Default: { 
      screen: FancyNavigator, 
    }
}
```

```
const FancyNavigator = StackNavigator({
  FancyMain: { screen: FancyMain },
  GreatPage: { 
    screen: GreatPage, 
    navigationOptions: {
      tabBar: ({ state }) => ({
        visible: false
      })
    }
  }
})

```

If i did this below, the tabBar would be hidden for the whole stack but I just need the tabBar hidden for one specific view. It seems like you can only hide it from the parent (main app) and not from the children stack.

```
const MainNavigator = TabNavigator(
  {
    Default: { 
      screen: FancyNavigator,
     navigationOptions: {
        tabBar: ({ state }) => ({
          visible: false
        })
      }
    }
}

```

**Comment by quangas** [comment] 2017-03-05 17:40
same issue as #464

**Comment by PatNeedham** [comment] 2017-03-05 18:21
```
const YourStack = StackNavigator({
    First: { screen: FirstScreen },
    Second: { screen: SecondScreen, navigationOptions: { tabBar: { visible: false } } },
    Third: { screen: ThirdScreen },
}, { mode: "card" });
```

Try passing `navigationOptions: { tabBar: { visible: false } }` to the specific page inside your StackNavigator.

**Comment by Kerumen** [comment] 2017-03-05 22:06
@PatNeedham This is not working.

I also face this problem and didn't find a solution.

**Comment by f0rr0** [comment] 2017-03-06 09:28
@quangas this is a duplicate of https://github.com/react-community/react-navigation/issues/464
I suggest you close this

**Closed** 2017-03-06 10:24 UTC

**Comment by garstikaitis** [comment] 2017-06-13 19:43
API for changing visibility has changed: Now it is `navigationOptions: tabBarVisible: false`

**Comment by gulshanzealous** [comment] 2017-07-19 14:18
i have two tabBars  - one at the top and one at the bottom. on using the following config
`tabBarVisible: false`
both the tabs hide. I want to selectively hide one tab.

**Comment by shixiaoquan** [comment] 2017-10-18 09:35
solved the problem @quangas

**tabBarVisible: false**
```
Device: {
    screen: DevicesList,
    navigationOptions: {
        title: '设备总览',
        gesturesEnabled: false,
        tabBarVisible: false,
    }
 }
```

**Comment by bvaibhav95** [comment] 2017-11-18 15:15
**Just add this into your class/component code snippet and Header will be hidden**

`static navigationOptions = { header: null }`

**Comment by Kida007** [comment] 2018-02-11 18:02
after Hiding TabBar for a Specific Screen, if we press 'hardware back button' instead of going to TabBar initial, it closes the application. Any solution ?

**Comment by brentvatne** [comment] 2018-02-21 20:25
@Kida007 - update to react-navigation@1.1.2, this is resolved

**Comment by Ronnyrr** [comment] 2018-06-04 15:20
I got DrawerNavigator > TabNavigator > StackNavigator. I want to hide the tabBar inside my stack on some screen. How can I do this?

**Comment by jpudysz** [comment] 2018-06-06 08:38
I have same question as @Ronnyrr

**Comment by jpudysz** [comment] 2018-06-06 10:24
@Ronnyrr I followed your approach but changed it a little bit to be more efficient

1. Let's say I have multiple StackNavigators inside BottomTabNavigator:

```
const BottomTabBarNavigator = createBottomTabNavigator({
       [SCREEN.NAMES.HOME_NAVIGATOR]: {
             screen: HomeNavigator,
             navigationOptions: {
                   title: 'Home',
                   // other default options
             }
       },
      // other navigators
})
```

2. Here is deffinition of HomeNavigator:
```
const HomeNavigator = createStackNavigator(getMultipleRoutes([
    SCREEN_NAMES.HOME,
    // other screens
]), STACK_CONFIG)
```

Please ignore `STACK_CONFIG` it doesn't matter here and `getMultipleRoutes` - it's my helper function to merge `SCREEN_NAMES` with `ScreenComponents`

3. Let's extend HomeNavigator to handle `tabBarVisible`:

```
HomeNavigator.navigationOptions = ({ navigation }) => {
    // get active route from navigation
    const activeRoute = navigation.state.routes[navigation.state.index]
    // here is my Javascript Map where I have key,value where key is SCREEN_NAME and value is config
    const routeDefinition = ROUTES.get(activeRoute.routeName)

    if (!routeDefinition || !routeDefinition.navigationOptions) {
        return undefined
    }

    // override tabBarVisible or other options
    return routeDefinition.navigationOptions
}

export {
    HomeNavigator
}
```

I tested it and it's working :)

**Comment by DenysYakubets** [comment] 2018-06-11 12:37
Hi there! I found answer here: [https://reactnavigation.org/docs/en/navigation-options-resolution.html](url)

```
FeedStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true;
  if (navigation.state.index > 0) {
    tabBarVisible = false;
  }

  return {
    tabBarVisible,
  };
};
```

**Comment by brentvatne** [comment] 2018-06-11 17:59
not sure why @DenysYakubets was :-1:'d, his answer is correct. https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens
