### ISSUE TITLE
props.navigation undefined

### ISSUE THREAD

**Issue by vvasiloud** [react-community/react-navigation#832] opened 2017-03-26 22:26 UTC
Hello,
I am trying React native for the first time and I want to implement the [Basic Tutorial](https://reactnavigation.org/docs/intro/) into a new react native project but I get an "this.props.navigation" undefined error when opening the main page. 

It seems that this.props doesn't have a navigation method. 

In main app page:
`const App = StackNavigator({
  Signup: { screen: SignupScreen },
});`

In page Render:
`const { navigate } = this.props.navigation;`    
` <Text onPress={() => navigate('Signup')} Sign Up</Text>`

What am I may miss in this case?

**Comment by ChristianTucker** [comment] 2017-04-09 10:07
I'm having the same problem, I went over the tutorial several times to make sure I didn't miss anything. Was wanting to give react-navigation a try since it's so popular and can't even get through the basic tutorial. 

I'm on react-native 0.43 and I'm on master, so that may have to do with the problem.

**Comment by zcsongor** [comment] 2017-04-11 16:03
Same problem as well. Did you find any solution for this?

**Comment by DarthRumata** [comment] 2017-04-14 14:33
Same problem. react-navigation@1.0.0-beta.7

**Comment by DarthRumata** [comment] 2017-04-14 15:09
Now it works. Problem was in callback for button
 onPress={this.openList}>
It wasn't binded to this.

**Comment by codemonkey1337** [comment] 2017-04-24 12:21
Same problem here (react-native 0.43.3)

**Comment by grabbou** [comment] 2017-04-24 13:56
Can anyone please post a reproduction?

**Comment by gogeta95** [comment] 2017-04-25 14:16
Had same problem, fixed it be going through this: https://reactnavigation.org/docs/intro/#Introducing-Stack-Navigator

in the last few lines:

```
const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
});

AppRegistry.registerComponent('SimpleApp', () => SimpleApp);
```

You have to use your Navigator assigned variable i.e **SimpleApp** as registry component, and first screen will be the screen added on top while creating StackNavigator.

**Comment by cif** [comment] 2017-04-27 18:57
I am able to reproduce this issue. 
```
import EditProfile from './EditProfile'
class Me extends Component {
  render() {
    return (
      <View style={styles.container}>
        <MeNavbar
          gotoView={this.props.gotoView}
          onEditPress={() => console.log(this.props)}
        />
      </View>
    )
  }
}
// THE ABOVE CONSOLE OUPUTS ONLY: 
// {"navigation":{"state":{"routeName":"Base","key":"Init"}}}
// navigate method and any other unexpected properties of the navigation prop are undefined


const Navigator = StackNavigator(
  {
    Base: { screen: Me },
    Edit: { screen: EditProfile },
  },
  {
    // headerMode:'none',
  },
)
```

**Comment by coreform** [comment] 2017-05-01 06:54
@gogeta95 's solution fixed it for me, to be clearer:

`const WhateverYouWantToCallMe = StackNavigator({
  Home: { screen: HomeScreen }, //Default entry screen
});

AppRegistry.registerComponent('SimpleApp', () => WhateverYouWantToCallMe);`

...and `SimpleApp` is (has to be) the name of your App.

**Comment by angryanatole** [comment] 2017-05-16 20:10
I actually have the same issue (even with `.registerComponent()`) when I try to make decomposition.

@gogeta95 's solution made `this.props.navigation` available only in the first class (`HomeScreen` in his example). When I place, let's say, `'TestScreen'` in the `render()` of the `HomeScreen`, my `TestScreen` doesn't receive `this.prop.navigation`.

My temporary solution is to do it with my own hands: `<TestScreen  navigation={this.props.navigation}/>`.
I am new to RN development, so I may be missing something.

**Comment by fpauer** [comment] 2017-07-12 16:26
Same problem here (react-native 0.46), (react-navigation 1.0.0-beta.11)

**Comment by nolcay** [comment] 2017-07-22 15:17
Well, I found my own fix, if you are using `this.props.navigation` in the constructor, just move that to the `componentWillMount()` function. In the constructor of a component, `this.props` is `undefined`. You can trust me, **because `console.debug()` does not lie.**

**Comment by regitasfrk97** [comment] 2017-08-09 08:05
@nolcay can you give me the example of your code with componentWillMount()?

**Comment by nolcay** [comment] 2017-08-09 11:35
@regitasfrk97 I don't remember doing it, but I seem to have abandoned that solution and just made a function that fetches stuff from the nav, if `this.props.navigation` is not undefined. Otherwise, it just returns an empty function/array/string.

    data = (key) => {
        return ("navigation" in this.props ? this.props.navigation.state.params.data[key] : [])
    }

**Comment by developDS** [comment] 2017-08-13 18:17
This worked for me.

Replace this: `onPress={this.handlePress}` with `onPress={() => this.handlePress() }`.

**Comment by MehediH** [comment] 2017-08-24 11:11
Is there any fix for this issue yet? I am still getting the same undefined error despite doing exactly as noted by the starter docs.

**Comment by dekm** [comment] 2017-08-24 21:53
I am getting this error as well and there is now this.props.navigation when I do a trace.  All my other nav functions work correctly like menu and tabs.  I have this setup with redux also.  I think my issue might be related to using Expo as there is some extra setup you have to do for redux.  Is there any work around for this?

**Comment by ianrandmckenzie** [comment] 2017-08-25 08:17
I did a straight up copy/paste of this guide up to and including the "Adding a new screen" section here:
https://reactnavigation.org/docs/intro/

I am getting this error and am completely stumped. I made my app with create-react-native-app

**Comment by oseifrimpong** [comment] 2017-09-21 12:33
Hey, guys, have anyone found the solution for this issue. I made my app with create-react-native-app. I have been on this error for 4 days.

**Comment by gowthamkumar7** [comment] 2017-09-25 13:47
It seems not working. The Issue is still open.

**Comment by kelset** [comment] 2017-09-25 14:07
I'll have a look at it this weekend, sorry guys but we have a huge workload and we are starting now to get back on track.

**Comment by frantisek-dobrota** [comment] 2017-09-28 14:34
Same problem here, cannot even get through the tutorial 👎

**Comment by kelset** [comment] 2017-09-30 19:19
Hey guys, you were right there was a mistake in the code in that page - I've submitted a PR and I'm quite sure it will be merged soon.

In the meantime, basically you need to change `export default const SimpleApp = StackNavigator({
` to `export const SimpleApp = StackNavigator({`

**Comment by GuillotJessica** [comment] 2017-10-03 09:16
@kelset still navigate of undefined

**Comment by kelset** [comment] 2017-10-03 09:40
@GuillotJessica weird.

Can you tell me if you followed the `react-native init` or the `create-react-native-app` route?

Can you copy/paste your code so I can have a look at it?

**Comment by GuillotJessica** [comment] 2017-10-03 11:20
Hello I'm using  react-native init
[image: Images intégrées 1]

 App/Components/Navigation/Navigation.js

> import { StackNavigator } from 'react-navigation';
>
> import BaseM2SScreen from "../BaseM2S";
> import BonsPlansScreen from "../BonsPlansScreen";
> import Login from "../Login";
>
> export const SimpleApp = StackNavigator({
>     BonsPlansScreen: { screen: BonsPlansScreen },
>     Login: { screen: Login }
>
> });
>
> Footer.js

import React, { Component } from 'react';
import { Container, Header, Content, Footer, FooterTab, Button, Icon,
Text, Badge } from 'native-base';
import { SimpleApp } from '../Navigation/Navigation';
export default class FooterM2S extends Component {

    render() {
        const { navigate } = this.props.navigation;
        return (
                <Footer>
                    <FooterTab customStyleProp vertical="true" >
                        <Button badge vertical
                        onPress={alert(this.props)}>
                            <Badge><Text>2</Text></Badge>
                            <Icon name="store" />
                            <Text>Commerces</Text>

                        </Button>
                        <Button
                            vertical
                            onPress={() => navigate('BonsPlansScreen')}>
                            <Icon name="euro-symbol" />
                            <Text>Bons Plans</Text>
                        </Button>
                        <Button active badge vertical disabled>
                            <Badge><Text>51</Text></Badge>
                            <Icon active name="Ajouter-au-panier" />
                            <Text>Fidelité</Text>
                        </Button>
                        <Button vertical disabled>
                            <Icon name="list" />
                            <Text>Actualités</Text>
                        </Button>
                        <Button
                            vertical
                            onPress={() => navigate('Login')}>>
                            <Icon name="person" />
                            <Text>Profil</Text>
                        </Button>
                    </FooterTab>
                </Footer>

    );

}}

BonsPlansScreen .js

> import React, { Component } from "react";
> import { Text } from 'react-native';
> import { StyleProvider, Container, Content, Header } from "native-base";
>
> import getTheme from "../../native-base-theme/components";
> import material from '../../native-base-theme/variables/material.js';
>
> import HeaderM2S from "./Header/HeaderM2S";
> import Filter from './Filter/Filter';
> import FooterM2S from "./Footer/FooterM2S";
>
>
>
> export default class BonsPlansScreen extends Component {
>     render() {
>         return (
>             <StyleProvider  style={getTheme(material)}>
>                 <Container>
>                     <Header>
>                         <Body>
>                         <Text>BonsPlansScreen</Text>
>                         </Body>
>                     </Header>
>                     <FooterM2S/>
>                 </Container>
>             </StyleProvider>
>         );
>     }
> }
>
> Thank you for helping me out

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-03 11:40 GMT+02:00 Lorenzo Sciandra <notifications@github.com>:

**Comment by kelset** [comment] 2017-10-03 11:40
Well, this code seems not the one from the tutorial 😶

Anyway, your issue I think it's related to the fact that in `Footer.js` you are trying to use the `navigation` props but the component is not "attached" to the `StackNavigator`, only `Login` and `BonsPlansScreen` are.

**Closed** 2017-10-03 14:05 UTC
Labels: Component: Docs

**Comment by GuillotJessica** [comment] 2017-10-03 14:50
But I put the const navigate= this.prop.navigate
onPress for each the component i want to navigate into
what do you mean by attach the footer?
Thanks again

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-03 16:05 GMT+02:00 Gant Laborde <notifications@github.com>:

**Comment by jackson-sandland** [comment] 2017-10-08 22:37
One solution to this issue as mentioned above, is that the context of the function calling this.props is not bound to the component. To resolve, you can try the following: 
```
class BindMe extends Component {
  constructor(props){
    super(props)
    this.bindThisFunction = this.bindThisFunction.bind(this)
  }
}
```
This should now show defined for the navigation props!

**Comment by Ishjot** [comment] 2017-10-20 06:24
I have tried to bind the function calling this.props and am still running into a similar issue.
`    constructor(props) {
        super(props)

        this._navigateTo = this._navigateTo.bind(this);
    }

    _navigateTo(pageName) {
        this.props.navigation.navigate(pageName)
    }
`

And I am calling the function later like this...
`onPress={() => this._navigateTo('PageToNavigateTo')}`

**Comment by rscharfer** [comment] 2017-10-29 10:44
@Ishjot Did you figure out how to solve the problem?  I have the exact same issue.

**Comment by Ishjot** [comment] 2017-10-29 20:09
@rscharfer yes, you need to define a StackNavigator that contains the two pages that you are trying to navigate between.

**Comment by NasarudinAbdulShukor** [comment] 2017-10-31 03:37
@Ishjot Can you elaborate on how did you define the StackNavigator? is it on `main.js` / `App.js` where people usually define the navigator(stack, drawer, tab) for their pages or inside the function `onPress`?

**Comment by Ishjot** [comment] 2017-10-31 03:40
@NasarudinAbdulShukor this should help - https://facebook.github.io/react-native/docs/navigation.html

**Comment by connorwaslo** [comment] 2017-11-04 23:32
@NasarudinAbdulShukor I still get "TypeError: undefined is not an object (evaluating 'this.props.navigation.navigate')" as an error even following the tutorial you just linked.

**Comment by randyqiu** [comment] 2017-11-19 14:03
You should pass the `navigation` prop to the screen component of navigator YOURSELF. For example:

```
import PlayerView from 'player-view';
const PlayerScreen = ({ navigation }) => (<PlayerView navigation={navigation}/>);
```

Then you will have `this.props.navigation` in your component.

**Comment by cglacet** [comment] 2017-11-20 16:57
__flow-bin__ *0.56.0*
__react__ *16.0.0*
__react-navigation__ *1.0.0-beta.19*

If you manually add a type for the Props objects that your Component is supposed to handle then it will remove the error (at least it does for me)

```javascript
type Props = { navigation: Function }
class HomeScreen extends Component<Props> {
    render() {
      const { navigate } = this.props.navigation; 
      ...
   }
}
```
This only help ignoring the problem until a real solution is found, but it's still decent if the only thing you are doing with `props` is calling the `navigation` function.

Nevertheless I guess there is a way to retrieve the actual type of Props that should be used here, but I can't find it and it seems that most people really don't care and just ignore this error.  This doesn't change much in the end because types are really just here to help you 😛.

PS, here the definition I have for React.Component: 
```javascript
declare class React$Component<Props, State = void>
```

**Comment by hugoh1995** [comment] 2017-12-20 21:02
I'm still experiencing the same issue, is this thing still not fixed? 🤒

**Comment by DiegoFelipe** [comment] 2018-01-07 04:51
I'm facing the same problem I still can't understand how to do it, I got a component with a button that needs to call another screen, I'm importing StackNavigator from react-navigation and when I try to call another screen with 'this.props.navigation.navigate('Quadros')' it says that it's not an object. I could understand, by reading this issue that my component can't see my navigation props, but I haven't figured out how to pass the navigation props in order to be able to call the screen from my custom component. It's actually a screen that render a component inside drawer and this component inside drawer call another component <- this is the one that needs to call another screen.

**Comment by GuillotJessica** [comment] 2018-01-08 09:01
show us us your code with the navigator settings

**Comment by DiegoFelipe** [comment] 2018-01-08 12:21
I could made it work, like I said I had a 'home screen' that called a 'sidebar' custom component that called a nother custom component called webservice that called another component WSBody, to make it work I did the following:

In Home screen:

I called the sidebar component this way:

`<Sidebar nav = {this.props.navigation}/>`

In my Sidebar component:

```
constructor(props) {
    super(props);
    this.state = {};
    const nav = this.props.nav; 
  }
```

still in sidebar I called the webservice component this way:

`<WebService nav = {this.props.nav}/>`

I did the same thing that I've done in sidebar in webservice, finally in WSbody I could use:

`this.props.nav.navigate('MyScreen');`

I hope it help other peoples with the same issue.

**Comment by GuillotJessica** [comment] 2018-01-08 13:02
I was thinking of something like this
```
const ModalStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    path: 'people/:name',
    screen: MyProfileScreen,
  },
});
```
from [documentation website](https://reactnavigation.org/docs/navigators/stack)
In this particular architecture, you may use the navigation props and go from Home and Profile and vice versa

**Comment by GuillotJessica** [comment] 2018-01-08 13:55
I was thinking of something like this
```
const ModalStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    path: 'people/:name',
    screen: MyProfileScreen,
  },
});
```
from [documentation website](https://reactnavigation.org/docs/navigators/stack)
In this particular architecture, you may use the navigation props and go from Home and Profile and vice versa

**Comment by GuillotJessica** [comment] 2018-01-08 13:56
but if your are using different kind of navigation like tab then you may nest them together

**Comment by EricWiener** [comment] 2018-01-23 14:55
You need to pass the navigation prop down to the component (it doesn't just magically get it). So if you are trying to navigate from a child component, you would need to do something like: 

```
//parent Component
export default class Parent extends Component{
  //...
  render(){
    const {navigate} = this.props.navigation; //recieves prop from StackNavigator
    return(
      //...
      <Child navigate={navigation}>
      //...
    );
  }
}

//child Component
export default class Child extends Component{
  //...
  render(){
    const {navigate} = this.props.navigation; //this is the navigation prop passed from the prop
    return(
      //...
      <Button onPress={()=>navigate('Home')}> 
      //...
    );
  }
}
```

**Comment by uanthwal** [comment] 2018-03-08 19:08
@EricWiener : I tried your solution but no luck. May be I am missing something. Please help me out.
Here's my code:
LoginScreen.js
```
export default class LoginScreen extends Component {
	constructor(props) {
		super(props);
	}
	render() {
		return (
			<SignupSection navigate={this.props.navigation} />
		);
	}
}
```

SignupSection.js
```
export default class SignupSection extends Component {
	constructor(props) {
		super(props);
	}
	render() {
		const {navigate} = this.props.navigation; -- tried printing this it shows the data but on button click (added below: Create account), it says cannot find variable navigate
		return(
			<TouchableOpacity style={styles.button}
			onPress={this.props.navigation.navigate('signupScreen')} >
				{
					<Text style={styles.text}>Create account</Text>
				}
			</TouchableOpacity>
		);
	}
}

```
AppNavigation.js
```
// login stack
const LoginStack = StackNavigator({
	loginScreen: { screen: LoginScreen },
	signupScreen: { screen: SignupScreen }
}, {
	headerMode: 'float',
	navigationOptions: {
	headerStyle: {backgroundColor: '#E73536'},
	headerTintColor: 'white'
}
})

const PrimaryNav = StackNavigator({
	loginStack: { screen: LoginStack }
	}, {
	// Default config for all screens
	headerMode: 'none',
	title: 'Main',
	initialRouteName: 'loginStack',
	transitionConfig: noTransitionConfig
})

export default PrimaryNav
```

One thing I have noticed is if I move the sign up screen content to Loginscreen then the navigation is working but want to know the solution where we have nested navigations.

**Comment by brentvatne** [comment] 2018-03-09 19:20
hi there. please create a new issue and follow the issue template if this problem persists for you. thank you!
