### ISSUE TITLE
Drawer Navigator not opening over a Mapview on Android

### ISSUE THREAD

**Issue by alanselo** [react-community/react-navigation#2791] opened 2017-10-19 16:12 UTC
### Issue Description
Hi everyone, 

I set a component (that uses a Mapview) as the main screen for a Drawer navigator like this: 

```
const Drawer = DrawerNavigator({
  mapDrawer:{screen:MapViewerScreen},
  profile:{
    screen: StackNavigator({
      profileReview: { screen: ProfileReview },
      profileInfo: { screen: ProfileInfo },
      editVehicule: { screen: EditVehicule },
      editPassword: { screen: EditPassword }
    })
  }
},{
  navigationOptions: ({navigation}) => ({
    drawerLockMode: 'locked-closed'
  })
})
```

Inside the the MapViewerScreen theres a button that opens the drawer:

```
class MapViewerScreen extends Component{
  render(){
    return(
      <View  style={{flex:1}}>
        <View style={styles.toggleMenu}>
        <TouchableOpacity onPress={() => { this.props.navigation.navigate('DrawerOpen');} }>
          <Image
          style={{width: 20, height:20}}
          source={require('../src/img/toggle-menu.png')}/>
        </TouchableOpacity>
      </View>
      <View style={{flex:1}}>
        <MapViewer/>
      </View>
    </View>
    )
  }
}
```

It works very well in IOS but on Android the drawer doesn't open although I get a black background over the map as you can see in this screenshot:

![whatsapp image 2017-10-18 at 14 53 59](https://user-images.githubusercontent.com/4858209/31740007-82225fda-b415-11e7-9ae8-c5f2a74aacdc.jpeg)

Any guess? Thanks.

**Comment by kelset** [comment] 2017-10-20 15:50
This to me looks like a duplicate of #2728 (so I'll close this one). If you could provide an [expo snack](https://snack.expo.io/) of the issue it would be really helpful.

**Closed by kelset** 2017-10-20 15:50 UTC
