### ISSUE TITLE
Documentation at `https://reactnavigation.org/docs/` does not reflect latest stable release

### ISSUE THREAD

**Issue by samijaber** [react-community/react-navigation#1128] opened 2017-04-20 02:40 UTC
I have been trying to add labels to my`TabNavigator` screens for some time, but to no avail. The [docs](https://reactnavigation.org/docs/navigators/tab) tell me to set it using `navigationOptions.tabBarLabel`. After looking into the source code of I realized that `TabView._getLabel` changed:

```js
// 1.0.0-beta7
  _getLabel = ({ focused, route, tintColor }: TabScene) => {
    const tabBar = this.props.router.getScreenConfig(
      this.props.childNavigationProps[route.key],
      'tabBar'
    );

    if (tabBar && tabBar.label) {
      return typeof tabBar.label === 'function'
        ? tabBar.label({ tintColor, focused })
        : tabBar.label;
    }

// master (and documentation)
  _getLabel = ({ focused, route, tintColor }: TabScene) => {
    const options = this.props.router.getScreenOptions(
      this.props.childNavigationProps[route.key],
      this.props.screenProps || {}
    );

    if (options.tabBarLabel) {
      return options.tabBarLabel;
    }

    if (typeof options.title === 'string') {
      return options.title;
    }

    return route.routeName;
  };
```

And then was able to figure out that the format for `navigationOptions` of `TabNavigator` screens has changed:
```js
// 1.0.0-beta7
const navigationOptions = {
  tabBar: { label: 'Settings' }
};

// master
const navigationOptions = {
  tabBarLabel: 'Settings'
};
```

I should be able to trust the documentation though. It makes no sense for `https://reactnavigation.org/docs/` not to reflect the state of the most recent stable version. From my minimal experience maintaining one very small open-source library, the two options I have to suggest (so as to not make this issue a mere complaint):

- Make the website point explicitly to the documentation of the latest stable release.
- Publish a new major/minor/patch version with every push to master, so that whatever code is in master is actually in the newest version.

I wanted to go ahead and make a PR for the former, but I'm not sure if the maintainers of this project want to do that (I'd be glad to help however I can!). Thanks for building this great tool, I hope this issue can be fixed to avoid frustration for others. 🙂

**Comment by srounce** [comment] 2017-04-20 08:03
Please see #1124

**Comment by samijaber** [comment] 2017-04-20 12:36
Perhaps I made a poor choice of words. Doesn't matter if it's `stable` or not. The fact is, the documentation doesn't represent any released version of `react-navigation`...it's describing a version that will be released sometime in the future. And since the framework is changing rapidly, it's causing a lot of people to make "mistakes" by simply following the documentation accurately.

**Comment by srounce** [comment] 2017-04-20 13:37
> This makes it impossible to trust the react-navigation docs.

I totally agree. I've taken to just reading the sources until the documentation situation is sorted. 

What might be very useful for the team could be to start making a list of outdated documentation sections. That way it's obvious what needs updating, and (hopefully) easier for the community to contribute, so the team can focus more on the v1 stable checklist (#723).

**Comment by skevy** [comment] 2017-04-20 15:59
You are all correct -- reactnavigation.org is generated directly from the docs on master, which doesn't match up to a released version. We absolutely understand that this is not ideal.

Does anyone want to contribute?

It seems like a great contributor to task to help us version the docs.

**Comment by samijaber** [comment] 2017-04-20 16:02
I'll dig into it :)

**Comment by grabbou** [comment] 2017-04-22 05:58
Duplicate of #1060

**Closed by grabbou** 2017-04-22 05:58 UTC
