### ISSUE TITLE
Can't long-press a TextInput inside a TabNavigator until user inputs some characters

### ISSUE THREAD

**Issue by uriva** [react-community/react-navigation#1992] opened 2017-06-26 21:34 UTC
A `TextInput` component, if put inside a `TabNavigator`, is not responding to long press on android. This long press usually brings up a paste/select all menu.

Once user inputs some letters, it is again possible to long-press and get the menu.

| software         | version
| ---------------- | -------
| react-navigation |   1.0.0-beta.11  
| react-native     |    0.45.1 (but it doesn't work on 0.44 either)

**Comment by spencercarli** [comment] 2017-08-17 02:05
Please provide a reproduction of this issue. [Snack](https://snack.expo.io) is a great option for this

**Comment by agat** [comment] 2017-08-30 13:30
Hello, i've created example with this bug – https://snack.expo.io/ry1wa4NtZ

TextInput has no context menu inside tabs navigation.

**Comment by XiaolongJason** [comment] 2017-10-27 09:10
I have the same problem on Samsung Galaxy S7, but work well on Galaxy  Note 3

software | version
-- | --
react-navigation | 1.0.0-beta.12
react-native | 0.46.0

**Comment by spencercarli** [comment] 2017-10-28 15:23
Can you duplicate this on the latest version of react navigation?

**Comment by kelset** [comment] 2017-11-19 10:22
Pinging OP @uriva since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment] 2017-11-25 08:29
Hi there @uriva,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2017-11-25 08:29 UTC
Labels: 7 days countdown, bug

**Comment by pkhien95** [comment] 2018-06-19 07:14
I'm facing this issue on react-navigation 1.0.0-beta.22 and react-native 0.54.4 @kelset

**Comment by brentvatne** [comment] 2018-06-20 18:58
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
