### ISSUE TITLE
examples/ReduxExample not working 

### ISSUE THREAD

**Issue by somsin** [react-community/react-navigation#1242] opened 2017-04-26 10:25 UTC
cannot find entry file "examples/ReduxExample/index.js" in any of the root.  
same error in NavigationPlayground.

what i used to run example .
Downloaded the ZIP for the github project
Extracted the Redux Example folder and copied it across to another area
run "npm install"
added rn-cli.config.js on root lable .
react-native run-ios

**Comment by grabbou** [comment] 2017-04-26 11:36
Duplicate of #1244

**Closed by grabbou** 2017-04-26 11:36 UTC
