### ISSUE TITLE
Weird animation on going back

### ISSUE THREAD

**Issue by santomegonzalo** [react-community/react-navigation#2938] opened 2017-11-09 09:39 UTC
Hi, I'm having some issues when I'm going back to the prev screen.

I tried everything:
- goBack
- dispatch reset
- move state inside redux and handle the index to go back 

So basically I tried everything...

Here is an example please look the **navigation bar** how after going back I'm seeing and splash title on the prev screen

![navigation](https://user-images.githubusercontent.com/2914973/32598316-c9620e06-c539-11e7-8fd4-bda2f49056c8.gif)

The structure that I have is the following:

- TabNavigator
     - Tab1 (CardStack)
           - WelcomeScreen
           - InfoScreen
     - Tab2 (CardStack)
           - CampaignsScreen
           - CampaignScreen

What I'm doing is the following:
User goes to Tab2, then click something and goes to **CampaignScreen**, and then press the Tab2 again. and here is where I tried everything to goBack, and of course it's working but with a weird transition **(gif)** 

anyone with this bug?

Thanks

**Comment by kelset** [comment] 2017-11-09 09:50
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

Moreover I actually think it's a duplicate of https://github.com/react-community/react-navigation/issues/2732

**Closed by kelset** 2017-11-09 09:50 UTC

**Comment by santomegonzalo** [comment] 2017-11-09 12:02
Thanks @kelset I added more details to a new issue https://github.com/react-community/react-navigation/issues/2938
