### ISSUE TITLE
Navigate problems

### ISSUE THREAD

**Issue by fenglu09** [react-community/react-navigation#3069] opened 2017-12-03 09:59 UTC
There is such a scene in my application： 
from ` list -> detail -> list2 -> detail`.
`list` and `list2` are different screens. But `detail` page are the same one width different `id`.
Currently, I cannot go `detail` from `list2`.

And one can help me ? 

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.48.2
| node             |  v6.9.1
| npm or yarn      | 4.0.2

**Comment by kelset** [comment] 2017-12-03 10:01
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-03 10:01 UTC
