### ISSUE TITLE
Custom Tab return undefined is not an object (evaluating nextState.routes.forEach)

### ISSUE THREAD

**Issue by ariona** [react-community/react-navigation#1102] opened 2017-04-19 00:23 UTC
Hello,

I am following the CustomTab example but can't get it to work. It show the message mentioned on the title.
```
undefined is not an object (evaluating 'nextState.routes.forEach')
```

Here is my complete code for the custom tab:

```js
import React from 'react'
import {
	Button,
	Platform,
	ScrollView,
	StyleSheet,
	Text,
	TouchableOpacity,
	View
} from 'react-native'
import {
	createNavigator,
	createNavigationContainer,
	TabRouter,
	addNavigationHelpers,
} from 'react-navigation'
import Icon from 'react-native-vector-icons/Ionicons'
import Home from './HomeScreen'
import Browse from './BrowseScreen'
import Radio from './RadioScreen'
import Settings from './SettingsScreen'

const HomeScreen = ({navigation}) => (
	<Home navigation={navigation}/>
)

const BrowseScreen = ({navigation}) => (
	<Browse navigation={navigation}/>
)

const RadioScreen = ({navigation}) => (
	<Radio navigation={navigation}/>
)

const SettingsScreen = ({navigation}) => (
	<Settings navigation={navigation}/>
)

const CustomTabBar = ({
  navigation,
}) => {
  const { routes } = navigation.state;
  return (
    <View style={styles.tabContainer}>
      {routes.map(route => (
        <TouchableOpacity
          onPress={() => navigation.navigate(route.routeName)}
          style={styles.tab}
          key={route.routeName}
        >
          <Text>{route.routeName}</Text>
        </TouchableOpacity>
      ))}
    </View>
  );
}

const CustomTabView = ({
  router,
  navigation,
}) => {
  const { routes, index } = navigation.state;
  const ActiveScreen = router.getComponentForState(navigation.state);
  return (
    <View style={styles.container}>
      <CustomTabBar navigation={navigation} />
      <ActiveScreen
        navigation={addNavigationHelpers({
          ...navigation,
          state: routes[index],
        })}
      />
    </View>
  );
};

const CustomTabRouter = TabRouter({
	Home: {
		screen: HomeScreen,
		path: ''
	},
	Browse: {
		screen: BrowseScreen,
		path: 'browse'
	},
	Radio: {
		screen: RadioScreen,
		path: 'radio'
	},
	Settings: {
		screen: SettingsScreen,
		path: 'settings'
	}
},{
	initialRouteName: 'Home'
})

const MainScreenNavigator = createNavigationContainer(createNavigator(CustomTabRouter)(CustomTabView));

// const MainScreenNavigator = createNavigationContainer(createNavigator(CustomTabRouter)(CustomTabView))

const styles = StyleSheet.create({
  container: {
    marginTop: Platform.OS === 'ios' ? 20 : 0,
  },
  tabContainer: {
    flexDirection: 'row',
    height: 48,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 4,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
  }
});

export default MainScreenNavigator
```

**Comment by JakeGinnivan** [comment] 2017-04-20 03:55
I had this issue when directly nesting different navigators. Try:

```
const Wrapper: React.SFC<{}> = () => (
    < CustomTabRouter />
)

const MainScreenNavigator = createNavigationContainer(createNavigator(Wrapper)(CustomTabView));
```

**Comment by spencercarli** [comment] 2017-08-15 02:34
Going to close this since there seems to be a solution and no followup occurred.

**Closed by spencercarli** 2017-08-15 02:34 UTC

**Comment by burabure** [comment] 2018-02-14 00:09
@spencercarli This is not solved, the underlying issue is that manually passing the navigation prop to a nested navigation component breaks like described on #2316.

This solution doesn't really solve anything just avoids passing the navigation prop to nested navs.

**Comment by brentvatne** [comment] 2018-02-21 20:10
can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!
