### ISSUE TITLE
Cannot read property 'routeName' of undefined

### ISSUE THREAD

**Issue by alainib** [react-community/react-navigation#3095] opened 2017-12-08 09:25 UTC
I upgrade react-navigation version, my code stop working with the following error : 
 
    	TypeError: Cannot read property 'routeName' of undefined

	This error is located at:
		in DrawerView (at DrawerNavigator.js:127)
		in Unknown (at createNavigator.js:52)
		in Navigator (at createNavigationContainer.js:210)
		in NavigationContainer (at App.js:75)
		in RCTView (at View.js:113)
		in View (at App.js:74)
		in Provider (at App.js:73)
		in App (at renderApplication.js:35)
		in RCTView (at View.js:113)
		in View (at AppContainer.js:102)
		in RCTView (at View.js:113)
		in View (at AppContainer.js:122)
		in AppContainer (at renderApplication.js:34)

<img src='https://i.stack.imgur.com/YIFK1.png' />
 
### Expected Behavior

The last version i have was :  `react-navigation@1.0.0-beta.15` , my code work with it.
Now i tryed with the last one : `react-navigation@1.0.0-beta.21`
 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "git+https://github.com/react-community/react-navigation.git#950d0c68772ea5fc93f6279659514e0086db71e1"
| react-native     |   0.50.4
| node             |      8

### Code simplify to reproduce the bug 
//test.js 

	import React, { Component } from 'react';
	import { Text } from 'react-native';
	export default class App extends Component {
		constructor() {super();}
		render() {return ( <Text>simple hello</Text> ); }
	}

// app.js 

	import React, { Component } from "react";
	import { AppRegistry, StyleSheet, Text, View, Image, Alert, ScrollView } from "react-native";
	import { StackNavigator, TabNavigator, DrawerNavigator } from "react-navigation";

	 
	import Test from "plantnet/src/Test";
	import styles from "plantnet/src/styles";
	import ActionButton from "react-native-action-button";
	import Icon from "react-native-vector-icons/Ionicons";
	import { Provider } from "react-redux";
	import store from "plantnet/src/redux/store"; 

	const MyTabView = TabNavigator(
	  {
		 Test: { screen: Test },     
	  } 
	);

	class TabsAndCamera extends Component {
	  constructor(props) { super(props);  }
	 
	  render() {return ( <View style={{ flex: 1 }}><MyTabView
			  navigation={this.props.navigation}
			  screenProps={{ navigation: this.props.navigation }}
			/></View > ); }
	}

	TabsAndCamera.router = MyTabView.router;

	const StackView = StackNavigator({
	  global: {
		screen: TabsAndCamera,
		headerMode: "none",
		header: null,
		navigationOptions: {
		  header: null
		}
	  }   
	});

	const MyDrawerNavigator = DrawerNavigator({
	  All: { screen: StackView }, 
	}, {
		drawerWidth: 300,
		drawerPosition: 'left',
	});

	import * as actions from "plantnet/src/redux/actions";

	export default class App extends Component {
	  constructor(props) {
		super(props);
	  }
	  
	  render() {
		return (
		  <Provider store={store}> <View style={{ flex: 1, marginTop: 10}}>
			<MyDrawerNavigator />
		  </View></Provider>
		);
	  }
	}

	const thisstyles = StyleSheet.create({

	});

**Comment by kelset** [comment] 2017-12-08 09:29
In both beta.16 and beta.20 there have been breaking changes, please read the release notes: https://github.com/react-community/react-navigation/releases

So please make sure to modify your code accordingly.

Moreover, you are pointing to master. I highly suggest you don't do that unless you know what you are putting yourself into.

**Comment by alainib** [comment] 2017-12-08 09:32
ok thank you i will read it. 
i change in package.json  `"react-navigation": "1.0.0-beta.XX"` unstead of `"react-navigation": "git+https://github.com/react-community/react-navigation.git"`

**Comment by nbergen** [comment] 2017-12-11 03:10
@alainib were you able to get past this?  I have the same problem.

**Comment by alainib** [comment] 2017-12-11 06:59
@nbergen Yes I solved it.

Read this for breaking change liste of v16 and v20 https://github.com/react-community/react-navigation/releases
I get back to v13 to check if my code Work, then to v15, then to v16 then to v20 then to v21

**Comment by kelset** [comment] 2017-12-11 11:28
@alainib so is it solved? If so can you please close the issue?

**Comment by nbergen** [comment] 2017-12-12 01:51
I'll continue looking and reply when I have some time to solve the [same] issue, but it would be helpful to have a solution posted in the thread, as this seems to be expected behavior resulting from a breaking change, presumably `beta.16`.

**Closed** 2017-12-12 08:37 UTC
Labels: needs more info

**Comment by danstepanov** [comment] 2017-12-19 03:33
@nbergen Did you have to add that within the react-navigation node module or within your own code?

**Comment by nbergen** [comment] 2017-12-19 03:49
This was my own code, in the click event that actually triggers the navigation.

**Comment by danstepanov** [comment] 2017-12-19 04:09
@nbergen You removed the action and it still works? How is that possible?

**Comment by nbergen** [comment] 2017-12-19 04:14
No, it was doing an odd double-action.  The outer action is the actual `NavigateAction`.  The inner `action: NavigationActions.navigate()` is just... odd.

**Comment by trajakovic** [comment] 2017-12-19 14:23
It seems that latest beta22 also broke some NavigationActions.navigate() in conjuction with DrawerNavigator.



`AppNavigator.js`
```
const SidebarComponent = props => <Sidebar {...props} />;
const HomeNavigator = DrawerNavigator(
  {
    Home: { screen: Home },
  },
  {
    initialRouteName: 'Home',
    contentComponent: SidebarComponent,
  },
);

const WelcomeNavigator = TabNavigator(
  {
    WelcomePage1: {
      screen: Welcome,
    },
  },
  {
    initialRouteName: 'WelcomePage1',
    navigationOptions: {
      tabBarVisible: false,
    },
  },
);

export const AppNavigator = StackNavigator(
  {
    WelcomePage: { screen: WelcomeNavigator },
    LoginPage: { screen: Login },
    HomePage: { screen: HomeNavigator },
  },
  {
    headerMode: 'none',
  },
);
```

reducer.js
```
import { NavigationActions } from 'react-navigation';

import { AppNavigator } from '../AppNavigator';

const initialNavState = AppNavigator.router.getStateForAction(NavigationActions.init());

export default function nav(state = initialNavState, action) {
  let nextState;
  switch (action.type) {
    default:
      nextState = AppNavigator.router.getStateForAction(action, state);
      break;
  }

  // Simply return the original `state` if `nextState` is null or undefined.
  return nextState || state;
}
```

For **beta21**, when navigating to `HomePage` (DrawerNavigator) with: 

**Start State**:
```
{
  nav: {
    index: 0,
    routes: [
      {
        routeName: 'LoginPage',
        key: 'id-1513692633966-1'
      }
    ]
  }
}
```

**Action:**
```
NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({ routeName: 'HomePage' })],
  })
```

```
{
  type: 'Navigation/RESET',
  index: 0,
  actions: [
    {
      type: 'Navigation/NAVIGATE',
      routeName: 'HomePage'
    }
  ]
}
```

ends up with state:
```
{
  nav: {
    index: 0,
    routes: [
      {
        type: 'Navigation/NAVIGATE',
        routeName: 'HomePage',
        routes: [
          {
            routes: [
              {
                key: 'Home',
                routeName: 'Home'
              }
            ],
            index: 0,
            key: 'DrawerClose',
            routeName: 'DrawerClose'
          },
          {
            key: 'DrawerOpen',
            routeName: 'DrawerOpen'
          },
          {
            key: 'DrawerToggle',
            routeName: 'DrawerToggle'
          }
        ],
        index: 0,
        key: 'id-1513692633966-2'
      }
    ]
  }
}
```



But for **beta22** the same **start state** and **action** produces different end state:

```
{
  nav: {
    index: 0,
    routes: [
      {
        type: 'Navigation/NAVIGATE',
        routeName: 'HomePage',
        routes: [
          {
            key: 'undefined',
            routeName: 'undefined'
          }
        ],
        index: 0,
        key: 'id-1513693154203-2'
      }
    ]
  }
}
```

which ends up with error:

TypeError: Cannot read property 'routeName' of undefined

**Comment by danstepanov** [comment] 2017-12-19 18:51
Yea, I'm not even sure what in my code is causing the error

**Comment by danstepanov** [comment] 2017-12-19 20:46
@trajakovic #3148 Seems to have a fix for this breaking change

**Comment by giantss** [comment] 2017-12-20 06:01
+1
I also encountered the same error message.
My environment:
`react native 0.49.5`
`react-navigation 1.0.0-beta.22`
When I configured any `DrawerNavigatorConfig` configuration items will be reported such an error, do not configure it will not be reported， I'm not even sure what in my code is causing the error. help me
![image](https://user-images.githubusercontent.com/13778798/34193345-27d30ed0-e58e-11e7-865b-0c95da14a6ea.png)
@alainib @kelset

**Comment by giantss** [comment] 2017-12-20 06:21
I reinstalled `react-navigation 1.0.0-beta.21` ,Such as the above operation can work properly.This is a beta.22 version of the bug?

**Comment by trajakovic** [comment] 2017-12-20 11:14
Like @danstepanov  pointed out, #3148 is addressing this issue.

Btw. I've tried solution from #3148 on beta22 and it works (add drawerOpen/Close/Toggle routes by hand in `DrawerNavigator` config object)

**Comment by agustinaliagac** [comment] 2017-12-21 14:59
I did what @trajakovic suggested and it worked. Here's how I had to modify my code:

```
const AppNavigator = DrawerNavigator(navigatorConfigs, {
  contentComponent: Drawer,
  drawerWidth: 300,

  // I had to add the following lines
  drawerOpenRoute: 'DrawerOpen',
  drawerCloseRoute: 'DrawerClose',
  drawerToggleRoute: 'DrawerToggle',
});
```

If the config object is not passed, only then it will create default values (https://github.com/react-community/react-navigation/blob/d5618ebd41ec1ac53cb40301d0f71610fbbb7172/src/navigators/DrawerNavigator.js#L71).

**Comment by LingboTang** [comment] 2018-01-05 23:35
I meet the same problem when I upgrade this from beta 14 to beta 22 and beta 23.

**Comment by inferusvv** [comment] 2018-01-06 10:09
@agustinaliagac Yes. This works. Thank you :)

I think this should be somehow documented.

**Comment by kelset** [comment] 2018-01-06 15:01
> I think this should be somehow documented.

There's a link in the release notes.

**Comment by petrogad** [comment] 2018-01-16 20:08
It would be nice to have this information communicated out via the docs here:
https://reactnavigation.org/docs/navigators/drawer
