### ISSUE TITLE
react-navigation giving error to push after using custom header 

### ISSUE THREAD

**Issue by somsin** [react-community/react-navigation#3026] opened 2017-11-21 18:50 UTC
![simulator screen shot - iphone 6s - 2017-11-22 at 00 03 29](https://user-images.githubusercontent.com/4973590/33090696-e559c654-cf1a-11e7-8bf0-c3f280113295.png)
## The issue list is reserved for bugs and feature requests, not for questions.

this.props.navigation.navigate(
   'detail',
   {},
   NavigationActions.navigate({ routeName: 'DETAILSA' }),
 );

---

0down votefavorite | I am getting some error when trying to push new screen . same screen I am pushing from other screen its working fine , but I have added custom header in navigationOptions and setParams for custom action , all action working fine , now I am trying to go another screen from this screen getting issue not able to find what is issue ,I am using  "react-navigation": "1.0.0-beta.11",code I used for header , and set action working fine

componentWillMount() {
        this.props.navigation.setParams({
          onChangeText: this.onChangeText,
          goBack: this.goBack,
          seachAction: this.seachAction,
        });
//here is my code to push new screen but getting error

this.props.navigation.navigate(
   'detail',
   {},
   NavigationActions.navigate({ routeName: 'DETAILSA' }),
 );

**Comment by kelset** [comment] 2017-11-21 22:19
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-11-21 22:19 UTC
