### ISSUE TITLE
Glitch when using an image as a stack navigator title

### ISSUE THREAD

**Issue by sonaye** [react-community/react-navigation#3071] opened 2017-12-03 11:29 UTC
I noticed this glitch and I thought I should share.

![kapture 2017-12-03 at 14 22 50](https://user-images.githubusercontent.com/23000873/33524889-c10d873a-d835-11e7-9c8a-53331372b880.gif)

```javascript
static navigationOptions = {
  headerTitle: (
    <Image
      resizeMode="contain"
      source={require('../assets/img/logo.png')}
      style={{ alignSelf: 'center', height: 32, width: 32 }}
    />
  )
};
```

`react-navigation@1.0.0-beta.21`
`react-native@0.49.3`

**Comment by kelset** [comment] 2017-12-03 13:53
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-03 13:53 UTC

**Comment by sonaye** [comment] 2017-12-23 02:37
Glitch was caused by LayoutAnimation, `componentWillUpdate` fires with navigation events.

Fix:
```javascript
componentWillUpdate(nextProps: Props, nextState: State) {
  if (this.state.height === 0 && nextState.height === 100)
    LayoutAnimation.easeInEaseOut();
}
```

**Comment by sonaye** [comment] 2017-12-23 02:37
iOS only.
