### ISSUE TITLE
Open screens from a single StackNavigator over current tab?

### ISSUE THREAD

**Issue by Talor-A** [react-community/react-navigation#586] opened 2017-03-06 07:31 UTC
Hi all,
I'm working on a project that has persistent bottom tabs as well as a stackNavigator (think instagram style navigation). For example, the layout might look like this:
```
TabNavigator:
    -home feed
    -search page
    -new post
    -notifications
    -my profile
```
and each of those tabs can link to a page in my stackNavigator, which might look like this:
```
StackNavigator:
    -user profile view
    -post view
    -comment view
    -etc...
```
right now, I place my StackNavigator inside my `home feed` tab, and any time i navigate to one of the screens inside the StackNavigator, the `TabNavigator` switches over to the home page and then the new screen comes up. Is there any way to get the new StackNavigator screen to appear over the current tab instead?

**Comment by bjrn** [comment] 2017-03-06 08:09
I'm working on a small side-project with similar navigation structure - the solution is to have a StackNavigator as your primary navigator, then as mainScreen add you TabNavigator. Add userProfile, Post, Comment etc that you'd like to overlap the tabs to the root StackNavigator instead.

**Comment by guoliang1206** [comment] 2017-03-06 10:25
```
const rootApp  = StackNavigator({
    Main:{screen:YourTabNavigator},
})
```

I used like this.

**Comment by Talor-A** [comment] 2017-03-06 10:33
thanks for the solutions. although looking at them, it seems that the tabs will only appear on the main screen and I would prefer them to be persistent.

**Comment by bjrn** [comment] 2017-03-06 14:34
> Is there any way to get the new StackNavigator screen to appear over the current tab instead?

Judging from that comment I thought that was what you wanted?

But you want the tab bar to be visible also on post/comment/user profile views?

In that case, you should probably consider making each of the tabScreens a StackNavigator, otherwise, how would you keep track of which tab should be selected?

**Comment by diegorodriguesvieira** [comment] 2017-05-11 17:43
@bjrn this is correct? I need each tab to have a navigation stack...

```
import React, { Component } from 'react';

import {
  AppRegistry,
  Text,
  TouchableOpacity,
  View,
  StyleSheet,
  Image,
  Button,
  TouchableNativeFeedback,
  Platform,
} from 'react-native';

import { StackNavigator, TabNavigator, TabView } from 'react-navigation';
import Icon from 'react-native-vector-icons/FontAwesome';

console.disableYellowBox = true;

class HomeScreen extends Component {
  static navigationOptions = {
    tabBarLabel: 'Home',
    title: 'Home 01',
    tabBarIcon: ({ tintColor, focused }) => (
      <View>
        <Icon name="home" size={24} color={tintColor} />
      </View>
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('HomeTwo', {name: 'Diego', age: 24,})}
        title="Go Home 02"
      />
    );
  }
}

class HomeScreen2 extends Component {
  static navigationOptions = {
    tabBarLabel: 'Home',
    title: 'Home 02',
    tabBarIcon: ({ tintColor, focused }) => (
      <View>
        <Icon name="home" size={24} color={tintColor} />
      </View>
    ),
  };

  render() {
    const {state} = this.props.navigation;
    return (
      <View>
        <Text>{`Name: ${state.params.name}`}</Text>
        <Text>{`Age: ${state.params.age}`}</Text>
        <Button
          onPress={() => this.props.navigation.goBack()}
          title="Go Home 01"
        />
      </View>
    );
  }
}

class NotificationsScreen extends Component {
  static navigationOptions = {
    tabBarLabel: 'Notifications',
    title: 'Notifications 01',
    tabBarIcon: ({ tintColor }) => (
      <View>
        <Icon name="bell" size={24} color={tintColor} />
      </View>
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('NotificationsTwo')}
        title="Go Notifications 02"
      />
    );
  }
}

class NotificationsScreen2 extends Component {
  static navigationOptions = {
    tabBarLabel: 'Notifications',
    title: 'Notifications 02',
    tabBarIcon: ({ tintColor }) => (
      <View>
        <Icon name="bell" size={24} color={tintColor} />
      </View>
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack()}
        title="Go Notifications 01"
      />
    );
  }
}

class ProfileScreen extends Component {
  static navigationOptions = {
    tabBarLabel: 'Profile',
    title: 'Profile 01',
    tabBarIcon: ({ tintColor }) => (
      <View>
        <Icon name="user" size={24} color={tintColor} />
      </View>
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('ProfileTwo')}
        title="Go Profile 02"
      />
    );
  }
}

class ProfileScreen2 extends Component {
  static navigationOptions = {
    tabBarLabel: 'Profile',
    title: 'Profile 02',
    tabBarIcon: ({ tintColor }) => (
      <View>
        <Icon name="user" size={24} color={tintColor} />
      </View>
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack()}
        title="Profile 02"
      />
    );
  }
}

export const Home = StackNavigator(
  {
    HomeOne: { screen: HomeScreen},
    HomeTwo: { screen: HomeScreen2},
  },
  {
    cardStyle: {
      shadowOpacity: 0,
      backgroundColor: '#fff',
    }
  }
);

export const Notifications = StackNavigator(
  {
    NotificationsOne: { screen: NotificationsScreen},
    NotificationsTwo: { screen: NotificationsScreen2},
  },
  {
    cardStyle: {
      shadowOpacity: 0,
      backgroundColor: '#fff',
    }
  }
);

export const Profile = StackNavigator(
  {
    ProfileOne: { screen: ProfileScreen},
    ProfileTwo: { screen: ProfileScreen2},
  },
  {
    cardStyle: {
      shadowOpacity: 0,
      backgroundColor: '#fff',
    }
  }
);

const SimpleApp = TabNavigator(
  {
    Home: {
      screen: Home,
    },
    Notifications: {
      screen: Notifications,
    },
    Profile: {
      screen: Profile,
    },
  },
  {
    lazy: true,
    animationEnabled: false,
    swipeEnabled: false,
    tabBarPosition: 'bottom',
    tabBarOptions: {
      showLabel: false,
      activeTintColor: 'green',
      inactiveTintColor: 'magenta',
      style: {
        backgroundColor: '#fff',
        height: 48,
        ...Platform.select({
          ios: {
            shadowColor: '#000',
            shadowOffset: {
              width: 0,
              height: 4
            },
            shadowRadius: 4,
            shadowOpacity: 0.6
          },
          android: {
            elevation: 8,
            backgroundColor: '#fff',
          }
        }),
      }
    }
  }
);

AppRegistry.registerComponent('SimpleApp', () => SimpleApp);
```

**Comment by bjrn** [comment] 2017-05-11 21:13
@diegorodriguesvieira Yep, If you want the tab to "own" the separate navigationStacks that seems right! If you'll have places where you want a screen to "slide in" on top of the tabbed navigation, you can always add a stackNavigator as the root screen, and then put the TabNavigator (SimpleApp in your example) as the first screen in there.

I didn't know it was actually possible to override the tabIcon from the screen navigationOptions like that. (For example, change icon in HomeScreen2 to "bell" and it will change tabBar when navigating)

If you'd like to have the same tabBarIcon for all screens under your "home" tab, you can save yourself from some typing and instead add a `navigationOptions` section in the `Home = StackNavigator` like below. You can still override all navigationOptions in the individual screens.

```javascript
export const Home = StackNavigator(
  {
    HomeOne: { screen: HomeScreen },
    HomeTwo: { screen: HomeScreen2 },
  },
  {
    cardStyle: {
      shadowOpacity: 0,
      backgroundColor: '#ffc',
    },
    // It's possible to add tabBarIcon in here as a default, 
    // and still be able to override them from the individual screens.
    navigationOptions: {
      tabBarLabel: 'Home',
      tabBarIcon: ({ tintColor, focused }) => (
        <View><Icon name="home" size={24} color={tintColor} /></View>
      ),
    },
  }
);
```

**Comment by diegorodriguesvieira** [comment] 2017-05-12 12:05
@bjrn thank thanks so much for the explanation!

**Comment by 1c7** [comment] 2017-06-23 15:13
@guoliang1206 it work! Thank you!
![image](https://user-images.githubusercontent.com/1804755/27488389-82a53c78-5869-11e7-9554-c2074d078f1e.png)

**Comment by kelset** [comment] 2017-10-08 18:03
Pinging OP @Talor-A since the solution proposed seems to fix the issue. If no answer I'll close it in 7 days.

**Closed** 2017-10-09 01:18 UTC

**Comment by shashankwadi** [comment] 2017-12-06 09:54
This issue is still not fixed because with @guoliang1206 approach the tab bar goes hidden, however I want the tab bar to be consistently there.

**Comment by ahmadabdul3** [comment] 2018-01-06 07:04
The solution does not fix the issue. I have the same problem right now. Let me explain where I'm stuck with an instagram comparison:

on instagram, you may be on your newsfeed, so you decide to:
1. click on a person's name and end up on their profile page
2. click on one of their image posts, which opens it up larger
3. while viewing the post, click on their name again, which brings you to their profile again
4. click on one of their image posts, which opens it up larger
5. click on their name again... 

you see where I'm going with this. Every time you click on a post or their name, the entire screen (including the top navigation bar), EXCEPT the bottom tabnavigation, slides to the right. So this means theres 1 tabnavigation bar on the bottom and 1 stacknavigation bar on top

Now, if you start clicking back, you will go back in the order that you got to where you are. So you will go back to their post, back to profile, back to post, etc... until you end up on the newsfeed.

Also, you can get to a person's profile from the newsfeed tab, or from the search tab, or from posts that you've liked, so there's many ways to get to the same destination.

So far, my set up has been a top level tabnavigation, and each screen is a stacknavigation. Something like:

```
const mainNav = TabNavigator({
  home: {
    screen: HomeScreen // stackNavigator
  },
  somethingElse: {
    screen: SomethingElse // stackNavigator
  }
})
```

but I also have other nested stackNavigators inside of the home screen and the other screens. When I click on a button in home screen to go to a nested stackNavigator, the main stackNavigator header bar doesnt slide away, only the inner screen content slides. In instagram, the entire page (minus the bottom tab navigation) slides and the new back button only goes back 1 level like I explained above.

**Comment by lucaspedroza1** [comment] 2018-04-19 19:39
Hi guys, 

In the project I'm working on, I had a similar problem and instead of creating multiple variables for each new screen that uses the same tab, I did a function that solved the problem. See if it helps.

```
import React from 'react'
import { StackNavigator, TabNavigator, TabBarBottom } from 'react-navigation'
import ResponsiveImage from 'react-native-responsive-image';

//screens
import DoneStepsScreen from '../Containers/DoneStepsScreen'
import FilterStepsScreen from '../Containers/FilterStepsScreen'
import ResidentialScreen from '../Containers/ResidentialScreen'
import IntroScreen from '../Containers/IntroScreen'
import VisitsScreen from '../Containers/VisitsScreen'
import ChannelsScreen from '../Containers/ChannelsScreen'
import InstallationScreen from '../Containers/InstallationScreen'

//styles
import { Images, Colors } from '../Themes/'
import styles from './Styles/NavigationStyles'

const screens = {
  assistance: {
    initial: ResidentialScreen,
    FilterStepsScreen: FilterStepsScreen,
    DoneStepsScreen: DoneStepsScreen,
  },
  installation:{
    initial: InstallationScreen,
  },
  channels:{
    initial: ChannelsScreen,
  },
  visits:{
    initial: VisitsScreen,
  }
}

const setTab = (tabName, tabTitle) => {
  const tabConfig = {
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;
        iconName = focused ? Images.menu[routeName + 'Active'] : Images.menu[routeName];

        return <ResponsiveImage source={iconName}  initWidth="25" initHeight="25" />
      }
    }),
    tabBarOptions: {
      activeTintColor: Colors.tabActiveTintColor,
      inactiveTintColor: Colors.tabInactiveTintColor,
      labelStyle: styles.tabLabel,
      tabStyle: styles.tabStyles,
      style: styles.containerStyle
    },
    tabBarComponent: TabBarBottom,
    tabBarPosition: "bottom"
  };

  return TabNavigator({
    assistance: {
      screen: screens.assistance.hasOwnProperty(tabName) ? screens.assistance[tabName] : screens.assistance.initial,
      navigationOptions:{
        title: 'Assistência',
      },
    },
    installation: {
      screen: screens.installation.hasOwnProperty(tabName) ? screens.installation[tabName] : screens.installation.initial,
      navigationOptions:{
        title: 'Instala',
      },
    },
    channels: {
      screen: screens.channels.hasOwnProperty(tabName) ? screens.channels[tabName] : screens.channels.initial,
      navigationOptions:{
        title: 'Chamadas',
      },
    },
    visits: {
      screen: screens.visits.hasOwnProperty(tabName) ? screens.visits[tabName] : screens.visits.initial,
      navigationOptions:{
        title: 'Atendimento',
      },
    }
  },
  tabConfig)
}



// Manifest of possible screens
const PrimaryNav = StackNavigator({
  IntroScreen: { screen: IntroScreen },

    //Residential Group
    ResidentialScreen: { screen: setTab('ResidentialScreen', 'Assistance') },
    FilterStepsScreen: { screen: setTab('FilterStepsScreen', 'Assistance') },
    DoneStepsScreen: { screen: DoneStepsScreen },

    //Installation Group
    InstallationScreen: { screen: setTab('InstallationScreen', 'Installation') },

    //Visits Group
    VisitsScreen: { screen: VisitsScreen },

    //Channels Group
    ChannelsScreen: { screen: ChannelsScreen },
}, {
  // Default config for all screens
  headerMode: 'none',
  initialRouteName: 'ResidentialScreen',
  navigationOptions: {
    headerStyle: styles.header
  }
})

export default PrimaryNav

```

**Comment by gianpaj** [comment] 2019-05-09 11:23
Hi @ahmadabdul3 and all, sorry for re-surfacing an old issue, but I've been trying to do what you mention and yes, the issue is when you navigate back.

For example, if you're on the 2nd tab, and navigate within the StackNavigator to another screen, when you go back, it doesn't stay on the 2nd tab. It goes back to the 1st tab.

i.e. from Search -> Product and back.
It goes back to the Home screen

```js
const HomeStack = StackNavigator(
  {
    home: { screen: Home },
    product: { screen: Product },
    profileInStack: { screen: Profile },
  },
);

const routeConfiguration = {
  home: { screen: HomeStack },
  search: { screen: Search },
  new: { screen: CreatePost },
  chats: { screen: ChatRooms },
  profile: { screen: Profile },
};
```

Note: I'm still using `react-navigation v1.5` but not sure the new versions have made changes to this

**Comment by swizes** [comment] 2019-11-07 21:23
Does anyone have a working solution? I am also trying to achieve a navigation like fb and instagram
