### ISSUE TITLE
Nested TabNavigator is not getting rendered when app starts? 

### ISSUE THREAD

**Issue by vbhv19** [react-community/react-navigation#823] opened 2017-03-25 09:49 UTC
I cant see the ChildScene1 when my app starts. When i make transitions to another child tabs or click on existing tab  only then content of ChildScreen is visible.

    class ChildScene1 extends React.Component {
      render(){
        return(
          <View>
             <Text> this is content of Child Tab1 </Text>
          </View>
        )
      }
    }

    class ChildScene2 extends React.Component {
       render(){
         return(
           <View>
             <Text> this is content of Child Tab2 </Text>
           </View>
         )
       }
    }

    class ChildScene3 extends React.Component {
        render(){
          return(
            <View>
               <Text> this is content of Child Tab3 </Text>
            </View>
          )
        }
    }

    class ChildScene4 extends React.Component {
        render(){
          return(
            <View>
               <Text> this is content of Child Tab4 </Text>
            </View>
          )
        }
    }

    const ParentScene1 = TabNavigator ({
      Tab1: { screen: ChildScene1 },
      Tab2: { screen: ChildScene2 }
    });

    const ParentScene2 = TabNavigator ({
      Tab1: { screen: ChildScene3 },
      Tab2: { screen: ChildScene4 }
    });

    const GParentScene = TabNavigator({
      A: { screen: ParentScene1 },
      B: { screen: ParentScene2 },
    });

    const SimpleApp = StackNavigator({
      Home: { screen: GParentScene, navigationOptions:{ title:'MyChats', header:{ visible:false } } },
    });

    AppRegistry.registerComponent('testtabs', () => SimpleApp);
![screenshot_20170325-141901](https://cloud.githubusercontent.com/assets/24244850/24321275/44fc6a64-116e-11e7-8510-6e2301511119.png)

My ChildScreen1 contents should be visible on screen .

**Comment by antonio-costa** [comment] 2017-03-26 23:28
+1
I'm having the exact same problem.

**Comment by Minishlink** [comment] 2017-03-27 07:28
+1

Here are my navigators for reference:
* StackNavigator
  * Screen A (initial, resets automatically to TabNavigator 1 (login))
  * TabNavigator 1
    * TabNavigator 2
      * View B
      * View C
    * TabNavigator 3
      * View D
      * View E
    * TabNavigator 4 (initial)
      * View F (initial)
      * View G 
      * View H
      * View I

TabNavigators 2 and 4 are not initialized. TabNavigator 4 is sometimes initialized, sometimes not.

**Comment by Minishlink** [comment] 2017-03-28 18:06
Do you guys have this problem on iOS too? (I don't) 
If not, the problem most likely comes from the dependancy [react-community/react-native-tab-view](https://github.com/react-native-community/react-native-tab-view).

**Comment by AlanFoster** [comment] 2017-04-03 23:36
+1 Also having this issue with two nested tabbed navigators

**Comment by Andrei-Vakulski** [comment] 2017-04-04 14:11
+1 Same issue.

**Comment by onlydave** [comment] 2017-04-05 14:44
After updating to react-native 0.43.1 I'm still experiencing this issue. Similar to #662 

The render function of screens does run.

Tapping the tab to force it to show no longer works.

The tab content does display on dismissal of a warning, e.g. "remote debugger is in a background tab..."

**Comment by Lukkub** [comment] 2017-04-05 18:41
+1 Also having this issue with two nested tabbed navigators

**Comment by ldipasquale** [comment] 2017-04-08 04:55
+1

**Comment by allmaxgit** [comment] 2017-04-12 08:20
+1

**Comment by onlydave** [comment] 2017-04-14 16:21
I've been using a fork with `TabViewPagerAndroid` swapped out for `TabViewPagerScroll` and it seems to be working pretty well. Combined with FlatLists we're seeing much better performance across android and iOS devices.

Involves using a lot of very knew versions of things though.
```
"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-navigation": "git+https://github.com/onlydave/react-navigation.git",
}
```  

https://github.com/onlydave/react-navigation

**Comment by Crazy-Ivan** [comment] 2017-04-16 11:40
👍

**Comment by kelset** [comment] 2017-04-18 10:53
+1
Same issue here on Android 6.0.1, using RN 0.42 and react-navigation beta7.

**Comment by grabbou** [comment] 2017-04-24 14:52
Duplicate of #662

**Closed by grabbou** 2017-04-24 14:52 UTC

**Comment by sharathkoppolu** [comment] 2017-12-29 08:39
const AppNavigation = StackNavigator({
    TabTop: {
        screen: TabNavigator({
            TabBtm: {
                screen: TabNavigator({
                    TabT1: { screen: TabT1 },
                    TabT2: { screen: TabT2 },
                    TabT3: { screen: TabT3 }
                }, {
                    tabBarPosition: 'top',
                    swipeEnabled: true,
                    tabBarOptions: {
                      activeTintColor: '#e91e63',
                    },
                  })
            },
            Tab1: { screen: Tab1 },
            Tab2: { screen: Tab2 },
            Tab3: { screen: Tab3 },

            
        }, {
            tabBarPosition: 'bottom',
            swipeEnabled: false,
            tabBarOptions: {
              activeTintColor: '#e91e63',
            },
          })
    }
})

Swipe and tab click is working fine on ios but not working properly on android. I think this is similar to what the discussion is about. can someone let me know where am I going wrong? did it work for anyone on android?
