### ISSUE TITLE
Unexpected Token in src/views/CardStack/Card.js in latest beta

### ISSUE THREAD

**Issue by claykohut** [react-community/react-navigation#2508] opened 2017-08-31 17:18 UTC
I'm getting this issue when trying to use the latest veta (v1.0.0-beta.12)

<img width="487" alt="screen shot 2017-08-31 at 1 00 27 pm" src="https://user-images.githubusercontent.com/3993332/29936049-d471b264-8e4e-11e7-97d1-a56c729c28a3.png">

Can anyone help?

**Comment by azz0r** [comment] 2017-09-03 15:47
Also suffering with this right now 👍

**Comment by ahmadsyamim** [comment] 2017-09-08 04:28
Suffering also

**Comment by gfitzy123** [comment] 2017-09-09 16:04
Also experiencing this.

**Comment by indrasantosa** [comment] 2017-09-12 18:38
Any clue how to get around with this?

**Comment by pedrofmlopes** [comment] 2017-09-16 15:25
Has anyone found any answer about this issue?

**Comment by wardcraigj** [comment] 2017-09-19 00:39
Only solution at this point is to pin the version of the react-navigation library to beta11 for now until there is a fix in the library. Update your package.json and change the line with "react-navigation" to:

"react-navigation": "1.0.0-beta.11",

then blow away your node_modules directory and yarn/npm install again

**Comment by paulobiscotto** [comment] 2017-09-19 16:16
Still experiencing the bug with "react-navigation": "1.0.0-beta.11" in package.json on a fresh clone. 

Any idea?

**Comment by skovhus** [comment] 2017-09-19 20:04
This seems to be a duplicate of https://github.com/react-community/react-navigation/issues/2207

**Comment by davidhellsing** [comment] 2017-10-01 04:02
I’m still getting this. My `package.json`:

```
    "flow-bin": "^0.56.0",
    "flow-scripts": "^0.4.0",
    "react-navigation": "^1.0.0-beta.13",
```

**Comment by kiidbrian** [comment] 2017-10-03 17:29
@wardcraigj your answer worked for me

**Comment by fabryx92** [comment] 2017-10-26 10:07
I have the exact same problem

**Comment by spencercarli** [comment] 2017-11-03 17:03
I believe this was solved with beta.16 and we're now at beta.17. I'm going to close this but if the error persists please let me know and I'll re-open (also, please be sure to let me know how to reproduce because I haven't seen this behavior before).

**Closed by spencercarli** 2017-11-03 17:03 UTC
Labels: Type: Bug

**Comment by ShivamKJJW** [comment] 2017-12-12 06:13
To instantly resolve the issue with latest beta.21 release just comment out the line number 12 in `CardStack/Card.js` file. Compile will work smoothly.

**Comment by TimHu6001** [comment] 2018-02-01 17:38
Having the same issue on beta26. Have to revert to beta11 to make it work.

**Comment by brentvatne** [comment] 2018-02-01 17:40
please create a new issue if you have this problem and fill out the appropriate issue template. i'm unable to reproduce it on my own.
