### ISSUE TITLE
Issue with navigating stacks within tabs

### ISSUE THREAD

**Issue by balajivenkatesh** [react-community/react-navigation#2895] opened 2017-11-03 21:07 UTC
I have stack navigators inside tabs of a tab navigator.
I want to switch tabs and and navigate within the stack on the other tab.

Example, from Tab1,
`
NavigationActions.navigate({
    routeName: "Tab2",
    action: NavigationActions.reset({
      index: 1,
      actions: [
        NavigationActions.navigate({ routeName: "Tab2_Stack0" }),
        NavigationActions.navigate({ routeName: "Tab2_Stack1" }),
      ],
    }),
  });
`

According to the following line of code - 
https://github.com/react-community/react-navigation/blob/7adad618d1ab0080004df8d6f2f1c1d1125551c7/src/routers/TabRouter.js#L125
handling tab changing happens after current tab tries to handle the action.

But this breaks navigation by creating a state like 
Tab1 {
  Tab2_Stack0,
  Tab2_Stack1
}
and these screens are not defined under Tab1.

Possible fix is to check if some other tab must handle the action first.

**Comment by vonovak** [comment] 2017-11-03 21:29
I'm wondering - can you try the code from this PR: https://github.com/react-community/react-navigation/pull/2747 and report back on whether it fixes your issue? Thanks!

**Comment by kelset** [comment] 2017-11-03 21:31
Possible duplicate https://github.com/react-community/react-navigation/issues/2670?

**Comment by balajivenkatesh** [comment] 2017-11-03 21:42
@vonovak it does not fix the issue.
I think the incorrect state is generated by the line
https://github.com/react-community/react-navigation/blob/7adad618d1ab0080004df8d6f2f1c1d1125551c7/src/routers/TabRouter.js#L118

**Comment by vonovak** [comment] 2017-11-03 21:48
@balajivenkatesh this indeed seems to be a duplicate of #2670, so I'll close, can you check whether any of the comments help you out? (and continue discussion there)

**Closed by vonovak** 2017-11-03 21:48 UTC
Labels: Type: Bug

**Comment by balajivenkatesh** [comment] 2017-11-09 00:07
@vonovak sorry those comments don't help. I want to navigate from one tab to another, both of which are stack navigators themselves.
I see that the state the navigator gets into is that it tries to put the screens of the destination stack navigator in the current tab's stack navigator.
