### ISSUE TITLE
android  tabbar not showing text for Unfocused Tab- React Native 0.50.4. Version

### ISSUE THREAD

**Issue by kartiikeyabaleneni** [react-community/react-navigation#3090] opened 2017-12-07 12:09 UTC
I'm using tab navigator, When tab is not focused  tab label text is not  displaying in android. while it's working perfectly in IOS.

```
`export const HomeTab = TabNavigator(
  {
    notification: {
      screen: Notifications,
      navigationOptions: {
        tabBarLabel: "Notifications",
        header: null,
        tabBarIcon: ({ focused }) => <Image
          source={
            focused ? require('../resources/toolbar/notifications_active.png') : require('../resources/toolbar/notifications_inactive.png')
          } />
      }
    },
    homePage: {

      screen: HomeScreen,
      navigationOptions: {
        tabBarLabel: "Home",
        header: null,
        tabBarIcon: ({ focused }) => <Image
          source={
            focused ? require('../resources/toolbar/home_active.png') : require('../resources/toolbar/home_inactive.png')
          } />
      }
    },
    settings: {
      screen: Settings,
      navigationOptions: {
        tabBarLabel: "Settings",
        header: null,
        tabBarIcon: ({ focused }) => <Image
          source={
            focused ? require('../resources/toolbar/settings_active.png') : require('../resources/toolbar/settings_inactive.png')
          } />
      }
    }
  },
  {
    // tabBarPosition: "top",

    animationEnabled: false,
    tabBarPosition: 'bottom',
    swipeEnabled: true,
    tabBarOptions: {
      upperCaseLabel: false,
      showIcon: true,
      activeTintColor: colors.themeColor,
      labelStyle: {
        fontSize: 16,
       // color:''
      },
      style: {
        backgroundColor: colors.white
      },
       //tabStyle: { width: 200 } //Set width to make INLINE TABS
    }
  }
);`
```

**Comment by kelset** [comment] 2017-12-07 13:29
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-07 13:29 UTC
