### ISSUE TITLE
TabRouter ignores params when navigating

### ISSUE THREAD

**Issue by hwaterke** [react-community/react-navigation#371] opened 2017-02-17 10:11 UTC
I have a simple TabNavigator with two Tabs:
```
export const SecTabNavigator = TabNavigator({
  A: {
    screen: AScreen
  },
  B: {
    screen: BScreen
  },
});
```

In `AScreen`, issuing :
```
this.props.navigation.navigate('BScreen', {mySuperParam: 'fooBar'});
```
brings me to the second tab but the **params are empty**.

```
// this.props.navigation
{
  state: {
    key: "B",
    routeName: "B"
  }
}
```

**Comment by lukesanantonio** [comment] 2017-02-22 22:49
I encountered the same problem, but I think #306 fixes this.

**Comment by ggarek** [comment] 2017-02-27 13:39
@satya164  @grabbou isn`t it a duplicate of #80 #42?

**Comment by grabbou** [comment] 2017-02-28 10:00
Yup, thanks!

**Closed by grabbou** 2017-02-28 10:00 UTC
