### ISSUE TITLE
key is not unique with nested navigators

### ISSUE THREAD

**Issue by aknad** [react-community/react-navigation#1149] opened 2017-04-20 22:40 UTC
In our app we have a configuration with many nested navigator
We need to use the [setParams](https://reactnavigation.org/docs/navigators/navigation-actions#SetParams) method but the key of each navigator is not always unique

e.g.
const SubMasterNavigator = StackNavigator({
    SubMaster: { screen: Home },
});
const MasterNavigator = StackNavigator({
    Master: { screen: SubMasterNavigator },
});

If I log the nav state in the js console both navigators have the key 'Init'
Can we overwrite the key value?

**Comment by grabbou** [comment] 2017-04-22 06:19
Can you demonstrate what exactly you are logging? I suspect the `Init` is the key of the `initial action` that is dispatched to set state of navigators, not the key of screen.

**Comment by grabbou** [comment] 2017-04-25 07:54
I am going to close it for now. Please provide steps to reproduce as requested and I'll be happy to reopen :)

**Comment by aknad** [comment] 2017-04-25 20:23
I'm logging the 'nav' redux state

<img width="261" alt="screen shot 2017-04-25 at 22 07 51" src="https://cloud.githubusercontent.com/assets/7056879/25405511/d1ad6b86-2a03-11e7-8ebe-a97c042de3eb.png">

If it's the initial action, how can I use the setParams method?

**Comment by nouh** [comment] 2017-05-18 04:14
for my case,  use the 'Init' key for goBack(key) is  not working, How could I goBack to the screen before the nesting navigator?

**Comment by aknad** [comment] 2017-05-18 10:35
@nouh did you try with goBack(null) ?

**Comment by nouh** [comment] 2017-05-19 03:14
@aknad  That doesn't work,  I just want to goBack to the screen before my nesting navigator,  can't figure a way out

**Comment by spencercarli** [comment] 2017-08-30 01:17
Is this still an issue in the latest release of React Navigation?

**Comment by kelset** [comment] 2017-10-21 13:37
Closing since OP never replied in months. (and related to old version of lib)

**Closed by kelset** 2017-10-21 13:37 UTC
Labels: Status: Needs More Info, Type: Bug
