### ISSUE TITLE
Tab Changes feeling slow

### ISSUE THREAD

**Issue by joecaraccio** [react-community/react-navigation#2757] opened 2017-10-15 01:27 UTC
Hi Everyone,

Running on Device,  with JS Dev Mode turned off tab changes feel slow

The actual transition is fine, but the time in between pressing the button and then when the transition occurs is too long, it feels like there is a good second before the tab will actually change.

Tab Press -> Delay -> Transition to Tab

Any ideas?

**Comment by vonovak** [comment] 2017-10-15 20:49
just a thought.. do you have lazy rendering enabled?

**Comment by joecaraccio** [comment] 2017-10-15 23:07
I don't.. should I? 

off of quick quess woudln't you want everything rendered as much as possible

**Comment by vojtechnovak** [comment] 2017-10-15 23:33
Can you try enabling the lazy rendering of tabs (if you check the docs or other issues I'm sure you'll find the prop that does that) and see if that makes things better?

**Comment by SteffeyDev** [comment] 2017-10-16 15:09
I noticed the same thing, primarily on Android, doesn't matter if lazy mode is enabled or not for me.

**Comment by sanjayholla94** [comment] 2017-10-17 13:51
Few things you can try out:
1. Turn off Debug JS Remotely if it's on. Animations are slow when it's on
2. Try production build and check if it's still happening
3. If that still doesn't work, try settting swipeEnabled and animationEnabled to false. You can check the documentation for these props

**Comment by joecaraccio** [comment] 2017-10-17 14:18
@sanjayholla94 I know this probably makes me sound like a painful ametuer.. but whats the difference between a production build and a nonproduction build?
I assumed production just ment going into the settings and disabling JS dev mode

**Comment by sanjayholla94** [comment] 2017-10-17 15:53
If you're running it on Android and integrating with existing code, then you can check this to create a production build https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#creating-a-release-build-in-android-studio
I haven't worked on iOS but there must be something similar for it. I'm sure you can find it in the docs

**Comment by joecaraccio** [comment] 2017-10-18 12:08
Ah,
so I guess turning off JS Dev Mode isn't a good indicator of performance, as we should expect it to improve in Dev Mode as well?
@sanjayholla94

**Comment by vonovak** [comment] 2017-10-18 12:42
I'm not aware of any performance gain you'll get by release build, compared to running with devMode off and minification enabled @joecaraccio

**Comment by kelset** [comment] 2017-10-20 14:09
Closing this since it's technically a duplicate of #739. Moreover I highly suggest that you check out my comments at the bottom of #608.

We know that there are some performance issues here and there, but most times it's about the way you structured your components.
A prod build VS a non prod build is quite different, the packager uses a lot of optimizations when creating the prod build.
If you see a huge perf gain by turning on the JS debugger it's because when it is active the JSCore that handles your JS code is on your laptop instead of the device you are using. So when this is the case is quite surely something related to your code.

**Closed by kelset** 2017-10-20 14:09 UTC

**Comment by uinz** [comment] 2018-06-09 12:37
@joecaraccio  you can

1. open chrome debugger
2. choose Performance Tab
3. click Record button
4. change tab
5. stop record

we can see cost time of each function

---

I found that I use `withNavigation` on my list `<Item />`, 

like this
```js
@withNavigation
class Item extends React.Component {
  render () {
    return (
      // ...
    )
 }
}

```

and when I change Tab, All `<Item />` updated and that It cost so many time.

after that,  I add

```js
  shouldComponentUpdate() {
    return false
  }
```
on my `<Item />` component

haha, become faster.

**Comment by tobiastornros** [comment] 2018-09-14 08:56
You can use PureComponent also.
