### ISSUE TITLE
How to hide Drawer Item from Drawer

### ISSUE THREAD

**Issue by zakster12** [react-community/react-navigation#2021] opened 2017-06-29 05:16 UTC
I have a screen which I would like to be part of the Drawer navigator but not to be visible as an item in the Drawer when it's opened. Here is an example:

![oczee](https://user-images.githubusercontent.com/25477229/27672305-9032fd84-5ca2-11e7-83b6-52dbe3b7d95b.png)

I would like 'Test' to not be visible when the drawer is opened. 

This is my configuration:

```
const DrawerRoutes = {
    Home: {
        name: 'Home',
        screen: StackNavigator(HomeStack, { initialRouteName: 'HomeTab', ...navOptions })
    },
    Notifications: {
        name: 'Notifications',
        screen: StackNavigator(Stack, { initialRouteName: 'NotificationsTab', ...navOptions })
    },
    LastAdded: {
        name: 'LastAdded',
        screen: StackNavigator(VideosStack, { initialRouteName: 'LastAddedTab', ...navOptions })
    },
    ChangeLog: {
        name: 'ChangeLog',
        screen: StackNavigator(Stack, { initialRouteName: 'ChangelogTab', ...navOptions })
    },
    AboutUs: {
        name: 'AboutUs',
        screen: StackNavigator(Stack, { initialRouteName: 'AboutUsTab', ...navOptions })
    },
    Test: {
        name: 'Test',
        screen: StackNavigator(ProfileStack, { initialRouteName: 'ProfileScreen', ...navOptions })
    }
};

export const DrawerNav =
    DrawerNavigator(
        DrawerRoutes, {
            drawerWidth: windowWidth - Normalize(48),
            contentOptions: {
                activeBackgroundColor: Colors.selectedRowHeader,
                activeTintColor: Colors.navigationBar,
                labelStyle: {
                    fontSize: 16,
                    fontFamily: Fonts.light,
                    color: Colors.navigationBar,
                }
            },
            contentComponent: props => {
                return (<View style={styles.container}>
                    <StatusBar />
                    <Header />
                    <DrawerItems {...props} />
                    <LogOut {...props} />
                </View>);
            }
        },
        { headerMode: 'none' }
    );
```
Is this possible? The reason is that I need to go to this screen from the other routes from DrawerRoutes and open the Drawer from the Test screen the same way as from the others.

**Comment by markusguenther** [comment] 2017-07-24 12:45
I solved this by an own custom drawerItem.

I override the regular renderIcon and call it in my own custom item within the getLabel().
So you have the advantage that the styles are also for the icon possible

```javascript
<DrawerItems
        {...props}
        getLabel={scene => <SliderItem scene={scene} {...props} />}
        renderIcon={() => {}}
        style={styles.drawerItemsContainer}
      />
```

```
const SliderItem = props => {
  const route = getRoute(props);
  if (route.routeName === 'Test') {
    return null;
  }

  const icon = props.renderIcon(props.scene);
  const iconView = (
    <View
      style={[
        styles.sliderIcon,
        props.scene.focused ? null : styles.sliderIconInactive
      ]}
    >
      {icon}
    </View>
  );

  return (
    <View style={styles.sliderItem}>
      {icon ? iconView : null}
      <Text style={styles.sliderLabel}>
        {getLabelName(props)}
      </Text>
    </View>
  );
};
```

**Comment by BastienGermain** [comment] 2017-07-25 10:35
I found the following workaround : 

- Create a component returning null
- Pass the component to the drawerLabel navigationOptions of the screen you want the item to be hidden

Hope this helps.

**Comment by JoeRoddy** [comment] 2017-07-26 20:45
Would it be possible to add a _hidden_ attribute to the class's navigation options that does this?  Would make it a lot simpler.

**Comment by markusguenther** [comment] 2017-07-26 21:00
Of course such things would be easier. Had an issue in the TabNavigator in the past and there the PR was abandoned. So for tabs the team don't want the possibility to hide items.

Maybe it is different for the drawer ;)

**Comment by nishiltamboli** [comment] 2017-08-03 07:56
@BastienGermain thanks! That worked. However, there should be an attribute at navigationOptions level to make it cleaner.

**Comment by AnderScore** [comment] 2017-08-03 08:17
Do any one have some example code for @BastienGermain solution?

**Comment by spencercarli** [comment] 2017-08-28 01:27
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Closed by spencercarli** 2017-08-28 01:27 UTC
Labels: Type: Question

**Comment by arryanggaputra** [comment] 2017-09-07 09:45
@BastienGermain  Thanks a lot, it worked.

**Comment by bencodezen** [comment] 2017-09-20 15:37
In support of @BastienGermain's suggestion, I tried simply inlining the null stateless component which worked as well.

```js
class ScreenYouWantToHide extends React.Component {
    static navigationOptions = {
         drawerLabel: () => null
    }
}
```

**Comment by tannera** [comment] 2018-05-03 15:44
A more simplified version of TynaKam's code could be:

```
class Sidebar extends Component {

render() {
    const { items, ...rest } = this.props;
    const filteredItems = items.filter(item => item.key !== "RouteNameToHide");
    return (
            <ScrollView>
              <DrawerItems items={filteredItems} {...rest} />
            </ScrollView>
...
```

**Comment by AGASampath** [comment] 2018-08-15 08:01
@zakster12 thanx for your code

**Comment by AmadeuszZaradny** [comment] 2019-03-12 11:37
i have the same problem but with drawerIcon. 
```
    static navigationOptions = ({ navigation }) => {
        return {
            drawerIcon: () => null,
            drawerLabel: () => null
        }
    }
```
this code works only on drawerLabel ( makes it invisible ) but drawerIcon is still visible.

**Comment by tiagobnobrega** [comment] 2019-04-02 02:23
My workaround was to filter out items wich getLabel returns null.

```javascript

const filterItems = ({ activeItemKey, activeTintColor, inactiveTintColor, getLabel }) => (route, index) => {
  const focused = activeItemKey === route.key;
  const color = focused ? activeTintColor : inactiveTintColor;
  const scene = { route, index, focused, tintColor: color };
  const label = getLabel(scene);
  return !!label;
};

const DrawerContent = props => {
  const { items, ...rest } = props;
  const itemsToRender = items.filter(filterItems(props));
  return (
    <ScrollView>
      <SafeAreaView style={styles.container} forceInset={{ top: 'always', horizontal: 'never' }}>
        <DrawerItems items={itemsToRender} {...rest} />
      </SafeAreaView>
    </ScrollView>
  );
};
```

And on my screen component:
```javascript
export default class Screen extends Component<Props> {
  static navigationOptions = {
    drawerLabel: ()=>null,
  };
//Component Logic....
}
```

**Comment by rafaelsts** [comment] 2019-04-23 10:50
My workaround and what look easier and simpler to me, was to return null on the Drawer itself, instead of  inside the component like almost everyone suggested, for example like this:

```js
const Drawer = createDrawerNavigator({
    OverviewStack: {
        screen: OverviewStack,
        navigationOptions: ({navigation}) => {
            return {
                drawerLabel: "Overview"
                drawerIcon: ({ tintColor }) => (
                    <Image
                        source={require('../../assets/icons/Dashboard.png')}
                        resizeMode="contain"
                        style={{ width: 20, height: 20, tintColor: tintColor }}
                    />
                )
            }
        }
    },
    Notifications: {
        screen: Notifications,
        navigationOptions: ({navigation}) => {
            return {
                drawerLabel: () => null,
            }
        }
    },
```

And this worked as expected 😊

**Comment by j-ornelas** [comment] 2019-04-26 21:56
> My workaround and what look easier and simpler to me, was to return null on the Drawer itself, instead of inside the component like almost everyone suggested, for example like this:
> 
> ```js
> const Drawer = createDrawerNavigator({
>     OverviewStack: {
>         screen: OverviewStack,
>         navigationOptions: ({navigation}) => {
>             return {
>                 drawerLabel: "Overview"
>                 drawerIcon: ({ tintColor }) => (
>                     <Image
>                         source={require('../../assets/icons/Dashboard.png')}
>                         resizeMode="contain"
>                         style={{ width: 20, height: 20, tintColor: tintColor }}
>                     />
>                 )
>             }
>         }
>     },
>     Notifications: {
>         screen: Notifications,
>         navigationOptions: ({navigation}) => {
>             return {
>                 drawerLabel: () => null,
>             }
>         }
>     },
> ```
> 
> And this worked as expected 😊

I think this is the cleanest and simplest option. This way, the navigation logic is kept out of the component file. 

That being said, if I'm understanding the library well enough, I think the real ideal situation would be for each drawer navigation item to have its own set of stack navigation.

**Comment by annjawn** [comment] 2020-01-25 19:15
So my use case is that i am using the drawer as a side menu not to navigate to any of the screens, but to show buttons that would open webviews (like About us, Contact Us, Legal info, and a Logout button). So in that case should I be filtering out all the drawer items as suggested by @TynaKam ?

**Comment by Pardhasaradhi6777** [comment] 2020-04-14 06:57
> > My workaround and what look easier and simpler to me, was to return null on the Drawer itself, instead of inside the component like almost everyone suggested, for example like this:
> > ```js
> > const Drawer = createDrawerNavigator({
> >     OverviewStack: {
> >         screen: OverviewStack,
> >         navigationOptions: ({navigation}) => {
> >             return {
> >                 drawerLabel: "Overview"
> >                 drawerIcon: ({ tintColor }) => (
> >                     <Image
> >                         source={require('../../assets/icons/Dashboard.png')}
> >                         resizeMode="contain"
> >                         style={{ width: 20, height: 20, tintColor: tintColor }}
> >                     />
> >                 )
> >             }
> >         }
> >     },
> >     Notifications: {
> >         screen: Notifications,
> >         navigationOptions: ({navigation}) => {
> >             return {
> >                 drawerLabel: () => null,
> >             }
> >         }
> >     },
> > ```
> > 
> > 
> > And this worked as expected 😊
> 
> I think this is the cleanest and simplest option. This way, the navigation logic is kept out of the component file.
> 
> That being said, if I'm understanding the library well enough, I think the real ideal situation would be for each drawer navigation item to have its own set of stack navigation.

Thank you

**Comment by xstable** [comment] 2020-05-01 09:14
> So my use case is that i am using the drawer as a side menu not to navigate to any of the screens, but to show buttons that would open webviews (like About us, Contact Us, Legal info, and a Logout button). So in that case should I be filtering out all the drawer items as suggested by @TynaKam ?

I had a similar approach for my App. In first step I also was a bit confused how to get this done, but it's only a question about structuring your Navigators / Screens in the right way.

In my drawer I have an Imprint, and Legal-Info in the Footer.
_I solved it this way:_ 
My Drawer has an StackNavigator "Home" inside, where "Home" is also the intialRouteName of my Drawer.
To this StackNavigator, I've added the Screens I need for Imprint and Legal-Info. Now you can easily browse to this Screen, but the Item are not shown in the Drawer.
Hope that helps you a bit.

**Comment by harshitraghav** [comment] 2020-06-04 06:01
I have added drawerLabel null but I can still see some space at that position. Can anyone help with this?

**Comment by elisegriset92** [comment] 2020-06-15 09:37
> > So my use case is that i am using the drawer as a side menu not to navigate to any of the screens, but to show buttons that would open webviews (like About us, Contact Us, Legal info, and a Logout button). So in that case should I be filtering out all the drawer items as suggested by @TynaKam ?
> 
> I had a similar approach for my App. In first step I also was a bit confused how to get this done, but it's only a question about structuring your Navigators / Screens in the right way.
> 
> In my drawer I have an Imprint, and Legal-Info in the Footer.
> _I solved it this way:_
> My Drawer has an StackNavigator "Home" inside, where "Home" is also the intialRouteName of my Drawer.
> To this StackNavigator, I've added the Screens I need for Imprint and Legal-Info. Now you can easily browse to this Screen, but the Item are not shown in the Drawer.
> Hope that helps you a bit.

Hi ! Could you send your navigation / drawer code please? I would love to take a look because when I try to reproduce and use the navigation function I still get the error "do you have a screen named footer " 
Thanks !

**Comment by twocs** [comment] 2020-06-17 15:04
There is a problem. Either the drawer should be able to hide items, or nesting navigators is always preferable. There are hundreds of requests to hide drawer items, since many apps are not hierarchical, but there are no useful guides on how to handle the situations.

For example, you have 40 screens. 36 of the screens should be accessible from the drawer. 3 of the screens should be accessible from every other screen including each other. 1 of the screens should sometimes be available from the drawer, but other times should only be accessible when someone clicks a button on one of the other 39 screens. Thus 95% of screens are handled by the drawer navigator, but the 5% requires more hassle with nested navigation. 

The deadline is soon, but there is little guidance other than suggestions that nesting should work. Can we please be able to hide items from the drawer, similarly to a display: none, or alternatively see a clear example of how to display most of the items in the drawer but also support navigation to a small number of non-drawer screens from every other screen. If it is really so easy, why is there no example?

**Comment by leninsheikh** [comment] 2020-06-30 10:57
### Solution for react navigation 5
```
export default props => {
    const { state, ...rest } = props;
    const newState = { ...state}
    newState.routes = newState.routes.filter(item => item.name !== 'Login') //replace "Login' with your route name

    return (
         <DrawerContentScrollView {...props}>
             <DrawerItemList state={newState} {...rest} />
        </DrawerContentScrollView>
    )
}
```

**Comment by Raplebre** [comment] 2020-07-01 15:23
Thanks, @leninsheikh. That seems to me to be the best solution, as setting the label to null seems to still let me click on the item. This way, the item is not even displayed on the list and the screen can still be accessed through other means.

**Comment by mixa9269** [comment] 2020-07-01 18:21
Thanks, @leninsheikh! It really works!

**Comment by nupipe** [comment] 2020-07-03 21:34
> ### Solution for react navigation 5
> ```js
> //custom drawer content
> export default props => {
>     const { state, ...rest } = props;
>     const newState = { ...state}  //copy from state before applying any filter. do not change original state
>     newState.routes = newState.routes.filter(item => item.name !== 'Login') //replace "Login' with your route name
> 
>     return (
>          <DrawerContentScrollView {...props}>
>              <DrawerItemList state={newState} {...rest} />
>         </DrawerContentScrollView>
>     )
> }
> ```

Thanks! Really work! I just change <DrawerItemList /> for <DrawerNavigatorItems />, and 'state' for 'items'.

**Comment by fabio-rsys** [comment] 2020-09-08 17:25
> ### Solution for react navigation 5
> ```js
> //custom drawer content
> export default props => {
>     const { state, ...rest } = props;
>     const newState = { ...state}  //copy from state before applying any filter. do not change original state
>     newState.routes = newState.routes.filter(item => item.name !== 'Login') //replace "Login' with your route name
> 
>     return (
>          <DrawerContentScrollView {...props}>
>              <DrawerItemList state={newState} {...rest} />
>         </DrawerContentScrollView>
>     )
> }
> ```
Awsome! It worked like a charm.

Just one tip for the newbier devs that can struggle with this(like I did), you guys have to pass this function to the **drawerContent** prop of the **Drawer.Navigator**! Something like this:

```
const Drawer = createDrawerNavigator();

const CustomDrawerContent = (props) => {
  const { state, ...rest } = props;
  const newState = { ...state };
  newState.routes = newState.routes.filter(
    (item) => item.name !== 'Login',
  );

  return (
    <DrawerContentScrollView {...props}>
      <DrawerItemList state={newState} {...rest} />
    </DrawerContentScrollView>
  );
};

export default () => (
  <Drawer.Navigator
    initialRouteName="Home"
    drawerContent={(props) => <CustomDrawerContent {...props} />}
    screenOptions={{
      headerShown: true,
    }}>
    <Drawer.Screen
      name="Home"
      component={HomeScreen}
      options={{ title: 'Home' }}
    />
    .
    .
    .
```

**Comment by nickojs** [comment] 2020-09-10 16:42
> ### Solution for react navigation 5
> 
> ```js
> //custom drawer content
> export default props => {
>     const { state, ...rest } = props;
>     const newState = { ...state}  //copy from state before applying any filter. do not change original state
>     newState.routes = newState.routes.filter(item => item.name !== 'Login') //replace "Login' with your route name
> 
>     return (
>          <DrawerContentScrollView {...props}>
>              <DrawerItemList state={newState} {...rest} />
>         </DrawerContentScrollView>
>     )
> }
> ```

Great fix, its working here! But filtering the items breaks the item's index (on my current project). I'm still working on it, so I may come back later with more details.

**Comment by lysachok** [comment] 2020-12-03 22:59
To fix the index issue I've added this line:
`newState.index -= state.routes.length - newState.routes.length;`

**Comment by trongtai1801** [comment] 2020-12-17 16:05
![image](https://user-images.githubusercontent.com/31733095/102512157-47f1f280-40bc-11eb-9a64-321fd37d5bb1.png)
working well on vv5

**Comment by gilad7** [comment] 2020-12-17 18:52
@trongtai1801 you are a genius. I was looking so much for a simple an clean solution. Thanks!

**Comment by dilincoln** [comment] 2021-01-26 12:50
@trongtai1801 genius!

**Comment by gusmarques** [comment] 2021-01-28 22:17
createDrawerNavigator({
    Home:{
      screen: Home,
      navigationOptions:{
        drawerLabel: () => null   <--- HERE 
      }
    },
    Conta,
    Pedidos,
    Sobre,
  }, {
    initialRouteName:'Conta',
    contentComponent: Drawer,
    
    
  } )
);

**Comment by gioramies** [comment] 2021-02-23 21:59
@leninsheikh @fabio-rsys 
Thank you guys

**Comment by ashmdev** [comment] 2021-04-06 18:09
in version 4 of the navigation I used the following code
`
              <DrawerNavigatorItems
                {...this.props}
                items={this.props.navigation.state.routes.filter(item => {
                  if (item.routeName === 'DrawerHelp') {
                    return true;
                  }
                  return true;
                })}>
`

**Comment by an0o0nym** [comment] 2021-06-21 22:12
The only way to make it work is via rendering custom DrawerItem. I posted working solution in  #7954  at this repo

**Comment by sadikyalcin** [comment] 2021-09-03 15:38
Filtering the screens by using solutions like https://github.com/react-navigation/react-navigation/issues/2021#issuecomment-651720504 will break the index.

Instead of messing around with the indexes as per https://github.com/react-navigation/react-navigation/issues/2021#issuecomment-738419940, better to place your `hidden` screens at the end of drawer so all the indexes before that will be correct.

`react-navigation` should implement an options to hide/show these items from the drawer IMO.

**Comment by ChristopheBelpaire** [comment] 2021-10-11 15:03
Hello,
It seems the workarounds don't work anymore on version 6.
Does anyone has a solution for this in version 6 ?

Kind Regards,

**Comment by lukemcgregor** [comment] 2022-11-03 20:02
> ```js
> drawerItemStyle: { display: 'none' }
> ```

This is so much better a solution than setting the label to null which leaves a clickable hidden item behind.

**Comment by behnamjahan90** [comment] 2022-11-05 12:31
> ```js
> drawerItemStyle: { display: 'none' }
> ```

The best and easiest solution I've been looking for. Thanks a lot.

**Comment by sergioDavidCano** [comment] 2023-01-26 14:16
drawerItemStyle: { display: 'none' }

@satya164
Gracias eres un crack, era lo que estaba buscando..
