### ISSUE TITLE
Redux-bound component in StackNavigator won't rerender immediatly after 'Back' action

### ISSUE THREAD

**Issue by DavideValdo** [react-community/react-navigation#1810] opened 2017-06-09 12:37 UTC
https://vid.me/SYMi

I have a VendorGallery screen which is parent of a VendorFullGallery screen in a StackNavigator.
VendorsFullGallery can trigger a BOOKMARK_ADDED or BOOKMARK_REMOVED action, which change state.Bookmarks. 

1. I can see from the console that VendorGallery's this.props.bookmarks is correctly updated
2. I can also see that VendorGallery's render method is triggered
3. As you can see from the video, if I switch the upper segment (js-based) I can see the new props being rendered correctly.

**Comment by Jacse** [comment] 2017-06-10 07:37
Duplicate of #1617. Let's keep the discussion there, @DavideValdo.

**Closed** 2017-06-10 12:46 UTC
