### ISSUE TITLE
Can't access static NavigationOptions when a screen is called as a function

### ISSUE THREAD

**Issue by EslamNasser** [react-community/react-navigation#1774] opened 2017-06-05 15:37 UTC
I have a tab navigator with a stack navigator as one of the tab items and i was trying to access the navigation options from inside the stack navigator but it doesn't reflect/change anything.
This is what i'm trying to do inside the component with the stack navigator
```
export default class MyStackNavigatorComponent extends Component {
static navigationOptions = {
tabBarLabel: 'Search'
}
....//return stack navigator
}
```
This is how i'm calling the stack navigator inside the tab navigator:
```
const mynavigator = TabNavigator({
Home: {
screen: (props) => <MyStackNavigatorComponent prop1={prop1} prop2={prop2}/>
}
})
```
I tried calling the stack navigator without passing the props that i want to pass `prop1` and `prop2` and it worked fine.
```
const mynavigator = TabNavigator({
Home: {
screen: MyStackNavigatorComponent
}
})
```
But i need to pass these props to the component. 
Am i missing something here?, or am i doing anything wrong?

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 6.9.1
| npm or yarn      | 4.3.0

**Comment by EslamNasser** [comment] 2017-06-06 12:07
I was able to fix this by using `hoist` from `hoist-non-react-statics` and doing the following:
```
const mynavigator = TabNavigator({
Home: {
screen: hoist((props) => <MyStackNavigatorComponent prop1={prop1} prop2={prop2}/>, MyStackNavigatorComponent)
}
})
```
So by using `hoist` i was able to get the static property `navigationOptions` and merge it into the component with the probs passed.
You may close this now.

**Comment by iMaddin** [comment] 2017-07-16 16:56
Any way to do this without installing another dependency?

**Comment by EslamNasser** [comment] 2017-07-17 09:45
@iMaddin So far that's the only solution i was able to come up with.

**Comment by vonovak** [comment] 2017-11-03 23:42
Closing since the issue is solved with using `hoist`. `hoist-non-react-statics` is a standard package in react, and is used in cases like this.

**Closed by vonovak** 2017-11-03 23:42 UTC
