### ISSUE TITLE
TabNavigator pass different param from each screen to StackNavigator header

### ISSUE THREAD

**Issue by JayricMok** [react-community/react-navigation#2716] opened 2017-10-09 03:26 UTC
I have Question. How can I pass specific param from each screen to the StackNavigator header in order to come out different kind of components when reached the screen.

    const mainNav = TabNavigator({
      Home: { 
        screen: HomeScreen,
        param:{
          tabval:1
        }
      },
      Live: {
       screen: LiveScreen,
       param:{
          tabval:2
        }
      },
      Radio: {
       screen: RadioScreen,
       param:{
          tabval:3
        }
      },
    } );

    function DifferentComponents(tabval){
      if(tabval == 1){
        //do something
      }else if(tabval == 2){
        //do something
      }else{
        //do something
      }
    }

    export const mainStack = StackNavigator({
      Home: { 
        screen: mainNav,
        navigationOptions: {
          header: (
            <View style={styles.topnavscrollview}>
              <View style={{width:300}}>
                <ScrollView horizontal={true} showsHorizontalScrollIndicator={false}>
                  {this.DifferentComponents(tabval)} <-- Change this when switch to Live tab or others
                </ScrollView>
              </View>
            </View>
          ),
        },
      },
      Content: { screen: ContentScreen },
    });

**Comment by kelset** [comment] 2017-10-09 08:10
@JayricMok please don't post again your issues, it's clearly a duplicate of #2699

**Closed by kelset** 2017-10-09 08:10 UTC
