### ISSUE TITLE
stack navigation dispatch reset with animation

### ISSUE THREAD

**Issue by hyochan35** [react-community/react-navigation#1741] opened 2017-05-31 14:49 UTC
When will this be done?

I am still using Navigator in 'react-native-deprecated-custom-components'
because reset with animation is not fully supported in react-navigation.

I wish I can use react-navigatino instead of navigator in 'react-native-deprecated-custom-components'

**Comment by spencercarli** [comment] 2017-08-16 02:15
duplicate of #351

**Closed by spencercarli** 2017-08-16 02:15 UTC
