### ISSUE TITLE
Determine current screen

### ISSUE THREAD

**Issue by michaelduminy** [react-community/react-navigation#259] opened 2017-02-09 13:39 UTC
This isn't an issue so much as a question. I'd like to know if I can interrogate something to find out if a screen or component is currently on top of a stack.

On one of my screens I register a custom back listener for android back presses `BackAndroid.addEventListener('hardwareBackPress', this.androidBackHandler);`. When I navigate to another screen (pushing it on top of the stack) and press the hardware back button my previous screen captures this even though it is not on top. 

I'd like to be able to add a check in my back handler that checks if the screen receiving the event is currently on top. So is there a way to tell from a screen whether or not it is the current screen?

**Comment by satya164** [comment] 2017-02-09 14:10
Duplicate of #51

**Closed by satya164** 2017-02-09 14:10 UTC

**Comment by michaelduminy** [comment] 2017-02-09 16:43
Thanks @satya164

**Comment by SirPhemmiey** [comment] 2018-08-07 16:02
You probably want to use `withNavigationFocus `instead of using this directly, it will pass in an isFocused boolean a prop to your component.

Cheers!

**Comment by nwaughachukwuma** [comment] 2018-11-10 20:33
@SirPhemmiey please expatiate further how to do this

**Comment by mjgaylord** [comment] 2018-12-17 19:14
This should explain how to use it: [https://reactnavigation.org/docs/en/with-navigation-focus.html](https://reactnavigation.org/docs/en/with-navigation-focus.html)

**Comment by bhutta420** [comment] 2020-04-06 09:49
> You probably want to use `withNavigationFocus `instead of using this directly, it will pass in an `` isFocused ``boolean ``a prop to your component.
> 
> Cheers!

How to get a current screen information

**Comment by joshuapinter** [comment] 2023-10-16 16:01
FYI, an updated way to do this is something like; 

```js
if ( !this.props.navigation.isFocused() ) return false;
```

`isFocused()` will return `false` if the screen this is called from is not in focus. If this is done in an event handler, returning `false` will ensure that the event will not be trapped, but instead will bubble up and be handled appropriately somewhere else.

This is on version 5.x btw.
