### ISSUE TITLE
Q: Android navigate transition from right to left (Like iOS)?

### ISSUE THREAD

**Issue by krailler** [react-community/react-navigation#815] opened 2017-03-24 18:34 UTC
Is it possible to navigate on Android, with a transition from right to left (Like iOS)? My views when I navigate, appear in modal.

**Comment by mokhtarmoustafa** [comment] 2017-04-09 13:31
yes of curse you can do it by create an .xml files in the anime folder and use them in your activity
and the idea is to simple create for each navigate an xml file for more details see this url
http://stackoverflow.com/questions/18147840/slide-right-to-left-android-animations

**Comment by mmerickel** [comment] 2017-07-19 15:05
@krailler see https://github.com/react-community/react-navigation/issues/705#issuecomment-314322254 for one option.

**Comment by kelset** [comment] 2017-10-14 18:39
Duplicate of #705

**Closed by kelset** 2017-10-14 18:39 UTC
