### ISSUE TITLE
warning 

### ISSUE THREAD

**Issue by TrustTheBoy** [react-community/react-navigation#1504] opened 2017-05-14 16:17 UTC
ios 10.3
rn:0.44
react-navigation: ^1.0.0-beta.9

warning :View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

**Comment by swcisel** [comment] 2017-05-15 15:00
I believe this is a duplicate of [#1352](https://github.com/react-community/react-navigation/issues/1352).

**Comment by skevy** [comment] 2017-05-15 15:35
Rolling into #1352.

**Closed by skevy** 2017-05-15 15:35 UTC
